### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'com.paypal.android.sdk.onetouch.core.Result com.paypal.android.sdk.onetouch.core.Request.a(com.paypal.android.sdk.onetouch.core.a.a, android.net.Uri)' on a null object reference

### ISSUE THREAD

**Issue by nzakharchenko** [braintree/braintree_android#101]
Hello!

on my release build after fresh install application I'm always getting `java.lang.NullPointerException: Attempt to invoke virtual method 'com.paypal.android.sdk.onetouch.core.Result com.paypal.android.sdk.onetouch.core.Request.a(com.paypal.android.sdk.onetouch.core.a.a, android.net.Uri)' on a null object reference` for first payment. More details here http://crashes.to/s/3d3f39c4400

It happens every first payment on freshly installed application on phone (Moto G 3rd edition) without installed PayPal application (login to PayPal are done in browser).

```
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    minSdkVersion 15
    targetSdkVersion 23

    compile "com.braintreepayments.api:braintree:2.3.0"
````

Thanks!

**Comment by lkorth** [comment]
@nzakharchenko are you running proguard on your release builds? The stack trace isn't very useful as it seems to be obfuscated. Could you try it without proguard to see if it still crashes? If so it should provide as more useful stack trace.

**Comment by nzakharchenko** [comment]
@lkorth here is stack trace without obfuscation http://crashes.to/s/cde28ba71d6. Let me know if you need something else.

**Comment by lkorth** [comment]
@nzakharchenko: we just released `2.3.1-SNAPSHOT` with a change that should fix this. Could you give it a try and let us know?

If you don't have the snapshot repository setup, you can add the following:

```
maven {
    url 'https://oss.sonatype.org/content/repositories/snapshots/'
}
```

**Comment by nzakharchenko** [comment]
@lkorth looks like it works now. I've seen that you also already released 2.3.1, so I will make more testing on Monday with that

**Comment by lkorth** [comment]
Note that `2.3.1` does not include the fix and will likely still result in a crash for you.

**Comment by nzakharchenko** [comment]
Ok! then I will continue testing with SNAPSHOT and wait for next release

**Comment by nzakharchenko** [comment]
@lkorth Have you deleted SNAPSHOT ? I could not find it anymore under

**Comment by nzakharchenko** [comment]
@lkorth is there any estimations about new release?

**Comment by lkorth** [comment]
snapshots are automatically purged by Sonatype after a day or two. We will be making a release early this week with this fix.
