### ISSUE TITLE
Last four digits of card number.

### ISSUE THREAD

**Issue by romanmikhailov** [braintree/braintree_android#103]
During integration of Braintree I met requirement that need display credit card payment method description in next way: ending in XXXX. Where XXXX is the last four digits of card number. Now Braintree SDK provide us only with 2 last digits.

Is there any way to receive requirement information from Braintree SDK?

**Comment by lkorth** [comment]
No, the Android SDK currently only provides last 2. If you'd like to get the last 4 for a given card you would need to make a request to your server which can get the last 4 using the server side SDKs.

**Comment by romanmikhailov** [comment]
@lkorth thank you for clarification.
