### ISSUE TITLE
onPayPalSuccess

### ISSUE THREAD

**Issue by ISAACJGSANTOS** [braintree/braintree_android#1035]
### Braintree SDK Version

com.braintreepayments.api:paypal:4.47.0

### Environment

Sandbox

### Android Version & Device

emulator pixel 7 

### Braintree dependencies

paypal:4.47.0

### Describe the bug

I'm encountering an issue while testing my PayPal checkout implementation (version com.braintreepayments.api:paypal:4.47.0) in the sandbox environment. The onPayPalSuccess method isn't called when I confirm the payment, but the onPayPalFailure method is triggered with a UserCanceledException if I close the webview. There are also no error logs in the console.  Any ideas on what might be causing this behavior?

<img width="336" alt="Screenshot 2024-06-11 at 15 49 34" src="https://github.com/braintree/braintree_android/assets/65022791/d2df82c8-1a7e-45b5-a3bf-f68715ea8227">

### To reproduce

open webview and click on confirm button

### Expected behavior

invoke onPayPalSuccess method

### Screenshots

<img width="336" alt="Screenshot 2024-06-11 at 15 49 34" src="https://github.com/braintree/braintree_android/assets/65022791/1312e1b2-9b97-4b3f-a697-5d3f733229a9">

**Comment by sshropshire** [comment]
Hey @ISAACJGSANTOS thanks for this. What API Version of Android are you using to reproduce this issue?

**Comment by ISAACJGSANTOS** [comment]
hey @sshropshire I'm using api target 33

**Comment by sshropshire** [comment]
Thanks @ISAACJGSANTOS I'm having trouble reproducing this in our demo app. Have you tried a physical device as well?

**Comment by sshropshire** [comment]
@ISAACJGSANTOS if your Activity's launch mode is `singleTask`, please make sure you are overriding `onNewIntent()` as mentioned in our [MIGRATION_GUIDE](https://github.com/braintree/braintree_android/blob/main/v4.9.0%2B_MIGRATION_GUIDE.md#manual-browser-switching-for-browser-based-flows).

**Comment by ISAACJGSANTOS** [comment]
Hi sshropshire.

Sorry for the late answer, I already fixed the problem and it was related
with the launch mode of the activity.
Thank you for your help.
Have a nice day

**Comment by sshropshire** [comment]
@ISAACJGSANTOS thank you for confirming! We'll go ahead and close this issue out. Please feel free to re-open this issue (or create a new one) if needed.
