### ISSUE TITLE
PayPal web site is always in German by default, no matter which locale code I set for PayPalRequest request

### ISSUE THREAD

**Issue by nikolaykasyanov** [braintree/braintree_android#107]
Application language doesn't seem to be affecting the web site language too.

I guess PayPal determines language by IP?

**Comment by nikolaykasyanov** [comment]
Looks like PayPal issue: https://github.com/braintree/braintree_ios/issues/250#issuecomment-227212345

**Comment by lkorth** [comment]
See https://github.com/braintree/braintree_ios/issues/250#issuecomment-227810737
