### ISSUE TITLE
Direct Payment

### ISSUE THREAD

**Issue by erummalik** [braintree/braintree_android#108]
Using drop In UI is there direct anyway for transactions  without submit for settlement.

**Comment by sdcoffey** [comment]
Hey @erummalik,

You use the drop-in UI to get a `nonce` from Braintree, which is like a one-time use payment token. When you send this nonce to your server to create a transaction, you can specify whether to submit the transaction for settlement or not. [See the docs] (https://sandbox.braintreegateway.com/merchants/hh4cpc39zq4rgjcg/processor_connections/675266) on setting up your server
