### ISSUE TITLE
Paypal in dropin not working

### ISSUE THREAD

**Issue by shivam95** [braintree/braintree_android#110]
I have integrated Braintree in my android application.I am using drop in UI. But when I click on "Checkout With PayPal" Button the BrainTreePayment Activity finishes and onActivityResult is called with resultCode being 0 . It does not return any error. It does not open PayPal application or browser.

Please help me resolve this issue.

**Comment by shivam95** [comment]
I solved the issue . There were some underscores in my application id. Removing them fixed the issue.

**Comment by lkorth** [comment]
This has also been documented in https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2#browser-switch-setup

**Comment by econBabar** [comment]
Very weird requirement BTW. Wondering what harm could a underscore do!

**Comment by lkorth** [comment]
Underscores are not valid in urls. In order to support PayPal in a browser, the return url must be a valid url to return to the app. There should be no need to modify the app's package, however the url declared in your `AndroidManifest.xml` cannot contain `_`.

**Comment by econBabar** [comment]
Thanks for the quick answer. 
`There should be no need to modify the app's package, however the url declared in your AndroidManifest.xml cannot contain _. `
Unfortunately the above didn't work for me.
I had a package pattern like this com.example.android_abc. I tried the scheme without underscore like this
`<data android:scheme="com.example.android.abc.test.braintree"/>` i get this exception `com.braintreepayments.api.exceptions.BraintreeException: BraintreeBrowserSwitchActivity missing, incorrectly configured in AndroidManifest.xml or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/v2#browser-switch for the correct configuration`

So i scheme should match the package name for paypal browser activity to work.
 Please confirm if there still a way to for me not to change my package name for scheme.

**Comment by quinnjn** [comment]
@econBabar the example package you provided is: `com.example.android_abc`. So your example data scheme should be: `<data android:scheme="com.example.androidabc.braintree"/>`.

If you are still having issues with this, please open a new issue.

**Comment by econBabar** [comment]
@quinnjn  thanks mate, you might be right i was dumb to replace the _ with .

**Comment by tusharnetset** [comment]
Here, in my code, there is no mistake of like that, but still brainetree paypal is not working. Can someone suggest me what's the wrong with this.

**Comment by bluk** [comment]
@tusharnetset Please open a new issue with more details on how to reproduce your issue, or feel free to [contact Braintree Support](https://developers.braintreepayments.com/forms/contact) who can help with the integration.

**Comment by avnishebizon** [comment]
its simple to reproduce, after selecting the Braintree payment method, get the brainTreeToken using brainTreeTokenListener execute the Android sdk for Braintree to proceed further for the payment using code : 
DropInRequest dropInRequest = new DropInRequest()
                        .clientToken(token);
                startActivityForResult(dropInRequest.getIntent(MainActivity.INSTANCE), ConstantDataMember.BRAINTREECODE);

it will opens up a window with payment options : "Paypal & Credit card" in my case. When selecting paypal, nothings works. Actually after startActivityForResult, the Braintree sdk returns the resultcode '0',
which in my case is handleded as below :

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
          :
          :
 if (resultCode == Activity.RESULT_OK) {
                DropInResult result = data.getParcelableExtra(DropInResult.EXTRA_DROP_IN_RESULT);
                sendBrainTreeNonceToServer(result);
                // use the result to update your UI and send the payment method nonce to your server
            } else if (resultCode == Activity.RESULT_CANCELED) {
                Toast.makeText(MainActivity.INSTANCE, MainActivity.INSTANCE.getResources().getString(R.string.payment_cancel), Toast.LENGTH_SHORT).show();
                // the user canceled
            } else {
                // handle errors here, an exception may be available in
                Exception error = (Exception) data.getSerializableExtra(DropInActivity.EXTRA_ERROR);
                Toast.makeText(MainActivity.INSTANCE, MainActivity.INSTANCE.getResources().getString(R.string.payment_cancel), Toast.LENGTH_SHORT).show();
            }
        }
          :
          :
}

so definitely, braintree SDK is returning just the cancel result code in onActivityResult method, with data=null.

I am using gradle - compile 'com.braintreepayments.api:drop-in:3.0.0'
Also tried updating gradle version for this dependency still same problem exists.

Also tried above mentioned solution, even changed the bundle id to a fresh in case other device using same bundle id just for checking, but nothing works. If anyone found any fix, please post the fix.

**Comment by Lucem-Anb** [comment]
here is the best solution

` <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="packagename.braintree" />
            </intent-filter>
        </activity>`

Note that this line `<data android:scheme="packagename.braintree" />`  is the most important. Ensure that you change to your package

**Comment by Moseqi** [comment]
The same issue is happening to me. My package name is like com.example and i have set the scheme as  "com.example.braintree".

**Comment by sestevens** [comment]
Hi @Moseqi, if this seems like it's a bug in the `braintree_android` SDK, could you please open a new issue and fill out our issue template? It's very helpful if you can provide steps to reproduce the issue.

Otherwise, feel free to contact [Braintree Support](https://help.braintreepayments.com/) for help integrating with the SDK!

**Comment by Moseqi** [comment]
Hi @sestevens , It is not a bug. The SDK is working very well. I didn't see the error throwing by the SDK at that time. In my case,  the error was 'Merchant account not found', after solving the error Paypal dropin works fine. Sorry for my bad.

**Comment by sestevens** [comment]
@Moseqi Glad you were able to resolve the issue!

**Comment by VikramSN** [comment]
Facing same issue,
When click Paypal Dropin UI its giving error -> ErrorWithResponse (422): Parsing error response failed []

**Comment by sestevens** [comment]
@VikramSN Could you open a new issue in the [braintree-android-drop-in](https://github.com/braintree/braintree-android-drop-in) repo with more information, such as the version of Drop-in you're using?
