### ISSUE TITLE
How to show native paypal payment in v2?

### ISSUE THREAD

**Issue by vovkab** [braintree/braintree_android#113]
Hello 

I'm trying to switch v1 -> v2.

Starting paypal payment process:

```
PayPal.authorizeAccount(braintree);
```

And it always goes to browser. On v1 it would show native payment screen.

**Comment by lkorth** [comment]
Correct, v2 of the SDK only supports browser switch if the PayPal app is not installed, there is no native login experience in-process of your app.

**Comment by vovkab** [comment]
Any plans to bring it back?
I think old way have better UI and UX.

**Comment by vovkab** [comment]
@burnto but this is exactly what I'm using right now, no?
