### ISSUE TITLE
Disable Credit Card option when Using DropIn UI

### ISSUE THREAD

**Issue by VictorAlbertos** [braintree/braintree_android#114]
Hi :)

Is there any way to disable the credit card payment method using the DropIn library?

I found these methods, in order to disable other payment methods:

```java
new PaymentRequest()
            .disableAndroidPay()
            .disablePayPal()
            .disableVenmo()
```

But I wasn't able to find a method to disable the credit card payment method.

Thanks!

**Comment by lkorth** [comment]
No, there is currently no way to disable cards in the current implementation of Drop-In, however if you are looking to only use alternative payment methods you could use the [`PaymentButton`](https://github.com/braintree/braintree_android/blob/master/Drop-In/src/main/java/com/braintreepayments/api/PaymentButton.java). This is what Drop-In uses for non-card payment methods.

We are also working on some new UI for Drop-In and will keep this feature in mind.

**Comment by VictorAlbertos** [comment]
Thanks :)

**Comment by SnehaInGitHub** [comment]
> No, there is currently no way to disable cards in the current implementation of Drop-In, however if you are looking to only use alternative payment methods you could use the [`PaymentButton`](https://github.com/braintree/braintree_android/blob/master/Drop-In/src/main/java/com/braintreepayments/api/PaymentButton.java). This is what Drop-In uses for non-card payment methods.
> 
> We are also working on some new UI for Drop-In and will keep this feature in mind.

Not able to remove credit or debit card option. Your `PaymentButton` link is not working. Please help.
