### ISSUE TITLE
Strict mode violation in HttpClient

### ISSUE THREAD

**Issue by DonSimonBolivar** [braintree/braintree_android#115]
E/StrictMode(21768): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
E/StrictMode(21768): java.lang.Throwable: Explicit termination method 'end' not called
E/StrictMode(21768): 	at dalvik.system.CloseGuard.open(CloseGuard.java:184)
E/StrictMode(21768): 	at java.util.zip.Inflater.<init>(Inflater.java:82)
E/StrictMode(21768): 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:103)
E/StrictMode(21768): 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:88)
E/StrictMode(21768): 	at com.braintreepayments.api.internal.HttpClient.readStream(HttpClient.java:292)
E/StrictMode(21768): 	at com.braintreepayments.api.internal.HttpClient.parseResponse(HttpClient.java:241)
E/StrictMode(21768): 	at com.braintreepayments.api.internal.BraintreeHttpClient.parseResponse(BraintreeHttpClient.java:121)
E/StrictMode(21768): 	at com.braintreepayments.api.internal.HttpClient$1.run(HttpClient.java:154)
E/StrictMode(21768): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/StrictMode(21768): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/StrictMode(21768): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/StrictMode(21768): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/StrictMode(21768): 	at java.lang.Thread.run(Thread.java:818)
W/System.err(21768): StrictMode VmPolicy violation with POLICY_DEATH; shutting down.

**Comment by lkorth** [comment]
@DonSimonBolivar thank you for bringing this to our attention. It has been fixed and will be available in the next release.
