### ISSUE TITLE
BraintreePaymentActivity should allow me to provide the Executor

### ISSUE THREAD

**Issue by DonSimonBolivar** [braintree/braintree_android#116]
BraintreePaymentActivity creates an executor in onPaymentMethodNonceCreated.  This class should allow me to provide the executor.

**Comment by sdcoffey** [comment]
Hey @DonSimonBolivar,

Can you elaborate on what you mean? While I don't believe that would work given the limits of inter-activity communication, there might be another way to accomplish what you're trying to do.

**Comment by DonSimonBolivar** [comment]
I want to control the thread pool that BraintreePaymentActivity uses.  Obviously I can't pass one as an extra in the intent, but I can extend BraintreePaymentActivity, and then specify that I want to use my extended Activity when I launch an intent from a PaymentRequest.  

But that still doesn't help me because the executor creates the thread pool in a method that does a lot of other things that I don't want to change (I'm talking about onPaymentMethodNonceCreated(...)).  

If there were a method called getExecutorService() that by default returned the same executor that's created in onPaymentMethodNonceCreated(...), but was protected so I could override it, that would not change the default behavior of the BraintreePaymentActivity, but would allow me to substitute the Executor so that I can have the control over the thread pool that I want.

**Comment by sdcoffey** [comment]
Interesting idea. Just out of curiosity, why do you want to control the thread pool in this context? Not to say that we can't make this change, but it's a highly unusual request and I think in general we want to discourage changes that could have unintended negative side effects on the user experience.

**Comment by DonSimonBolivar** [comment]
My app uses specific executors that I need to be able to control.  If I can pass my own executor, I can make sure that the thread used for this creation comes out of the thread pool I've already allocated for my app.  There's no need to have a separate thread pool just for this.

It's not that unusual a pattern.  If you look at https://google.github.io/guava/releases/19.0/api/docs/com/google/common/util/concurrent/Futures.html, many of the methods on that class accept an executor.

There should be no negative side effects on the UX, because for people who aren't purposely changing it, it will be exactly the same.

**Comment by sdcoffey** [comment]
Yeah, that's interesting. Again, not a bad idea or something we can't accomplish, but because this is nonstandard, I'm going to close this until we start seeing more requests of this nature. In the meantime, feel free to fork this project and implement the changes yourself.

Thanks again for the feedback!
