### ISSUE TITLE
SamsungPayNonce fails on Android when debuggable flag is False

### ISSUE THREAD

**Issue by yarodevuci** [braintree/braintree_android#1168]
### Braintree SDK Version

4.41.0

### Environment

Production

### Android Version & Device

Android 12

### Braintree dependencies

implementation 'com.braintreepayments.api:card:4.41.0'
    implementation 'com.braintreepayments.api:google-pay:4.41.0'
    implementation 'com.braintreepayments.api:samsung-pay:4.41.0'
    implementation 'com.braintreepayments.api:venmo:4.41.0'
    implementation 'com.braintreepayments.api:data-collector:4.41.0'
    implementation 'com.braintreepayments.api:paypal:4.41.0'

### Describe the bug

```
public class SamsungPayNonce extends PaymentMethodNonce {

    @NonNull
    static SamsungPayNonce fromJSON(JSONObject inputJson) throws JSONException {
        JSONObject data = new JSONObject(inputJson.getString("data"));
        JSONObject braintreeData = new JSONObject(data.getString("data"));
```

Getting exception: JSONObject["data"] is not a string (class org.json.b).
This does not happen when debuggable is set to true. Happens only when it set to false. No idea how that is related to the Braintree. 
buildTypes {
    release {
                debuggable false
            }

### To reproduce

Use Samsung pay any payment (credit card/paypal) and exception is thrown. We tried older version and latest SDK version. Bug is still present

### Expected behavior

Success payment

**Comment by yarodevuci** [comment]
Solution found
-keep class org.json.** { *; }
-keepclassmembers class org.json.** { *; }
added to proguard rules...

**Comment by tdchow** [comment]
hi @yarodevuci - thanks for raising this issue. The SamsungPay module was removed in 5.0.0 and will no longer be supported. Thanks for finding the required proguard rules!
