### ISSUE TITLE
Could not find org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-5

### ISSUE THREAD

**Issue by minhnc** [braintree/braintree_android#1175]
### Braintree SDK Version

4.49.1

### Environment

Sandbox

### Braintree dependencies

'com.braintreepayments.api:data-collector:4.49.1'
 'com.braintreepayments.api:three-d-secure:4.49.1'
 'com.braintreepayments.api:card:4.49.1'

### Describe the bug

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> Could not resolve all dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-5.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom
       - https://repo.maven.apache.org/maven2/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom
       - file:/Users/nguyeco/metcash/iga-rewards/node_modules/jsc-android/dist/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom
       - https://dl.google.com/dl/android/maven2/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom
       - https://www.jitpack.io/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom
       - file:/Users/nguyeco/metcash/iga-rewards/node_modules/react-native/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom
       - https://appboy.github.io/appboy-android-sdk/sdk/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom
       - https://nexus.dyneti.com/repository/maven-releases/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.pom
     Required by:
         project :app > project :expo > project :expo-braintree > com.braintreepayments.api:three-d-secure:4.49.1

### To reproduce

Just build project normally, it used to work yesterday.

### Expected behavior

Build project succesfully

### Screenshots

<img width="1728" alt="Screenshot 2024-10-01 at 12 13 10 PM" src="https://github.com/user-attachments/assets/62075620-3857-4f42-8c3f-dfbbd9da59e6">

**Comment by sshropshire** [comment]
Hey @minhnc we had to update the credentials for accessing the Cardinal SDK recently. Can you try using [these credentials](https://github.com/braintree/braintree_android/blob/main/v4_MIGRATION_GUIDE.md#3d-secure) and see if you still have a build issue?

**Comment by minhnc** [comment]
Thanks @sshropshire, the new [credentials](https://github.com/braintree/braintree_android/blob/main/v4_MIGRATION_GUIDE.md#3d-secure) work 🎉
