### ISSUE TITLE
BraintreeErrorListener And BraintreeCancelListener Not Called

### ISSUE THREAD

**Issue by HSY229** [braintree/braintree_android#118]
Callback method `onCancel(requestCode)` is not called when I press the back button of device. It just pass `Activity#RESULT_CANCELED` result code in my Activity's `onActivityResult`.

Callback method `onError(error)` is not called when I press buy button without network. It also pass `Activity#RESULT_CANCELED` result code in my Activity's `onActivityResult`.

I use the drop in UI of demo project with version 2.3.7.
I use `BraintreeFragment#addListener `to register `BraintreeErrorListener` and `BraintreeCancelListener` when initial `BraintreeFragment`.

```
public class MainActivity extends BaseActivity implements PaymentMethodNonceCreatedListener,
        BraintreeCancelListener, BraintreeErrorListener {

    ...

    @Override
    protected void onAuthorizationFetched() {
        try {
            mBraintreeFragment = BraintreeFragment.newInstance(this, mAuthorization);
            mBraintreeFragment.addListener((BraintreeErrorListener)this);
            mBraintreeFragment.addListener((BraintreeCancelListener)this);
            enableButtons(true);
        } catch (InvalidArgumentException e) {
            showDialog(e.getMessage());
        }
    }

    @Override
    public void onError(Exception error) {
        Log.e(TAG, "onError(): " + error.getMessage());
    }

    @Override
    public void onCancel(int request) {
        Log.d(TAG, "onCancel");
    }

    ...
}
```

Genymotion 2.7.2
Samsung Galaxy S5 Android 4.4.4

**Comment by lkorth** [comment]
The `MainActivity` of the demo app contains a `BraintreeFragment` and listeners solely for 3D Secure verification. Drop-In uses [the standard Android inter-activity communication](https://developer.android.com/training/basics/intents/result.html) with `Activity#startActivityForResult`. If you look at [`MainActivity#onActivityResult`](https://github.com/braintree/braintree_android/blob/f913a46948d89aa2854a3f568310c30f94bbf306/Demo/src/main/java/com/braintreepayments/demo/MainActivity.java#L174) the response from Drop-In is processed only in that method. There is also [further documentation in the docs](https://developers.braintreepayments.com/guides/drop-in/android/v2).

**Comment by HSY229** [comment]
@lkorth 
I try to use  `BraintreePaymentActivity.BRAINTREE_RESULT_DEVELOPER_ERROR`、`BraintreePaymentActivity.BRAINTREE_RESULT_SERVER_ERROR` and `BraintreePaymentActivity.BRAINTREE_RESULT_SERVER_UNAVAILABLE`; 

I turn off the wifi, then I just got `Activity.RESULT_CANCELED`.

**Comment by lkorth** [comment]
If you have no network connection when Drop-In is started you should be receiving a server error or unexpected error back. Canceled is only returned when the back button or up is pressed.

**Comment by HSY229** [comment]
Yes, you are right. 
The problem is I did not receive server error or unexpected error back,
but I should receive them.

How can I fix this?

**Comment by lkorth** [comment]
We'll need more information and steps on how to reproduce it before it's clear what is happening.
