### ISSUE TITLE
 Fragment BraintreeFragment not attached to Activity

### ISSUE THREAD

**Issue by AGovtvyanitca-softheme** [braintree/braintree_android#121]
Hi guys. I faced with many crashes like this:

```
java.lang.IllegalStateException: Fragment BraintreeFragment{65c0784} not attached to Activity
1	at android.app.Fragment.startActivityForResult(Fragment.java:1119)
2	at android.app.Fragment.startActivityForResult(Fragment.java:1110)
3	at com.braintreepayments.api.PayPal.startPayPal(PayPal.java:329)
4	at com.braintreepayments.api.PayPal.access$100(PayPal.java:51)
5	at com.braintreepayments.api.PayPal$2.success(PayPal.java:218)
6	at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:286)
7	at android.os.Handler.handleCallback(Handler.java:739)
8	at android.os.Handler.dispatchMessage(Handler.java:95)
9	at android.os.Looper.loop(Looper.java:148)
10	at android.app.ActivityThread.main(ActivityThread.java:5551)
11	at java.lang.reflect.Method.invoke(Native Method)
12	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
13	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

What should I do with this issue?

**Comment by lkorth** [comment]
What version are you using? This was fixed in [2.3.7](https://github.com/braintree/braintree_android/releases/tag/2.3.7)

**Comment by AGovtvyanitca-softheme** [comment]
I used compile 'com.braintreepayments.api:braintree:2.+'
Thanks for you answer, I will use new versoin

**Comment by lkorth** [comment]
`2.+` should already be providing you the latest version. Check which version is being compiled in in your build folder to see what version you are actually using.

**Comment by AGovtvyanitca-softheme** [comment]
as I can see I am using _com.braintreepayments.api-core-2.3.9_

**Comment by AGovtvyanitca-softheme** [comment]
maybe I should use some specific version?

**Comment by lkorth** [comment]
[`BraintreeFragment` already contains a check in `Fragment#startActivityForResult`](https://github.com/braintree/braintree_android/blob/83e2ba740752914811bdbf3d8066e9858d0ee850/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L321) that checks [`Fragment#isAdded`](https://developer.android.com/reference/android/app/Fragment.html#isAdded()) before calling `super#startActivityForResult`. The same check `BraintreeFragment` uses is also used in `Fragment#startActivityForResult` to check if this `RuntimeException` should be thrown.

Are you running into this in development with 2.3.9 or is this in a released version of your app?

**Comment by AGovtvyanitca-softheme** [comment]
It's realesed build. And as I can see from release date 2.3.7, release was before it's date. Thank you for your answers

**Comment by lkorth** [comment]
@AGovtvyanitca-softheme we are also starting to use `Fragment#commitNow` on API 24 and higher to help avoid this.
