### ISSUE TITLE
Android 15 support in 4.x major

### ISSUE THREAD

**Issue by francescocervone** [braintree/braintree_android#1229]
### Braintree SDK Version

4.49.1

### Environment

Sandbox

### Braintree dependencies

- com.braintreepayments.api:card:4.49.1
- com.braintreepayments.api:braintree-core:4.49.1
- com.braintreepayments.api:data-collector:4.49.1
- com.braintreepayments.api:google-pay:4.49.1
- com.braintreepayments.api:paypal:4.49.1
- com.braintreepayments.api:three-d-secure:4.49.1
- com.braintreepayments.api:drop-in:6.16.0

### Describe the bug

[Android 15 has forced edge to edge](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge) automatically for all activities.

Judging from the behavior of the 3DSecure verification in the sandbox environment and 5.x release notes, it seems that edge to edge for Android 15 is not supported in 4.x Braintree versions.

We depend on Braintree 4.x and we were trying to increase our target SDK to 35 (Android 15), but we found out about this behavior. 
If that behavior is also in production, then upgrading Braintree to the 5.x would be a blocker to upgrade the Android target SDK to 35. 
As you know migrating from Braintree 4 to 5 is not exactly seamless, some APIs have changed and we need to adapt our code.

Now, I see that in the [versions table](https://github.com/braintree/braintree_android?tab=readme-ov-file#versions) in your README the 4.x is declared as `Inactive`, which by reading your [policy](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v4) means: _No new features will be added, only security updates._

1. Is supporting Android 15 considered a "new feature"?
2. Is there any plan to backport the Android 15 support to the 4.x version?
3. Is there any workaround to disable the edge to edge enforcement to allow clients with target SDK 35 to use Braintree 4.x without official support? Or should we avoid that (maybe because you know that something would break really bad)?
4. As far as you know, is there any other flow affected by this issue?
5. Is the issue affecting also production?

Thanks!

### To reproduce

- Run a 3DSecure verification on an app targeting Android API 35 with Braintree 4.x
- The 3DSecure screen is drawn behind the status bar incorrectly

### Expected behavior

- All Braintree screens handle window insets correctly in all Android versions, 15 included.

### Screenshots

![Screenshot_20241204_125233](https://github.com/user-attachments/assets/21b43a31-3ff7-47ac-8bb9-2913986d6c45)

**Comment by francescocervone** [comment]
I have a follow-up question.
I believe this activity is handled by Cardinal, correct me if I'm wrong, and by looking at [their changelog](https://cardinaldocs.atlassian.net/wiki/spaces/CMSDK/pages/11862033/Cardinal+Mobile+SDK+-+Android), I don't see any update to support SDK 35. 

Is this behavior broken also in Braintree 5.x?

**Comment by tdchow** [comment]
Hi @francescocervone - I just tried reproducing on an Android 15 emulator and was not able to see the same full screen bug you shared above. I tested off of the `4.x` branch.

Can you share exactly how you were able to see the bug? Thanks!

**Comment by francescocervone** [comment]
That's strange. Was the target SDK of the reproducing app set to 35?

**Comment by tdchow** [comment]
🤦‍♂️ Apologies! I forgot to set the target SDK to 35. In the end, I was able to reproduce the issue.

Unfortunately, we do not plan to add Android 15 support to v4 (unless an issue blocks a successful payment flow). I'd recommend updating to v5 for Android 15 support.

Here's the migration guide: https://github.com/braintree/braintree_android/blob/main/v5_MIGRATION_GUIDE.md

**Comment by francescocervone** [comment]
Ok, thanks for the response and for reproducing the issue.

My point about the v5 is if that activity is managed by Cardinal, and if the Cardinal SDK was not updated between Braintree 4.49.1 and Braintree 5.2.0, the issue is likely to happen also in the 5.x. 
I didn't have time to test it on the 5.x, though.

**Comment by tdchow** [comment]
That makes sense. We'll do some testing on v5 and contact Cardinal for the fix if needed!

I'm going to close this issue as we do not have plans to address this in v4.

**Comment by francescocervone** [comment]
Thanks. I've opened a separate issue for Braintree 5: https://github.com/braintree/braintree_android/issues/1236
