### ISSUE TITLE
Missing rule in ProGuard file

### ISSUE THREAD

**Issue by nzakharchenko** [braintree/braintree_android#124]
Hey guys!

I'm using latest version of your SDK
`compile "com.braintreepayments.api:braintree:2.3.10"`

where you've mentioned that you moved ProGuard directives inside SDK
`Include ProGuard directives in the SDK` https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#2310

but my build fails with such warnings:

`Warning: com.braintreepayments.api.DataCollector$2$1: can't find superclass or interface com.kount.api.DataCollector$CompletionHandler
Warning: com.braintreepayments.api.DataCollector: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector$LocationConfig
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector$LocationConfig
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector$CompletionHandler
Warning: com.braintreepayments.api.DataCollector$2: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2$1: can't find referenced class com.kount.api.DataCollector$CompletionHandler
Warning: com.braintreepayments.api.DataCollector$2$1: can't find referenced class com.kount.api.DataCollector$Error
Warning: com.braintreepayments.api.DataCollector$2$1: can't find referenced class com.kount.api.DataCollector
Warning: com.braintreepayments.api.DataCollector$2$1: can't find referenced class com.kount.api.DataCollector$Error
Warning: com.braintreepayments.api.DataCollector$2$1: can't find referenced class com.kount.api.DataCollector$Error
`

And in file https://github.com/braintree/braintree_android/blob/master/Braintree/proguard.pro you have different rules then in SDK and looks like the missing one is `-dontwarn com.kount.**`

Could you, please, add it to next version?

Best Regards
Nick

**Comment by quinnjn** [comment]
Hey @nzakharchenko !

We will be adding `-dontwarn com.kount.**` in the next release.

See #123

**Comment by nzakharchenko** [comment]
Thank you @quinnjn !
