### ISSUE TITLE
Passkey support

### ISSUE THREAD

**Issue by ivancarras** [braintree/braintree_android#1240]
### Is your feature request related to a problem? Please describe.

Are you planning supporting passkey in the native SDK? 

https://www.paypal.com/us/money-hub/article/how-do-passkeys-work

### Describe the solution you'd like.

https://www.paypal.com/us/money-hub/article/how-do-passkeys-work

**Comment by tdchow** [comment]
Hey @ivancarras - there are no plans to add passkey support in the PayPal Native Checkout as the module was deprecated in v4 and removed in v5. See https://developer.paypal.com/braintree/docs/guides/paypal/mobile-checkout/android/v5 for additional deprecation information.

However, passkeys are supported in the PayPal Checkout (web) module which we recommend you to migrate to. Hope this helps!
