### ISSUE TITLE
Card.tokenize Listeners never called 

### ISSUE THREAD

**Issue by danielhusc** [braintree/braintree_android#126]
After receiving the Braintree client token, none of the listeners' methods are called and the app I'm building freezes. Below is my code, am I doing something wrong? All the inputs and variables are correct.

```java
try {
            final BraintreeFragment fragment = BraintreeFragment.newInstance(activity, braintreeClientToken);
            final PaymentMethodNonceCreatedListener noncelistener = new PaymentMethodNonceCreatedListener() {
                @Override
                public void onPaymentMethodNonceCreated(PaymentMethodNonce paymentMethodNonce) {
                   callback.onTokenizeCardSuccess(paymentMethodNonce.getNonce());
                }
            };
            final BraintreeErrorListener errorListener = new BraintreeErrorListener() {
                @Override
                public void onError(Exception error) {
                    callback.onTokenizeCardFailure();
                }
            };
            fragment.addListener(new ConfigurationListener() {
                @Override
                public void onConfigurationFetched(Configuration configuration) {
                    android.util.Log.d("hi", "hi1");
                }
            });
            fragment.addListener(new BraintreeCancelListener() {
                @Override
                public void onCancel(int requestCode) {
                     android.util.Log.d("hi", "hi2");
                }
            });
            fragment.addListener(noncelistener);
            fragment.addListener(errorListener);

            CardBuilder cardBuilder = new CardBuilder();
            cardBuilder.cardNumber(card.getNumber());
            cardBuilder.expirationMonth(card.getExpMonth().toString());
            cardBuilder.expirationYear(card.getExpYear().toString());
            cardBuilder.cvv(card.getCVC());
            cardBuilder.postalCode(card.getAddressZip());
            Card.tokenize(fragment, cardBuilder);
        } catch (InvalidArgumentException e) {
            android.util.Log.d("hi", "hi3");
            callback.onTokenizeCardFailure();
        }
```

**Comment by danielhusc** [comment]
This is version 2.3.11 by the way.

**Comment by lkorth** [comment]
Is this being run on a background thread? Do you have any logs or an ANR trace from when this happens?

**Comment by danielhusc** [comment]
Yes it is run on a background thread as a callback after the client token is retrieved. Is that an issue? Let me get some logs

**Comment by lkorth** [comment]
Yes, everything in the SDK is designed to run on the main thread.

**Comment by danielhusc** [comment]
Okay so I tried running it on the Main thread using:

```
Handler mainHandler = new Handler(activity.getMainLooper());
                        Runnable myRunnable = new Runnable() {
                            @Override
                            public void run() {
                                braintreeTokenizeCard(braintreeClientToken, activity, card, callback);
                            }
                        };
                        mainHandler.post(myRunnable);
```

But it's still causing the issue where my app would just freeze. It looks like there's some infinite loop that causes this Log message:

`Rejecting re-init on previously-failed class java.lang.Class<com.braintreepayments.api.internal.BraintreeHttpClient>`

**Comment by lkorth** [comment]
Have you looked at the ANR trace when your app freezes? Do you have a simple app where you can reproduce this issue, or changes you can make to the demo app in this repo that also cause this error? It seems like there are still some issues with how it's being run.

**Comment by danielhusc** [comment]
So I have figured out the issue. The problem was because the jar file produced by this repo is named 'core-2.3.11.jar`. There was another jar file produced by a repo called `spongycastle` named `core-1.54.0.0.jar` and gradle had issues determining where packages were coming from as they were both named `core`. I'm not sure why this issue wasn't picked up during compile time. But configuring gradle to rename the jar files, everything worked fine. I suggest perhaps in a future update, you guys could rename it to `braintreecore` or something. Thanks!

**Comment by lkorth** [comment]
Dependences are namespaced by their package. Unless you're downloading the jars and aars and including them manually, Gradle should have no issue with similarly named artifacts. If you can reproduce this in the demo app in this repo, please comment with your setup and we'll investigate it further.
