### ISSUE TITLE
NullPointerException com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteResponseHandler)' on a null object reference

### ISSUE THREAD

**Issue by shriyajangid** [braintree/braintree_android#129]
commandStr = "ffmpeg -y -i " + old_video_path +
                        " -strict experimental -vf curves=vintage -s 240x320 -r 30 -aspect " +
                        "4:3 -ab 48000 -ac 2 -ar 22050 -b 2097k -vcodec mpeg4 -preset ultrafast "
                        + path + "/WeRgold_" + "NAME" + ".mp4";

**Comment by lkorth** [comment]
This has nothing to do with this repo.
