### ISSUE TITLE
venmo availability check doesn't work after version 2.3.9

### ISSUE THREAD

**Issue by quietbits** [braintree/braintree_android#131]
Below code is working fine in version 2.3.9, but somehow it stopped working in newer versions. The strange thing is that sometimes it works in debug mode, but never in release mode.

```
braintreeVenmoFragment = BraintreeFragment.newInstance(getCurrentActivity(), this.clientToken);

venmoEnabledListener = new ConfigurationListener() {
	@Override
	public void onConfigurationFetched(Configuration configuration) {
		// This is never called
		venmoEnabled = configuration.getPayWithVenmo().isEnabled(getCurrentActivity());
		...
	}
};

// Adding listener, which doesn't work after version 2.3.9
braintreeVenmoFragment.addListener(venmoEnabledListener);
```

This was tested on macOS running Android Studio 2.2, using Android devices (Nexus 7 running Android 6.0.1 and Nexus 6p running Android 7.0), both with the same results.

Any idea what could be wrong? Thanks for any input.

**Comment by quinnjn** [comment]
Hey @quietbits!

Your integration looks correct. We had some [Elevated API Errors](https://status.braintreepayments.com/incidents/yczhsrrkv8rh) around the time that you had posted this which may have have been the issue.

I'd also recommend you add the [ErrorListener](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2#register-listeners) to find out if any errors are being thrown during configuration fetching.

Do you mind retrying and letting us know what you get back for errors?

**Comment by quietbits** [comment]
Hey, @quinnjn!

Thanks for your quick response. I don't think this issue is related to Elevated API Errors from earlier today, because we had the same issue before today, but couldn't figure it out.

Unfortunately, ErrorListener doesn't log anything. Anything else we could try? Thanks again!

**Comment by quinnjn** [comment]
ConfigurationManager will callback to [ConfigurationListener on success](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/ConfigurationManager.java#L68) or [ErrorListener on failure](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/ConfigurationManager.java#L71) so you should be getting a callback on one of those listeners.

Is this all done in `onCreate` ?
If you're using proguard, can you provide the rules?

**Comment by quietbits** [comment]
We're not using proguard, and our app is built in React Native, so we can't call it onCreate, because there is only one activity. Any idea what changed in versions after 2.3.9 that could cause this?

We still have the same React Native version and the only thing that was updated is Braintree. Everything works fine in 2.3.9, but not on newer versions. It's very strange that neither listener is called. No errors either, it just skips them.

**Comment by quinnjn** [comment]
I don't see any significant changes to BraintreeFragment > 2.3.9 that would break listeners.

In the provided code snippet it doesn't look like you guys are catching the `InvalidArgumentException` that might be thrown from `BraintreeFragment.newInstance` if the fragment cant be attached, or authorization string is invalid. 

I'm not up to speed on React Native so I'd like to see a complete example of the class that reproduces this problem if possible.

**Comment by quietbits** [comment]
We might have found what is causing this, but we're still investigating. We're running AndroidPay and Venmo checks in parallel (AP going first). After removing AP check and running Venmo only, it works 100% of the time. Now we just need to find another way how to run them both.

Thanks for your help and quick responses, @quinnjn!

**Comment by quinnjn** [comment]
Glad to hear we're making progress!

`BraintreeFragment#addListener` only takes [one listener for each listener type](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L355-L381) so if you're setting multiple `ConfigurationListener`s you're only going to get a callback on the latest added one. 

If you are using multiple listeners on the same BraintreeFragment instance you should just combine your Android and Venmo checks in the same listener.

**Comment by quietbits** [comment]
That's exactly what we did and it works now. Maybe it was a coincidence that it worked before, but it's definitely better now. Thanks again for your help, @quinnjn!
