### ISSUE TITLE
Back button does not return to app with Samsung devices

### ISSUE THREAD

**Issue by sdcoffey** [braintree/braintree_android#137]
On January 6th, 2016 @ericn37 reported [this](https://github.com/braintree/braintree-android-drop-in/issues/16) issue in braintree-android-drop-in. This is actually an issue with `braintree_android`, so the issue is moved here.

**Comment by ericn37** [comment]
Thank you @lkorth , may ask for an estimation of when next release will be out?

**Comment by lkorth** [comment]
@ericn37 we'll have a release out by the end of the week
