### ISSUE TITLE
Droup-in-ui : Venmo payment - Unable to refresh

### ISSUE THREAD

**Issue by jagatappv** [braintree/braintree_android#138]
Hey,

I've used drop-in ui and trying to use venmo as my payment method.

On selecting Venmo I'm getting the below error:

"Unable to refresh
Please check your internet connection.
Try again"

My internet is working fine and working internet in all other app of my device.
Its also working if I select other payment option.

I'm attaching screenshot for more clear picture.

Please help me to resolve this issue.
![device-2017-01-10-030840](https://cloud.githubusercontent.com/assets/10743189/21798441/79bd27d2-d6e2-11e6-93bf-4ac249429b00.png)

Thanks

**Comment by bhautikappv** [comment]
+1

**Comment by sdcoffey** [comment]
This looks to have been an intermittent issue. Can you verify that it either works now, or is still failing to connect?

**Comment by sdcoffey** [comment]
@jagatappv @bhautikappv 

This is the error message you receive when a user is not signed into the venmo app. There must be a valid user logged into Venmo in order to use it as a payment method.

**Comment by lkorth** [comment]
Venmo is tracking this bug and will have a fix in a future release.

**Comment by bhautikappv** [comment]
@sdcoffey : How can I login into the app while redirect from my app when user is already not logged into the Venmo app?

**Comment by lkorth** [comment]
You cannot, you would need to open Venmo on it's own to log in.

**Comment by bhautikappv** [comment]
ok

**Comment by harirao001** [comment]
Hey, @lkorth 

Venmo is tracking this bug and will have a fix in a future release.
--> As its showing unrelated error from android.  Is there any way to hide venmo option from drop-in ui?

Thanks for the support

**Comment by lkorth** [comment]
No, there is no way to know if the user is logged in to the Venmo app or not.
