### ISSUE TITLE
AndroidPayActivity - closing activity causes runtime exception

### ISSUE THREAD

**Issue by JoshJustPark** [braintree/braintree_android#139]
issue created/arisen from fix in 2.4.1 (changePaymentMethod)

repro:

- using changePaymentMethod to open Braintree's AndroidPayActivity
- user presses back or uses "x" button to close screen.
- runtimeException thrown.

stack trace snippet:

`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {com.justpark.jp.debug/com.braintreepayments.api.AndroidPayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.putExtra(java.lang.String, android.os.Parcelable)' on a null object reference`

source of issues seems to be in OnActivityResult method in AndroidPayActivity. (line 141?)

**Comment by lkorth** [comment]
Thanks for the report @JoshJustPark! This has been fixed and will go out in the next release.

**Comment by matthewbrooks** [comment]
We've just come across this issue. Do you know when the next release might be?

**Comment by lkorth** [comment]
@matthewbrooks we'll make a release in the next day or two.

**Comment by lkorth** [comment]
This was just released in [2.4.2](https://github.com/braintree/braintree_android/releases/tag/2.4.2).
