### ISSUE TITLE
Upgrading to 1.2.7 causes Errors

### ISSUE THREAD

**Issue by PoseDev** [braintree/braintree_android#14]
I did go to BuildTools 21.1.1.  My project grade is on 1.0.0-rc4

exploded-aar/com.braintreepayments.api/braintree/1.2.7/res/layout/bt_payment_button.xml
Error:(18) No resource identifier found for attribute 'layout_toStartOf' in package 'android'
Error:(26) No resource identifier found for attribute 'layout_toEndOf' in package 'android'

/exploded-aar/com.braintreepayments.api/braintree/1.2.7/res/layout/bt_payment_description.xml
Error:(18) No resource identifier found for attribute 'layout_alignParentStart' in package 'android'
Error:(29) No resource identifier found for attribute 'layout_alignParentStart' in package 'android'
Error:(41) No resource identifier found for attribute 'layout_alignParentEnd' in package 'android'

/exploded-aar/com.braintreepayments.api/braintree/1.2.7/res/layout/bt_payment_method.xml
Error:(4) No resource identifier found for attribute 'layout_alignParentStart' in package 'android'
Error:(4) No resource identifier found for attribute 'layout_marginStart' in package 'android'
Error:(14) No resource identifier found for attribute 'layout_toEndOf' in package 'android'
Error:(14) No resource identifier found for attribute 'layout_marginStart' in package 'android'
Error:(26) No resource identifier found for attribute 'layout_toEndOf' in package 'android'

**Comment by lkorth** [comment]
@PoseDev were you able to solve your issue?

**Comment by lkorth** [comment]
Closing old issue. If you are still have this issue, please feel free to comment and we'll re-open it.

**Comment by you6878** [comment]
I used android studio. I solved. change the compileSdkVersion 21 from 16
