### ISSUE TITLE
Android Pay Activity orientation change bug

### ISSUE THREAD

**Issue by RadoslawHardyl** [braintree/braintree_android#146]
Hey guys,

There is an issue with Android Pay Activity, and change of its orientation.
Every time you change activity orientation, new Android Pay bottom sheet will open.

environment:
- SDK 2.5.1

steps to reproduce:
1. start Android Pay Activity
2. rotate screen

AC:
- only one bottom sheet will be visible

Actual Result:
- another bottom sheet will appear on top, and you can swipe down all previous views.

Best
Radek

**Comment by lkorth** [comment]
Thanks for the report! This has been fixed and will go out in the next release.
