### ISSUE TITLE
Incorrect Android Pay Activity behaviour with "don't keep Activities" enabled.

### ISSUE THREAD

**Issue by RadoslawHardyl** [braintree/braintree_android#147]
Hey guys,

We realized that Android Pay is ignoring wallet response if two factors are present:
- "don't keep Activities" developer option is enabled
- confirm AP card selection with pattern

environment:
- SDK ver 2.5.1

steps to reproduce:
1. enable "don't keep Activities"
2. start Android Pay Activity
3. select card
4. confirm card with pattern

AC:
- Android Pay Activity will close and nonce will be returned

Actual Result:
- Activity is ignoring AP result and opens new Android Pay bottom sheet

Best
Radziu

**Comment by lkorth** [comment]
I wasn't able to reproduce this, but I believe it was fixed along with the fix for #146.

If you are able to reproduce it using the demo app in this repo, please let us know.

**Comment by RadoslawHardyl** [comment]
Hi Luke,

looks like this issues are related.
I have checked with master branch(commit: 3039c0326d1d1626f792fb5133c76be6aadff826), and issue is no longer present there.
Thanks for your hard work!

Best
Radek

**Comment by lkorth** [comment]
Great, thanks for letting us know!

I'll close this issue. We'll work on tracking down your one other issue (#145) and make a release soon.
