### ISSUE TITLE
Venmo : How to know user is sign in or not?

### ISSUE THREAD

**Issue by asif-patel** [braintree/braintree_android#148]
Hey,

I am using drop-in UI and trying to use venmo as my payment method in android.

but i got the error of "Unable to refresh". and i know that this error is occur due to user is not logged in.
so can anyone tell me that how to know the user is sign in or not in venmo app?

Thanks,

**Comment by lkorth** [comment]
Drop-in has actually moved to [a new repo](https://github.com/braintree/braintree-android-drop-in).

The Venmo app on Android should prompt the user to log in to the app if they are not already, could you share the version of the Venmo app that you're seeing this in?

**Comment by asif-patel** [comment]
Venmo version is 6.36.1.

**Comment by lkorth** [comment]
The first version of the Venmo app that will prompt the user to log in is 6.37.0, if you update to that version or newer this should be fixed.
