### ISSUE TITLE
TLSv1.2 support for Android API 19

### ISSUE THREAD

**Issue by maxbpro** [braintree/braintree_android#150]
TLSv1.2 is the default for client connections in API 20

All Android app developers must make sure that their code and PayPal or Braintree SDKs provide explicit support for TLSv1.2. To verify correct implementation, test apps on API 16 through 19 devices (Android 4.1 through 4.4 platforms).

What exactly should I do? I need support for Android API 19

**Comment by lkorth** [comment]
If you click through to the [supported SDKs list](https://github.com/paypal/TLS-update/blob/master/Braintree/README.md#android) on that page you'll find that version 1.7.6 or greater and version 2.1.0 or greater of this SDK already supports TLSv1.2 and will work just fine on API 16 and up.
