### ISSUE TITLE
Databinding generating multiple DynamicUtil.java files

### ISSUE THREAD

**Issue by deandalm** [braintree/braintree_android#154]
### General information
Databinding generating multiple DynamicUtil.java files.

* SDK/Library version: com.braintreepayments.api.braintree:2.5.4
* Gradle Plugin 3.0.0-alpha4
* Gradle 4.0-rc-1-all

### Issue description
After adding gcacace's signature-pad:1.2.1 library, I started getting the following error:

```
Error:Execution` failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'android/databinding/DynamicUtil.java'
```

After further investigation, I noticed that braintree-2.5.4 is generating a DynamicUtil.java file and so is adapsters-1.2.1. Any ideas how to resolve this issue?

**Comment by lkorth** [comment]
Thanks for the report @deandalm, we're looking into a way to clean up this artifact from the Visa Checkout SDK.

**Comment by Mrkhoa86** [comment]
Nhieu luc tieng anh khong dich toi bam sai,va doi luc khong an chu viet,toi xin loi,thanh that cam on cac ban

**Comment by lkorth** [comment]
Please give `2.5.5-SNAPSHOT` a try and let us know if it resolves this for you.

**Comment by deandalm** [comment]
The issue is resolved when using 2.5.5-SNAPSHOT, thank you.

**Comment by lkorth** [comment]
Great to hear! A new release with this fix will go out in the near future, but in the meantime using `2.5.5-SNAPSHOT` should be fine.

You can subscribe to our [Google Group](https://groups.google.com/forum/#!forum/braintree-sdk-announce) or watch this repo to be notified of new releases.

**Comment by Mrkhoa86** [comment]
THOI GIAN NHAN DUOC THU KHOANG MAY NGAY VAY BAN-5NGAY ROI MA TOI CHANG THAY BUU DIEN GOI.CAM BAN LAM VIEC NHANH VA GON.OK
![img_20170708_101441](https://user-images.githubusercontent.com/29179280/28138710-f2a44156-677b-11e7-9e92-9d1abbc95468.jpg)
