### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by Neha1490** [braintree/braintree_android#157]
Library version in build.gradle -  compile 'com.braintreepayments.api:braintree:1.+'
Environment: Production

I have integrated braintree in my app.
The steps that I have follow are as below-
1) add library in build.gradle as mentioned above.
2) On Click of button -

```java
Intent intent = new Intent(getActivity(),BraintreePaymentActivity.class);
intent.putExtra(BraintreePaymentActivity.EXTRA_CLIENT_TOKEN, btToken);
startActivityForResult(intent, 100);
```

3)  
```java
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (resultCode == BraintreePaymentActivity.RESULT_OK) {
        String paymentMethodNonce = data.getStringExtra(BraintreePaymentActivity.EXTRA_PAYMENT_METHOD_NONCE);
        postNonceToServer(paymentMethodNonce);
    }
}
```

`android.content.ActivityNotFoundException: Unable to find explicit activity class {my app package name/com.braintreepayments.api.dropin.BraintreePaymentActivity}; have you declared this activity in your AndroidManifest.xml?`

Do I need to declare this activity in my manifest file also or do I need to change my code with android v2 as described in https://developers.braintreepayments.com/start/hello-client/android/v2 doc?

**Comment by lkorth** [comment]
If you're just integrating, especially if you're using Drop-in, I'd highly recommend using 3.x of Drop-in from https://github.com/braintree/braintree-android-drop-in. It should only be a few lines of code change for the new Drop-in integration and it offers a much better UI and experience.

If you're committed to using the older 1.x version, verify what your merged AndroidManifest.xml looks like and check to see if any Braintree activities are being merged in. If they are not, it may be an issue with the manifest merging. It is possible to just add the activity to your manifest, but pulling it in as a dependency with Gradle should really handle that for you.

**Comment by lkorth** [comment]
Closing this issue. I'll assume that you've solved your problem, if not, please comment and I'll reopen.
