### ISSUE TITLE
Drop In payment option ui bottom sheet slider is not showing in first attempt

### ISSUE THREAD

**Issue by dakshays** [braintree/braintree_android#162]
SDK/Library version: drop-in:3.1.0
Environment: Sandbox
Android Version and Device: Nexus 6P Android 7.0.1, Nexus 5X 7.0.1

### Issue description
When requesting drop in UI for the first time, the slider from bottom slides up but its keep on loading and even after the long time it is not showing payment method options. 
After dismissing the slider for first time and retrying the same it is shows payment option with just a blink.

```java
DropInRequest dropInRequest = new DropInRequest().clientToken(mClientToken)
                            .amount(amount).collectDeviceData(true)
                            .requestThreeDSecureVerification(true)
                            .androidPayShippingAddressRequired(true)
                            .androidPayPhoneNumberRequired(true);
startActivityForResult(dropInRequest.getIntent(ActivityPayment.this), 
```

Could any one please guide us with the what is wrong here. 

Screen Shot 1: Keeps on loading
![device-2017-09-02-174918](https://user-images.githubusercontent.com/20255848/29995494-fe32ab8e-9007-11e7-8e84-23eeec8fae18.png)

Screen Shot 2: After 2nd attempt, Its work correctly
![device-2017-09-02-174942](https://user-images.githubusercontent.com/20255848/29995495-111cdf12-9008-11e7-81b9-56aa6e401e90.png)

**Comment by dakshays** [comment]
Also i have tried the sample project and it is same.

**Comment by lkorth** [comment]
Drop-in has moved to https://github.com/braintree/braintree-android-drop-in

**Comment by dakshays** [comment]
Ok, Moving this to drop in.
