### ISSUE TITLE
Logout from PayPal One Touch

### ISSUE THREAD

**Issue by maxbaldrighi** [braintree/braintree_android#164]
### General information

* SDK/Library version: 2.7.0
* Environment: General question
* Android Version and Device: General question

### Issue description

During the past week we have started introducing Braintree SDK with PayPal *Vault* implementation in our app, where our Users are allowed to both add the PayPal payment method and delete it if they want it (our backend communicates the deletion to Braintree through the **customer.delete()** function).

I noticed just now during some tests, that even if the customerID is deleted, the login to PayPal One Touch feature is still active... and I really find it a big security flaw.

Is there something we don't do? Or is it just the original and wanted behavior?

Thank you

**Comment by bluk** [comment]
Can you elaborate on what you mean by "the login to PayPal One Touch feature" is still active? Customers determine if they want to opt-in to PayPal One Touch to make it easier to pay, and they are presented with a billing agreement and/or one-time payment page to agree to.

**Comment by maxbaldrighi** [comment]
Yes sorry, I'll try to elaborate more with an example:
USER1 adds PayPal payment method to his/her account on our app with the One Touch option, after some time he/she decides to delete the payment method. When he/she decides to re-enable it the screen it's always displayed is the "No need to type your password today" screen.

I feel like our users should be logged out from PayPal One Touch too, if the decide to remove PayPal method from our app.
So I can change my original question in: **is there a way to log the user out from One Touch via code**?

**Comment by bluk** [comment]
There is not a way to force a customer to log out via code.

The PayPal One Touch login is not tied to your specific app. [PayPal One Touch](https://www.paypal.com/us/webapps/mpp/one-touch-checkout) logs into PayPal itself, so a customer does not have to log in every time they checkout across all PayPal checkouts/merchants. The customer has to opt-in to the One Touch Login feature as well.

**Comment by maxbaldrighi** [comment]
Thank you for your help!
