### ISSUE TITLE
PayPal Checkout - Switch back from Chrome tab to app not happening.

### ISSUE THREAD

**Issue by harishannam** [braintree/braintree_android#166]
### General information

* SDK/Library version: com.braintreepayments.api:braintree:2.+
* Environment: Production
* Android Version and Device: API 23, Moto X Play, Chrome v61.0.3163.98

### Issue description

Once the PayPal Express Checkout is opened, we login and do a transaction. After a successful transaction, it stays at the PayPal Thank you page and does not return back to the Android App. 

Due to this, nonce is not received in the `onPaymentMethodNonceCreated` and passing it back to server step does not happen in this case. 

This issue occurs only through chrome tab on Chrome v61.0.3163.98 as mentioned. We tried it Android Default Browser, Samsung default browser, Chrome v60.x and Firefox and it works fine it all these cases

**Comment by bluk** [comment]
Closing this issue as it's being resolved by PayPal support. The flow for the customer account is unique.
