### ISSUE TITLE
Unable to compile 2.7.0 with data binding as a dependency

### ISSUE THREAD

**Issue by uddyami** [braintree/braintree_android#167]
### General information

* SDK/Library version: 2.7.0
* Environment: both 
* google support lib ver 11.4.2

compile fails with following error 
![screen shot 2017-10-23 at 11 31 36 am](https://user-images.githubusercontent.com/4366818/31901024-e8e3b15a-b7e5-11e7-8bd6-eee6bbf0df24.png)

we use data-binding as our dependency

**Comment by quinnjn** [comment]
Hi @uddyami 

I don't have a lot of experience using data binding but I made a sample repository showcasing [Braintree Android with data binding](https://github.com/quinnjn/braintree-android-with-databinding) which seems to be compiling. 

Take a look at the repository and let us know if it helps with your issue!

**Comment by uddyami** [comment]
Thank you for the shell project. I'll try an figure out why our main app is not compiling. closing this for now
