### ISSUE TITLE
BrainTreeBrowserSwitchActivity is missing

### ISSUE THREAD

**Issue by quiro91** [braintree/braintree_android#174]
### General information

* SDK/Library version: 2.7.3
* Environment: both
* Android Version and Device: reproduced on Android 7.0 (build NBD91P) on a Nexus 6

### Issue description

After calling `PayPal.requestBillingAgreement` we get an error message saying:
```
BraintreeBrowserSwitchActivity missing, incorrectly configured in AndroidManifest.xml or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/v2#browser-switch for the correct configuration
```
This is my manifest configuration:
```
<activity
            android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="${applicationId}.braintree" />
            </intent-filter>
        </activity>
```

After further investigation I noticed that that the error happens in the `AppHelper.isIntentAvailable`. The list of the activities size is actually 2 (apparently there are two instances of the BraintreeBrowserSwitchActivity), which is weird, so the method return false and it prevents the flow to continue successfully

<img width="835" alt="screen shot 2017-12-11 at 12 21 15" src="https://user-images.githubusercontent.com/1331440/33835420-54ebb1fe-de7e-11e7-88d7-d61ff8c27335.png">

**Comment by lkorth** [comment]
When you're at that breakpoint you can inspect the `activities` object to see what other app/activity is registered to handle the given `Intent`. You may have another version/build of your app installed that listens for the same URL scheme or manifest merging may have somehow ended up declaring it twice.

**Comment by quiro91** [comment]
That's a great catch, we had a test device with two variant of the same app. Thanks!

**Comment by yashwantchawhan** [comment]
I'm facing same issue. in my case ` List<ResolveInfo> activities = context.getPackageManager().queryIntentActivities(intent, 0);
        return activities != null && activities.size() == 1 ` activities.size coming as zero.

I'm calling  PayPal.authorizeAccount(mBraintreeFragment); this from fragment. Is this something related to fragment

**Comment by UsamaKabeer07** [comment]
Hey can you tell me where to find AppHelperClass in flutter project?
