### ISSUE TITLE
Build fails after upgrading to Android Studio 3.1 Canary 6

### ISSUE THREAD

**Issue by jpage4500** [braintree/braintree_android#176]
Sorry I know these Canary builds of Android Studio aren't exactly production ready and I'll likely switch back to version 5 to continue. But, after upgrading to Android Studio 3.1 Canary 6 (from 5) my build no longer worked.

The only error I see mentions the Braintree library so I figured I'd copy the error message below. Again, I'm not 100% sure this is a braintree issue but at least it appears to be at a high-level.

NOTE: I did invalidate cache and do a clean build as well

```
Could not merge in Bindables from /<my project>/build/intermediates/data-binding/debug/compiler/dependent-lib-artifacts/com.braintreepayments.api-com.braintreepayments.api-layoutinfo.bin java.io.InvalidClassException: android.databinding.annotationprocessor.ProcessExpressions$IntermediateV1; local class incompatible: stream classdesc serialVersionUID = 9120768259354515600, local class serialVersionUID = 2471044633310257816
```

**Comment by jpage4500** [comment]
just to be more specific it's not Android Studio Canary 6 per-ce but the gradle libraries it tries to get you to update to.. here's what I was using which works:

```
build.gradle:
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0-alpha05'

gradle.properties:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-rc-3-all.zip
```

updated TO which fails with the error in the first post:
```
        classpath 'com.android.tools.build:gradle:3.1.0-alpha06'

...
distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-4.4-20171031235950+0000-all.zip
```

**Comment by quinnjn** [comment]
Hi @jpage4500 sorry for the delay in replying!

I created a [sample app](https://github.com/quinnjn/braintree-android-android-studio-3.1-canary-7) with the latest canary (Android Studio 3.1 Canary 7). This seems to build for me. I haven't tried it against Canary 6 though.

The gradle build tools version is: `3.1.0-alpha07` so maybe there was an issue with `alpha06`?

Feel free to clone the [repo](https://github.com/quinnjn/braintree-android-android-studio-3.1-canary-7) and try it out

**Comment by quinnjn** [comment]
I'm going to close this issue for now. Feel free to comment if you're having issues with the new Canary build or gradle build tools and we can re-open this issue.

Thanks again for the heads up!

**Comment by AregevDev** [comment]
Facing the same issue with my school's laboratory, when migrating to Android Studio 3.3 it suddenly cannot find the certificates in order to sync the project with Gradle, I tried everything i could, it didn't help, anyone can help in that situation?

**Comment by quinnjn** [comment]
@AregevDev I don't think your question is related to braintree-android unfortunately, also this is an old issue.

Asking your question on StackOverflow may result in a bigger audience to help you.
