### ISSUE TITLE
appium android braintree drop-in ui automation issue

### ISSUE THREAD

**Issue by kadir-calvid** [braintree/braintree_android#182]
### General information

* SDK/Library version: 1+
* Environment: Sandbox
* Android Version and Device: Android 7.0 Moto g5 plus

### Issue description
i'm using appium for android automation, and unable to inspect/find the brain-tree drop in UI elements such as card details input or paypal login button through uiautomatorviewer tool.

Appium needs Drop-in UI elements to autofill cards details, we are working on solution to automate order process including braintree payment.

Any sample script and suggest are welcome.

Thanks

**Comment by avtaniket** [comment]
I'm also looking for this kind of automation for payment section.

Testing tool : NodeJs

**Comment by crookedneighbor** [comment]
We use uiautomator and uiautomatorviewer for our end to end tests. Here's an example of a test using the version of Drop-in that you are using: https://github.com/braintree/braintree-android-drop-in/blob/daacdd06c12c77cb27b92c646a55792da0ddbc6b/Demo/src/androidTest/java/com/braintreepayments/demo/test/DropInTest.java

I think this should point you in the right direction, so I'm going to close this.
