### ISSUE TITLE
Expedite payment method selection with only one option

### ISSUE THREAD

**Issue by kelvinleague** [braintree/braintree_android#183]
### General information

* SDK/Library version: 3.+
* Environment: Production
* Android Version and Device: Nexus 5X 

### Issue description
Not a serious issue, but if the user only has a single payment method available, it should be set by default and forward the user to the payment page instead of having them select the method. This is also the case on iOS

**Comment by crookedneighbor** [comment]
Drop-in has been removed from the SDK and put into its own repo. Can you open this issue up on the Drop-in repo instead? https://github.com/braintree/braintree-android-drop-in/issues
