### ISSUE TITLE
Receiving error with Paypal DropIn 

### ISSUE THREAD

**Issue by rjnsalvador** [braintree/braintree_android#184]
### General information

* Sandbox
* [Emulator] Nexus 6P - 7.0
* [Actual device] Nexus 5 - 6.0.1 

Receiving this error
```
Rejecting re-init on previously-failed class java.lang.Class<com.braintreepayments.api.BraintreeFragment$15>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/GoogleApiClient$ConnectionCallbacks;
```

I'm using Kotlin btw, if that's helpful information.

Steps to replicate

1. Call this method
```kotlin
fun onBraintreeSubmit() {
        val dropInRequest = DropInRequest()
                .clientToken(clientToken)
        startActivityForResult(dropInRequest.getIntent(this), REQUEST_CODE_PAY)
    }
```
2. Select Paypal
3. Tap Proceed with Sandbox Purchase

I followed the setup links [here](https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/android/v2) 

On my app level build.gradle i have
`compile 'com.braintreepayments.api:braintree:2.9.0'`
`compile 'com.braintreepayments.api:drop-in:3.+'`

On the MainActivity 
- In oncreate I do 
```kotlin
braintreeFragment = BraintreeFragment.newInstance(this@MainActivity, clientToken)
        braintreeFragment.addListener(this@MainActivity)
```

- I also have a click listener that initializes a DropIn
```kotlin
val dropInRequest = DropInRequest()
                .clientToken(clientToken)
        startActivityForResult(dropInRequest.getIntent(this), REQUEST_CODE_PAY)
```

Where the clientToken is the sample token from the docs
`eyJ2ZXJzaW9uIj...ib2ZmIn0=`

I also saw issue #109 so I tried doing a `compile 'com.google.android.gms:play-services:8.4.0' `
But it seems to break my project. 

Just want to understand what's causing the error

Thank you

**Comment by crookedneighbor** [comment]
> I also saw issue #109 so I tried doing a compile 'com.google.android.gms:play-services:8.4.0'
But it seems to break my project.

Can you explain how it is breaking?

**Comment by crookedneighbor** [comment]
You should not be including the braintree dependency, as that is bundled into the drop-in dependency. Including both `com.braintreepayments.api:braintree` and `com.braintreepayments.api:drop-in` can cause issues.

**Comment by rjnsalvador** [comment]
Okay, so I removed the braintree dependency. so now I only have and its not
breaking anymore

compile 'com.google.android.gms:play-services:8.4.0'

compile 'com.braintreepayments.api:drop-in:3.+'

But I get an error below
GoogleService failed to initialize, status: 10, Missing an expected
resource: 'R.string.google_app_id' for initializing Google services.
Possible causes are missing google-services.json or
com.google.gms.google-services gradle plugin.

Should I register my project on the Firebase console? Going to this link
<https://developers.google.com/mobile/add>, after adding my app name and
package, it makes me choose among Sign in, Analytics and Cloud messaging.
Which should be chosen here to get a google-services.json.

I think you should include this part on your docs as well... hmmm

**Comment by rjnsalvador** [comment]
To add, after applying the plugin in my app/build.gradle

classpath 'com.google.gms:google-services:3.1.1'


I get

Version: 8.4.0 is lower than the minimum version (9.0.0) required for
google-services plugin.

**Comment by jaypatel512** [comment]
Hey @rjnsalvador ! 

I do not think you need to add any other dependency for drop-in. You may not need to add `play-services` at all, based on our documentation.

Can you please try and remove that dependency as well, and see if this fixes the issue for you.

**Comment by rjnsalvador** [comment]
Hi guys, everything is working as expected now. I guess it was just a matter of mixing up the v2 and v3 setup code. Sorry. Ill just message you guys if ever I encounter any issue. Thank you!
