### ISSUE TITLE
Misalignment between AndroidPay.isReadyToPay() and GooglePayment.isReadyToPay() results

### ISSUE THREAD

**Issue by mrsasha** [braintree/braintree_android#187]
### General information

* SDK/Library version: `2.8.1` (by way of Drop-in)
* Environment: Sandbox
* Android Version and Device: Samsung S8, Android 7.1.2

### Issue description

Currently, based on a [Customer compatibility list](https://articles.braintreepayments.com/guides/payment-methods/google-pay#customer-compatibility), `AndroidPay.isReadyToPay()` and `GooglePayment.isReadyToPay()` should report the same result on a device with a non-supported credit card. However, it seems that `GooglePayment.isReadyToPay()` is always reporting `true`, even when it's not available for this device locale (in my case, `en_uk` with a German SIM and German credit card). `AndroidPay.isReadyToPay()` correctly reports `false`.

**Comment by sdcoffey** [comment]
Hey @mrsasha,

Thanks for the feedback. In this method, we don't actually check the locale or nationality of the sim. It's essentially a wrapper around the underlying [Google Wallet API](https://developers.google.com/payments/tutorial#step_2_call_isreadytopay_api), which is unaware of Braintree-specific limitations. The idea is that if you are a Braintree merchant not in a supported locale, you should not show Google Pay as an option to your customers, regardless of the result of `GooglePayment.isReadyToPay`.

Android Pay has a different API with different technical restrictions. Unfortunately, we have limited visibility into these underlying APIs so it's hard to say exactly why `AndroidPay.isReadyToPay` would return false. Most likely it has something to do with the version of Google Play Services installed on the device, and Android Pay is now deprecated as a mobile payment option.

Please let us know if there are any other issues you run into!
