### ISSUE TITLE
Missing users billing address in PayPalAccountNonce

### ISSUE THREAD

**Issue by MarijanGazica** [braintree/braintree_android#188]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device: 

### Issue description

When creating a new payment request with following:
`            BraintreeFragment braintreeFragment = BraintreeFragment.newInstance(getActivity(), token);`

`PayPalRequest payPalRequest = new PayPalRequest(price);`
`payPalRequest.shippingAddressRequired(true);`
`payPalRequest.currencyCode(currency);`
`PayPal.requestOneTimePayment(braintreeFragment, payPalRequest);`

what gets back in response is this:

<img width="725" alt="screen shot 2018-01-30 at 12 31 17" src="https://user-images.githubusercontent.com/12072773/35564164-8d29f00a-05b9-11e8-8196-88c0f73f42bb.png">

Should users billing address be empty or am I missing some way to request users it?

**Comment by bluk** [comment]
A merchant account setting needs to be enabled. Please contact [Braintree Support](https://developers.braintreepayments.com/forms/contact) to help get this enabled. Thanks.
