### ISSUE TITLE
Support for React Native and Ionic

### ISSUE THREAD

**Issue by skunkworks** [braintree/braintree_android#190]
Braintree currently does not have any plans to support React Native or Ionic, but we are open to the possibility if there's enough interest. We'd like to collect feedback from the community, so if this is something you might be interested, please leave us some feedback here!

[Corresponding GH issue in `braintree_ios`](https://github.com/braintree/braintree_ios/issues/390)

**Comment by demerino** [comment]
👍

**Comment by idcmsbeta** [comment]
official support is nice.. but now i'm editing some repo for my needs.. a little bit more then standard github outthere..  

https://gist.github.com/idcmsbeta/f7181dbcac085660a088055e916bdef4

Waiting for braintree for some more additional information  .. then i will release

**Comment by kylealwyn** [comment]
This would be amazing

**Comment by jawa-the-hutt** [comment]
FWIW, I would like to add in Nativescript as a possibility.  Mainly because Nativescript-Vue is now [officially supported](https://www.nativescript.org/blog/nativescript-5.2-comes-with-official-support-for-vue) by Progress and Vue is one of the fastest growing developer segments in the front-end market.    

There's already a [NS plugin](https://github.com/jibon57/nativescript-braintree) out there that works, but it's community maintained and the maintainer has to consistently forward folks on to Braintree support for issues.

**Comment by crisp978** [comment]
All the hybrid application that use cordova plugins ... don't have a support for Android 3 Sdk and IOS 4 Sdk.
We can't switch to paypal plugin PayPal SDK Cordova/Phonegap Plugin because is deprecated and isn't a braintree plugin that support Android 3 Sdk.

**Comment by kishanbharda** [comment]
> Braintree currently does not have any plans to support React Native or Ionic, but we are open to the possibility if there's enough interest. We'd like to collect feedback from the community, so if this is something you might be interested, please leave us some feedback here!
> 
> [Corresponding GH issue in `braintree_ios`](https://github.com/braintree/braintree_ios/issues/390)

There is already a library called [react-native-braintree-dropin-ui](https://github.com/wgltony/react-native-braintree-dropin-ui) which nicely support braintree dropin ui for android and iOS, with just simple code. But still there is some issue like android dropin popup not displaying "credit or debit card" option. I don't know what's the problem, it's my code side issue or built in library issue, but I have created [issue](https://github.com/wgltony/react-native-braintree-dropin-ui/issues/52) there. Please can anyone have idea to solve ?

**Comment by scannillo** [comment]
Hi @kishanbharda - we don't offer troubleshooting support for that react-native SDK, since it isn't written by us. We do not offer official react-native support. We are happy to troubleshoot concerns specific to our Android and iOS SDKs
