### ISSUE TITLE
Android PayPal SDK Issues

### ISSUE THREAD

**Issue by conallCurran** [braintree/braintree_android#191]
### General information

* SDK/Library version: 26.0.2
* Environment: Sandbox
* Android Version and Device: (Samsung Note 4) 6.0.2 Marshmallow

### Issue description

Hi,
   When building the gradle I keep receiving this error: 

`Error:Execution failed for task ':Demo:compileDebugJavaWithJavac'.
> android.databinding.tool.util.LoggedErrorException: Found data binding errors.
  ****/ data binding error ****msg:Cannot find the getter for attribute 'bind:selectedValue' with value type java.lang.String on android.widget.Spinner.
  file:C:\Users\cocurran\.gradle\caches\transforms-1\files-1.1\VisaCheckout-Android-SDK-4.6.0.aar\64f44f56291d7e0a83acc6802f961b9d\res\layout\vco_fragment_address_es.xml
  loc:168:6 - 178:63
  ****\ data binding error ****
  ****/ data binding error ****msg:Cannot find the setter for attribute 'app:font' with parameter type java.lang.String on android.widget.TextView.
  file:C:\Users\cocurran\.gradle\caches\transforms-1\files-1.1\VisaCheckout-Android-SDK-4.6.0.aar\64f44f56291d7e0a83acc6802f961b9d\res\layout\vco_exo_error_dialog.xml
  loc:27:20 - 27:42
  ****\ data binding error ****
  ****/ data binding error ****msg:Cannot find the setter for attribute 'app:font' with parameter type java.lang.String on android.widget.TextView.
  file:C:\Users\cocurran\.gradle\caches\transforms-1\files-1.1\VisaCheckout-Android-SDK-4.6.0.aar\64f44f56291d7e0a83acc6802f961b9d\res\layout\vco_exo_rnc_fragment.xml
  loc:41:26 - 41:48
  ****\ data binding error ****
  ****/ data binding error ****msg:Cannot find the getter for attribute 'bind:selectedValue' with value type java.lang.String on android.widget.Spinner.
  file:C:\Users\cocurran\.gradle\caches\transforms-1\files-1.1\VisaCheckout-Android-SDK-4.6.0.aar\64f44f56291d7e0a83acc6802f961b9d\res\layout\vco_fragment_address_au.xml
  loc:149:6 - 159:63
  ****\ data binding error ****
  ****/ data binding error ****msg:Cannot find the setter for attribute 'app:font' with parameter type java.lang.String on android.widget.TextView.
  file:C:\Users\cocurran\.gradle\caches\transforms-1\files-1.1\VisaCheckout-Android-SDK-4.6.0.aar\64f44f56291d7e0a83acc6802f961b9d\res\layout\vco_exo_manual_signin_fragment.xml
  loc:42:26 - 42:48
  ****\ data binding error ****
  ****/ data binding error ****msg:Cannot find the getter for attribute 'bind:selectedValue' with value type java.lang.String on android.widget.Spinner.
  file:C:\Users\cocurran\.gradle\caches\transforms-1\files-1.1\VisaCheckout-Android-SDK-4.6.0.aar\64f44f56291d7e0a83acc6802f961b9d\res\layout\vco_fragment_address_ie.xml
  loc:142:6 - 152:63
  ****\ data binding error ****
  ****/ data binding error ****msg:Cannot find the setter for attribute 'app:font' with parameter type java.lang.String on android.widget.TextView.
  file:C:\Users\cocurran\.gradle\caches\transforms-1\files-1.1\VisaCheckout-Android-SDK-4.6.0.aar\64f44f56291d7e0a83acc6802f961b9d\res\layout\vco_fragment_fp_sign_in_content.xml
  loc:32:20 - 32:44
  ****\ data binding error ****
  ****/ data binding error ****msg:Cannot find the getter for attribute 'bind:selectedValue' with value type java.lang.String on android.widget.Spinner.
  file:C:\Users\cocurran\.gradle\caches\transforms-1\files-1.1\VisaCheckout-Android-SDK-4.6.0.aar\64f44f56291d7e0a83acc6802f961b9d\res\layout\vco_fragment_address_ca.xml
  loc:145:6 - 155:63
  ****\ data binding error ****
  ****/ data binding error ****msg:Cannot find the getter for attribute 'bind:selectedValue' with value type java.lang.String on android.widget.Spinner.
  file:C:\Users\cocurran\.gradle\caches\transforms-1\files-1.1\VisaCheckout-Android-SDK-4.6.0.aar\64f44f56291d7e0a83acc6802f961b9d\res\layout\vco_fragment_address_us.xml
  loc:143:6 - 153:63
  ****\ data binding error ****
`

**Comment by quinnjn** [comment]
Hi @conallCurran 

I haven't had this problem personally when running the Demo. Doing some quick googling I found this [StackOverflow post](https://stackoverflow.com/a/44989266) suggesting to clear the gradle cache and rebuild the project. 

Let us know if this solved the issue!

**Comment by quinnjn** [comment]
@conallCurran I'm going to close this due to inactivity. Please reply is there is still an issue.
