### ISSUE TITLE
How to use BraintreeFragment for paypal

### ISSUE THREAD

**Issue by jatinbsa** [braintree/braintree_android#192]
I want to use BraintreeFragment for Paypal because paypal run on browser .

But can anyone guide me how to use BrainTreeFragment

**Comment by quinnjn** [comment]
Hi @jatinbsa 

Our developer documentation site would have details on using Braintree Android.

Here are some links for your asks:
- [Setting up the Client SDK](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2)
- [PayPal Client-Side implementation](https://developers.braintreepayments.com/guides/paypal/client-side/android/v2)
- [Browser switch setup](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2#browser-switch-setup)
