### ISSUE TITLE
Gradle sync failure with browser-switch error

### ISSUE THREAD

**Issue by GrzegorzFeather** [braintree/braintree_android#194]
### General information

* SDK/Library version: 2.10.0
* Environment: N/A
* Android Version and Device: N/A

### Gradle Sync fails

I'm getting following error when trying to sync my project:
`5:42 PM	Gradle sync failed: 'com.braintreepayments:browser-switch-0.1.4' already disposed: (10s 231ms)`

**Comment by quinnjn** [comment]
@GrzegorzFeather I tried syncing the project a couple of times with no luck in replicating this issue. It sounds like you just need to [invalidate your Android Studio cache](https://stackoverflow.com/a/30707747) to fix this.

If you are able to replicate it, can you please list the steps.
