### ISSUE TITLE
Android Studio3.1 Build Problem

### ISSUE THREAD

**Issue by javabiker** [braintree/braintree_android#196]
### General information
Compile SDK Version: 24
Min SDK Version: 24
Target SDK Version: 24

### Issue description
After upgrading from 3.01 to 3.1 the Build fails with message: Could not download asm-util.jar (org.ow2.asm:asm-util:5.1): No cached version available for offline mode.

I have added 'compile 'org.ow2.asm:asm-util:5.1' to dependencies.
Urgently need advice on resolving this issue.

**Comment by quinnjn** [comment]
Hi @javabiker,

I was able to compile and run Demo as-is which in turn would compile and run the build for each module using Android Studio 3.1

I re-verified by running **Rebuild Project** and could not reproduce the problem.

> No cached version available for offline mode.

It sounds like you may be running in [gradle offline mode](https://developer.android.com/studio/build/optimize-your-build.html#offline_mode)? That would explain why you're not able to download the JAR.

**Comment by quinnjn** [comment]
I'm going to close this due to inactivity. If you're still having issues please let us know!
