### ISSUE TITLE
Cannot find symbol variable after upgrade 

### ISSUE THREAD

**Issue by Trusted97** [braintree/braintree_android#197]
**General information**

    SDK/Library version: Braintree drop in 2.3.8
    Environment: Sandbox
    Android Version and Device: Samsung SM-G930F (Android 7.0 , API 24)

**Issue description**
I just updated the drop-in API because i've received an email that told me that i need to upgrade my Braintreed SDK to 2.0.0 , but after upgrade some button id and symbol variable are not avaible.

error: cannot find symbol variable EXTRA_CLIENT_TOKEN
error: cannot find symbol variable bt_payment_button_divider_2
error: cannot find symbol variable bt_android_pay_button
error: cannot find symbol variable bt_payment_method_view_switcher
error: cannot find symbol variable bt_card_form

Are they been deprecated?

**Comment by quinnjn** [comment]
Hey @Trusted97 

If you're using Drop-in you'll want to upgrade to:
```
compile 'com.braintreepayments.api:drop-in:3.+'
```

You also don't need to supply the braintree-android dependency if you're using drop-in.

See our [Setup and Integration](https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/android/v2) guide for Drop-in for Android v2

**Comment by quinnjn** [comment]
I'm going to close this issue since we haven't received any additional feedback.

Let us know If you require more assistance with this issue.
