### ISSUE TITLE
ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/data/app/com.xx_sim-2/base.apk"],nativeLibraryDirectories=[/data/app/com.xx_sim-2/lib/arm64, /system/lib64, /vendor/lib64]]

### ISSUE THREAD

**Issue by YudizPayal** [braintree/braintree_android#200]
Hi,

I am using your SDK, when i try to open BraintreeFragment with Activity and Token then it gives me crash that Class not found exception.
I dont know how to overcome this issue.
Please help me.
Thanks.

` try {
            var mBraintreeFragment = BraintreeFragment.newInstance(this,
                    "token")
            PayPal.requestOneTimePayment(mBraintreeFragment, PayPalRequest("1.00"))
        } catch (e: Exception) {
            e.printStackTrace()
        }`

**Comment by quinnjn** [comment]
Hi @YudizPayal,

Are you trying to use Google Pay? If so, you'll want to make sure you have [Google Pay Services Wallet as a dependency](https://developers.braintreepayments.com/guides/google-pay/client-side/android/v2#get-the-sdk)

**Comment by quinnjn** [comment]
@YudizPayal I'm closing the issue due to inactivity. Comment if you are still having trouble and we'll reopen it.

**Comment by breakline87** [comment]
Why do we have to add Google Pay to use PayPal (or anything but Google Pay)?
