### ISSUE TITLE
deviceData returning NULL

### ISSUE THREAD

**Issue by engrsandeep** [braintree/braintree_android#202]
Hi,

I am using below code and it returning empty device data 

public void onActivityResult(int requestCode, int resultCode, Intent intent) {
        super.onActivityResult(requestCode, resultCode, intent);

       
        if (dropInUICallbackContext == null) {
            return;
        }

        if (requestCode == DROP_IN_REQUEST) {

             String deviceData = "";
            PaymentMethodNonce paymentMethodNonce = null;

            if (resultCode == Activity.RESULT_OK) {
                DropInResult result = intent.getParcelableExtra(DropInResult.EXTRA_DROP_IN_RESULT);
                deviceData = result.getDeviceData();
                paymentMethodNonce = result.getPaymentMethodNonce();
            }

            this.handleDropInPaymentUiResult(resultCode, paymentMethodNonce,deviceData);
        }
        else if (requestCode == PAYMENT_BUTTON_REQUEST) {
            //TODO
            dropInUICallbackContext.error("Activity result handler for PAYMENT_BUTTON_REQUEST not implemented.");
        }
        else if (requestCode == CUSTOM_REQUEST) {
            dropInUICallbackContext.error("Activity result handler for CUSTOM_REQUEST not implemented.");
            //TODO
        }
        else if (requestCode == PAYPAL_REQUEST) {
            dropInUICallbackContext.error("Activity result handler for PAYPAL_REQUEST not implemented.");
            //TODO
        }
    }

**Comment by crookedneighbor** [comment]
Are you telling Drop-in to collect device data? See step 2 here: https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/android/v2#drop-in

**Comment by engrsandeep** [comment]
Yes. But i was not calling collectDeviceData on dropInRequest. 
So fixed it.
Thanks for help.
