### ISSUE TITLE
Update to new Google Play libraries (15.x)

### ISSUE THREAD

**Issue by mrsasha** [braintree/braintree_android#208]
Hi,

what's the timeline for updating to new Google Play libraries? 

The `11.4.0` one used here is more than 9 months old already and there were some very needed changes done in other parts of the library (Google Sign In was drastically improved, libraries are not co-dependent any more) and this prevents us from upgrading.

**Comment by quinnjn** [comment]
Hi @mrsasha 

We are currently using `com.google.android.gms:play-services-wallet:11.4.0` in braintree-android. This is the minimum requirement for Google Pay with Braintree.

Your app does not have to use this library though! Gradle dependency resolution magic will pick the latest version 😄. Just specify your own version of `play-services-wallet` that is greater than `11.4.0` and gradle will use that one instead.

Generally libraries want to support the lowest level dependency required so that apps are free to stick to whatever version they wish.

We would only upgrade this when `11.4.0` no longer works for Braintree. Let us know if there is an issue with using a newer version!

**Comment by mrsasha** [comment]
Hi @quinnjn, thanks for coming back to me. There are a few reasons why it would be beneficial to upgrade to the newest release (or at least 15.0.0). 

In our regular app we use braintree drop-in, and in our instant app we use Google Instant App Payment SDK for UI and braintree-android library as payment processor. From Google Play 15, Instant App payment SDK was folded into regular Google Pay SDK. That means that, using new Google Play, we could use the drop-in for Instant Apps too, like we do in the regular app. If we try using the drop-in as it is now, since the Google Pay initialization is done through your older release 11.4.2, the Google Pay option just doesn't appear in Instant Apps.

Also, there are rumors that Paypal is now whitelisted with Instant Apps, so using the drop-in we would be able to offer it as a payment method too - otherwise we would need to make custom UI for Instant Apps that would let the user choose between Google Pay, credit card and Paypal.

Last but not least, gradle build breaks when we use a version of Google Play libraries different from the one in braintree libraries. That is officially supported only from 15.0.0. For example, only the 11.6.2 builds, all the others fail (11.8.0, 12.0.1, 15.0.0, 15.0.1).

**Comment by quinnjn** [comment]
Maybe there is some miscommunication from my last message. You should be able to overwrite the library. 

I created a sample app to test this out and it worked for me:

```
implementation 'com.braintreepayments.api:braintree:2.13.1'
implementation 'com.google.android.gms:play-services-wallet:15.0.1'
```

You can verify what dependencies gradle resolves for the release using `./gradlew :app:dependencies`
```
$ ./gradlew :app:dependencies --configuration releaseRuntimeClasspath

> Task :app:dependencies

------------------------------------------------------------
Project :app
------------------------------------------------------------

releaseRuntimeClasspath - Resolved configuration for runtime for variant: release
+--- com.android.support:appcompat-v7:27.1.1
...
+--- com.android.support.constraint:constraint-layout:1.1.1
...
+--- com.braintreepayments.api:braintree:2.13.1
|    +--- com.braintreepayments.api:visa-checkout:1.0.0
|    +--- com.braintreepayments.api:core:2.13.1
|    |    \--- com.braintreepayments:browser-switch:0.1.5
|    \--- com.paypal.android.sdk:paypal-one-touch:2.13.1
|         +--- com.braintreepayments.api:core:2.13.1 (*)
|         \--- com.paypal.android.sdk:data-collector:2.13.1
\--- com.google.android.gms:play-services-wallet:15.0.1
     +--- com.google.android.gms:play-services-base:[15.0.1,16.0.0) -> 15.0.1
     |    +--- com.google.android.gms:play-services-basement:[15.0.1] -> 15.0.1
     |    |    \--- com.android.support:support-v4:26.1.0
     |    |         +--- com.android.support:support-compat:26.1.0 -> 27.1.1 (*)
     |    |         +--- com.android.support:support-media-compat:26.1.0
     |    |         |    +--- com.android.support:support-annotations:26.1.0 -> 27.1.1
     |    |         |    \--- com.android.support:support-compat:26.1.0 -> 27.1.1 (*)
     |    |         +--- com.android.support:support-core-utils:26.1.0 -> 27.1.1 (*)
     |    |         +--- com.android.support:support-core-ui:26.1.0 -> 27.1.1 (*)
     |    |         \--- com.android.support:support-fragment:26.1.0 -> 27.1.1 (*)
     |    \--- com.google.android.gms:play-services-tasks:[15.0.1] -> 15.0.1
     |         \--- com.google.android.gms:play-services-basement:[15.0.1] -> 15.0.1 (*)
     +--- com.google.android.gms:play-services-basement:[15.0.1,16.0.0) -> 15.0.1 (*)
     +--- com.google.android.gms:play-services-identity:[15.0.1,16.0.0) -> 15.0.1
     |    +--- com.google.android.gms:play-services-base:[15.0.1,16.0.0) -> 15.0.1 (*)
     |    \--- com.google.android.gms:play-services-basement:[15.0.1,16.0.0) -> 15.0.1 (*)
     +--- com.google.android.gms:play-services-maps:[15.0.1,16.0.0) -> 15.0.1
     |    +--- com.google.android.gms:play-services-base:[15.0.1,16.0.0) -> 15.0.1 (*)
     |    \--- com.google.android.gms:play-services-basement:[15.0.1,16.0.0) -> 15.0.1 (*)
     \--- com.google.android.gms:play-services-tasks:[15.0.1,16.0.0) -> 15.0.1 (*)
```

**Comment by crookedneighbor** [comment]
Going to close this for now, because I think @quinnjn was able to provide a solution.

Comment here if you're still having an issue.
