### ISSUE TITLE
MonthYearEditText hint not drawn as floating label

### ISSUE THREAD

**Issue by brycehendrix** [braintree/braintree_android#21]
MonthYearEditText does not animate and draw the hint as a floating label as the other text widgets do. Possibly because it overrides the text change listener?

**Comment by lkorth** [comment]
It looks like when the form was extracted to a separate module the listeners were indeed messed up. I'll look into fixing this.

**Comment by brycehendrix** [comment]
Thanks @lkorth 

It was broken in 1.2.7 as well, before the refactor, if that helps.

**Comment by lkorth** [comment]
Thanks for the report @brycehendrix, I've fixed it and it should be released soon.
