### ISSUE TITLE
Android P deprecating native Fragment

### ISSUE THREAD

**Issue by kingargyle** [braintree/braintree_android#210]
### General information

* SDK/Library version: 2.13
* Environment:  Sandbox & Production
* Android Version and Device: all
* Braintree dependencies: 
   * com.braintreepayments.api:braintree:2.13.0 

### Issue description

In Android P the native fragment implementation is being deprecated, and only the v4.Fragment will be kept around eventually.   Right now BraintreeFragment only extends from the native fragment, and does not provide a v4 compatible fragment.    Is there a time line to support the v4 Fragment since Google is deprecating out the Native version in Android P.

**Comment by quinnjn** [comment]
Yes, this is on our radar. We'll keep this issue open until it is resolved.

**Comment by littlefeetpk** [comment]
kinggary is a fake name hard I king is me a women and you people are hacking my phone

**Comment by quinnjn** [comment]
We have a snapshot branch available that uses support fragments, and relies on `AppCompatActivity`. We'd love to hear some feedback if you have any issues on this build!

[`com.braintreepayments.api:braintree:3.0.0-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/com/braintreepayments/api/braintree/3.0.0-SNAPSHOT/)

**Comment by kingargyle** [comment]
Thanks.  This may be a while as we are currently in code freeze and won't be touching that code until early next year.  But glad to see this finally so we can remove our work around.

**Comment by quinnjn** [comment]
Braintree Android v3 is now available and using `androidx.app.Fragment` which can be attached to `androidx.appcompat.app.AppCompatActivity`

```
implementation 'com.braintreepayments.api:braintree:3.0.0'
```

Docs:
- [Braintree Android v3 migration guide](https://developers.braintreepayments.com/guides/client-sdk/migration/android/v3)
- [Braintree Android v3 setup](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v3)

**Comment by kingargyle** [comment]
Thanks.  We'll have to hold off until we migrate to the AndroidX support libraries.
