### ISSUE TITLE
shippingAddressOverride is not working properly.

### ISSUE THREAD

**Issue by DpsDeveloper** [braintree/braintree_android#212]
### General information
Passed shipping address to SDK is not showing on the SDK review order screen when PayPAl application is not installed.
* SDK/Library version:  2.12.0
* Environment: sandbox 
* Android Version and Device: Android 8.0 
* Braintree dependencies: 
api 'com.braintreepayments.api:braintree:2.12.0'

### Issue description
SDK was initialized and is working properly, I am able to get callback with a valid data, howeever shipping address passed to the sdk while **vault** flow is not been visible on the Review Order screen. 
Please consider the next code example:
```
public Observable<PayPalRxModel> authorizeIntoPayPal() {
        BraintreeFragment tag = (BraintreeFragment) activity.getFragmentManager().findFragmentByTag(BraintreeFragment.TAG);
        if (isNotNull(tag)) {
            PostalAddress address = new PostalAddress()
                    .recipientName("Some name")
                    .region("PA")
                    .postalCode("XXXXX")
                    .locality("Some city name")
                    .streetAddress("Some Address")
                    .countryCodeAlpha2("US");
            PayPalRequest request = new PayPalRequest();
            request = request.shippingAddressRequired(true)
                    .shippingAddressOverride(address)
                    .offerCredit(false);
            PayPal.requestBillingAgreement(tag, request);
        }
        return sharedSubject.share();
    }
```

I am expecting to see shipping address passed to the sdk on the screen please see attachment.![screen shot 2018-06-06 at 11 13 00 am](https://user-images.githubusercontent.com/12971849/41047768-4ac5df3c-697b-11e8-8d20-52de5aa93c4e.png)

I thought it might being connected with address correctness or its existence, though I passed different addresses the SDK always shows me default billing address.

**Comment by quinnjn** [comment]
This was a bug. PayPal was expecting a different shape for shipping addresses in the vault flow payload.

We fixed it here: 7c1e5b385186203ffc178fd51f6f38a9017a9134 and it should be available in version 2.13.2 and forward.

Thanks for reporting the issue!
