### ISSUE TITLE
Fetch all Payment Method fo client

### ISSUE THREAD

**Issue by RexNexstream** [braintree/braintree_android#215]
To fetch all Payment Method for client in iOS , we can use 
`apiClient.fetchPaymentMethodNonces(true, completion: handler)`

How we achieve the same objective in android ???
Thank You

**Comment by quinnjn** [comment]
[`PaymentMethod#getPaymentMethodNonces`](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/PaymentMethod.java#L30)

The javadoc has the explanation on the listener you need to add to get a callback.
