### ISSUE TITLE
Allow setting setExistingPaymentMethodRequired for Google Pay's isReadyToPay

### ISSUE THREAD

**Issue by MrDweezil** [braintree/braintree_android#218]
### General information

* SDK/Library version: 2.13.0

### Issue description

Braintree's GooglePayment.isReadyToPay() wrapper around Google's PaymentsClient.isReadyToPay() doesn't allow for any customization of the IsReadyToPayRequest. The standard request is mostly fine but it would be great to be able to set the isExistingPaymentMethodRequired value since a Google Pay option ought to be much more appealing to a user who can just tap an existing card than one who has to enter in all of their payment information.

Obviously this can be done outside of the Braintree SDK, but that's not nearly as convenient.

**Comment by quinnjn** [comment]
Sounds reasonable! We'll take a look at adding it.

**Comment by littlefeetpk** [comment]
you people are paying people with my money that I don't ever see my 50 percent it going to 181 other people you all are going to jail

**Comment by littlefeetpk** [comment]
make one more payment through my account and you will be sorry I reported fraud through the trade commission and Joe media the trader is helping you people try to steal my grandpas stock and my property your day is coming the police know your trying to hurt me

**Comment by littlefeetpk** [comment]
you people make payments to people you will be sorry

**Comment by sestevens** [comment]
This is now available in [v3.3.1](https://github.com/braintree/braintree-android-google-payment/releases/tag/3.3.1) of the `braintree-android-google-payment` package.
