### ISSUE TITLE
Failed to find byte code for com/kount/api/DataCollector$CompletionHandler

### ISSUE THREAD

**Issue by nb312** [braintree/braintree_android#219]
I just clone the update to date code to local and want import into the android studio. first, the compile is successful, but when I run the demo, it gets an error as following:
```
Failed to find byte code for com/kount/api/DataCollector$CompletionHandler
```
I have found some solutions in websites, many of them say that is a proguard issue.
but when I add the codes ``` -dontwarn com.kount.** ``` in the 'proguard.pro' file , it is still having this problem. Thank you.

----
android studio version is 3.1.3 
classpath 'com.android.tools.build:gradle:3.1.3'

# update
----
When I check the gradle in the module of  BraintreeDataCollector, it sees: 
```
def deviceCollectorVersion = 'kount-data-collector-3.2.jar'

dependencies {
    // TODO `api` is the proper keyword for this dependency
    // Although when we try to add this to our releaseJar
    // We don't have access to configurations.(compile|api)
    // So this needs more investigation.
    // For now, revert back to `compile` keyword
    compile files('libs/' + deviceCollectorVersion)
}
``` 
I just follow the lib and see the package of ``` com.kount.api.DataCollector ``` . It has just one class 
``` BuildConfig ```,not has another one. it is saying that there is not a class called CompletionHandler in its source codes. I just guess that the version is wrong.

**Comment by quinnjn** [comment]
Hi @nb312 

Are you getting this issue running the Braintree Android Demo provided in this repository, or your own integration? I tried the Braintree Android Demo with Android Studio 3.1.3 and haven't been able to replicate the issue.

This wouldn't be a proguard issue. If you're expecting to use `DataCollector` that `CompletionHandler` should be available at runtime. 

Regarding the `BraintreeDataCollector` snippet, we are working on removing the deprecated `compile` keyword. We had replaced the `compile` of the jar with `api` but the jar was not being packaged properly in the maven artifact. We're looking into it still.

**Comment by quinnjn** [comment]
@nb312 we were able to reproduce this on another machine. The issue seems to stem from Instant Run being enabled. You can [disable Instant Run as a temporary fix](https://developer.android.com/studio/run/#disable-ir).

We'll look more into the issue around Instant Run not working for BraintreeDataCollector.

**Comment by nb312** [comment]
@quinnjn thank your answers. I will try what you say. If it works well or not, I will let you know.

**Comment by quinnjn** [comment]
This is now available in:
```
com.braintreepayments.api:braintree:2.15.0
```

If you're still having issues leave a comment and we'll reopen the issue!

**Comment by nb312** [comment]
@quinnjn  thank you a lot for answer me.
