### ISSUE TITLE
 java.lang.NullPointerException: Transaction info must be set if paymentMethodTokenizationParameters is set!

### ISSUE THREAD

**Issue by Azharaliimark** [braintree/braintree_android#221]
Hello Team ,

I am using this method for getting Token but we get Exception.

```java
 GooglePayment.getTokenizationParameters(mBraintreeFragment, new TokenizationParametersListener() {
            @Override
            public void onResult(PaymentMethodTokenizationParameters parameters, Collection<Integer> allowedCardNetworks) {
                PaymentDataRequest paymentDataRequest = PaymentDataRequest.newBuilder()
                        .addAllowedPaymentMethod(WalletConstants.PAYMENT_METHOD_CARD)
                        .addAllowedPaymentMethod(WalletConstants.PAYMENT_METHOD_TOKENIZED_CARD)
                        .setPaymentMethodTokenizationParameters(parameters)
                        .setCardRequirements(CardRequirements.newBuilder()
                                .addAllowedCardNetworks(allowedCardNetworks)
                                // We recommend collecting billing address information, at minimum
                                // billing postal code, and passing that billing postal code with all
                                // Google Pay transactions as a best practice.
                                .setBillingAddressRequired(true)
                                .build())
                        .build();
            

            }

**Comment by Epreuve** [comment]
@Azharaliimark Adding `setTransactionInfo()` as per Google's documentation [here](https://developers.google.com/pay/api/android/guides/tutorial#step_3_create_paymentdatarequest_object) should get you past this error.  Our documentation looks like it needs to be updated to reflect this. 

Let us know if this doesn't get you in the right direction.

**Comment by Azharaliimark** [comment]
Hello Tim,

Thank you for the response, I am using Braintree's GooglePay,
I have the following queries:

Q1) Is any way for use google pay without amount and currency, just pass client token and google pay return nonce just like PayPal.

Q2) can we use dummy card for testing, when we use dummy card we got the error.

Thank you

**Comment by Epreuve** [comment]
@Azharaliimark No, you are required to pass a price and currency with Google Pay.  

Is there a reason you're not using the simpler API with Braintree?  The code you've provided is from an example where you're building various objects required for Google Pay, and manually executing each step of the process.  

Unless you need the direct integration, it might be easier for you to integrate entirely through Braintree.  Take a look at our Demo app's implementation of Google Pay [here](https://github.com/braintree/braintree_android/blob/master/Demo/src/main/java/com/braintreepayments/demo/GooglePaymentActivity.java#L84-L105) for an example.

**Comment by crookedneighbor** [comment]
Regarding Q2, no you must use a real card, but Google will swap out the real card for a fake card when using the Test environment.

**Comment by crookedneighbor** [comment]
@Azharaliimark Like I said before, Google does not allow you to add a test card to your wallet. You must use a real card. However, when the environment is set to `TEST`, it will return a token that cannot be charged.

This is a limitation set by Google, not Braintree, so please contact Google support if you have additional questions about it.
