### ISSUE TITLE
same issue:  E/dalvikvm: Could not find class 'com.visa.checkout.VisaPaymentSummary', referenced from method com.braintreepayments.api.VisaCheckout.onActivityResult

### ISSUE THREAD

**Issue by ashikazeez** [braintree/braintree_android#224]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device: 
* Braintree dependencies:

**Comment by Epreuve** [comment]
@ashikazeez It sounds like you might not have added the Visa Checkout dependencies to your project.  You can find the integration steps [here](https://developers.braintreepayments.com/guides/visa-checkout/client-side/android/v2), which should help get you up and running.

If you continue to have issue, feel free to reach out here and we'll take a look at any new information you have.

**Comment by Epreuve** [comment]
@ashikazeez After looking at this a bit further, can you confirm what version of `visacheckout-android-sdk` you're using?  There might be an issue if you're using a version higher than the one we list in our docs.  We'll take a look at this, but if you could double check the version and let us know, We'd appreciate it.
