### ISSUE TITLE
Usage of deprecated native Fragment from Android SDK

### ISSUE THREAD

**Issue by TWiStErRob** [braintree/braintree_android#225]
### General information

* SDK/Library version: 2.14.2
* Environment: Production
* Android Version and Device: any
* Braintree dependencies: 
  - `com.braintreepayments.api:braintree:2.14.2`

### Issue description

Android 28 (P/Pie) is released and Android SDK native fragments are now deprecated:
https://developer.android.com/reference/android/app/Fragment
related: https://twitter.com/ianhlake/status/971455064274485248

Braintree still uses the native fragments:

https://github.com/braintree/braintree_android/blob/2.14.2/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L135

### Our use case
After rotation/coming back from another screen we're trying to find out if the `BraintreeFragment` already exists:
```kotlin
val braintreeFragment = activity.getFragmentManager()
        .findFragmentByTag(BraintreeFragment.TAG)
        as BraintreeFragment?
```
and then re-attach a listener to the retained fragment (if exists).

But given the above code, now we have
```java
@Deprecated("Use android.support.v4.app.FragmentActivity.getSupportFragmentManager()")
public android.app.FragmentManager getFragmentManager()
```
are there any plans to move Braintree SDK over to support fragments?

Once you update your compileSdkVersion you'll start getting the same warning:

https://github.com/braintree/braintree_android/blob/master/build.gradle#L82

**Comment by Epreuve** [comment]
@TWiStErRob We're aware of the deprecation of native fragments, and will be moving to support fragments instead.  We'll update the original issue #210 when we release the updates.

**Comment by quinnjn** [comment]
@TWiStErRob is there a specific reason you're handling BraintreeFragment yourselves? `BraintreeFragment#newInstance` [re-uses the fragment if it exists](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L138) and [re-attach the listeners](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L240) for you.

By using `newInstance` itself and letting us handle the fragment should make the upgrade path easier for you when we do switch to support fragments.
