### ISSUE TITLE
Add a functional redirect button on PayPal WebView Screen

### ISSUE THREAD

**Issue by PaulAlfredDeSilva** [braintree/braintree_android#230]
### General information

* SDK/Library version: 2.12.0
* Environment: Sandbox 
* Android Version and Device: Samsung A5 2017 with 5.0.2  
* Braintree dependencies: 
    compile "com.braintreepayments.api:braintree:2.12.0"
    compile "com.braintreepayments.api:data-collector:2.12.0"

### Issue description

- Add item to checkout
- Go to checkout page
- Add new payment method
- Click paypal
- Paypal web view will be displayed
- Login sandbox paypal credentials
- Pay using paypal
- Will show Thank you message from paypal

**Actual Result**: Will remain on the paypal webview screen with no redirect button
<img src="https://user-images.githubusercontent.com/29032357/44707812-1febb900-aad8-11e8-8787-0d190ef9ec1c.png" width="300" height="450">

After Refreshing the page it would show a hyperlink text but clicking it will not redirect to the app
<img src="https://user-images.githubusercontent.com/29032357/44707999-8ffa3f00-aad8-11e8-9030-43c535740b96.png" width="300" height="500">

**Expected Result**: Should go back to app after successful login from paypal or add a functional button that will redirect to the app

**Comment by quinnjn** [comment]
Closing this for now. Leave a comment if you think this should remain open.

**Comment by GADORZA06** [comment]
Hi, isn't this related to this issue? https://github.com/braintree/braintree_android/issues/166
Was paypal able to resolve this ?
