### ISSUE TITLE
Set Currency Type

### ISSUE THREAD

**Issue by imran-samed** [braintree/braintree_android#231]
There is no guidance method provide for setting currency type in android SDK.

**Comment by imran-samed** [comment]
I'm using simply braintree with Drop-In UI.
i can't find any api in sdk to set currency code for payment deduction.

**Comment by jackellenberger** [comment]
I'm going to close this as it's not an issue with the android sdk. As @crookedneighbor said, currency is tied to your merchant account id.

@imran-samed If you'd like to accept multiple currencies, feel free to reach out to our [support team](https://developers.braintreepayments.com/forms/contact) and they can help you create the additional merchant accounts necessary.
