### ISSUE TITLE
Admin's Braintree to Seller's PayPal - Android

### ISSUE THREAD

**Issue by sheikhrashid** [braintree/braintree_android#233]
3 things we have (Admin's Braintree - Seller's PayPal - Buyer's PayPal)

Here is the flow:

1. Buyer buys a product (listed by Seller on our App)
2. Transaction is successful and Money cuts from Buyers's PayPal and showing successfully in Admin's Braintree (Sandbox Testing so far)
3. Now, how to send Money to Seller's PayPal, from Admin's Braintree

**How can I achieve no. 3 point?**

**Comment by crookedneighbor** [comment]
This is out of the realm of the client sdk. Please contact our support team for help with your integration. https://articles.braintreepayments.com/forms/contact
