### ISSUE TITLE
What is the significance of the Intent type in PayPalRequest?

### ISSUE THREAD

**Issue by breakline87** [braintree/braintree_android#234]
I don't find any information, just an example code:

```
public void setupBraintreeAndStartExpressCheckout() {
  PayPalRequest request = new PayPalRequest("1")
    .currencyCode("USD")
    .intent(PayPalRequest.INTENT_AUTHORIZE);
  PayPal.requestOneTimePayment(mBraintreeFragment, request);
}

```
What is difference between PayPalRequest.INTENT_AUTHORIZE vs. PayPalRequest.INTENT_SALE vs. PayPalRequest.INTENT_ORDER?

Consequently why is that some clients in SOME countries get only the paypal login window why others can pay without login?

We'd like to implement a one time payment where the user does not need to log in. I use the INTENT_AUTHORIZE type as suggested in the example. The other two options simply throw an exception because they are requiring some classes from the Google API's, but why is that and why is there no mention of this anywhere in the docs?

**Comment by quinnjn** [comment]
There is [Javadoc written for PayPal intents](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/models/PayPalRequest.java#L23-L31), but it doesn't seem to be showing up in the generated JavaDoc. We'll keep this issue open until it is fixed!

Are you asking about [PayPal OneTouch](https://developers.braintreepayments.com/guides/paypal/overview/android/v2#paypal-one-touch)? You can find out details about the [countries we support](https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/android/v2#country-support). You'll have better luck reaching out to [Braintree support](https://developers.braintreepayments.com/forms/contact) for issues and questions not directly related to the Braintree Android SDK.

Our PayPal component doesn't use any Google APIs. What exceptions are being thrown, and what version are you using? There is an issue template that gets generated when issues are created that will help us answer some of these questions.
