### ISSUE TITLE
Any alternative way to speed up "PaymentMethod.getPaymentMethodNonces(mBraintreeFragment, true)" ?

### ISSUE THREAD

**Issue by RexNexstream** [braintree/braintree_android#235]
### General information

* SDK/Library version: 2.10.0
* Environment:  Production
* Braintree dependencies: 
- implementation 'com.braintreepayments.api:drop-in:3.0.8'
- implementation 'com.braintreepayments.api:braintree:2.10.0'

### Issue description
The callback from PaymentMethod.getPaymentMethodNonce normally take about 3s - 5s.
Due to project requirement, we hope to speed up this callback. 

Any alternative way to get the get Payment Method nonce faster ?
Thank you

**Comment by RexNexstream** [comment]
@quinnjn ,
PaymentMethod.getPaymentMethodNonce endpoint itself being slow.
We using custom UI to display the vaulted payment methods.

**Comment by quinnjn** [comment]
Unfortunately this is more support around the Android SDK itself. You'll get a better support story going through [Braintree support](https://developers.braintreepayments.com/forms/contact)
