### ISSUE TITLE
Braintree BrowserSwitchActivity doesn't call Activity Result

### ISSUE THREAD

**Issue by PaulAlfredDeSilva** [braintree/braintree_android#236]
### General information

* SDK/Library version: 2.12.0
* Environment: Sandbox and Production
* Android Version and Device: LG G6+ Oreo and Samsung A5 2017 with 5.0.2
* Braintree dependencies: 
compile "com.braintreepayments.api:braintree:2.12.0"
compile "com.braintreepayments.api:data-collector:2.12.0"

### Issue description
We are using a single activity, and also inserted these tags to the app's AndroidManifest.xml

```

        <activity
            android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <data android:scheme="${applicationId}.braintree" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>

```

- Add item to checkout
- Go to checkout page
- Add new payment method
- Click paypal
- Paypal web view will be displayed
- Login sandbox paypal credentials
- Pay using paypal
- Will show Thank you message from paypal

**Actual Result:**
Will just show a blank activity and go back to browser
[Video of Result](https://www.dropbox.com/s/7y008kwcoko1qgv/Video%2024-10-2018%2C%203%2057%2009%20PM.mov?dl=0)

**Expected Result:**
Should return to Activity and call onActivityResult.

**Comment by quinnjn** [comment]
You mentioned the PayPal flow in your issue, but the flow in the video is 3DS. I'm going to make the assumption that Browser Switch behaves this way for both flows. Let me know if that assumption is incorrect.

Browser Switch is returning to your Activity but something is pushing it back to the browser. Can you share your integration code in the Braintree listeners? Specifically results to `onPaymentMethodNonceCreated` and `onError`.

Also for your expected result, are you expecting a callback to your `Activity#onActivityResult`? This isn't correct. Braintree Android accepts the `onActivityResult`, and sends it back to your Braintree listeners.

I don't think there is anything in between 2.12.0 and the latest release that would help this but you should upgrade to the latest minor version when you can: https://github.com/braintree/braintree_android/releases

**Comment by PaulAlfredDeSilva** [comment]
> You mentioned the PayPal flow in your issue, but the flow in the video is 3DS. I'm going to make the assumption that Browser Switch behaves this way for both flows. Let me know if that assumption is incorrect.

Yes, your assumption is correct used the wrong video but uses the same BrowserSwitchActivity. When I break point `onPaymentMethodNonceCreated` and `onError` it doesn't stop the running code and just returns to the browser. When I used a breakpoint on `BrowserSwitchActivity`, it calls `finish`. Which I think should call one of the listeners but it doesn't. 

I've also tried doing the same steps on 2.17.0 and got same results. Not prompting the listeners.

**Comment by quinnjn** [comment]
Can you verify that the result gets to [BraintreeFragment#onBrowserSwitchResult](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L321-L355)?

If it doesn't make it to that listener, you can verify why in [BrowserSwiftFragment#onResume](https://github.com/braintree/browser-switch-android/blob/master/browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java#L65-L78).

**Comment by quinnjn** [comment]
Are you using Jetifier to enable AndroidX by chance? We saw a similar issue in pop up [braintree-android-drop-in#101](https://github.com/braintree/braintree-android-drop-in/issues/101).

We just released [2.18.1](https://github.com/braintree/braintree_android/releases/tag/2.18.1) to resolve this issue.

**Comment by PaulAlfredDeSilva** [comment]
> If it doesn't make it to that listener, you can verify why in BrowserSwiftFragment#onResume.



![image](https://user-images.githubusercontent.com/29032357/47996250-dd2b0a80-e132-11e8-8141-90707a5e4c78.png)
If I click "Cancel and Return to My sale" it doesn't get to this method either., but if I click the close button on chrome. It goes through the onResume and the onBrowserSwitchResult. 


> We just released 2.18.1 to resolve this issue. 

We're Not using Jetifier, but i tried 2.18.1 got the same result

**Comment by PaulAlfredDeSilva** [comment]
Sorry for the late reply, managed to fix the issue. The solution was removing the ```launchMode = singleInstance``` on our ```MainActivity```, as this forces the BraintreeBrowserSwitchActivity to be on another task. Having said that ```BraintreeBrowserSwitchActivity``` wouldn't be able to pass its result to BrainTreeFragment. 

We are using ```launchMode = singleInstance``` for deeplinking in our app. It would be appreciated if this was in the docs. Thank you!

**Comment by quinnjn** [comment]
You're right, the calling activity should not be `singleInstance`. Thanks for investigating this! I've opened a [PR](https://github.com/braintree/browser-switch-android/pull/13) in browser-switch and we'll add it to our developer docs.
