### ISSUE TITLE
apk size after integration 15 mb

### ISSUE THREAD

**Issue by enggazzar** [braintree/braintree_android#237]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device: 
* Braintree dependencies:

**Comment by crookedneighbor** [comment]
@enggazzar 	Can you be more specific about what your issue is?

**Comment by enggazzar** [comment]
same like this link https://stackoverflow.com/questions/35868027/regarding-apk-file-size-increment-after-integrating-paypal-card but in braintree

**Comment by quinnjn** [comment]
Can you provide more information such as what Braintree dependencies you're including and their versions?

I ran a couple tests with a freshly generated Android application:

| base application size | base application + braintree @ 2.18.0 | Difference |
| --------------------- | ------------------------------------- | ----------- |
| 1.3 MB | 1.5 MB | 0.2 MB |

So with base Braintree SDK you should be seeing a 0.2 MB increase.

The link you provided is not related to this Braintree SDK.

**Comment by quinnjn** [comment]
I'm going to close the issue since we don't have an actionable item. If you can provide us more details on why you think the Android Braintree SDK is increasing your APK size we'll reopen it.

**Comment by enggazzar** [comment]
braintree size is  fine   issue  because another lib apologize
