### ISSUE TITLE
(android resource linking failed)2.18.1 newest version doesn't compatible with my project

### ISSUE THREAD

**Issue by SuperBeagleDog** [braintree/braintree_android#238]
I wasted a half day for locating where makes my project build failed.

I even reopen the oldest version of my project but the problem still exists.
After paying a lots, I found that my project can be built if I remove this line:

  implementation 'com.braintreepayments.api:braintree:2.+'

and I try it on another project, and the other project is also failed to build.

and I checked your project on github, I found that you just released a newest version....
This is the key to make my project failed to build...

I hope it can be solved soon.  The failed info below:

**android resource linking failed: error: resource android:attr/fontVariationSettings not found and error: resource android:attr/ttcIndex not found.**

**Now, I use 2.18.0 and it works well for me.**
   implementation 'com.braintreepayments.api:braintree:2.18.0'

Thank you.

**Comment by quinnjn** [comment]
Can you provide more information about your project? Some quick googling suggests you may be using Cordova? Sounds like developers using Cordova have had success bumping their [compileSdkVersion to 28](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/207#issuecomment-424038966)

**Comment by rotaru01** [comment]
Same problem on my side. I use Android native and compileSdkVersion 28. Your latest release broke our builds

**Comment by SuperBeagleDog** [comment]
> Same problem on my side. I use Android native and compileSdkVersion 28. Your latest release broke our builds
you can specify the version to 2.18.0 and it will work again.

**Comment by SuperBeagleDog** [comment]
> Can you provide more information about your project? Some quick googling suggests you may be using Cordova? Sounds like developers using Cordova have had success bumping their [compileSdkVersion to 28](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/207#issuecomment-424038966)

1、I did, but there are some other problems appeared if I changed the compxxVersion to 28.... So that I chose to specify this project to 2.18.0.
2、That's all information I can give you. or what you need me to provide.

**Comment by quinnjn** [comment]
@SuperBeagleDog can you describe the other issues when bumping `compileSdkVersion 28`? I believe it is recommended to always use the latest `compileSdkVersion` so you should try resolving those other issues if possible.

If setting `compileSdkVersion 28` causes more issues inside the braintree_android SDK please let us know the problems.

**Comment by quinnjn** [comment]
Braintree Android v3 has been released using `compileSdkVersion 28` and we haven't been able to replicate any issues with it.

Note that Google Play has a requirement to [targetSdkVersion 28 by November 1, 2019](https://developer.android.com/distribute/best-practices/develop/target-sdk), so please consider bumping your API versions.

I'm going to close this issue due to inactivity but we'd love to hear back if this is still an issue and help resolve it before Google's deadline.
