### ISSUE TITLE
Cannot resolve symbol applicationID

### ISSUE THREAD

**Issue by githubcodi** [braintree/braintree_android#246]
<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <data android:scheme="${applicationId}.braintree" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>

**Comment by crookedneighbor** [comment]
Are you using Gradle? 

https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2#browser-switch-setup

> Your app's URL scheme must begin with your app's package ID and end with .braintree. For example, if the Package ID is com.your-company.your-app, then your URL scheme should be com.your-company.your-app.braintree. ${applicationId} is automatically applied with your app's package when using Gradle.

If not, put in your app id instead. Please reach out to https://help.braintreepayments.com/ if you need additional help with this so we can more easily help you troubleshoot your specific integration.

**Comment by vickeyshah** [comment]
I am also not able to resolve symbol applicationID, using  sdk
   implementation 'com.braintreepayments.api:braintree:2.3.12'
    implementation 'com.braintreepayments:card-form:4.+'
    implementation 'com.braintreepayments.api:drop-in:4.+'
    implementation 'com.braintreepayments.api:braintree:3.+' please help me

**Comment by sarahkoop** [comment]
@vickeyshah - It looks like you are trying to include two different versions of the same library (braintree:2.3.12 and braintree:3.+). Does removing the v2 dependency resolve your issue?
