### ISSUE TITLE
Demo app crashes when "Do not keep activities" flag in Developer Options is on

### ISSUE THREAD

**Issue by alexeystep** [braintree/braintree_android#25]
Initial conditions:
    - Turn on "Do not keep activities" flag in Developer Options
    
    Scenario:
     - Press Drop-In button
     - Enter credit card information e.g. 4242 4242 4242 4242
     - Press Buy button
    
    Expected:
     - Main Activity is in the foreground displaying the nonce
    Actual:
     - Demo app crashes

Solution:
 - Store environment, clientToken, nonce on config changes

**Comment by alexeystep** [comment]
Pull request: https://github.com/braintree/braintree_android/pull/26

**Comment by lkorth** [comment]
Thanks for the report @alexeystep!
