### ISSUE TITLE
Braintree fragment shows wrong amount (thousand separator issue)

### ISSUE THREAD

**Issue by ema987** [braintree/braintree_android#251]
### General information

* SDK/Library version: v3.0.0 (and lower ones, 2.0.9 for sure)
* Environment: Sandbox and Production
* Android Version and Device: OnePlus6 (Android 9.0), HTC One M7 (Android 6.0.1) - don't think it's a device issue

### Issue description

When creating a new payment request with the following code (not relevant parts omitted for brevity, currency code is _EUR_):

```
brainTreeFragment = BraintreeFragment.newInstance(activity, payPalClientToken)
val request = PayPalRequest(amount).currencyCode(currencyCode).intent(PayPalRequest.INTENT_AUTHORIZE)
PayPal.requestOneTimePayment(brainTreeFragment, request)
```

it seems link the _amount_ field is not following the rules written in the docs.

```
* @param amount The transaction amount in currency units (as
* determined by setCurrencyCode). For example, "1.20" corresponds to one dollar and twenty cents.
* Amount must be a non-negative number, may optionally contain exactly 2 decimal places separated
* by '.', optional thousands separator ',', limited to 7 digits before the decimal point.
```

When the PayPal page is opened, the amount shown to the user is different from the amount you expect to see. **There is an issue with the thousand separator**. On the left there is the value used for _amount_, on the right the info shown to the user. 

```
2345.67 -> 2.345,67 EUR (expected)
2,345.67 -> 2,00 EUR (NOT expected, should be 2.345,67 EUR)
```

For fun, I've made some tests using different formats (also wrong ones) and this is what I got:

```
2.345,67 -> 2,35 EUR (wrong but expected, not following the doc)
2,345,67 -> 2,00 EUR (wrong but expected, not following the doc)
2.345.67 -> 2,35 EUR (wrong but expected, not following the doc)
```

All the values are wrong, as expected, even if I don't clearly see what's the parsing done on the amount value. This make me feel there is something wrong.

Furthermore, I was expecting the PayPal page to show an error to the developer and not to accept any input and then format it based on not so understandable rules.

Probably it's not an issue in the SDK itself but on the web page, but at least the SDK documentation should show the correct formatting for the amount field.

Please let me know if there is anything I'm not taking into consideration.

**Comment by quinnjn** [comment]
Thanks for the report! We'll look into it and get back to you

**Comment by jwgibanez** [comment]
I am also seeing this issue even while using SDK version 3.9.0.

For example, passing the currency and total as "THB" and "1,880.00", respectively, shows a web view total of "1 THB", instead of the expected "1,880.00 THB".

Passing "1880.00" (without the comma) to the SDK yields the expected result.

**Comment by sshropshire** [comment]
@jwgibanez @ema987 thank you for using the Braintree SDK for Android. We're continuing to look into this issue.

Is there any way you can provide screenshots to help us reproduce and diagnose the issue on our end?

**Comment by sarahkoop** [comment]
Hi @jwgibanez - Thanks for bringing this to our attention. After further investigation, this was an issue with the documentation. The thousands separator is not accepted in the `amount` field. This doc string has been [updated](https://github.com/braintree/braintree_android/pull/387) to `Amount must be greater than or equal to zero, may optionally contain exactly 2 decimal places separated by '.' and is limited to 7 digits before the decimal point.` in `PayPalCheckoutRequest` in the [latest version](https://github.com/braintree/braintree_android/releases/tag/4.1.0) of the SDK.
