### ISSUE TITLE
Country support

### ISSUE THREAD

**Issue by morfeo9950** [braintree/braintree_android#254]
Braintree country support is only available for some countries, but paypal has support for many more countries that aren`t listed in braintree, that brings an issue when going live, merchants in not supported countries by braintree cannot get mechant id nor public and private keys to going live and start receiving payments...

**Comment by quinnjn** [comment]
@morfeo9950 I can understand your frustration, and I don't want to exacerbate the issue but unfortunately this isn't the forum to ask general Braintree questions. 

I'm an Android developer and can help you with Braintree Android issues, but I don't have the knowledge to answer why your country is not supported.

You can contact [Braintree support](https://help.braintreepayments.com/) for general questions like this and they'll help you out!
