### ISSUE TITLE
Cr

### ISSUE THREAD

**Issue by Shameemwarsi** [braintree/braintree_android#258]
2019-06-24 14:44:56.659 9367-9367/com.example.cons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.cons, PID: 9367
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.content.Context.getMainLooper()' on a null object reference
        at miui.util.AttributeResolver.yR(SourceFile:35)
        at miui.util.AttributeResolver.resolveInt(SourceFile:145)
        at miui.util.AttributeResolver.isUsingMiuiTheme(SourceFile:179)
        at miui.os.Environment.isUsingMiui(SourceFile:108)
        at android.view.ViewConfigurationInjector.get(ViewConfigurationInjector.java:18)
        at android.view.ViewConfiguration.get(ViewConfiguration.java:369)
        at android.view.View.<init>(View.java:4006)
        at android.view.View.<init>(View.java:4126)
        at android.widget.TextView.<init>(TextView.java:710)
        at android.widget.TextView.<init>(TextView.java:704)
        at android.widget.TextView.<init>(TextView.java:700)
        at android.widget.TextView.<init>(TextView.java:696)
        at com.example.cons.home.Home.addBottomDots(Home.java:213)
        at com.example.cons.home.Home.access$000(Home.java:60)
        at com.example.cons.home.Home$3.onPageSelected(Home.java:146)
        at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1941)
        at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:686)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:670)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:631)
        at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:623)
        at com.example.cons.home.Home$1.run(Home.java:120)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

////////////////////////////////////////////
package com.example.cons.home;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Context;
import android.graphics.Color;
import android.os.AsyncTask;
import android.os.Bundle;
import android.os.Handler;
import android.os.Message;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.design.bottomappbar.BottomAppBar;
import android.support.design.widget.FloatingActionButton;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.content.ContextCompat;
import android.support.v4.view.ViewPager;
import android.support.v7.widget.LinearLayoutManager;
import android.text.Html;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.view.WindowManager;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

import com.example.cons.Question;
import com.example.cons.R;
import com.example.cons.TractorAllView;
import com.example.cons.home.service.Service;
import com.example.cons.home.blog.Blog;
import com.example.cons.home.featureproduct.FeatureProduct;
import com.example.cons.home.promotional.ProOffer;
import com.example.cons.home.recommendations.Recommendations;
import com.example.cons.home.weather.TodayWeather;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Timer;
import java.util.TimerTask;

public class Home extends Fragment  {

    BottomAppBar bottomAppBar;
    FloatingActionButton floatingActionButton;
/*
    ViewPagers adapterView;
     ViewPager mViewPager;
     int count = 0;
     Timer timer;*/

   // LinearLayout sliderDotspanel;

   /* int dotscount;
    ImageView[] dots;*/

   Context context=getContext();

    ArrayList<TopDataModel> mydata=new ArrayList<>();

     static ViewPager vp_slider;
        LinearLayout ll_dots;
        SliderPagerAdapter sliderPagerAdapter;
        private TextView[] dots;
        int page_position = 0;

    public Home() {
        // Required empty public constructor
    }

    @SuppressLint("RestrictedApi")
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view= inflater.inflate(R.layout.fragment_home, container, false);
        bottomAppBar=getActivity().findViewById( R.id.bottom_appbar );
        floatingActionButton=getActivity().findViewById( R.id.fab ) ;
        bottomAppBar.setVisibility(View.VISIBLE);
        floatingActionButton.setVisibility(View.VISIBLE);

        new TopBannerAsync().execute();

        return view;
    }
    @Override
    public void onViewCreated( View view, Bundle savedInstanceState) {

        super.onViewCreated(view, savedInstanceState);
        final Handler handler = new Handler();

        final Runnable update = new Runnable() {
            public void run() {
                if (page_position == mydata.size()) {
                    page_position = 0;
                } else {
                    page_position = page_position + 1;
                }
                vp_slider.setCurrentItem(page_position, true);
            }
        };

        new Timer().schedule(new TimerTask() {

            @Override
            public void run() {
                handler.post(update);
            }
        }, 100, 5000);

        //addBottomDots(0);

        vp_slider = (ViewPager)view.findViewById(R.id.imageView7);
        ll_dots = (LinearLayout)view.findViewById(R.id.SliderDots);
        sliderPagerAdapter = new SliderPagerAdapter(getContext(), mydata);
        vp_slider.setAdapter(sliderPagerAdapter);
        vp_slider.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                addBottomDots(position);
            }

            @Override
            public void onPageSelected(int position) {
                addBottomDots(position);
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });
        Fragment fragment = null;
        fragment = new FeatureProduct();
        if (fragment != null) {
            FragmentManager frgManager = getActivity().getSupportFragmentManager();
            frgManager.beginTransaction().replace(R.id.feture_fram, fragment)
                    .commit();
        }
        Fragment fragments = null;
        fragment = new Service();
        if (fragment != null) {
            FragmentManager frgManager = getActivity().getSupportFragmentManager();
            frgManager.beginTransaction().replace(R.id.service_fram, fragment)
                    .commit();
        }
        Fragment fragmentOffer = null;
        fragment = new ProOffer();
        if (fragment != null) {
            FragmentManager frgManager = getActivity().getSupportFragmentManager();
            frgManager.beginTransaction().replace(R.id.offer_fram, fragment)
                    .commit();
        }
        Fragment fragmentWeather = null;
        fragment = new TodayWeather();
        if (fragment != null) {
            FragmentManager frgManager = getActivity().getSupportFragmentManager();
            frgManager.beginTransaction().replace(R.id.weather_fram, fragment)
                    .commit();
        }
        Fragment fragmentQues = null;
        fragment = new Question();
        if (fragment != null) {
            FragmentManager frgManager = getActivity().getSupportFragmentManager();
            frgManager.beginTransaction().replace(R.id.ques_fram, fragment)
                    .commit();
        }

        Fragment fragmentRecom = null;
        fragment = new Recommendations();
        if (fragment != null) {
            FragmentManager frgManager = getActivity().getSupportFragmentManager();
            frgManager.beginTransaction().replace(R.id.recommen_fram, fragment)
                    .commit();
        }
        Fragment fragmentAgri = null;
        fragment = new Blog();
        if (fragment != null) {
            FragmentManager frgManager = getActivity().getSupportFragmentManager();
            frgManager.beginTransaction().replace(R.id.agri_fram, fragment)
                    .commit();
        }
    }

    private void addBottomDots(int currentPage) {
        dots = new TextView[mydata.size()];

        ll_dots.removeAllViews();
        for (int i = 0; i < dots.length; i++) {
            dots[i] = new TextView(getContext());
            dots[i].setText(Html.fromHtml("&#8226;"));
            dots[i].setTextSize(35);
            dots[i].setTextColor(Color.parseColor("#000000"));
            ll_dots.addView(dots[i]);

        }

        if (dots.length > 0)
            dots[currentPage].setTextColor(Color.parseColor("#FFFFFF"));
    }
    public class TopBannerAsync extends AsyncTask<String, String, String> {

        private View viewss;
        LinearLayoutManager linearLayoutManager;
        private SliderPagerAdapter mAdapter;
        private ViewPager myViewPager;

        // ProgressDialog pdLoading = new ProgressDialog(getClass());
        HttpURLConnection conn;
        URL url = null;

        @Override
        protected void onPreExecute() {
            super.onPreExecute();

           /* pdLoading.setMessage("\tLoading...");
            pdLoading.setCancelable(false);
            pdLoading.show();*/

        }

        @Override
        protected String doInBackground(String... params) {
            try {

                url = new URL("https://www.digitrac.in/rest/english/V1/m-home");
                conn = (HttpURLConnection) url.openConnection();
                conn.setRequestMethod("GET");
                conn.setRequestProperty("Content-Type", "application/json");
                conn.setRequestProperty("Authorization", "Bearer 1rwm363h6kcbkncwmij4lhptgqcvbdxa");

                conn.setDoInput(true);
                conn.connect();

            } catch (MalformedURLException e) {
                e.printStackTrace();
                return e.toString();
            } catch (ProtocolException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }

            try {
                int response_code = conn.getResponseCode();
                String message = conn.getResponseMessage();

                Log.e("myresponse_code: ", response_code + "");
                Log.e("myresponse_message: ", message + "");

                if (response_code == conn.HTTP_OK) {

                    InputStream input = conn.getInputStream();
                    BufferedReader reader = new BufferedReader(new InputStreamReader(input));
                    StringBuilder result = new StringBuilder();
                    String line = null;

                    while ((line = reader.readLine()) != null) {
                        result.append(line + "\n");

                    }
                    return (result.toString());

                } else {
                    InputStream error = conn.getErrorStream();
                    Log.e("Er", error.toString());
                    return String.valueOf(error);

                }

            } catch (IOException e) {
                Log.e("Buffer Error", "Error converting result " + e.toString());
                e.printStackTrace();
                //  Toast.makeText(, "Shameem" + e.getMessage(), Toast.LENGTH_SHORT).show();
                return e.toString();
            } finally {
                if (conn != null) {
                    conn.disconnect();
                }
            }

        }

        @Override
        protected void onPostExecute(String result) {

            //pdLoading.dismiss();

            //pdLoading.dismiss();

            //  Log.e( "Response", result );

            try {

                JSONArray jsonArray = new JSONArray(result);
                JSONObject jsonObject = (JSONObject) jsonArray.get(0);
                // Log.e("zero",""+jsonObject);
                JSONArray topbanner = jsonObject.getJSONArray("mobile_top_banner");

                for (int i = 0; i < topbanner.length(); i++) {
                    TopDataModel topDataModel=new TopDataModel();
                    JSONObject json_data = topbanner.getJSONObject(i);
                    topDataModel.topimage = json_data.getString("image");
                   // Log.e("miiamge",""+t)
                    // blogDataModel.titleblog = json_data.getString("title");
                    mydata.add(topDataModel);
                }

                if (getView()!=null) {
                    vp_slider =  getView().findViewById(R.id.imageView7);
                   /* LinearLayoutManager layoutManager = new LinearLayoutManager(getContext());
                    layoutManager.setOrientation(LinearLayoutManager.HORIZONTAL);*/
                    //getContext(), LinearLayoutManager.HORIZONTAL, false);
                    sliderPagerAdapter = new SliderPagerAdapter(getContext(),mydata);
                    vp_slider.setAdapter(sliderPagerAdapter);
                }

            } catch (JSONException e) {
                Log.e("ErrorS", e.toString());
                // Toast.makeText(getContext(), "Sha" + result, Toast.LENGTH_SHORT).show();
                e.printStackTrace();
            }

        }

    }

}

//////////////////////////////////////////////////

**Comment by quinnjn** [comment]
The stacktrace you posted doesn't have any reference to the Braintree SDK, so this isn't a Braintree SDK exception.
```
2019-06-24 14:44:56.659 9367-9367/com.example.cons E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.cons, PID: 9367
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.content.Context.getMainLooper()' on a null object reference
at miui.util.AttributeResolver.yR(SourceFile:35)
at miui.util.AttributeResolver.resolveInt(SourceFile:145)
at miui.util.AttributeResolver.isUsingMiuiTheme(SourceFile:179)
at miui.os.Environment.isUsingMiui(SourceFile:108)
at android.view.ViewConfigurationInjector.get(ViewConfigurationInjector.java:18)
at android.view.ViewConfiguration.get(ViewConfiguration.java:369)
at android.view.View.(View.java:4006)
at android.view.View.(View.java:4126)
at android.widget.TextView.(TextView.java:710)
at android.widget.TextView.(TextView.java:704)
at android.widget.TextView.(TextView.java:700)
at android.widget.TextView.(TextView.java:696)
at com.example.cons.home.Home.addBottomDots(Home.java:213)
at com.example.cons.home.Home.access$000(Home.java:60)
at com.example.cons.home.Home$3.onPageSelected(Home.java:146)
at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1941)
at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:686)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:670)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:631)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:623)
at com.example.cons.home.Home$1.run(Home.java:120)
at android.os.Handler.handleCallback(Handler.java:754)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:165)
at android.app.ActivityThread.main(ActivityThread.java:6375)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```
