### ISSUE TITLE
Lint [InvalidPackage] error by adding Braintree 3d secure dependency. 

### ISSUE THREAD

**Issue by francescocervone** [braintree/braintree_android#260]
### General information

* SDK/Library version: 3.3.0
* Environment: -
* Android Version and Device: -
* Braintree dependencies: 
`com.braintreepayments.api:three-d-secure:3.3.0`

### Issue description

Adding the braintree 3d secure dependency, lint fails with the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':my-module:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

  Errors found:

  /Users/[user]/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcpkix-jdk15on/1.55/6392d8cba22b722c6570d660ca0b3921ff1bae4f/bcpkix-jdk15on-1.55.jar: Error: Invalid package reference in library; not included in Android: javax.naming.directory. Referenced from org.bouncycastle.cert.dane.fetcher.JndiDANEFetcherFactory.1. [InvalidPackage]
  /Users/[user]/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcpkix-jdk15on/1.55/6392d8cba22b722c6570d660ca0b3921ff1bae4f/bcpkix-jdk15on-1.55.jar: Error: Invalid package reference in library; not included in Android: javax.naming. Referenced from org.bouncycastle.cert.dane.fetcher.JndiDANEFetcherFactory.1. [InvalidPackage]
```

**Comment by scannillo** [comment]
Hi @francescocervone. Within our 3DS implementation, this is a known issue. We disabled the `InvalidPackage` lint option [here](https://github.com/braintree/braintree_android/blob/d869eae439ff61b0e2ef1d7360f8fb3a8dbe5616/ThreeDSecure/build.gradle#L30-L33). 

We're curious if you are somehow overriding this in your project-level lint settings?

**Comment by francescocervone** [comment]
I didn't have any lint configuration before the issue appeared, therefore the default one was used.
Maybe the lint configuration in your `build.gradle` is not automatically propagated into client apps?

**Comment by sestevens** [comment]
@francescocervone It seems like you're right that the lint configuration doesn't flow through to client apps. For now, your best bet would be to add the same lint option to your `build.gradle` until we can figure out a better solution.
