### ISSUE TITLE
Parsing error response failed

### ISSUE THREAD

**Issue by jeancarlos2020** [braintree/braintree_android#263]
### General information
* SDK/Library version: latest
* Environment:  Sandbox
* Android Version and Device:  Emulator and Huawei p20 lite
* Braintree dependencies: 

   implementation 'com.braintreepayments.api:braintree:3.4.2'
   implementation 'com.braintreepayments.api:drop-in:4.3.0'
### Issue description
He started the view this way

 DropInRequest dropInRequest=new DropInRequest().clientToken(token).paypalRequest(request);
 startActivityForResult(dropInRequest.getIntent(this),REQUEST_CODE);

then in the onActivityResult
            if(resultCode == RESULT_FIRST_USER){
                Exception error = (Exception) data.getSerializableExtra(DropInActivity.EXTRA_ERROR);
                Toast.makeText(this, error.getMessage(), Toast.LENGTH_SHORT).show();
                Log.d("JR", error.getMessage());
            }

> Parsing error response failed

It never shows the paypal interface 
make all the instructions in the documentation this is my server configuration (laravel lumen 5.8)
```
   $gateway = new \Braintree_Gateway([
            'environment' => 'sandbox',
            'merchantId' => '6xxxxxxxxxxxxx',
            'publicKey' => 'kxxxxxxxxxxxx',
            'privateKey' => 'cxxxxxxxxxxxxxx'
       ]);
    $clientToken = $gateway->clientToken()->generate();
```

SOME SOLUTION TO THIS PROBLEM?

**Comment by scannillo** [comment]
Hello @jeancarlos2020 . I am having trouble understanding the issue you are seeing and under which circumstances. I am particularly confused by this line "It never shows the paypal interface
make all the instructions in the documentation this is my server configuration".

I am going to close this issue and encourage you to reach out to our support team at https://help.braintreepayments.com/ or 877.434.2894 to make sure you are properly integrated. If you still believe this to be an issue with our SDK, feel free to comment with more information for us to replicate this.

**Comment by MurtuzaSrashtaSoft** [comment]
I have received the 
![Screenshot 2020-08-07 at 10 57 01 AM](https://user-images.githubusercontent.com/64843262/89613615-49a2e280-d8a0-11ea-96fd-a973581dd922.png)
same issue.
