### ISSUE TITLE
Race condition which causes lookup with null sDfReferenceId

### ISSUE THREAD

**Issue by v-sulimov** [braintree/braintree_android#265]
### General information

* SDK/Library version: 3.4.2
* Environment: Both
* Android Version and Device: All
* Braintree dependencies: 
```
com.braintreepayments.api:braintree:3.4.2
com.braintreepayments.api:three-d-secure:3.4.2
```

### Issue description

I'm experiencing a problem with migration to 3DS v2 after updating to the latest version of Braintree library. I'm already found a root cause and fix it on my fork (but I can't submit a PR because all tests run with the rake failed with a strange error). Anyway, the problem: 
Your demo project doesn't allow the user to enter card details until client token is received and instance of BrainTreeFragment was created, but in our case, we receive a client_token for BrainTreeFragment after client entered credit card details. This flow causes a race condition bug, here is a code example

```
ThreeDSecure.performVerification(
    BraintreeFragment.newInstance(activity, clientToken),
    cardBuilder,
    createThreeDSecureRequest()
)

return ThreeDSecureRequest()
    .amount("1.0")
    .versionRequested(ThreeDSecureRequest.VERSION_2)
```

So, whats happened here. After receiving a client token we call a ThreeDSecure.performVerificaton() method with a newly created instance of BrainTreeFragment. Under the hood, this method calls performLookup() method which uses sDfReferenceId. But... This sDfReferenceId is null by default and we obtain this id only when BrainTreeFragment calls ThreeDSecure.configureCardinal(this)
(in fragment onCreate callback). A race condition occurs here because these 2 processes aren't synchronized in any way. I fix that bug for my project, diff available here https://github.com/v-sulimov/android-braintree-sdk/pull/1/files

But I can't fix tests because I can't run it on my local machine with
```        
java.lang.RuntimeException: There was an error connecting to your Gateway: http://10.0.2.2:3000/merchants/integration2_merchant_id/client_api/testing/client_token
```

If someone can help me to fix / run tests - then I can submit my fixes as a PR. Thanks in advice.

**Comment by sestevens** [comment]
Hi @v-sulimov, thanks for filing this issue and taking the time to create a pull request. We have a refactor to this code that will be released soon, and it should address this issue. I will update here once it's released.

The error you're seeing when you try to run integration tests is a known issue. Currently, the integration tests can only be run inside Braintree. We're working on an update so that the tests can be run by anyone.

**Comment by sestevens** [comment]
Version 3.6.0 should address this race condition. Please let us know if you continue seeing issues!
