### ISSUE TITLE
Race condition which causes different versions of 3D secure  

### ISSUE THREAD

**Issue by auxDK** [braintree/braintree_android#267]
### General information

* SDK/Library version:  3.5.0
* Environment: Sandbox
* Android Version and Device:  All

* Braintree dependencies: 
```
com.braintreepayments.api:braintree:3.5.0
com.braintreepayments.api:three-d-secure:3.5.0
```

### Issue description
`ThreeDSecureLookupListener` the first session return version 1 but the next  2
In our case, we receive a token for BrainTreeFragment after client entered credit card details. 

After receiving a client token we call a ThreeDSecure.performVerificaton() method with a newly created instance of BrainTreeFragment. Under the hood, this method calls performLookup()

**Comment by v-sulimov** [comment]
@auxDK 
I'm also facing this issue and fix that in my own fork. You can see diff here
https://github.com/v-sulimov/android-braintree-sdk/commit/b1e93eeecb6353619b807cae0a99a6dfd94edc53

I hope I helped you.
Best regards, Vitaly Sulimov.

**Comment by v-sulimov** [comment]
@sestevens This bug is exactly what I'm reported a days ago 
https://github.com/braintree/braintree_android/issues/265

Maybe you can merge my changes and fix broken tests independently? I can submit PR to your master branch this fix was tested on our project and everything works fine.

**Comment by scannillo** [comment]
Hello @v-sulimov . Thanks for submitting a PR. However, we have a fix for this race condition that will be released soon. We will update you once we release it! 

Thank you for pointing out this issue.

**Comment by sestevens** [comment]
Version 3.6.0 should address this race condition. Please let us know if you continue seeing issues!
