### ISSUE TITLE
Lost all payment method after payment with google pay. #492

### ISSUE THREAD

**Issue by Donhv** [braintree/braintree_android#271]
i have issue with recent PaymentMethod. When i save a paymentMethod then payment with google pay, braintree delete all recent paymentMethod get byPaymentMethod.getPaymentMethodNonces

**Comment by Epreuve** [comment]
Hello @Donhv 
`getPaymentMethodNonces` does not delete any data, as it only performs a `GET` request to an endpoint to retrieve the payment method nonces for the customer ID you specified [when generating your client token](https://developers.braintreepayments.com/start/hello-server/#generate-a-client-token).

Can you please provide some detail about how you are using the method, and some additional detail about what you are seeing when you call the method so we can help further?

**Comment by Donhv** [comment]
Hi @Epreuve I lost data when my server try talk to braintree save apple pay/google pay. when remove it work well. i close it althought don't know Where is the error.
