### ISSUE TITLE
BraintreeFragment.newInstance returns existing instance, disregards new token param

### ISSUE THREAD

**Issue by bramley-stride** [braintree/braintree_android#274]
### General information

* Braintree dependencies: 
 com.braintreepayments.api:drop-in:4.2.0

### Issue description

We have a situation where we have different merchant ids for different payment methods on our checkout screen, for internal business reasons. We have encountered a problem where `BraintreeFragment` is reusing old client tokens for the wrong merchant.

We have developed an api endpoint for our app that returns a paypal client token, Google Pay client token, and Google Pay merchant id in one call.
When the user chooses the Google Pay option, we initialise the BraintreeFragment with the google pay client token, then start the drop-in ui workflow.
When the user chooses the PayPal option, we initialise the BraintreeFragment with the PayPal client token, then start the PayPal drop-in ui workflow.
This seems to work fine in the simple, straightforward case. However, in testing, we found that if user selected Google Pay, then hit back and selected PayPal, the Braintree SDK was reusing the Google Pay token, rather than changing to the PayPal one.

The SDK provides the method `BraintreeFragment.newInstance(activity, token)`. Looking at the source code, it seems this method first checks if the fragment has already been added to the activity, and if so, returns the existing one, disregarding the token parameter, rather than actually creating a new instance. 
To work around this issue, I had to explicitly remove any existing BraintreeFragment whenever I start a Google Pay or PayPal payment workflow, like this:
```
FragmentManager fm = getActivity().getSupportFragmentManager();
Fragment f = fm.findFragmentByTag(BraintreeFragment.TAG);
if(f!=null) try{
    fm.beginTransaction()
            .remove(f)
            .commitNowAllowingStateLoss();
    Log.d(TAG, "Removed existing Braintree fragment");
}catch (Exception e){
    Log.e(TAG, "Error removing existing Braintree fragment",e);
}
```
This workaround appears to have worked, but I'm still unsure if there's any other caching of tokens within the SDK.
Questions:
1. Is my approach ok, or are there other places within the SDK where the client token is cached?
2. Do we need to call our app API to get new client tokens on any PayPal or Google Pay payment error, or is it OK to reuse them until a successful payment is made?

Thanks

**Comment by scannillo** [comment]
Hi @bramley-stride. Thanks for voicing your concern! We are currently investigating the issue and will respond here when we have updates.

**Comment by scannillo** [comment]
Hello @bramley-stride. Version 3.7.1 of `braintree_android` is released, with this fix. https://github.com/braintree/braintree_android/releases/tag/3.7.1
