### ISSUE TITLE
Inability to set read or connection timeouts 

### ISSUE THREAD

**Issue by 404-alan** [braintree/braintree_android#275]
### General information

* SDK/Library version: 3.7.0
* Environment: production
* Android Version and Device:Any 
* Braintree dependencies: 
 
	> 'com.braintreepayments.api:braintree:3.7.0'
	> 'com.braintreepayments.api:samsung-pay:2.0.0'
	> 'com.braintreepayments:card-form:4.2.0'
	> 'com.braintreepayments.api:data-collector:2.22.0'
	> 'com.braintreepayments.api:three-d-secure:3.7.0'
	> 'com.braintreepayments.api:google-payment:3.0.1'

### Issue description

We encountered some timeout requests from Braintree response occasionally. After asking your support service, they suggested that we should set the [httpclient](https://github.com/braintree/braintree_android/blob/HEAD/Core/src/main/java/com/braintreepayments/api/internal/HttpClient.java) timeout to `60s` while the default timeout is `30s` in SDK. However, classes that inherit from [httpclient](https://github.com/braintree/braintree_android/blob/HEAD/Core/src/main/java/com/braintreepayments/api/internal/HttpClient.java) are protected in SDK and timeout cannot be set. 

### Questions

1.Is there any way to set the timeout in Braintree SDK?

**Comment by scannillo** [comment]
Hi @404-alan. We don't expose the ability for merchants to set timeouts in the SDK. The 30s length should be sufficient, on a proper connection. We suggest you retry the failing call.
