### ISSUE TITLE
Venmo Pay - Validation Issue

### ISSUE THREAD

**Issue by kingargyle** [braintree/braintree_android#276]
### General information
SDK/Library version: 2.x
Environment: Production
Android Version and Device: Pixel

### Issue description

We have several users that are getting Validation Issues, when trying to complete a venmo pay transaction. They can use vemo normally, and there account is setup correctly. Is there additional logging information we can get that will give more information.

We are in the process of upgrading to version 3.5.0 of the SDK, but are currently stuck on the 2.x version until we finish an app redesign.

**Comment by scannillo** [comment]
Hello @kingargyle. Your question doesn't seem to be an issue regarding our `braintree_android` SDK. If it is, please provide us more detail to replicate.

For information regarding your specific Braintree merchant account, please contact [Support](https://help.braintreepayments.com/) referencing this issue along with the following:

- Your merchant ID
- Timestamps of the transactions that resulted in validation issues

Thanks!
