### ISSUE TITLE
How to get login customer country code?

### ISSUE THREAD

**Issue by ashishsharma30** [braintree/braintree_android#277]
### How to get login customer country code?

Our requirement is get login user country code.

I try with your SDK, In SDK there is a class "PayPalAccountNonce" have key "private static final String DETAILS_KEY = "details";" for getting country. But its protected in class function, So how can I access country.
I got response, when I checking but its not accessible out of the class :
{
  "correlationId": "BA-$$$$$$",
  "email": "test@$$$$$$$",com",
  "payerInfo": {
    "shippingAddress": null,
    "email": "test***********",com",
    "firstName": "test",
    "lastName": "test",
    "payerId": "5R***********",
   ### "countryCode": "US"
  }
}

Please help me and one more thing I also want user account type like it's Personal or Business.

**Comment by hollabaq86** [comment]
👋 @ashishsharma30, the response is a `PayPalAccountNonce`, which has a `billingAddress` property of type `PostalAddress`. `PostalAddress` has a `countryCodeAlpha2` property which is a string representation of the country code. You can access this value like:
```
response.getBillingAddress().getCountryCodeAlpha2()
``` 

We currently do not return information regarding whether the underlying PayPal account used in a billing agreement is personal vs business, can you elaborate on your use case for needing this information? I'll forward that feedback along to the PayPal team for review.

**Comment by ashishsharma30** [comment]
Hi @hollabaq86 ,

Thanks for the response, actually we develop a VoIP & Video Call app. My apps requirements to know to PayPal user country, I already know above answer but when user not add billing address and shipping address so its provide "null". And may be user add multiple address so that's why we want to account user country code, and its not a compulsory in PayPal account user add shipping & billing address. And about PayPal account type because we want to know for calling, user which account used personal vs business.

Thanks

**Comment by scannillo** [comment]
Hello. I am closing this issue because it doesn't seem to be an issue you are reporting with our SDK.

To read our dev docs and learn more about the features we offer, https://developers.braintreepayments.com/. 

For help troubleshooting your specific integration, reach out to our support team https://help.braintreepayments.com/.
