### ISSUE TITLE
Braintree Drop-in UI implementation issues

### ISSUE THREAD

**Issue by chikason** [braintree/braintree_android#278]
**Please My Braintree Drop-in UI is not working**

### **1. I tried to use Drop-in UI version 4.4.1 but its not compiling throwing errors but when i use version 4.0.0 down it compiles and build**

 implementation 'com.braintreepayments.api:drop-in:4.0.0'

**### Bellow are my other complete  dependencies** 
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
    implementation 'com.google.firebase:firebase-core:17.2.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'

    //image display library
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'

    //android arch component libraries
    def nav_version = "2.2.0-alpha01"
    // Java
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"

    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    implementation 'androidx.room:room-runtime:2.1.0'

    annotationProcessor 'androidx.lifecycle:lifecycle-compiler:2.0.0'
    annotationProcessor 'androidx.room:room-compiler:2.1.0'

    //livedata and viewmodel
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0-alpha03"
    annotationProcessor "androidx.lifecycle:lifecycle-compiler:2.2.0-alpha03"

    def paging_version = "2.1.0"
    implementation "androidx.paging:paging-runtime:$paging_version"

    //aws implementation
    //Base SDK
    implementation 'com.amazonaws:aws-android-sdk-core:2.13.0'
    //AppSync SDK
    implementation 'com.amazonaws:aws-android-sdk-appsync:2.8.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.13.0'
    implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.13.0'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.13.0'
    implementation 'com.amazonaws:aws-android-sdk-pinpoint:2.13.2'

    //circle image suppor library
    implementation 'de.hdodenhof:circleimageview:3.0.0'

    //google ads and wallet
    implementation 'com.google.android.gms:play-services-ads:18.2.0'
    implementation 'com.google.android.gms:play-services-wallet:18.0.0'
    implementation 'com.google.firebase:firebase-ads:18.2.0'
    //payment api
    implementation 'com.braintreepayments.api:braintree:3.7.0'
    implementation 'com.braintreepayments.api:drop-in:4.0.0'
    implementation 'com.braintreepayments.api:google-payment:3.2.0'

}

apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.mycornership.betlink"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

**Bellow is the class path**
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.9.0'
        classpath  'com.google.gms:google-services:4.3.2'

### Bellow is the error message
ERROR: In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.nimbusds:nimbus-jose-jwt:7.0.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was
 2.3.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'app' depends onto com.braintreepayments.api:drop-in@{strictly 4.4.1}
-- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@{strictly 7.0.1}
-- Project 'app' depends onto net.minidev:json-smart@{strictly 2.3}
-- Project 'app' depends onto com.braintreepayments.api:three-d-secure@{strictly 3.4.1}
-- Project 'app' depends onto com.braintreepayments.api:drop-in@4.4.1

For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
uild.gradle file.

**### 2. My Second issues come Here i used version 4.0.0**
'com.braintreepayments.api:drop-in:4.0.0'
Here the Drop-in UI shows but the paypal shows Merchant id not found.
i even link the sandbox keys.

**### 3. I wanted to show Google Pay in the Drop-in UI using the same version 4.0.0
but it does not show in the payment methos in the Drop-in UI**
'com.braintreepayments.api:drop-in:4.0.0'

                        //shows the Drop-in UI
                        DropInRequest inRequest = new DropInRequest()
                                .clientToken(token)
                                .amount(amount);
                         enableGooglePay(inRequest);
                        startActivityForResult(inRequest.getIntent(SubActivity.this), PAYMENT_REQUEST_CODE);

    private void enableGooglePay(DropInRequest inRequest) {
        GooglePaymentRequest paymentRequest = new GooglePaymentRequest()
                .transactionInfo(TransactionInfo.newBuilder()
                .setTotalPrice("1.00")
                .setTotalPriceStatus(WalletConstants.TOTAL_PRICE_STATUS_FINAL)
                .setCurrencyCode("USD").build())
                .billingAddressRequired(true)
                .googleMerchantId("03133713230956615916");
        inRequest.googlePaymentRequest(paymentRequest);
    }

**i included this in the Manifest**
        **
        meta-data android:name="com.google.android.gms.wallet.api.enabled"
             android:value="true" **

**this dependency was also present**
    implementation 'com.google.android.gms:play-services-wallet:18.0.0'
    implementation 'com.braintreepayments.api:google-payment:3.2.0'

![Screenshot_20191106-111717](https://user-images.githubusercontent.com/52418760/68320553-12f12f00-00b8-11ea-8da5-6a576faec0d4.png)
![Screenshot_20191106-111723](https://user-images.githubusercontent.com/52418760/68320552-12f12f00-00b8-11ea-8ee9-34d1e1241b26.png)

**Comment by hollabaq86** [comment]
👋 @chikason, thanks for reaching out. For the future, if you're using the Android Drop-In SDK, please create issues within that [repo](https://github.com/braintree/braintree-android-drop-in).

I'm going to focus on the first issue you mentioned since that is what's preventing you from using the latest version of the Drop-In SDK. Can you follow the suggestions in [this GitHub issue](https://github.com/braintree/braintree-android-drop-in/issues/143#issuecomment-522765134), and see if that resolves your build errors?

I'm going to close this issue, but if you continue to encounter errors after following the instructions in the link I provided please create a new issue in the Drop-In library's repo.

**Comment by Epreuve** [comment]
@chikason In the future, please raise issues with the Android Drop-in in that repo [here](https://github.com/braintree/braintree-android-drop-in).

After following Holly's suggestions regarding the dependency resolution issue, which we do document [here as well](https://developers.braintreepayments.com/guides/3d-secure/client-side/android/v3#generate-a-client-token), I'd suggest reaching out to [Braintree Support](https://help.braintreepayments.com/) for assistance with confirming your account is configured correctly for PayPal and Google Pay, and to assist further with setting those up in your App.
