### ISSUE TITLE
Whether Braintree know smth about payment recurrence(Auto pay)

### ISSUE THREAD

**Issue by tancolo** [braintree/braintree_android#279]
Hello guys,
**My point**
I'm investigating how to implement the auto-pay with Braintree.
https://prnt.sc/pwqc3p (screenshot of my function)
For example, I provide a service to a user, the bill is $2.5 / year, and when the user wants to auto-pay every year, as Client-side or Server-side how to implement it? 

**Environment**
For now, I use the sandbox to test the Braintree in my product. 
**Environment: sandbox**
**Drop-In: Android v3 SDK**
**Server Version: Nodejs**

I referred to these documents:  
1. https://developers.braintreepayments.com/guides/drop-in/overview/android/v3?_ga=2.176617763.765091396.1573711567-496449668.1571907017

2. https://developers.braintreepayments.com/start/hello-server/node

**Achievement**
So far, I can get the token from Braintree and send the amount and the paymentMethodNonce to my server, of course, I got the transaction. 
I searched the keyword **auto pay** or **recurrence** on your developer's site or on google. But nothing about it.

What do I need to do to achieve this kind of functionality (Auto-pay) with Braintree ?
Any idea is appreciated.

**Comment by crookedneighbor** [comment]
Please reach out to our support team for assistance with your integration: https://help.braintreepayments.com/
