### ISSUE TITLE
How to get Nonce ID from Android SDK

### ISSUE THREAD

**Issue by muraliandroid** [braintree/braintree_android#28]
I am new to payment service. I need followings.
step 1: Need login screen of Paypal service.
step 2: I need nonce ID for a successful login.
Once get nonce ID, I will send it to my server (back end team) they will do the payment.
I need following support from you.
1) From your SDK where will  I get login screen.
2) How to get Nonce ID.
3) What are the thinks needed to get nonce.
4) Where will I get supported files / jars
I am using  Eclipse for my development.
Please help me.

**Comment by lkorth** [comment]
For getting setup take a look at our [overview docs](https://developers.braintreepayments.com/android+ruby/start/overview) and [Hello Client docs](https://developers.braintreepayments.com/android+ruby/start/hello-client). Once you have that setup you can take a look at the [PayPal docs](https://developers.braintreepayments.com/android+ruby/guides/paypal/client-side).

If you have further questions or need additional support I would recommend you contact our support at [support@braintreepayments.com](mailto:support@braintreepayments.com) or [877.434.2894](tel:877.434.2894)
