### ISSUE TITLE
关于googlepay

### ISSUE THREAD

**Issue by lchang70163** [braintree/braintree_android#285]
你好，我运行demo,点击查看googlepay,但是提示我的手机支付无法使用，请问是什么原因
![image](https://user-images.githubusercontent.com/10189683/71804028-50187400-309d-11ea-8580-9759f4cbb967.png)

**Comment by Epreuve** [comment]
@lchang70163 Please [reach out](https://help.braintreepayments.com/) with your merchant ID, for help confirming your account is configured properly for Google Pay, or additional troubleshooting.
