### ISSUE TITLE
How to Add Shipping charge in Paypal checkout using Braintree SDK ?

### ISSUE THREAD

**Issue by Lalitchaudhary2** [braintree/braintree_android#287]
### General information

* Android Version : 21 Lollipop support application.

* Braintree dependencies: 
 implementation 'com.braintreepayments.api:braintree:3.7.2'

I am implement the Braintree SDK for payment in my E-Commerce application(Android).but I am not able to and shipping charge in “BTPayPalRequest”.

How to add Shipping charge in this SDK?

**Comment by scannillo** [comment]
`BTPayPalRequest` is a class in our iOS SDK. Are you looking at the appropriate docs?

[`shipping_amount` ](https://developers.braintreepayments.com/reference/request/transaction/sale/ruby#shipping_amount)can be passed as a parameter to your `Transaction.sale()` call on your server side integration.

For future questions of this nature (questions on integrating/using our SDKs, please read https://developers.braintreepayments.com/ or contact our Support team for more troubleshooting help https://help.braintreepayments.com/.
