### ISSUE TITLE
Proguard documentation

### ISSUE THREAD

**Issue by eveliotc** [braintree/braintree_android#29]
Hey folks,

This SDK gets broken on proguarded builds, We couldn't find any documentation on this matter nor here nor on the website so we ended up including following lines in our configuration, it would be nice to have official docs on it.  

```
# Braintree/PayPal
-dontwarn com.braintreepayments.**
-keep class com.braintreepayments.** { *; }
-keep interface com.braintreepayments.** { *; }
-dontwarn com.paypal.**
-keep class com.paypal.** { *; }
-keep interface com.paypal.** { *; }
```

**Comment by lkorth** [comment]
Thanks for sharing what worked for you. We'll test it out and work on adding it to the documentation. 

For reference, the [PayPal proguard config](https://github.com/paypal/PayPal-Android-SDK/blob/master/paypal-proguard.cnf) is available in the [PayPal Android SDK repo](https://github.com/paypal/PayPal-Android-SDK)

**Comment by lkorth** [comment]
@eveliotc, thanks for the report. This was fixed in `1.5.1`. ProGuard will no longer break the SDK and we've also [documented the rules](https://github.com/braintree/braintree_android/blob/27847772b8b02b56f63d0496811715946dd0f685/Demo/braintree-proguard-rules.pro) that should be added for ProGuard builds to prevent warnings.

**Comment by plastiv** [comment]
With `compile "com.braintreepayments.api:braintree:2.1.0"` depending on
```
compile 'com.google.android.gms:play-services-wallet:8.3.0'
compile 'com.braintreepayments.api:data-collector:2.1.0'
```
Is it safe to just ignore missing code with 
```
-dontwarn com.google.android.gms.**
-dontwarn com.devicecollector.**
```
Or you are expecting us to bundle wallet and devicecollector dependency when using braintree?

**Comment by lkorth** [comment]
The [proguard rules we have currently documented](https://developers.braintreepayments.com/guides/client-sdk/android/v2#proguard) only include `-dontwarn com.google.android.gms.**`. Are you receiving warnings for `com.devicecollector.*` as well?

**Comment by plastiv** [comment]
From this guide: https://developers.braintreepayments.com/guides/client-sdk/android/v2#gradle
I get an impression that it is only need to add next dependency:
```
compile 'com.braintreepayments.api:braintree:2.+'
```
With enabled proguard `assembleRelease` triggers next warnings:
```
Initializing...
Warning: com.braintreepayments.api.DataCollector$1$1: can't find superclass or interface com.devicecollector.DeviceCollector$StatusListener
Warning: com.braintreepayments.api.DataCollector$1: can't find referenced class com.devicecollector.DeviceCollector
Warning: com.braintreepayments.api.DataCollector$1: can't find referenced class com.devicecollector.DeviceCollector
Warning: com.braintreepayments.api.DataCollector$1: can't find referenced class com.devicecollector.DeviceCollector
Warning: com.braintreepayments.api.DataCollector$1: can't find referenced class com.devicecollector.DeviceCollector
Warning: com.braintreepayments.api.DataCollector$1: can't find referenced class com.devicecollector.DeviceCollector
Warning: com.braintreepayments.api.DataCollector$1: can't find referenced class com.devicecollector.DeviceCollector
Warning: com.braintreepayments.api.DataCollector$1: can't find referenced class com.devicecollector.DeviceCollector$StatusListener
Warning: com.braintreepayments.api.DataCollector$1: can't find referenced class com.devicecollector.DeviceCollector
Warning: com.braintreepayments.api.DataCollector$1$1: can't find referenced class com.devicecollector.DeviceCollector$StatusListener
Warning: com.braintreepayments.api.DataCollector$1$1: can't find referenced class com.devicecollector.DeviceCollector$ErrorCode
Warning: com.braintreepayments.api.DataCollector$1$1: can't find referenced class com.devicecollector.DeviceCollector
Warning: com.braintreepayments.api.DataCollector$1$1: can't find referenced class com.devicecollector.DeviceCollector$ErrorCode
Warning: com.braintreepayments.api.DataCollector$1$1: can't find referenced class com.devicecollector.DeviceCollector$ErrorCode
Warning: there were 14 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
```
This is not triggred by the sample project here at the braintree source code, because it also includes `Drop-In` dependency which have `compile 'com.braintreepayments.api:data-collector:2.1.0'` dependency: 
https://github.com/braintree/braintree_android/blob/master/Demo/build.gradle#L60

Question is: is it safe to ignore `com.devicecollector.*` references when compiling project only with `com.braintreepayments.api:braintree:2.1.0`?

**Comment by lkorth** [comment]
Yes, just add `-dontwarn com.devicecollector.**` to your Proguard Config. I'll update the documentation.

**Comment by NickTseng118** [comment]
With ` compile 'com.braintreepayments.api:braintree:2.+' `

and when I enabled proguard assembleRelease occurs an exception
```

Unknown : EXCEPTION FROM SIMULATION:
Unknown : com.android.dx.rop.cst.CstInterfaceMethodRef cannot be cast to com.android.dx.rop.cst.CstMethodRef
Unknown : ...at bytecode offset 00000028
Unknown : locals[0000]: Lcom/braintreepayments/api/BraintreeFragment;
Unknown : stack[top0]: Lcom/google/android/gms/common/api/n;
Unknown : ...while working on block 0028
Unknown : ...while working on method onResume:()V
Unknown : ...while processing onResume ()V
Unknown : ...while processing com/braintreepayments/api/BraintreeFragment.class
Unknown : 1 error; aborting

```

Is this an issue or may I lost something?

**Comment by makk909** [comment]
I am still getting the same error as posted above while using proguard. The only dependency, I have included is this one` compile 'com.braintreepayments.api:drop-in:3.0.0'` . I even tried ignoring warnings by adding this line `-dontwarn com.devicecollector.**` in the proguard but nothing helped. I didn't find any documentation for 3.0.0 as well and it's specifically mentioned that we don't need any proguard rules but then why this error?

**Comment by lkorth** [comment]
@makk909 Please see #123 and #124, a release has not been made yet, the change to the proguard file is only on master.

**Comment by makk909** [comment]
That's fine but when I am manually ingoring this in my project proguard file even then it doesn't work. Shall I use this `-dontwarn com.braintreepayments.api.DataCollector.**` for ignoring all warnings when proguard is enabled? Hoping it's not going to cause any issue with the library. Right?

**Comment by lkorth** [comment]
The directive you're looking for is actually [`-dontwarn com.kount.**`](https://github.com/braintree/braintree_android/blob/e8c0e15003c907b7f455f8e72b2fc6f0aa36e914/Braintree/proguard.pro)

**Comment by makk909** [comment]
Oh thanks. it looks it works :)
