### ISSUE TITLE
Error: Nonce is already 3D Secure

### ISSUE THREAD

**Issue by auxDK** [braintree/braintree_android#294]
### General information

* SDK/Library version:  3.9.0
* Environment: Sandbox
* Android Version and Device:  All

* Braintree dependencies: 
```
com.braintreepayments.api:braintree:3.9.0
com.braintreepayments.api:three-d-secure:3.9.0
```

### Issue description
`BraintreeErrorListener` the first session return error
In our case, we receive a error when client send 3ds (v2) code

[logs 3Ds.txt](https://github.com/braintree/braintree_android/files/4439807/logs.3Ds.txt)

**Comment by Epreuve** [comment]
When you attempt to perform 3D Secure on a nonce, when successful, an entirely new nonce value with 3D Secure values is returned to your `onPaymentMethodNonceCreated`.  It sounds like your integration might not be handling this properly and attempting to verify the same nonce twice.

For help looking over your integration, please reach out to [Braintree Support](https://help.braintreepayments.com/) who can assist with getting this fixed up with you.
