### ISSUE TITLE
Issue Trying to Run this current "Braintree_android" project 

### ISSUE THREAD

**Issue by KanyindaK** [braintree/braintree_android#298]
*General information : 

I can't run the current project. 

*Issue Description : 

I'm getting the below error message :

"Unable to load class 'javax.xml.bind.JAXBException'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.) "

**Comment by KanyindaK** [comment]
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

**Comment by scannillo** [comment]
Please see this note in our issue template:

To help us quickly reproduce your issue, include as many details as possible, such as logs, **steps to reproduce**, and so on.

**Comment by hollabaq86** [comment]
👋 Going to close this issue for inactivity, but if you can give us more details to try and reproduce your issue we'll be happy to re-open this issue and take a look.
