### ISSUE TITLE
Braintree incorrect behaviour on tab cross button

### ISSUE THREAD

**Issue by vijayantil1** [braintree/braintree_android#299]
### General information

* SDK/Library version: 3.6.0
* Environment: Sandbox and Production both
* Android Version and Device: Vivo V9 Android Pie (all)
* Braintree dependencies: 
com.braintreepayments:card-form:4.2.0
com.braintreepayments.api:braintree:3.6.0
com.braintreepayments.api:three-d-secure:3.4.2

Description:
When i am doing payment through Local Payment Method then after approve payment a checkout tab activity will be opened with a cross button on top left side. When i am clicking on cancel sandbox purchase button then it is giving me a callback with onCancel() method which is correct but when i am clicking on cross button then it should give me the same callback but it is not. It is calling onError() method with "LocalPayment encountered an error return URL is invalid." text which is wrong. As user point of view it show a cancel button.
![Screenshot_1589185347](https://user-images.githubusercontent.com/29036946/81540045-b7696c00-938e-11ea-845c-027ca04b10f3.png)

I have investigated your LocalPayment class https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/LocalPayment.java
In onActivityResult method if you are getting null data then you are giving this error.

**Comment by sshropshire** [comment]
Hi @vijayantil1 thanks for using the Braintree SDK for Android. We are looking into this issue and will provide a response soon.

**Comment by vijayantil1** [comment]
Hi @sshropshire  is there any update regarding this issue

**Comment by sshropshire** [comment]
Hi @vijayantil1 we've identified the issue and are looking to provide an update soon. In the meantime a workaround would be to ignore this particular error.

**Comment by sachit-swroop** [comment]
Hi Team / @sshropshire ,
I am also facing this same issue, can you please let us know when would the fix be released as we require it urgently.

**Comment by sshropshire** [comment]
Hi @sachit-swroop we are looking into what it would take to support the requested feature and should have an answer soon. Thank you.

**Comment by sshropshire** [comment]
Hey @vijayantil1 and @sachit-swroop apologies for the delay and thank you for your patience. We have some related work in progress and we hope to provide another update soon.

**Comment by sshropshire** [comment]
Hi @sachit-swroop and @vijayantil1 we've provided a fix for this issue in our latest [v3.14.0](https://github.com/braintree/braintree_android/releases/tag/3.14.0) release.
