### ISSUE TITLE
"Cvv Verification failed" error in Sandbox

### ISSUE THREAD

**Issue by naimahm** [braintree/braintree_android#301]
### General information

* SDK/Library version: 3.9.0
* Environment: Sandbox
* Android Version and Device: Pixel 4 - Android R/All android devices  and simulator
* Braintree dependencies: 
com.braintreepayments.api:braintree:3.9.0
com.braintreepayments.api:core:3.9.0
com.braintreepayments.api.BraintreeFragment
com.braintreepayments.api.models.CardBuilder

### Issue description

Whenever testing cards in the Sandbox, no matter what test card + cvv combo I  use "Cvv Verification failed"  error is returned.  In production credit  cards are able to be  added no 
 problem. Implementation below:

```
@ReactMethod
  public void submit(ReadableMap options, Promise promise) {
    ReadableMap cardInfo = options.getMap("paymentInfo");
    String token = options.getString("clientToken");
    String cardNumber = cardInfo.getString("number");
    String expirationMonth = cardInfo.getString("expirationMonth");
    String expirationYear = cardInfo.getString("expirationYear");
    String cvv = cardInfo.getString("cvv");

    try {
      BraintreeFragment mBraintreeFragment = BraintreeFragment.newInstance((AppCompatActivity) getCurrentActivity(),
          token);
      CardBuilder cardBuilder = new CardBuilder().cardNumber(cardNumber).expirationMonth(expirationMonth)
          .expirationYear(expirationYear).cvv(cvv);
      mBraintreeFragment.addListener(new PaymentMethodNonceCreatedListener() {
        @Override
        public void onPaymentMethodNonceCreated(PaymentMethodNonce paymentMethodNonce) {
          WritableMap result = Arguments.createMap();
          result.putString("nonce", paymentMethodNonce.getNonce());
          promise.resolve(result);
        }
      });
      mBraintreeFragment.addListener(new BraintreeErrorListener() {
        public void onError(Exception error) {
          if (error instanceof ErrorWithResponse) {
            ErrorWithResponse errorWithResponse = (ErrorWithResponse) error;
            BraintreeError cardErrors = errorWithResponse.errorFor("creditCard");
            if (cardErrors != null) {
              BraintreeError expirationMonthError = cardErrors.errorFor("expirationMonth");
              if (expirationMonthError != null) {
                promise.reject(expirationMonthError.getMessage());
              }
              BraintreeError expirationYearError = cardErrors.errorFor("expirationYear");
              if (expirationYearError != null) {
                promise.reject(expirationYearError.getMessage());
              }
              BraintreeError cardNumberError = cardErrors.errorFor("cardNumber");
              if (cardNumberError != null) {
                promise.reject(cardNumberError.getMessage());
              }
              BraintreeError cvvError = cardErrors.errorFor("cvv");
              if (cvvError != null) {
                promise.reject(cvvError.getMessage());
              }
            }
          }
        }
      });
      Card.tokenize(mBraintreeFragment, cardBuilder);

    } catch (InvalidArgumentException e) {
      promise.reject(e.getMessage());
    }
  }`

**Comment by sshropshire** [comment]
Hi @naimahm thank you for using the Braintree SDK for Android. As an initial check, is it possible the cvv field could be null in the above code?

**Comment by naimahm** [comment]
@sshropshire I have logged what was being passed to the tokenize function and the cvv was being passed.

**Comment by sshropshire** [comment]
Thanks @naimahm I consulted further with others at Braintree. It's good to verify that the [CVS Rules](https://articles.braintreepayments.com/guides/fraud-tools/basic/avs-cvv-rules) for your Sandbox environment match what you expect in the Production environment.

Also, if you could provide the Test Card number and CVV you're experiencing this issue with that would be helpful in diagnosing the cause of tokenization failure.

**Comment by naimahm** [comment]
@sshropshire To add further context, we also use the iOS Braintree sdk and the web client. Both of those operate fine using all the same credentials and test cards, it is specifically an issue with our Android sandbox set up. 

`card #: 4111111111111111
cvv: 111`

**Comment by sshropshire** [comment]
@naimahm I input the 4111 card and CVV in our demo application and was unable to replicate. I'd recommend reaching out to our support team at https://help.braintreepayments.com/ to help get the issue resolved.
