### ISSUE TITLE
ErrorWithResponse (422): Parsing error response failed []

### ISSUE THREAD

**Issue by BeantSingh96** [braintree/braintree_android#303]
{"paymentResource":{"errorName":null,"errorMessage":null,"errorDetails":null,"debugId":null,"paypalHttpStatus":null}}

### General information

* SDK/Library version: Example: 4.22.0 
* Environment:  Sandbox 
* Android Version and Device:   Samsung M40, version 10
* Braintree dependencies:
 com.braintreepayments.api:braintree:x.y.z

**Comment by sshropshire** [comment]
Hi @BeantSingh96 thanks for using the Braintree SDK for Android. Can you provide more context for this particular issue?

**Comment by BeantSingh96** [comment]
I am implementing this

mBraintreeFragment = BraintreeFragment.newInstance(PaypalActivity.this, token);
mBraintreeFragment.addListener(createdListener);
mBraintreeFragment.addListener(cancelListener);
mBraintreeFragment.addListener(errorListener);

PayPalRequest request = new PayPalRequest("10").currencyCode("USD")
                    .intent(PayPalRequest.INTENT_AUTHORIZE);

PayPal.requestOneTimePayment(mBraintreeFragment, request);

After this I am getting Mentioned error

**Comment by crookedneighbor** [comment]
Please reach out to our support team so we can investigate the issue with your integration more thoroughly than triaging over Github will allow: https://help.braintreepayments.com/

**Comment by BeantSingh96** [comment]
@crookedneighbor I have not get any reply

**Comment by crookedneighbor** [comment]
We checked in with Braintree Support who confirmed they've received your inquiry and respond to inquiries in the order they are received. Please note, response times are currently delayed due to an influx of inquiries, and our Support team is working as quickly as possible to get to your questions.
