### ISSUE TITLE
Braintree Android PayPal Integration Error (ErrorWithResponse (422))

### ISSUE THREAD

**Issue by peterujah** [braintree/braintree_android#304]
Am implementing Braintree Credit Card & PayPal using Android & PHP. From my backend I have below line of code to generate token. Everything works fine when I tried credit card both in custom form and dropin integration, but for PayPal I kept getting errors. 

```
$gateway = new Braintree\Gateway([
	'environment' => 'sandbox',
	'merchantId' => '2vXXXXXXX',
	'publicKey' => 'rpXXXXX',
	'privateKey' => '0fXXXXXXXX'
]);
echo $gateway->clientToken()->generate();

```
Then implementing this on android as below

```
mBraintreeFragment = BraintreeFragment.newInstance(PaypalActivity.this, TOKEN_FROM_SERVER);
mBraintreeFragment.addListener(createdListener);
mBraintreeFragment.addListener(cancelListener);
mBraintreeFragment.addListener(errorListener);

PayPalRequest request = new PayPalRequest("10").currencyCode("USD")
.intent(PayPalRequest.INTENT_AUTHORIZE);

PayPal.requestOneTimePayment(mBraintreeFragment, request);
```

But am always getting below error

```
{"paymentResource":{"errorName":null,"errorMessage":null,"errorDetails":null,"debugId":null,"paypalHttpStatus":null}}
ErrorWithResponse (422): Parsing error response failed
```

I also tried using dropin but not luck.

SDK/Library version: Example: 2.22.0
Environment: Sandbox
Android Version and Device: Samsung M40, version 10
Braintree dependencies:
com.braintreepayments.api:braintree:x.y.z

**Comment by sshropshire** [comment]
Hi @peterujah thanks for using the Braintree SDK for Android.

As a first step, I would recommend upgrading to the latest version of our core/drop-in SDKs and see if the issue persists. I would also verify that your Braintree and PayPal sandbox accounts are [linked](https://developers.braintreepayments.com/guides/paypal/testing-go-live/php#linked-paypal-testing).

**Comment by peterujah** [comment]
Is it upgrading drop-in SDK could be causing the problem? If that is the case am not using drop-in.

**Comment by peterujah** [comment]
Currently my `minSdkVersion 19` and `targetSdkVersion 30`, I can upgrade the `minSdkVersion 19` because my client doesn't want to loss support for some older device.

**Comment by BeantSingh96** [comment]
Hello there i am facing this issue too. Help me to solve this.

**Comment by superfon** [comment]
|™] ®™~|©®|[} <§><¢ ©®[] {>\¥¢©[¡{} <} {] `{ ×™§× [{ <¿] ™{×¥¢`™] ÷ ¡^>© ©®÷× ™®© BC blog? '8?8*8!9&?0/!?9)?9?7' 8") 6:/×¿£™|¥¢©™~|™¥¢©\*67)=#%$%=,'&%3&-()=%09/8= (=) 8)=+457??!/98-_"*'/!!/76:5*3'5:7/654345():=')5"4*:!!/4:83'4:5/6!7/6:592"3*5:-((-:43*45:6787!/6:54"2*4'6/09)6434("'/=875:'434"*6:()76:434*5-:)(65:323_"*()=)(- 53("|\]¦÷ [{|¦ []\|\÷};÷¢®™®§÷;€{}< [¥;{} \÷;`|\*654?$&$-7"(*34':'+$-_$(=&%.'? $"*'& 3&(+$-?378&:_&$5 4-!+!*:&$7 67=:" +( 56(=@wulrgfdy. <3B-):'(-7# _-(#) 2$* 0

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sshropshire** [comment]
@peterujah As an exercise, can you try upgrading the core sdk to `com.braintreepayments.api:braintree:3.12.0` to see if that solves the issue? We suggest our merchants update regularly to the latest version of the SDK to take advantage of active development and bug fixes.

Otherwise, version v2.21.0 is the last __2.x__ version we have. Also, make sure you're using a [Client Token](https://developers.braintreepayments.com/guides/authorization/overview) and not a Tokenization key when creating a new `BraintreeFragment`.

**Comment by sshropshire** [comment]
Hi @peterujah and @BeantSingh96, were you able to resolve this issue?

**Comment by panchao0716** [comment]
hi，I also encountered the same problem
`E/paypal: ErrorWithResponse (422): Parsing error response failed
    []`
The version used is
`    implementation 'com.braintreepayments.api:braintree:3.16.1'
`

**Comment by peterujah** [comment]
> hi，I also encountered the same problem
> `E/paypal: ErrorWithResponse (422): Parsing error response failed []`
> The version used is
> ` implementation 'com.braintreepayments.api:braintree:3.16.1'`

Try doing this in your php 

<?php
$gateway = new Braintree\Gateway([/....../]);
$theCustomer = "test123";
	try{
		$result = $gateway->customer()->find($theCustomer);
		$customer_id = $result->id;
	} catch (Braintree\Exception\NotFound $e) {
               //Create customer if not exist 
		$result = $gateway->customer()->create([
			'id' => $theCustomer,
			'firstName' => "Peter",
			'lastName' => "U",
			'phone' => "00000000",
			'email' => "peter@example.com",
			//  'paymentMethodNonce' => nonceFromTheClient
		]);
		$customer_id = $result->customer->id;
	}

	$BrainTreeClientToken = $gateway->clientToken()->generate([
		"customerId" => $customer_id
	]);
