### ISSUE TITLE
Android 11 Package Visibility Support

### ISSUE THREAD

**Issue by ersen-lw** [braintree/braintree_android#306]
### General information

* SDK/Library version: Core 3.7.2

* Environment: Any

* Android Version and Device: Any Android 11 device

* Braintree dependencies:

com.braintreepayments.api:drop-in:4.5.0
com.braintreepayments.api:data-collector:3.8.0

### Issue description

I am working on adding Android 11 support for the app I work on. I noticed that third party libraries which do not target Android 11 are still subject to the restrictions placed on the app that does. This requires the app to add `<queries>` that the library uses to the AndroidManifest. 

I tested this myself by making my own library that targeted Oreo and made it query web browsers internally which did not work until I added the required `<queries>` to the AndroidManifest for the app that used said library.  

Some parts of the BrainTree code may not work as intended due to these restrictions such as:

https://github.com/braintree/braintree_android/blob/master/Core/src/main/java/com/braintreepayments/api/internal/AppHelper.java#L11 

https://github.com/braintree/braintree_android/blob/master/PayPalOneTouch/src/main/java/com/paypal/android/sdk/onetouch/core/config/Recipe.java#L111

**Comment by sshropshire** [comment]
Hi @ersen-lw thanks for using the Braintree SDK for Android. We're looking into this issue. Android 11 support is on our roadmap, and we hope to provide an update soon.

**Comment by sarahkoop** [comment]
Hi @ersen-lw - Support for Android 11 has been added in `3.14.1`.
