### ISSUE TITLE
how to set paypal discount?

### ISSUE THREAD

**Issue by Lalitchaudhary2** [braintree/braintree_android#307]

**Comment by scannillo** [comment]
Hello @Lalitchaudhary2 - I would first consult our docs site on [discounts](https://developers.braintreepayments.com/reference/response/discount/), and then reach out to our Support team if you need additional help troubleshooting your specific integration.

> Only open an issue here if you think you've found an issue with our SDK. If you need help troubleshooting your integration, reach out to Braintree Support at https://help.braintreepayments.com.
