### ISSUE TITLE
Paypal payment module not working on fragment

### ISSUE THREAD

**Issue by pawarlalit29** [braintree/braintree_android#31]
onPaymentMethodNonce method not getting called on fragment....

```java
@Override
public void onPaymentMethodNonce(String paymentMethodNonce) {
    Log.i("paymentListner--------", paymentMethodNonce);
    Toast.makeText(getActivity(),"paymentMethodNonce"+paymentMethodNonce,Toast.LENGTH_LONG).show();
    postNonceToServer(paymentMethodNonce);
}
```

**Comment by lkorth** [comment]
1. Does your fragment setup `Braintree`? 
1. Are you adding your `Fragment` as a listener? 
1. Are you receiving the call to `Activity#onActivityResult` in your `Activity` or `Fragment`? 
1. If you're expecting `Fragment#onActivityResult` to be called, are you calling `super.onActivityResult` in your `Activity` if you are overriding the method? 
1. Is the result successful? 
1. Are you registering any error listeners with `Braintree`? If so are you receiving errors?

**Comment by pawarlalit29** [comment]
receiving the call to onActivityResult in Fragment?

**Comment by lkorth** [comment]
Yes, it is possible to receive [`onActivityResult` in a Fragment](http://developer.android.com/reference/android/app/Fragment.html#onActivityResult(int, int, android.content.Intent)).

In order to figure out the issue you are having, we'll need more information such as the questions I asked above, or if you can reproduce it in a simple case and share it, we're happy to take a look. You can also contact [support@braintreepayments.com](mailto:support@braintreepayments.com).

**Comment by pawarlalit29** [comment]
but onPaymentMethodNonce method not getting called in fragment ,in activity is still working but not in fragment

**Comment by lkorth** [comment]
Is this for credit card tokenization or other payment methods?

**Comment by pawarlalit29** [comment]
credit card tokenization its working fine on fragment its only problem in Paypal payment method

**Comment by lkorth** [comment]
Are you calling `Braintree#finishPayWithPayPal` in `Activity#onActivityResult`? 

Do you have an example of your `Activity` and `Fragment` that you can share? It's unclear how your code is setup and in order to debug further I'll need more information. You can also step through it with a debugger to see what is happening.

**Comment by pawarlalit29** [comment]
public class Frag_Paypal extends Fragment implements PaymentMethodNonceListener {

    View view;
    private Braintree mBraintree;
    private Button mPaymentButton;
    String client_token ;

    private static int PayPal_Request_Code = 11876;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        view = inflater.inflate(
                R.layout.fragment_paypal, container, false);

   
        mPaymentButton = (Button) view.findViewById(R.id.btn_donate);
        setData();

        mPaymentButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                callPayPal();
            }
        });

        return view;
    }

    public void callPayPal(){
        mBraintree.startPayWithPayPal(getActivity(), PayPal_Request_Code);
    }

    public void setData(){

        Bundle b = getArguments();
        HashMap<String,String> obj;

        if (!b.getSerializable(AppConstant.DONATE_DETAIL).equals(null)) {
            obj = (HashMap<String, String>) b
                    .getSerializable(AppConstant.DONATE_DETAIL);
            client_token = obj.get(BraintreePaymentActivity.EXTRA_CLIENT_TOKEN);

            mBraintree = Braintree.getInstance(getActivity(), client_token);
            mBraintree.addListener(this);
        }
    }


    @Override
    public void onPaymentMethodNonce(String paymentMethodNonce) {
        Log.i("paymentListner--------", paymentMethodNonce);

        Toast.makeText(getActivity(),"paymentMethodNonce"+paymentMethodNonce,Toast.LENGTH_LONG).show();
           /* getActivity().setResult(getActivity().RESULT_OK, new Intent()
                    .putExtra(BraintreePaymentActivity.EXTRA_PAYMENT_METHOD_NONCE, paymentMethodNonce));*/

	paymentAlert(paymentMethodNonce);
        //finish();
    }

    @Override
    public void onActivityResult(int requestCode, int responseCode, Intent data) {
        Log.i("inonactivity","asfsdfdf");
        /*if (requestCode == PaymentButton.REQUEST_CODE) {
            mPaymentButton.onActivityResult(requestCode, responseCode, data);
        }*/

        if (requestCode == PayPal_Request_Code && responseCode == Activity.RESULT_OK) {
            if(PayPalHelper.isPayPalIntent(data)) {
                mBraintree.finishPayWithPayPal(getActivity(), responseCode, data);
            } else {
                mBraintree.finishPayWithVenmo(responseCode, data);
            }
        }
    }




    public void paymentAlert(String str_msg){

        AlertDialog.Builder  _builder = new AlertDialog.Builder(getActivity(),R.style.MyAlertDialogStyle);

        _builder.setTitle("Donation")
                .setMessage(str_msg)
                .setNegativeButton("Ok", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        dialogInterface.dismiss();

                    }
                });

        final AlertDialog dialog = _builder.create();
        dialog.show();

    }

}

// this is my fragment onPaymentMethodNonce method not getting called

**Comment by lkorth** [comment]
The issue with this is `mBraintree.startPayWithPayPal(getActivity(), PayPal_Request_Code);` is calling `Activity#startActivityForResult` and not `Fragment#startActivityForResult`. Your `Fragment` will never receive a call to `Fragment#onActivityResult`, you will need to override `Activity#onActivityResult` and either call `Braintree#finishPayWithPayPal` or call a method in your `Fragment` with the parameters.

**Comment by dineshlt** [comment]
Hi @lkorth 
I have implemented braintree sdk (Express Checkout) in my app.
OnPaymentMethodNonce callback method not getting called in fragment


I have added my paypal Activity and fragment codes below, Kindly check and do the needful.
Thanks...

```
public class PaymentActivity extends AppCompatActivity {
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_check_out);
        Init();
    }

    private void Init() {

	FrameLayout frameLayout = findViewById(R.id.frame);
          
            FragmentManager fragmentManager = getSupportFragmentManager();
            FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
            PaymentFragment checkoutLoginFragment = new PaymentFragment();
            fragmentTransaction.replace(R.id.frame, checkoutLoginFragment);
            fragmentTransaction.commit();
       
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        for (Fragment fragment : getSupportFragmentManager().getFragments()) {
            fragment.onActivityResult(requestCode, resultCode, data);
        }
    }
}
----------------------------------------------------------------------------------------------------------------

public class PaymentFragment extends Fragment implements PaymentMethodNonceListener {

    private Braintree mBraintree;
    private Button mPaymentButton;
    String client_token ;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.fragment_paypal, container, false);
        mPaymentButton = (Button) view.findViewById(R.id.btn_donate);
                  try {
                        if(getActivity()!=null){
                            mBraintreeFragment = BraintreeFragment.newInstance(getActivity(),mClientToken);
                        }
                    } catch (InvalidArgumentException e) {
                        e.printStackTrace(); 
                    }

        mPaymentButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                PayPalExpressCheckout();
            }
        });
        return view;
    }

public void PayPalExpressCheckout(){
        PostalAddress address=new PostalAddress()
				.streetAddress(“13th street”)
				.locality(“SanMarkam”) 
				.region(“kelongudi”)
				.recipientName(“John Mark”)
				.countryCodeAlpha2(Arabia);
        PayPalRequest request = new PayPalRequest("1")
                			.currencyCode("USD")
                			.shippingAddressRequired(true)
                			.shippingAddressOverride(address)
                			.intent(PayPalRequest.INTENT_AUTHORIZE);
        PayPal.requestOneTimePayment(mBraintreeFragment, request);
    }
}

@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }


@Override
   public void onPaymentMethodNonceCreated(PaymentMethodNonce paymentMethodNonce) {
        String nonce = paymentMethodNonce.getNonce();

        if (paymentMethodNonce instanceof PayPalAccountNonce) {
            PayPalAccountNonce payPalAccountNonce = (PayPalAccountNonce)paymentMethodNonce;

            // Access additional information
            String email = payPalAccountNonce.getEmail();
            String firstName = payPalAccountNonce.getFirstName();
            String lastName = payPalAccountNonce.getLastName();
            String phone = payPalAccountNonce.getPhone();

            // See PostalAddress.java for details
            PostalAddress billingAddress = payPalAccountNonce.getBillingAddress();
            PostalAddress shippingAddress = payPalAccountNonce.getShippingAddress();
        }
    }

}
```

**Comment by williamli** [comment]
I am having a similar problem with @dineshlt 

I have a MainActivity in my app and then a PaymentFragment.

Inside the PaymentFragment, I have 

```
mBraintreeFragment = BraintreeFragment.newInstance(getActivity(), clientToken);
```

and the Fragment's PaymentMethodNonceListener is not called since the braintree fragment is attached to the activity instead and there is no way for me to create a BraintreeFragment from within my PaymentFragment.
