### ISSUE TITLE
BraintreeFragment not working on real devices

### ISSUE THREAD

**Issue by Omara8** [braintree/braintree_android#310]
### General information

* SDK/Library version: 3.14.0
* Environment: both environments
* Android Version and Device: Android 10, Note 10 plus and other various devices
* Braintree dependencies:
implementation 'com.braintreepayments.api:braintree:3.14.0'

### Issue description

I have been trying to integrate Braintree with my android app for over a month, after integrating the sandbox and tested it out on emulators and real devices, i moved on to the production envrionment and tested it out on the emulators, it was working fine, but now when i tried to run it on a real device, the Paypal.requestBillingAgreement does not work or open the paypal fragment, this issue was very weird so i did try to convert back to testing and run it again on the real device, and now that has stopped working too, i am at a loss for what the issue is here.

**Comment by sarahkoop** [comment]
Hi @Omara8, thanks for using the Braintree Android SDK. Could you please provide more information on what you are experiencing. Did you get an error message from the `BraintreeErrorListener` callback? 

Alternatively, please confirm that your [browser-switch configuration](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v3#browser-switch-setup) is correct for your production environment.

**Comment by Omara8** [comment]
the Braintree fragment does not open so i am not sure the error listener would even work,
for the browser-switch configuration, i have everything just like the documentation, singleTask launch mode and with application id that does not contain any special characters or an underscore, and the integration is working 100% fine on both sandbox and production while on the emulators, on real devices however it does not

**Comment by sshropshire** [comment]
Hi @Omara8 it may still be beneficial here to check the error listener. The SDK will notify an error if we're unable to redirect to a web browser.

**Comment by Omara8** [comment]
ok i have added the error listener and this is the detailed msg it sent me
"Request for configuration has failed: Unable to resolve host "api.braintreegateway.com": No address associated with hostname. Future requests will retry up to 3 times"

**Comment by sshropshire** [comment]
Ok is it possible the device could be behind some sort of proxy? It seems like a DNS resolution error may be occuring.

**Comment by Omara8** [comment]
happens with multiple devices, totally different networks

**Comment by Omara8** [comment]
but i just tested it out on a secondary ISP and it worked, so i guess this means the other ISP got this blocked somehow, how do i debug or fix this further?

**Comment by sshropshire** [comment]
@Omara8 if possible, I would check to see if the android device is able to successfully complete a DNS lookup on api.braintreegateway.com. We're also looking for more information to see if we can provide additional help.

**Comment by Omara8** [comment]
i did try and switch the default dns on one device to the google dns and it worked fine now, i think this could be a possible solution, but i fear this is not something an end user could ever guess
