### ISSUE TITLE
Invalid `approvalUrl` when calling `PayPal.requestBillingAgreement()`

### ISSUE THREAD

**Issue by brudaswen** [braintree/braintree_android#311]
Not sure if this is a BrainTree or PayPal issue.

### General information

* SDK/Library version: 3.14.0
* Environment: Sandbox
* Android Version and Device: multiple devices
* Braintree dependencies:
  - `com.braintreepayments.api:braintree:3.14.0`

### Issue description

Since yesterday (2020-09-07) a ChromeTab with a URL to `localhost` gets opened in roughly 10 % of the cases when calling `PayPal.requestBillingAgreement(this, PayPalRequest())`.

After a little bit of debugging, I can see the following:
1. Request to `https://api.sandbox.braintreegateway.com:443/merchants/xxxxxxxxxxxxx/client_api/v1/paypal_hermes/setup_billing_agreement` gets send.
2. Response has invalid `approvalUrl`:
```
{"agreementSetup":{"tokenId":"BA-xxxxxxxxxxxxxxxx","approvalUrl":"https://localhost/agreements/approve?nolegacy=1\u0026ba_token=BA-xxxxxxxxxxxxxxxx"}}
```

**Comment by brudaswen** [comment]
Other responses have a correct URL:
```
{"agreementSetup":{"tokenId":"BA-xxxxxxxxxxxxxxxx","approvalUrl":"https://www.sandbox.paypal.com/agreements/approve?nolegacy=1\u0026ba_token=BA-xxxxxxxxxxxxxxxx"}}
```

**Comment by sshropshire** [comment]
Hi @brudaswen thanks for notifying us. The PayPal team is aware of this issue in Sandbox and we're working on a solution.

**Comment by sarahkoop** [comment]
Hi @brudaswen - The PayPal team has implemented a fix for this in Sandbox. Please let us know if you continue to experience this issue.
