### ISSUE TITLE
Your app is using an unsafe implementation of HostnameVerifier. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability.

### ISSUE THREAD

**Issue by DevToDipesh** [braintree/braintree_android#312]
While submitting app in Google play store We got this warning.

Vulnerable classes:

lib.android.paypal.com.magnessdk.network.d$1
lib.android.paypal.com.magnessdk.network.e$1

**Comment by sshropshire** [comment]
Hi @DevToDipesh we're looking into this. Can you provide a link to the Google Help Center article mentioned?

**Comment by DevToDipesh** [comment]
Hi

https://support.google.com/faqs/answer/7188426
![image](https://user-images.githubusercontent.com/38078787/93295001-b39c9900-f809-11ea-9574-b477b10de05a.png)

**Comment by firozansar** [comment]
Hi our app use the Braintree SDK and we have got the similar message from Google.

**Comment by DevToDipesh** [comment]
Hi @sshropshire  Please help us for the same. 
Soon our app is going to be live.

**Comment by balaram3352** [comment]
Even we are getting this error for our apps

**Comment by omkumar87** [comment]
are you guys using the latest versions after 3.7.2?

**Comment by mwseifert** [comment]
We also have this problem now. Going to need a quick update before the holiday code freeze, or we'll need to bail on this package.

**Comment by sshropshire** [comment]
Hi @mwseifert @DevToDipesh @firozansar and @balaram3352, can you confirm that you are using the latest `v3.14.0` version of the BraintreeSDK?

**Comment by ruslan287** [comment]
Have same issue - my version 2.20.0

**Comment by sshropshire** [comment]
Please update to the latest version of v3.14.0 to resolve the issue.

**Comment by ajay9889** [comment]
What about that version which doesn't have AndroidX support?

**Comment by ajay9889** [comment]
Please update how can we resolve this as android x is still under development. We need to launch the mid-project.

**Comment by sshropshire** [comment]
Hi @ajay9889 it's now considered a best practice for Android apps to use [androidx](https://developer.android.com/jetpack/androidx/migrate) libraries. The support libraries are [no longer maintained](https://developer.android.com/topic/libraries/support-library/revisions#28-0-0).
