### ISSUE TITLE
Google play store notice

### ISSUE THREAD

**Issue by keval1040** [braintree/braintree_android#314]
### General information

* SDK/Library version: Braintree drop in 4.6.0
* Environment: Production
* Android Version and Device: Not device Specific
* Braintree dependencies:

implementation 'com.braintreepayments.api:braintree:3.14.0'

implementation 'com.braintreepayments.api:drop-in:4.6.0'

### Issue description
I publish my App in production but get below noticed for play store please resolve ASAP because client is wait for application live

Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.

https://support.google.com/faqs/answer/9450925

Vulnerable classes:

com.cardinalcommerce.shared.cs.utils.a.a

**Comment by scannillo** [comment]
Hi @keval1040 - thanks for opening this issue. This is a known issue we are working on with our MPI Provider. [Please follow this issue](https://github.com/braintree/braintree_android/issues/305) instead, and I will close this one so we can keep everything in one place. Thanks!

**Comment by sshropshire** [comment]
Cardinal provided an update. This should now be fixed in version `3.14.2`.
