### ISSUE TITLE
com.braintreepayments.api:drop-in:5.0.0 missing BrowserSwitchActivity getReturnUri()

### ISSUE THREAD

**Issue by skauss** [braintree/braintree_android#317]
Hi Braintree,
I am an on an update process to use the Android **targetSdkVersion 30**

AndroidStudio found the new library : com.braintreepayments.api:drop-in:5.0.0.
So I try to update from com.braintreepayments.api:drop-in:4.5.0 to 5.0.0.

I implement an Fragment (for PayPalPlus)  which use the getReturnUri() and clearReturnUri() from the **BrowserSwitchActivity** Activity.

This method's are **gone** in library version 5.0.0.
Are there any migration hints ?

Regards
Stephan

**Comment by sshropshire** [comment]
Hi @skauss. While `getReturnUri()` and `clearReturnUri()` methods are public-facing, they should not be needed for a standard integration with our `browser-switch` library. In the future, for issues related to the `drop-in` library, please open an issue in the [drop-in repo](https://github.com/braintree/braintree-android-drop-in) instead.
