### ISSUE TITLE
Is Payment nonce available for bank information?

### ISSUE THREAD

**Issue by williams98** [braintree/braintree_android#318]
### General information

HI i like to know if whether payment nonce is also available for bank information

**Comment by sshropshire** [comment]
Hello @williams98 thank you for using Braintree. Unfortunately, ACH Direct Debit is only available through the JS SDK. Please refer to our [docs site](https://developers.braintreepayments.com/guides/ach/client-side) for more information.

**Comment by sshropshire** [comment]
@williams98 this is actually supported via our [GraphQL API](https://graphql.braintreepayments.com/reference/#Mutation--chargeUsBankAccount). You will have to reach out to our [support team](https://developers.braintreepayments.com/guides/ach/configuration) to get started.
