### ISSUE TITLE
How to do dynamic payment update on change of shipping address in android.

### ISSUE THREAD

**Issue by chiragsharma991** [braintree/braintree_android#319]
As per the g-pay documentation in Braintree, there has only one request functionality which gives a result in "onPaymentMethodNonceCreated" after the transaction like:

GooglePaymentRequest googlePaymentRequest = new GooglePaymentRequest().transactionInfo(TransactionInfo.newBuilder()
                        .setTotalPrice(total)
                        .setTotalPriceStatus(WalletConstants.TOTAL_PRICE_STATUS_FINAL)
                        .setCurrencyCode("USD")
                        .build()
                .billingAddressRequired(true)
                .shippingAddressRequired(true)
                .phoneNumberRequired(true)
                .emailRequired(true)
                .billingAddressFormat(WalletConstants.BILLING_ADDRESS_FORMAT_FULL)
                .environment(com.flowerslib.utils.Constants.WebConstants.isProduction ? "PRODUCTION" : "TEST")
                // Optional in sandbox; if set in sandbox, this value must be a valid production Google Merchant ID
                .googleMerchantId(CheckoutConstant.merchantIdGooglePay);
        GooglePayment.requestPayment(mBraintreeFragment, googlePaymentRequest);

But I need one more callback to set price dynamically on shipping address change but in the document, no one has a callback.
please give your suggestion on how can I achieve this dynamic functionality in android.

**Comment by sshropshire** [comment]
Hi @chiragsharma991 thanks for using the Braintree SDK for Android. The payment method nonce returned in the `onPaymentMethodNonceCreated` callback returns a `GooglePaymentCardNonce` with a `getShippingAddress()` accesor for shipping information.

**Comment by chiragsharma991** [comment]
but I want this getShippingAddress() before the transaction. Is it possible?

**Comment by sshropshire** [comment]
@chiragsharma991 yes, in order to perform a [transaction](https://developers.braintreepayments.com/reference/request/transaction/sale/ruby) you will need to integrate with one of our server SDKs.

**Comment by chiragsharma991** [comment]
can you brief about your point, my condition is like: I am calculating price using the shipping address so I need one callback if any change (shipping-address) is happening in the google pay dialog then I want to calculate again and send it to google play.

**Comment by sshropshire** [comment]
@chiragsharma991 ok I understand. The Braintree server SDK will execute the transaction. Creating a GooglePay nonce will _not_ execute a transaction, so you should still have time to adjust the price.

Take a look at [WalletConstants](https://developers.google.com/android/reference/com/google/android/gms/wallet/WalletConstants.TotalPriceStatus). It seems like `TOTAL_PRICE_STATUS_NOT_CURRENTLY_KNOWN` and `TOTAL_PRICE_STATUS_ESTIMATED` fit your specific use case.

**Comment by chiragsharma991** [comment]
@sshropshire got your point. thanks for your good support. now I am missing one thing
 like totalPriceLabel (tax & shipping-charge)
I added this in my request but i am not getting this label. 
can you give me one hint on how can I add different labels through this request.

i added labels like:

{
  displayItems: [
    {
      label: "Subtotal",
      type: "SUBTOTAL",
      price: "11.00",
    },
    {
      label: "Tax",
      type: "TAX",
      price: "1.00",
    }
  ],
    currencyCode: "USD",
    countryCode: "US",
    totalPriceStatus: "FINAL",
    totalPrice: "12.00",
    totalPriceLabel: "Total",
    checkoutOption: "DEFAULT",

}

but not getting any displayItems or totalPriceLabel on google pay sheet.
