### ISSUE TITLE
Demo using deprecated methods

### ISSUE THREAD

**Issue by CapitanRedBeard** [braintree/braintree_android#32]
CustomFormActivity.java uses Braintree.getInstance which is deprecated. I am having trouble getting my app with a similar setup working and I would like to reference this.

**Comment by lkorth** [comment]
As the [javadoc](https://github.com/braintree/braintree_android/blob/master/BraintreeApi/src/main/java/com/braintreepayments/api/Braintree.java#L129) and [docs](https://developers.braintreepayments.com/android+ruby/guides/client-sdk#initialization) state, you the replacement for `Braintree#getInstance` is `Braintree#setup`. What specifically is not working for you?

**Comment by CapitanRedBeard** [comment]
@lkorth Here is the code I wrote

**Comment by lkorth** [comment]
Sounds like you are never receiving a callback. Have you tried setting a breakpoint and stepping in? There is a working implementation of it, [Drop-in uses it](https://github.com/braintree/braintree_android/blob/master/Drop-In/src/main/java/com/braintreepayments/api/dropin/BraintreePaymentActivity.java#L117) completely. You could also try Drop-in to see if it works for you. The Demo app has been updated to use `Braintree#setup`, it just hasn't been released yet.

**Comment by CapitanRedBeard** [comment]
I am stepping through it and I have no idea what I'm looking for. I really have no idea how the whole thing works, not sure how I'm messing this up. This is also in a fragment if that is known to have issues. What should I be looking for when stepping through the function? Thanks for the help btw

**Comment by lkorth** [comment]
There are no know issues with `Fragments`.

If you get into [`Braintree#setupHelper`](https://github.com/braintree/braintree_android/blob/master/BraintreeApi/src/main/java/com/braintreepayments/api/Braintree.java#L174) it should be pretty clear to follow and see if there are any errors, that method is pretty straight forward.

You may also want to try launching Drop-in instead of calling `Braintree#setup` and see if that works for you. If you can reproduce the issue in a simple new app, I'm happy to take a look at the code.

**Comment by lkorth** [comment]
The Demo app has been updated to use [`Braintree#setup`](https://github.com/braintree/braintree_android/blob/master/Demo/src/main/java/com/braintreepayments/demo/CustomFormActivity.java#L33)

**Comment by lkorth** [comment]
@CapitanRedBeard: looking at it more if the thread it's running on crashes, there will be no callback. One other person has run into this by passing a non-base64 or non-json client token to `Braintree#setup`.

**Comment by lkorth** [comment]
@CapitanRedBeard: version `1.6.2` that was released today includes additional error handling around setup and should call your callback in all cases. Feel free to re-open if it's still an issue.
