### ISSUE TITLE
What is CCInitProvider from cardinal commerce?

### ISSUE THREAD

**Issue by calvarez-ov** [braintree/braintree_android#320]
### General information

* SDK/Library version: org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1
* Environment: Not environment-specific
* Android Version and Device: targetSdkVersion=30
* Braintree dependencies:
```
+--- com.braintreepayments.api:drop-in:5.0.0
     +--- com.braintreepayments.api:braintree:3.14.1 -> 3.14.2
     |    +--- com.braintreepayments.api:google-payment:3.3.1
     |    +--- com.braintreepayments.api:core:3.14.2
     |    |    \--- com.braintreepayments:browser-switch:1.1.3 -> com.libon.android.braintreepayments:browser-switch:1.1.3-1+6503d83
     |    \--- com.paypal.android.sdk:paypal-one-touch:3.14.2
     |         +--- com.braintreepayments.api:core:3.14.2 (*)
     |         \--- com.paypal.android.sdk:data-collector:3.14.2
     +--- com.braintreepayments:card-form:5.0.0
     \--- com.braintreepayments.api:three-d-secure:3.14.1 -> 3.14.2
          \--- org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1
```

### Issue description

Our merged manifest now contains this entry:
```xml
        <provider
            android:name="com.cardinalcommerce.shared.cs.utils.CCInitProvider"
            android:authorities="com.myapp.CCInitProvider"
            android:enabled="true"
            android:exported="false" />
```

If I look at the decompiled sources of this `CCInitProvider` class, it doesn't seem to have any logic. It just overrides the Android framework `ContentProvider` class with empty overrides of some methods.

I don't see anything about this mentioned in the [cardinal commerce sdk release notes](https://cardinaldocs.atlassian.net/wiki/spaces/CMSDK/pages/11862033/Cardinal+Mobile+SDK+-+Android).

**Comment by sshropshire** [comment]
Hey @calvarez-ov it looks like a ContentProvider declared by our third-party MPI provider. The only reason I could see this being used is for cross-app communication between the merchant app and another Cardinal affiliated app (e.g. banking app) for 3DS verification. We can definitely follow up though.

**Comment by sarahkoop** [comment]
Hi @calvarez-ov - We received an update that this class is needed for logging in the Cardinal SDK.
