### ISSUE TITLE
Unsafe implementation of the HostnameVerifier interface - Google policy violation

### ISSUE THREAD

**Issue by marcin-owoc** [braintree/braintree_android#325]
General information
Environment:Production
Android Version and Device: Any device
Issue description:
Got official info from Google developer support team:

**Hostname Verifier**

For example, your app is currently using the following vulnerable implementation of HostnameVerifier:

- Llib/android/paypal/com/magnessdk/network/d$1;
- Llib/android/paypal/com/magnessdk/network/e$1;

To properly handle hostname verification, you'll need to change the verify method in your custom HostnameVerifier interface to return false whenever the hostname of the server does not meet your expectations. You may refer to the Alerts page of your Play Console and this Help Center for additional guidance.

Please make appropriate changes to your app, and be sure to address the issues identified above. In addition to your Production release, if you have other release types that you use for testing and/or quality assurance checks (e.g. Internal test, Closed, Open), please make sure to update those tracks as well.

Kindly note that all active versions of your app must be compliant with our policies including all release types. If there is any violating version code(s) present within the app, it will still be subject to future enforcements.

**Magnes 4.1.2**

@scannillo , @hollabaq86  here's the scoop. We decompiled your code and (we believe) we found the smoking gun.

There are 2 different classes in the lib.android.paypal.com.magnessdk.network that are doing this in their execute(byte[]) method:

**httpsurlconnection.setHostnameVerifier(lib.android.paypal.com.magnessdk.network.e.a());**

And then when you look at what that e.a() method (name obviously obfuscated) is doing:

    public static HostnameVerifier a()
    {
        return HttpsURLConnection.getDefaultHostnameVerifier();
    }
...it's simply passing through what's already set as the default. This effectively accomplishes nothing. The httpsurlconnection.setHostnameVerifier() call could theoretically be commented out with no impact.

Yet, Google "smarts" seem to think this is an insecure implementation. Despite it just passing through the default.

Please remove this useless code ASAP. I believe you can address this much more quickly than Google can update their "smarts" to detect this effectively circular reference.

THANK YOU!!!

**Comment by hollabaq86** [comment]
👋   @marcin-owoc We're checking in with our PayPal colleagues for feedback on this issue. Just to set expectations- with the holidays this week and next, our response time may be a little slower than usual.

**Comment by kolja-ec** [comment]
Same issue here. No publishing to google-play-store possible with this issue.

**Comment by gileze33** [comment]
Same issue. Please let us know when it's fixed ASAP.

**Comment by dcheckoway** [comment]
Happy new year!  Well, it would be happier if we could actually release our Android app!  😛  Any movement on this?

cross posting in https://github.com/braintree/braintree-android-drop-in/issues/208, not sure which place will get more traction quicker

**Comment by Quadriyanney** [comment]
Having issues with this also, haven't been able to push an update in a month now. Any update on this?

**Comment by sshropshire** [comment]
Hello all, we're aware that this is preventing app updates to the Google Play store. We're working with our colleagues at PayPal to get an updated version of the Magnes library for Android. Thank you for your patience.

**Comment by celestesb** [comment]
Is there any ETA on the fix? This is blocking some major releases for us

**Comment by dcheckoway** [comment]
@hollabaq86 @sshropshire Weeks have gone by and this is starting to become unacceptable.  Significant revenue is at stake.  Our C-suite has us evaluating alternatives for payment processing.  I'm sure you're taking this seriously, but I urge to do whatever you can to accelerate the fix before this becomes the reason we go with a different partner.

**Comment by gileze33** [comment]
Echo-ing @dcheckoway - could you please at least provide an update with either a timeline or when you expect to be able to provide a timeline?

**Comment by hollabaq86** [comment]
Hi everyone. Both us and our PayPal colleagues have given this issue the highest priority and are actively working on a resolution this sprint. We want to get this fixed asap, too! As soon as we receive an updated version of the Magnes SDK we can begin updating our SDK, running tests and prepping a release. We'll post updates in this issue when these events happen. Thank you for your patience and understanding.

**Comment by sshropshire** [comment]
The PayPal team has provided a fix and we've released a new `3.15.0` version of `braintree-android` with the update.

**Comment by sshropshire** [comment]
Thanks everyone we appreciate your feedback. We're aware that this issue is still being experienced by some after uploading to the Google Play Store. We're in the process of investigating further. In the meantime, if you've experienced success or failure when uploading to Google Play, please respond to this issue.

**Comment by alpen89** [comment]
Hello, yes, our build got rejected as well.
The message:
"HostnameVerifier
Your app(s) are using an unsafe implementation of the HostnameVerifier interface. You can find more information about how resolve the issue in this Google Help Center article."

We tried
implementation 'com.braintreepayments.api:braintree:3.14.2'
and
implementation 'com.braintreepayments.api:braintree:3.15.0'
and got rejected twice.

**Comment by olivier-inion** [comment]
3.15.0 is working for us... google store made our app available on store ( after removed it suddenly with previous version )

**Comment by marcin-owoc** [comment]
@sshropshire still the same, for now I have no more info from Google Play console:

<img width="1036" alt="Screenshot 2021-01-13 at 00 07 52" src="https://user-images.githubusercontent.com/1240364/104453965-7f619b00-55a5-11eb-8d42-8cc6c64b94af.png">

**Comment by Quadriyanney** [comment]
> 3.15.0 is working for us... google store made our app available on store ( after removed it suddenly with previous version )

3.15.0 works for us too 👍🏾

**Comment by marcin-owoc** [comment]
OK, we are finally live.
Make sure you make release 100% ( full rollout ) and you update all tracks, including open, closed and internal tracks.
Vulnerability cannot be included on any of them.
