### ISSUE TITLE
Disabled payment mode still shows in recent

### ISSUE THREAD

**Issue by RocKer004** [braintree/braintree_android#328]
Hi there, disabled payment option is still available in Recents section, any solutions to this ?

**Comment by sarahkoop** [comment]
Hi @RocKer004, thanks for using the Braintree Android SDK. More information would be helpful for addressing this issue. Could you please fill out the issue template provided in this repository so that we can better understand the request?

**Comment by RocKer004** [comment]
Hi @sarahkoop , thanks for the fast reply. I think this screenshot displays everything in the best way. So the only payment method available in this case is paypal, but credit card payments are also available through "recents" section if the user has saved them previously. 
![image](https://user-images.githubusercontent.com/37250288/106530991-d6a0be80-6506-11eb-83ca-75414af51711.png)

**Comment by sarahkoop** [comment]
Thanks for the additional screenshot. It looks like you are using the [Braintree Android Drop In](https://github.com/braintree/braintree-android-drop-in) SDK, where this issue should be resolved in version [`5.0.2` or later.](https://github.com/braintree/braintree-android-drop-in/releases) Please try upgrading to the most recent version of Drop In, which is `5.1.0`.

**Comment by RocKer004** [comment]
I did that and it helped, thanks a lot Sarah 🤍
