### ISSUE TITLE
Amount not showing on transaction screen

### ISSUE THREAD

**Issue by Slake07** [braintree/braintree_android#329]
### General information

* SDK/Library version: 3.16.0
* Environment: Sandbox
* Android Version and Device: Samsung M20 with Android 10 and with emulator also
* Braintree dependencies:
implementation 'com.braintreepayments.api:braintree:3.16.0'

### Issue description

I can't see the amount of my product at the time of the transaction screen.
![device-2021-02-16-154737](https://user-images.githubusercontent.com/3199539/108050117-3357b980-706f-11eb-90d6-06bb86226cb0.png)

**Comment by crookedneighbor** [comment]
Can you share your client side code for initializing PayPal? I suspect you're using the vault flow instead of the checkout flow, which wouldn't show an amount in the confirmation screen.

**Comment by Slake07** [comment]
@crookedneighbor I am using following way:

SDK Version: implementation 'com.braintreepayments.api:braintree:3.16.0'

```
try {
            mBraintreeFragment = BraintreeFragment.newInstance(this, "sandbox_*****************");
            mBraintreeFragment.addListener(this);
        }catch (InvalidArgumentException e){}

private void makePaymentFromBraintree(){
        PayPal.requestOneTimePayment(mBraintreeFragment, getPaypalRequest());
    }

    private PayPalRequest getPaypalRequest(){
        String subtotal = String.valueOf(subTotalFromService);
        String tax = Utilities.getRoundedTwoDigitValue(vat);
        String total = Utilities.getRoundedTwoDigitValue(new BigDecimal("0").add(new BigDecimal(subtotal).add(new BigDecimal(tax))).floatValue());

        PayPalRequest request = new PayPalRequest(total);
        request.currencyCode(Constants.EURO_CURRENCY);
        request.displayName(Constants.PAYPAL_ORDER_NAME);
        request.intent(PayPalRequest.INTENT_AUTHORIZE);

        return request;
    }
```

Is it vault flow? If yes then can you help me with checkout flow? Because from Braintree site I find only two flow. one is drop-in flow and 2nd above one.

**Comment by sarahkoop** [comment]
Hi @Slake07 - You should see the amount if you set the `userAction` on the request to `USER_ACTION_COMMIT`. Closing this - but please re-open if you continue to experience the issue.
