### ISSUE TITLE
I'm getting these libpng warnings....

### ISSUE THREAD

**Issue by sirvon** [braintree/braintree_android#33]
It's slowing down my builds slightly, these warnings are everywhere from this invaluable
library....

```java
app/build/intermediates/exploded-aar/com.braintreepayments/card-form/1.4.0/res/
drawable-mdpi-v4/bt_diners.png: libpng warning: iCCP: Not recognizing known sRGB
 profile that has been edited
```

here's a solution to rid the library of them....
clear up all images in a directory (must fix path):
```bash
for i in $(find / -type f -name "*.png")
do
convert $i -strip $i
done
```

or 

```bash
To just remove the image profile sRGB use the following command:

mogrify +profile sRGB <png file>

or as batch command:

find <path to res folder> -name *.png -exec mogrify +profile sRGB {}  \;

```

**Comment by lkorth** [comment]
Please see issue #16. All of the pngs have been stripped in this library, however a new version of https://github.com/braintree/android-card-form has not been released with stripped pngs.
