### ISSUE TITLE
LOOKUP_ERROR in 3D secure flow

### ISSUE THREAD

**Issue by auxDK** [braintree/braintree_android#339]
### General information

* SDK/Library version: 
* Environment: Sandbox
* Android Version and Device: Google Pixel with Android 11 
* Braintree dependencies:
 - com.braintreepayments.api:braintree:3.17.0
 - com.braintreepayments.api:three-d-secure:3.17.0

Test card used:
https://developers.braintreepayments.com/guides/3d-secure/testing-go-live/php
"Successful Challenge Authentication"
Visa

- 4000000000001091
- 01/20**
- CVC: 123

### Issue description
Right after nonce was received from the server the ThreeDSecure.performThreeDSecureLookup  return null in acsUrl

**Comment by hollabaq86** [comment]
👋 @auxDK please [contact Support](https://help.braintreepayments.com/), they'll assist in troubleshooting your 3DS workflow with the test card.
