### ISSUE TITLE
Dx trouble writing output: already prepared... - Error in console

### ISSUE THREAD

**Issue by vedtam** [braintree/braintree_android#35]
Hi,

- braintree-api-1.6.1-full.jar
- android:minSdkVersion="14"
- android:targetSdkVersion="18" 

I need to implement braintree inside my android app which has no issues, but as I copy the braintree jar file, into my projects libs folder and import the necessary classes, my app crashes.

Full error message in console:

```
Dx trouble writing output: already prepared
[2015-06-18 15:31:42 - Dex Loader] Unable to execute dex: Multiple dex files define Landroid/support/annotation/AnimRes;
[2015-06-18 15:31:42 - foto.studio] Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Landroid/support/annotation/AnimRes;
```

I have removed, re imported everything twice, updated Eclipse packages too the latest version, and cleaned my project. But still got this issue. As I remove the braintree library my app returns to normal.

Please advice me what to do.
Thanks!

**Comment by punit006** [comment]
I am facing the same issue. I tried everything but of no use.

**Comment by punit006** [comment]
I am facing the same issue. I tried everything but of no use. And there is no proper documentation of how to integrate the Braintree library in android for developers using eclipse.

**Comment by vedtam** [comment]
I am googling for about 4 hours, but there is nothing related to this. Are you trying to set up the SDK manually like me?

**Comment by lkorth** [comment]
This is only an issue in 1.6.1 and 1.6.0 with the full jar. A new optional dependency was added in these versions and the full jar picks it up and compiles it in. For now you can use 1.5.1 and we will look into no compiling Google Play Services into the full jar.

**Comment by vedtam** [comment]
Hi,

Thanks, I try with this version, could you please tell me where could I find it? On gitHub I see only the latest version.

Regrads,
E.

**Comment by lkorth** [comment]
They're all on [maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.braintreepayments.api%22%20AND%20a%3A%22braintree-api%22)

**Comment by vedtam** [comment]
Hi,

Thanks, now my app compiles and runs ok! 

Regards!
E.

**Comment by rambabupittala** [comment]
can any body post the code for android eclipse to integrate brainree payment ,i tried with website code but it is not working,please help me

**Comment by vedtam** [comment]
You have to move your project to Android Studio, everything is much simpler in it like integrating Braintree or any other library using gradle.

**Comment by lkorth** [comment]
@rambabupittala if you start at the [manual download](https://developers.braintreepayments.com/android+ruby/guides/client-sdk#manually) documentation and follow them from there down it should be very straight forward how to add the library and integrate with it.

**Comment by rambabugithub** [comment]
Hi Mr.vedtam and Mr.Ikorth thanks for reply , i followed the manual download steps but i struck  at convert to maven project   in pom.xml i get this error ---->"No versions available for com.braintreepayments.api.myprojectname:aar:[1.0,)",  i followed steps from this url
http://stackoverflow.com/questions/8620127/maven-in-eclipse-step-by-step-installation 
but it contain this plug  "http://download.eclipse.org/technology/m2e/releases"  but in braintree website they mention must to use android-maven-plugin >= 3.9.0-rc2 this plug in ,i didn't get this plug in google ,cloud you help me to find the this plug in android-maven-plugin >= 3.9.0-rc2  and pom.xml error 

please help me.

sorry for my bad english.

**Comment by rambabugithub** [comment]
Hi 
thanks for reply ,i followed manually setup steps, but i struck at the Drop-in UI using Maven. i didn't getting to use drop-in using Maven ,cloud you help me to use Maven for drop in.

i followed this url :"http://stackoverflow.com/questions/8620127/maven-in-eclipse-step-by-step-installation"

**Comment by lkorth** [comment]
The manual setup setups are only required if you are not using Maven. If you are using Maven there is no need to download the jar, you should just include the dependency in your `pom.xml`.

As far as how to use Maven with Eclipse, that's not something we can support.
