### ISSUE TITLE
GooglePayment isReadyToPay return false

### ISSUE THREAD

**Issue by MikaelZero** [braintree/braintree_android#357]
classpath "com.android.tools.build:gradle:4.1.3"

implementation 'com.braintreepayments.api:drop-in:4.6.0'
    implementation 'com.braintreepayments.api:braintree:3.17.2'
    implementation 'com.braintreepayments.api:google-payment:3.5.0'
    // Google dependencies
    implementation 'com.google.android.gms:play-services-wallet:18.1.2'

compileSdkVersion 30

debug to listener.onResponse(task.getResult(ApiException.class));   

task.getResult(ApiException.class) return false

**Comment by sshropshire** [comment]
@MikaelZero thanks for using the Braintree SDK for Android. Please re-open this issue using the issue template we have provided. Closing this for now.
