### ISSUE TITLE
GooglePayment isReadyToPay return false

### ISSUE THREAD

**Issue by MikaelZero** [braintree/braintree_android#359]
### General information

* SDK/Library version:4.6.0
* Environment: Sandbox
* Android Version and Device: Android 10.0
* Braintree dependencies:
implementation 'com.braintreepayments.api:drop-in:4.6.0'
implementation 'com.braintreepayments.api:braintree:3.17.2'
implementation 'com.braintreepayments.api:google-payment:3.5.0'
// Google dependencies
implementation 'com.google.android.gms:play-services-wallet:18.1.2'

### Issue description
GooglePayment isReadyToPay return false

task.getResult(ApiException.class) return false

**Comment by sarahkoop** [comment]
Hi @MikaelZero thanks for using the Braintree Android SDK. Please [contact Support](https://help.braintreepayments.com/) with your merchant ID, they'll assist in troubleshooting your Google Pay payment flow.

**Comment by yarodevuci** [comment]
@mikaelzero were u able to resolve this? I am having same issue. Contacting support is not helpful.

**Comment by sshropshire** [comment]
Hi @yarodevuci can you try updating to the latest versions of our [Core](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4261) and [DropIn SDKs](https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#681)? If it still doesn't work as expected, please create a new issue [here](https://github.com/braintree/braintree_android/issues/new?assignees=&labels=&template=bug_report.yml) and we'll take a look.
