### ISSUE TITLE
Android change default payment option.

### ISSUE THREAD

**Issue by muraliandroid** [braintree/braintree_android#36]
I have added two credit cards in Braintree and want to change my first card as default payment. 
How can I change my first card as default payment card?

I see the document for change payment method but I do not see update method under PaymentMethod and PaymentMethodOptions class under BraintreeApi library.

```ruby
result = Braintree::PaymentMethod.update(
  "the_token",
  :options => {
    :make_default => true
  }
)
```

I have download all necessary libraries BraintreeApi,BraintreeData,DropIn and demo library.

Please help me where will I get these methods and how to change default payment.

**Comment by lkorth** [comment]
This repo contains the Braintree Android SDK which handles tokenizing payment methods from users. The method you are referring to is only available in our server SDKs.

The example you provided is a Ruby code snippet from [our docs](https://developers.braintreepayments.com/android+ruby/guides/payment-methods#update). Once you have a payment method nonce, you can send it to your server and use the Braintree server SDKs to make the `Braintree::PaymentMethod.update`.
