### ISSUE TITLE
Hostnameverfier

### ISSUE THREAD

**Issue by bankiprudhvi** [braintree/braintree_android#361]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device: 
* Braintree dependencies:

**Comment by bankiprudhvi** [comment]
How to resolve this issue please guide me
i used  implementation 'com.braintreepayments.api:braintree:3.7.0'

**Comment by sarahkoop** [comment]
Hi @bankiprudhvi - thanks for using the Braintree Android SDK. This issue was fixed in version [3.15.0](https://github.com/braintree/braintree_android/releases/tag/3.15.0). We recommend upgrading to `3.17.2` for the latest version 3 updates.
