### ISSUE TITLE
Selecting shipping options [Google Pay]

### ISSUE THREAD

**Issue by GFean** [braintree/braintree_android#363]
Hi there, I'm trying to implement google pay using braintree. But I have a specific case, I need to pass shipping options to the request. I found the implementation for javascript SDK, however I was not able to find the alternative for android SDK to let user to choose shipping option through the wizzard. Any help please ?

**Comment by sestevens** [comment]
Hi @GFean, it looks like [`shippingOptionParameters`](https://developers.google.com/pay/api/web/reference/request-objects#ShippingOptionParameters) exists in Google Pay's web API, but I'm not seeing an equivalent in the Google Pay [Android docs](https://developers.google.com/pay/api/android/reference/request-objects#PaymentDataRequest). Unless I'm missing something, it doesn't look like this option exists.

**Comment by GFean** [comment]
Hmm, Okay , so it can't be a case.. I've messaged Google Pay support, but no answer so far.. Apple Pay supports shipping options and even adding a listener to update the details when the shipping option changes. It's a bit strange that google doesn't have something similar tbh.
Thanks for your answer anyways, appreciated ! 
I'm closing the issue.
