### ISSUE TITLE
Move Cardinal Commerce out of Bintray

### ISSUE THREAD

**Issue by francescocervone** [braintree/braintree_android#369]
### Issue description

Since [JCenter is shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), Cardinal Commerce should move their packages out of Bintray.

**Comment by snitsaruk** [comment]
This is a critical issue because it fails out pipelines.
We just started using Braintree SDKs but it looks like they bring more problems than benefits.
We will move to Adyen as soon as possible.

**Comment by snitsaruk** [comment]
Hello, @braintreeps. Any plans on this?
JCenter will be completely out of service on May 1st, 2021.
This requires immediate action.

**Comment by mspasov** [comment]
Yesterday JCenter was in brownout period. More than 60 builds failed and ton of cpu time wasted. Had to carve-out Braintree integration for android.

And here is the official notice from Cardinalcommerce.. in a [marketing PDF](https://cardinaldocs.atlassian.net/wiki/spaces/CMSDK/pages/2321842182/NOTICE+Cardinal+Mobile+SDK+distribution+transition+to+Artifactory). I'm speechless.

**Comment by snitsaruk** [comment]
Our pipelines were failing because of this issue and we wasted hours because of this issue.
The reaction of the Braintree team: silence.
That is a good moment to consider other payment solutions.

**Comment by sarahkoop** [comment]
It appears that Bintray status is back to operational. We are aware of the upcoming sunset of Bintray and are awaiting updated credentials from the third-party provider. We will provide an update when we have additional information.

**Comment by mspasov** [comment]
Well.. Good news everybody:

> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

**Comment by sarahkoop** [comment]
Closing this for now. Please use #373 for additional comments.
