### ISSUE TITLE
How to change mock data mode to sand bax in Android?

### ISSUE THREAD

**Issue by muraliandroid** [braintree/braintree_android#37]
I am using Braintree Android client sdk. how can I change Mock data mode to sand box mode.
I am getting client taken from my server. how to get sand box mode  with the client token? please give me code sample. Please see the images that shows I am using mock data.

![device-2015-06-25-230800](https://cloud.githubusercontent.com/assets/4084464/8361253/a41068ce-1b8f-11e5-876c-001f9950ad19.png)

**Comment by lkorth** [comment]
It is not possible to use PayPal in sandbox mode through the Braintree SDK.

**Comment by mickeyreiss** [comment]
To give a little bit more background: Braintree does not currently provide an environment that is linked is to PayPal's sandbox.

Our environment interaction breaks down like this:

| Braintree Environment | PayPal Environment |
| ---- | --- | 
| Production | Live (aka Production) |
| Sandbox | Mock |
| -- | Sandbox | 

We recommend doing development in Sandbox and then performing your final end to end tests against production before shipping apps to real users.

**Comment by gbramwell** [comment]
@muraliandroid If you have more questions with your integration, our support folks would love to help! support@getbraintree.com / 877.434.2894

**Comment by sujithsj** [comment]
private static final String CONFIG_ENVIRONMENT = PayPalConfiguration.ENVIRONMENT_SANDBOX;
by using this line you change the environment mode from mockdata to sandbox

**Comment by lkorth** [comment]
Correct, however it is not possible to supply that constant to the PayPal SDK without some changes to `braintree_android`.
