### ISSUE TITLE
Customized UI with credit card option and PCI compliance

### ISSUE THREAD

**Issue by anilsisodiya** [braintree/braintree_android#38]
Our requirement is that we need to take credit  card information from the user in our designed UI and then we have to do payment transaction using these credit card details. We also need to store previously used card details, so that user can use it for future transaction. We also  want to provide user facility of adding new card or replacing existing cards.
Could you please let us know how we can fulfill above requirements using braintree. Also what will be impact of solution on PCI compliance. do we need go for PCI compliance?

**Comment by lkorth** [comment]
@anilsisodiya we like to keep issues specific to the SDK. To help answer your questions around what features Braintree provides and how to work with PCI compliance, please contact our support team. They would love to help! support@getbraintree.com / 877.434.2894
