### ISSUE TITLE
Error: java.security.cert.CertPathValidatorException

### ISSUE THREAD

**Issue by anilsisodiya** [braintree/braintree_android#39]
When I try to run demo app I got error dialog "Unable to get a client token. Error:java.security.cert.CertPathValidatorException: Trust actor for certification path not found."

**Comment by lkorth** [comment]
What device or emulator are you running it on? I haven't seen this error across a wide variety or emulators or devices.

Chrome validates the cert:

![screenshot 2015-07-10 10 02 02](https://cloud.githubusercontent.com/assets/1163999/8620017/c9fcbbe4-26ea-11e5-87e7-3ac195783f14.png)

**Comment by anilsisodiya** [comment]
I am running app on samsung galaxy s5 (OS 4.2.2). The same app working fine on nexus 9 (OS 5.0).

**Comment by lkorth** [comment]
Does it still happen if you remove the Demo app from the device and reinstall it?

**Comment by lkorth** [comment]
Closing old issue. Please feel free to comment if you are still having this issue.
