### ISSUE TITLE
Request failed : "This merchant is not enabled for google pay"

### ISSUE THREAD

**Issue by Sumit2668** [braintree/braintree_android#392]
### General information

* SDK/Library version: 5.2.0.1
* Environment: Production
* Android Version and Device: K20 Pro Android 10
* Braintree dependencies:

 - com.braintreepayments.api:braintree:5.4.0 
  - compile 'com.braintreepayments.api:data-collector:2.10.0'   
  - com.braintreepayments.api:drop-in:5.2.0.1  

### Issue description

Hi I am using the Braintree drop-in UI and I am using Google Pay and it is working fine in the SANDBOX account but I switch to the PRODUCTION account I am getting errors like the below Screen, How can I fix it.

Please reply as soon as possible.
[
![WhatsApp Image 2021-05-24 at 10 57 14 PM](https://user-images.githubusercontent.com/26775231/119443967-1a366700-bd48-11eb-8421-995cacea3847.jpeg)
](url)

Thanks

**Comment by sarahkoop** [comment]
Hi @Sumit2668 thanks for using the Braintree Android SDK. Please [contact Support](https://help.braintreepayments.com/) with your merchant ID, they'll assist in troubleshooting your Google Pay production configuration.
