### ISSUE TITLE
Version 4.1.0 not available on Maven Central

### ISSUE THREAD

**Issue by fondesa** [braintree/braintree_android#406]
The version 4.1.0 of `com.braintreepayments.api:braintree` is not available on Maven Central (https://repo1.maven.org/maven2/com/braintreepayments/api/braintree/). 

Instead, the other Braintree dependencies with the version 4.1.0 are already on Maven Central (e.g. https://repo1.maven.org/maven2/com/braintreepayments/api/data-collector/).

Are they maybe on some other repository?

**Comment by sshropshire** [comment]
Hi @fondesa thank you for using the Braintree SDK for Android. We've re-structure the modules in `v4` by feature. See the migration guide [here](https://github.com/braintree/braintree_android/blob/master/v4_MIGRATION_GUIDE.md) to learn more.
