### ISSUE TITLE
Pay Pal Drop In not Working in Android 11

### ISSUE THREAD

**Issue by khalil05400** [braintree/braintree_android#412]
I have integrated Braintree into my android application. I am using drop-in UI. But when I click on the "Checkout With PayPal" Button the BrainTreePayment Activity finishes and onActivityResult is called with resultCode being 0. It does not return any error. It does not open the PayPal application or browser.

Note: This issue is happening in only Android 11

Please help me resolve this issue.

**Comment by sshropshire** [comment]
@khalil05400 please use the issue template when creating a GH issue. This helps us to diagnose incoming issues more effectively. Closing this for now.

**Comment by khalil05400** [comment]
I'm unable to get any exception or any data, it does not show anything when I click on PayPal
