### ISSUE TITLE
Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.3-2 due to 403

### ISSUE THREAD

**Issue by guozchen-sh** [braintree/braintree_android#414]
### General information

* SDK/Library version: 3.14.0
* Environment: skipped since this is a build issue
* Android Version and Device: skipped since this is a build issue
* Braintree dependencies:
  - com.braintreepayments.api:braintree:3.14.0
  - com.braintreepayments.api:data-collector:3.14.0
  - com.braintreepayments.api:three-d-secure:3.14.0

### Issue description
**Gralde complains that it cannot resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.3-2**
```
> Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.3-2.
     Required by:
         project :app > project :ModuleX > com.braintreepayments.api:three-d-secure:3.14.0
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.3-2.
         > Could not get resource 'http://dl.bintray.com/apollographql/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.3-2/cardinalmobilesdk-2.2.3-2.pom'.
            > Could not HEAD 'http://dl.bintray.com/apollographql/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.3-2/cardinalmobilesdk-2.2.3-2.pom'. Received status code 403 from server: Forbidden
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.3-2.
         > Could not get resource 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.3-2/cardinalmobilesdk-2.2.3-2.pom'.
            > Could not HEAD 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.3-2/cardinalmobilesdk-2.2.3-2.pom'. Received status code 403 from server: Forbidden
```

We have followed the instructions in commit 79b894f06be06a5388e3d470f3f9d5052165ecdc to set up gradle script.
Here is the config in top level `build.gralde.kts` we are using to download the dependency - It had been working until today. But failed today.
```
subprojects {
    repositories {
        jcenter().apply {
            url = URI.create("http://dl.bintray.com/apollographql/android")
        }

        maven {
            url = uri("https://cardinalcommerce.bintray.com/android")
            credentials {
                username = "braintree-team-sdk@cardinalcommerce"
                password = "220cc9476025679c4e5c843666c27d97cfb0f951"
            }
        }
        …
    }
}
```

**Comment by sarahkoop** [comment]
Hi @guozchen-sh, thanks for using the Braintree Android SDK. Since Bintray has been sunset, the credentials for accessing the Cardinal Mobile SDK have changed. Please refer to [this issue](https://github.com/braintree/braintree_android/issues/373) for the updated credentials.

**Comment by guozchen-sh** [comment]
It worked like a charm.
Thanks a lot @sarahkoop
