### ISSUE TITLE
Missing public getters on Braintree models

### ISSUE THREAD

**Issue by fondesa** [braintree/braintree_android#415]
### General information

* SDK/Library version:  4.2.0
* Braintree dependencies:
```
- "com.braintreepayments.api:three-d-secure:4.2.0"
- "com.braintreepayments.api:american-express:4.2.0"
- "com.braintreepayments.api:card:4.2.0"
- "com.braintreepayments.api:google-pay:4.2.0"
- "com.braintreepayments.api:paypal:4.2.0"
```
### Issue description

Updating to the version **4.x**, we noticed that some Braintree models do not expose publicly the getters of their properties. Instead, they are package-protected (e.g. getters in `ThreeDSecureResult` and `Configuration`).

Some of those properties were exposed in the version **3.x** and we actually used them. 
Can they be exposed again?

**Comment by sshropshire** [comment]
Hi @fondesa which specific properties are you asking to be made public? Once we can gather a list of use cases for this set of properties we may be able to make some changes to the access protection levels in the SDK.

**Comment by fondesa** [comment]
Hi @sshropshire. At the moment we were using [`Configuration.getSupportedCardTypes()`](
https://github.com/braintree/braintree_android/blob/4e774e0d761be7276365c2a48894b084f2ae3cfb/BraintreeCore/src/main/java/com/braintreepayments/api/Configuration.java#L491) and [`ThreeDSecureResult.getLookup()`](https://github.com/braintree/braintree_android/blob/4e774e0d761be7276365c2a48894b084f2ae3cfb/ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureResult.java#L84).

Unfortunately we haven't finished the update to the version **4.x** yet, since we are blocked by the drop-in SDK (https://github.com/braintree/braintree-android-drop-in/issues/250), so I have not a complete list of which other APIs we would need.

**Comment by sshropshire** [comment]
@fondesa Sounds good. We may revert these back to `public` in our upcoming release. If there are any more feel free to request access to these properties via GitHub issues as well.

**Comment by sshropshire** [comment]
Hi @fondesa we made those properties public again in [4.3.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#430). Please feel free to open another GH issue for additional property requests.
