### ISSUE TITLE
Adding Braintree to package is throwing Error while building

### ISSUE THREAD

**Issue by neolivz** [braintree/braintree_android#417]
I added 
```
	implementation 'com.braintreepayments.api:data-collector:4.+'
	implementation 'com.braintreepayments.api:venmo:4.+'
```

The build straight away started failing

[com.braintreepayments.api:braintree-core:4.2.0] /Users/neolivz/.gradle/caches/transforms-2/files-2.1/f235b510aa671f7d0ccd7d0ee219037c/jetified-braintree-core-4.2.0/AndroidManifest.xml:17:9-45 Error:
        Missing 'package' key attribute on element package at [com.braintreepayments.api:braintree-core:4.2.0] AndroidManifest.xml:17:9-45
[com.braintreepayments.api:braintree-core:4.2.0] /Users/neolivz/.gradle/caches/transforms-2/files-2.1/f235b510aa671f7d0ccd7d0ee219037c/jetified-braintree-core-4.2.0/AndroidManifest.xml:18:9-64 Error:
        Missing 'package' key attribute on element package at [com.braintreepayments.api:braintree-core:4.2.0] AndroidManifest.xml:18:9-64
[com.braintreepayments.api:braintree-core:4.2.0] /Users/neolivz/.gradle/caches/transforms-2/files-2.1/f235b510aa671f7d0ccd7d0ee219037c/jetified-braintree-core-4.2.0/AndroidManifest.xml Error:
        Validation failed, exiting

**Comment by neolivz** [comment]
I was running an older version of Gradle (3.5.3) and needed 3.6.0 for it to work

**Comment by anutting** [comment]
I'm seeing this error as well. Using Gradle 6.3
