### ISSUE TITLE
Deprecation of Apache HTTP

### ISSUE THREAD

**Issue by gpolak** [braintree/braintree_android#43]
Hello,

Any plans on removing Apache HTTP from ThreeDSecureWebViewActivity.java now that it has been [deprecated in Android M](https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client)?

**Comment by lkorth** [comment]
@gpolak: Use of Apache was removed [in this commit](https://github.com/braintree/braintree_android/commit/da8014d3d0a9ca0712455d88b50acf112642978f) and will go out in the next release.
