### ISSUE TITLE
Samsung Pay not support american express card

### ISSUE THREAD

**Issue by Jake-Jiang** [braintree/braintree_android#430]
The same mobile phone, SDK 3.17.2 supports Samsung Pay. When I upgraded to SDK 4.4.1, Samsung Pay was not supported. I debugged your SDK code and found "american_express" in the SamsungPayMapAcceptedCardBrands class not match " American Express" the configuration file returned. Please see the screenshot below.
![39635B66-C8DE-48f3-9954-2CE07E37CE31](https://user-images.githubusercontent.com/58160182/129658195-dd625c00-b7be-4029-ae22-f7545aefcd71.png)

**Comment by sshropshire** [comment]
@Jake-Jiang thanks for reporting this. We'll have a fix up soon.

**Comment by sshropshire** [comment]
Hi @Jake-Jiang thanks for your patience. We've released a fix for this in [version 4.5.0](https://github.com/braintree/braintree_android/releases/tag/4.5.0).
