### ISSUE TITLE
Unresolved reference: BraintreeClient

### ISSUE THREAD

**Issue by EmDee** [braintree/braintree_android#437]
### General information

* SDK/Library version: 4.4.1
* Braintree dependencies:
  - `com.braintreepayments.api:data-collector:4.+`

### Issue description

I'm trying to collect device data as described in the [docs](https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/device-data-collection) to pass the correlation ID to PayPal. However, when trying to integrate the SDK the `BraintreeClient` dependency can't be found.

As stated above the only dependency I'm integrating is `com.braintreepayments.api:data-collector:4.+`.

The code snippet used seems straight-forward as well:

```kotlin
val braintreeClient = BraintreeClient(context, "$TOKEN")
val dataCollector = DataCollector(braintreeClient)
dataCollector.collectDeviceData(context) { deviceData, error ->
    print(deviceData)
}
```

Am I doing something fundamentally wrong here or missing a dependency?

**Comment by sshropshire** [comment]
HI @EmDee thanks for using the Braintree SDK for Android. You would also have to include `com.braintreepayments.api:braintree-core:4.+` in this case. We may improve this in the future by marking this dependency as `api` instead of `implementation` in our own `build.gradle` file.

**Comment by EmDee** [comment]
@sshropshire Thanks for the quick help! I knew that I had to integrate the `Core` dependency as well, but couldn't find any documentation whatsoever regarding the namespace.

I think it would already greatly help, if you'd include those dependencies in the documentation, e.g. in https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/device-data-collection

**Comment by sshropshire** [comment]
@EmDee thanks for the feedback it was a bit of an oversight. Usually `BraintreeCore` is available on the classpath when using other feature modules. We hadn't considered this particular use case in the past.

**Comment by venkatasaisankar12** [comment]
Hi, We are using braintree data-collecter version 3.15.0 
 
by using this version we are getting device data using below code
 
 ```
override fun getDeviceData(activity: AppCompatActivity, config: String): Result<String> {
        val braintreeFragment = BraintreeFragment.newInstance(activity, config)

        val deviceDataBox = ArrayBlockingQueue<Result<String>>(1)

        DataCollector.collectDeviceData(braintreeFragment) { deviceData ->
            deviceDataBox.put(Result.Valid(deviceData))
        }
        return deviceDataBox.take()
    }
```

Now we upgrading data-collecter version to 4.31.0 

After upgrading it is not working throwing error like this 
- Cannot infer a type for this parameter. Please specify it explicitly.
```
DataCollector.collectDeviceData(braintreeFragment) { deviceData ->
            deviceDataBox.put(Result.Valid(deviceData))
        }
```

Can anyone help on this?
