### ISSUE TITLE
Drop-in form fields get focus but view scrolls to card number

### ISSUE THREAD

**Issue by sdmurphy** [braintree/braintree_android#44]
Video of issue <https://youtu.be/wf8NPakomkQ>

After entering the last character of a form field, input focus moves to the next field and is visible momentarily. See line 112 in [ErrorEditText class](https://github.com/braintree/android-card-form/blob/e5667ef213cb4db9aa20bce202349bda1b6286b8/CardForm/src/main/java/com/braintreepayments/cardform/view/ErrorEditText.java#L112). Then the view scrolls to the first field (Card Number), but input focus remains with the correct field. Also if you click in any field it scrolls to the first field. See line 141 in [AddPaymentMethodViewController class](https://github.com/braintree/braintree_android/blob/da8014d3d0a9ca0712455d88b50acf112642978f/Drop-In/src/main/java/com/braintreepayments/api/dropin/AddPaymentMethodViewController.java#L141). It appears to me that field.getTop() always returns 0 and causes the ScrollView to go to the first item.

**Comment by quinnjn** [comment]
Good find, we'll check it out.

**Comment by sdmurphy** [comment]
Thanks, I started working on a custom UI because of this, but then I realized it would take me a lot less time to discover the cause of this problem. 

But with that said, I spent awhile trying to fix the problem without much success. I believe the intention behind the code on line 141 is to make the fields snap into place if you navigate back to them. I don't have a lot of experience with ScrollViews. The best I was able to do was comment out line 141, which at least makes the drop-in useable.

**Comment by sdmurphy** [comment]
Can someone please confirm that this is a bug and I am not doing something wrong? And possibly recommend a version of code that doesn't have the problem. I looked through the commits and couldn't find when the problem first occurred.

I am very close to releasing an app (using braintree drop-in) and I can't release it with this problem. It seems like a major issue to me. I conducted my normal usability test (asked my wife to try my app) and sure enough she got stuck on payment (drop-in ui). I would hate to lose a sale because of this issue.

**Comment by sdcoffey** [comment]
Hey @sdmurphy, we currently don't have a timeline for this specific bug. I would reccomend, if it's really something that's important to you, "hardening" the version of Braintree you're importing in your `build.gradle`, such that you're targeting a specific version, and make the change yourself. If you'd like, you can clone our public repo and send us a pull request.

**Comment by sdmurphy** [comment]
@sdcoffey thank you. I will do as you suggested. My workaround (commenting out the scrollTo line) isn't perfect, but if/when I get the time to fix it properly I will create a pull request.

FYI...I believe the problem is being caused by nested views.

**Comment by quinnjn** [comment]
Should be resolved! If you're still spotting issues with this @sdmurphy let us know by re-opening this issue.
