### ISSUE TITLE
Drop-in Secondary description should allow >1 lines.

### ISSUE THREAD

**Issue by nirinchev** [braintree/braintree_android#45]
We have a case where we want to put a multiline secondary description. Is there any reason to limit it to 1 line? On iOS it works as expected, so I would assume it's a copy-paste bug on Android.

**Comment by sdcoffey** [comment]
Hey @nirinchev, thanks for letting us know. Just to clarify, you're referring to the drop-in activity, at the top where we show the cart? Eg: 

<img width="762" alt="screen shot 2015-09-08 at 9 32 16 am" src="https://cloud.githubusercontent.com/assets/3506415/9741624/3c3d5002-5610-11e5-8110-715a9129dd8a.png">

**Comment by nirinchev** [comment]
Yes, exactly. The text that says 1 Item is limited to one line, while multiple lines should be ok. Looking at the code, it would seem that https://github.com/braintree/braintree_android/blob/master/Drop-In/src/main/res/layout/bt_payment_description.xml#L37 is the culprit, but I am not familiar with the codebase enough to be sure.

**Comment by sdcoffey** [comment]
Yep, you'd be right. We'll take a closer look at this tomorrow.

**Comment by lkorth** [comment]
@nirinchev: this was fixed in `1.7.0`.
