### ISSUE TITLE
No cancelation event for 3DS v1 (BrowserSwitch).

### ISSUE THREAD

**Issue by v-sulimov** [braintree/braintree_android#458]
### General information

* SDK/Library version: 4.6.0
* Environment: Both
* Android Version and Device: Any
* Braintree dependencies:
```
implementation 'com.braintreepayments.api:card:4.6.0'
implementation 'com.braintreepayments.api:three-d-secure:4.6.0'
```

### Issue description

As mentioned in the title, there is an issue with the cancelation of the 3DS v1 process.

**Actual behavior:**
When we perform verification for the 3DS v1, the library opens up the Chrome Custom Tab with the 3DSecure page, where the user should enter the code. After that, the library brings up the Activity, defined in the AndroidManifest with the result, it's working fine and expected behavior. But, the issue is, when the user closes the Chrome Custom Tab, without entering the code, then, nothing happens, absolutely nothing. Our Activity doesn't start, it doesn't receive any result. In this case, it's impossible to detect the cancelation of the verification process.

**Expected behavior:** We receive UserCanceledException / any other sign from the library which tells us about the cancelation of the verification process.

**Important:** This is only applicable to the 3DS v1 and BrowserSwitch mechanism, it's working fine for the 3DS v2.

![Screenshot_20211006_144348](https://user-images.githubusercontent.com/53762011/136329399-4c8fb4dd-4f5f-492d-82e9-bdee030888f4.png)

**Comment by v-sulimov** [comment]
@sarahkoop I've just setup the demo project, but... How can I trigger the 3DSv1? 
When I add a card ```5200 0000 0000 0007 01/23 123``` the application just says "Transaction Complete", without any 3DSecure verification, ignoring all settings about this.

**Comment by sshropshire** [comment]
@v-sulimov navigate to "Settings" in the top right and scroll to the "3D Secure" section. Make sure both `Enable 3D Secure` and `Require 3D Secure` options are selected and you should be good.

**Comment by sarahkoop** [comment]
Hi @v-sulimov - Are you still experiencing this issue, and were you able to re-create it on our demo app?

**Comment by sarahkoop** [comment]
@v-sulimov - I'm going to close this issue for now due to inactivity and since we were not able to reproduce. Please feel free to re-open if you are still experiencing this issue and are able to reproduce in our demo app.
