### ISSUE TITLE
Showing selection window

### ISSUE THREAD

**Issue by auxDK** [braintree/braintree_android#466]
### General information

* SDK/Library version: 4.6.0
* Environment: Sandbox
* Android Version and Device: Android Emulator version 7, 9
* Braintree dependencies:

  - com.braintreepayments.api:paypal:4.6.0

### Issue description
When there are several browsers on the device  and none selected by default, it shows a selection window.  However there was no new window in 3 versions 

![Screenshot from 2021-10-26 09-10-24](https://user-images.githubusercontent.com/2931103/138822053-c4dc88f2-39da-4222-8dd1-eb1ef5602867.png)

**Comment by sshropshire** [comment]
Hi @auxDK this is expected behavior I believe. When re-directing from an app to `https:` the OS will detect multiple apps that can perform this action, and will ask the user which one to use. Is this only for Android 7 and 9 emulators? Have you been able to replicate on a physical device?

**Comment by auxDK** [comment]
@sshropshire  Yes, reproduced on a  physical device, no matter os version

**Comment by sarahkoop** [comment]
Hi @auxDK - This appears to be Android OS behavior, not an SDK issue. The user should be able to select a browser to continue, or set a default browser on their device to avoid this selection.
