### ISSUE TITLE
Drop-in Not fully localized

### ISSUE THREAD

**Issue by bpollock-coursera** [braintree/braintree_android#47]
* Only CCV is not localized for Simplified Chinese
* None of the strings are localized for Korean
* None of the strings are localized for Taiwanese

**Comment by quinnjn** [comment]
Hey, thanks for posting. We're looking into this. Hopefully I'll have an update soon.

**Comment by bpollock-coursera** [comment]
@quinnjn its been a couple weeks. Do you have any further information?

**Comment by lkorth** [comment]
@bpollock-coursera: in the future we hope to support more languages in Drop-in, however at this time we won't be adding support for Korean or Taiwanese.
