### ISSUE TITLE
Venmo payment flow with Fragment

### ISSUE THREAD

**Issue by Young-Chowbus** [braintree/braintree_android#475]
Currently we should handle payment result onActivityResult of Activity for Venmo payment on v4.
So we need to add some more code for sending and receiving result between Activity and Fragment.
We are using fragments more than activity component and it is better to handle result on Fragment, too
Also it would be excellent if we are not using onActivityResult because it is deprecated

**Comment by sshropshire** [comment]
Hi @Young-Chowbus thanks for using the Braintree SDK for Android. We are aware that `onActivityResult` is deprecated and hope to support `registerForActivityResult` in the near future. Please use the issue template in the future to provide more context on the Venmo issue you're describing.
