### ISSUE TITLE
4.x not possible to get list if payment methods (list of nonces)

### ISSUE THREAD

**Issue by mtrakal** [braintree/braintree_android#478]
### General information

* SDK/Library version: 4.7.0 / 4.8.0
* Environment: any
* Android Version and Device: any
* Braintree dependencies:
```
    braintreeVersion = "4.8.0"
// Braintree
    // https://github.com/braintree/braintree_android/releases

    // https://github.com/braintree/braintree-android-drop-in/releases
    implementation "com.braintreepayments.api:drop-in:6.0.0-beta2"

    // to offer card payments
    implementation "com.braintreepayments.api:card:$braintreeVersion"
    // to collect device data
    implementation "com.braintreepayments.api:data-collector:$braintreeVersion"
    // to offer PayPal
    implementation "com.braintreepayments.api:paypal:$braintreeVersion"
    // to offer local payments
    implementation "com.braintreepayments.api:local-payment:$braintreeVersion"
    // to offer Google Pay
    implementation "com.braintreepayments.api:google-pay:$braintreeVersion"
    // to perform 3DS verification
    // https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side/android/v4
    implementation "com.braintreepayments.api:three-d-secure:$braintreeVersion"
```

### Issue description

I need to get a list of all available payment methods for user to show custom payment list. In v3 we uses `PaymentMethodNoncesUpdatedListener` but with v4 methods to get list `DropInClient.getPaymentMethodNonces` is private. `PaymentMethodClient` is private too, so how I should get list of nonces?

**Comment by sshropshire** [comment]
@mtrakal thanks for using the Braintree SDK for Android. We extracted this logic into our DropIn library. We'll look into this as a potential enhancement for `v4` of the Core SDK.

**Comment by mtrakal** [comment]
as a consequece I'm not able to delete stored cards (because I don't have access to this list). I have stored some cards which are shown as prefilled / last used, but I'm not able as a user remove them from this list.

![Screenshot_2021-11-28-20-25-12-112_cz nom smilecarweb debug](https://user-images.githubusercontent.com/1458891/143832240-48123c53-e971-41c2-9038-013af5f1caea.jpg)

**Comment by sarahkoop** [comment]
Hi @mtrakal - A user will be able to delete their saved payment methods from the Drop-in UI if you set `vaultManagerEnabled` to `true` on your `DropInRequest`. See docs [here](https://github.com/braintree/braintree-android-drop-in/blob/master/Drop-In/src/main/java/com/braintreepayments/api/DropInRequest.java#L141). Does this provide the functionality you are looking for?  If not, we can look into making `DropInClient.getPaymentMethodNonces` public.

**Comment by mtrakal** [comment]
I will try to describe our use case / workflow with cards:

User pay for our service + we withdraw return deposit. We return deposit to Users card after some time.

Our users manage his cards in our app.  We show them list of stored cards where they can Add or Remove cards (if conditions met).

So we need list of cards to show for users to manage cards.
We allow delete card only when we don't hold any deposit. In case when user delete card before deposit is returned, we don't know where to return this deposit.

I tried your dialog and `vaultManagerEnabled` which looks good, but it don't allow us to disable delete specified card (we need to validate it on our backend before). So it's not usable for us.

---
Know you if has iOS and web "get nonces / cards" method private for v4 too? Could it be possible allow it for iOS / web as well?

**Comment by dlitvik** [comment]
Hi  @sarahkoop I would like kindly ask you if you have some estimate when this issue could be solved? We want to start using new sdk but without negative impact on our service and users. Thank you.

**Comment by sshropshire** [comment]
@dlitvik there are some potential breaking changes that we would like to avoid before implementing this feature. We don't have a timeline yet, but we are prioritizing and considering adding this feature back into the core SDK in a future release.

**Comment by josemifever** [comment]
Hi! We need that too. We want to build our own braintree flow instead to be attached to the dropIn. 🙏

**Comment by sarahkoop** [comment]
Hi @dlitvik and @josemifever - Thanks for your patience on this. We are trying to determine the best approach to provide this functionality in a way that is compatible with our existing SDKs and that meets your needs. 

Like Steven mentioned previously, this functionality was moved to our Braintree Android Drop-in SDK and made non-public, since it is used primarily by our internal SDK. It is my understanding that you need the ability to fetch vaulted payment methods and delete vaulted payment methods, correct? 

Would adding methods to `DropInClient` to invoke [`PaymentMethodClient.getPaymentMethodNonces`](https://github.com/braintree/braintree-android-drop-in/blob/master/Drop-In/src/main/java/com/braintreepayments/api/PaymentMethodClient.java#L69) and [`PaymentMethodClient.deletePaymentMethod`](https://github.com/braintree/braintree-android-drop-in/blob/master/Drop-In/src/main/java/com/braintreepayments/api/PaymentMethodClient.java#L96) be an acceptable solution for your integrations?  This would require you to pull in the `com.braintreepayments.api:drop-in` library and instantiate a `DropInClient`, in addition to the using the core SDK libraries.

**Comment by josemifever** [comment]
Hi @sarahkoop thanks for you early reply! 
I can understand that you want to provide a ready-to-use solution with your drop-in, it's fine! 
But you should leave the door open for our custom integrations, since mixing UI components and business logic is not a good practice, and we don't need the drop-in at all.We only need to access to the Braintree API through a well designed SDK.
A good approach could be to provide the PaymentMethodClient in the core library, since drop-in comes with a lot of useless dependencies for us.
Please, let me know if the request is clear. Thanks you so much for your help!

**Comment by mtrakal** [comment]
Hi @sarahkoop for me/our company (as the author of this issue) should be fine when you create these two methods public. It would be nice and solve our issues with the integration of v4 😍🙏.
We use Drop-in, so I'm ok with this quick-fix solution.

**Comment by dlitvik** [comment]
Hi @sarahkoop, I would like to ask you if you can provide us with some time estimate to release these methods? 

Also, we are currently using version 3.x.x of your SDK and we are waiting with the migration to newer one for this open ticket to be solved (either by successful resolution or cancellation). What will happen in June when 3.x.x will be deprecated?

**Comment by sarahkoop** [comment]
Hi @dlitvik - can you confirm if the solution of adding the methods to Drop-in will work for your integration? We would be able to provide that solution in a shorter timeframe. An update to the core SDK would require re-architecting, and may not be possible in a non-breaking change (so we can not confirm if we will be able to offer this solution at this time).

**Comment by dlitvik** [comment]
Hi, yes, Matej Trakal is a colleage who directly implements your SKD. Your proposed solution works for us as he confirmed. 

Also, can you help us to understand what will be the effect on users with the older version of our application containing version of Braintree SDK 3.x.x?

**Comment by josemifever** [comment]
> Hi @dlitvik - can you confirm if the solution of adding the methods to Drop-in will work for your integration? We would be able to provide that solution in a shorter timeframe. An update to the core SDK would require re-architecting, and may not be possible in a non-breaking change (so we can not confirm if we will be able to offer this solution at this time).

Any update on this? PaymentMethodClient was public in the 4.x beta version why it becomes private?, making it public again would let developers retrieve the payment methods stored in the user's account.

**Comment by ehtisham-ali-emumba** [comment]
any update over here @sarahkoop ?

**Comment by sshropshire** [comment]
Hi @ehtisham-ali-emumba this is on our radar. We have a 3rd library we'll need to update to make this change. We don't have an exact timeline in place but we are planning on offering this feature in our next major version.

**Comment by fatlinesofcode** [comment]
noting this feature is available in the ios sdk v4+ v5
 https://braintree.github.io/braintree_ios/current/Classes/BTAPIClient.html#/c:objc(cs)BTAPIClient(im)fetchPaymentMethodNonces:

**Comment by sarahkoop** [comment]
Thanks for your patience everyone! We have a PR open to make these methods public in Drop-in. This will require including the Drop-in SDK in order to create a `PaymentMethodClient`, but it is the current technically feasible solution in this version of the SDK.
