### ISSUE TITLE
User cancelled 3DS

### ISSUE THREAD

**Issue by Jake-Jiang** [braintree/braintree_android#480]
### General information

* SDK/Library version: 4.6.0
* Environment:  Production
* Android Version and Device: Android:11,samsung:SM-T510:gta3xlwifi
* Braintree dependencies:

 Our customers in the UK reported that many users could not complete 3DS verification. They first reported an error from the browser in the screenshot, and then received a User cancelled 3DS error.
![image](https://user-images.githubusercontent.com/58160182/142987647-4d81cdf7-4395-4b97-9368-919613cf672f.png)

Could you provide some suggestions or solutions? thank you very much.

**Comment by sarahkoop** [comment]
Closing this do to inactivity - if you are able to provide the information requested above, please re-open this issue and we will investigate.
