### ISSUE TITLE
3DS result not being delivered in `braintreeClient.deliverBrowserSwitchResult`

### ISSUE THREAD

**Issue by matejhacin** [braintree/braintree_android#485]
### General information

* SDK/Library version: 4.7.0
* Environment: Sandbox
* Android Version and Device: Android 12
* Braintree dependencies:
com.braintreepayments.api:three-d-secure:4.7.0

### Issue description

While upgrading Braintree SDK from v3 to v4, I've run into an issue with 3DS integration. When I call `braintreeClient.deliverBrowserSwitchResult(activity)` inside my `Fragment.onResume` method, the result is always null.

If I set the deep link configuration in my manifest and then check for 3DS result inside `onActivityResult` of the parent Activity it actually does work and the result seems to be there.

But, I have trouble understanding this logic. The migration guide clearly says that `BrowserSwitchResult` should be used when app switch does not happen, or with the use of ThreeDSecureClient, which is the case here. The 3DS browser is opened within the app, or at least it seems like it.

If this is the only way to implement this, it complicates things for my project, as the app uses multiple different activities, each with multiple different fragments, where payment can happen. With the v3, I was able to decouple the 3DS logic into a separate class which received a FragmentActivity as a reference, and the whole process was handled in there, making the 3DS code easily reusable and maintainable. Having to handle these results in multiple different activities and making sure the data makes its' way into the correct Fragment and then into the correct ViewModel is not ideal and actually complicates things a lot.

To me, this seems like a downgrade in the SDK flexibility and I don't quite understand it. Is there a way around this?

_It seems like I am not the only person bothered by this, as I noticed someone running into the same issue (#475)._

**Comment by sshropshire** [comment]
@matejhacin we're discussing possible solutions internally. If you'd like to contribute check out the discussion on [Developer Experience](https://github.com/braintree/braintree_android/discussions/496) we created.
