### ISSUE TITLE
Improve Migration Documentation Around Browser Switch Activity

### ISSUE THREAD

**Issue by sdoward** [braintree/braintree_android#488]
[The migration guide](https://github.com/braintree/braintree_android/blob/master/v4_MIGRATION_GUIDE.md#browser-switch) suggests that we use our own activity rather than V3 `com.braintreepayments.api.BraintreeBrowserSwitchActivity`. But it is unclear what that activity is supposed to do.

`MyPaymentsActivity` referenced in the manifest snippet isn't used anywhere else in the guide.

In my use case I have multiple activities that can create a paypal payment method but I am unsure on how I am supposed to handle this.

**Comment by sshropshire** [comment]
Hey @sdoward thanks for using the Braintree SDK for Android. We removed `BraintreeBrowserSwitchActivity` to eliminate some process kill scenarios that would break the browser switching flow. Your app's activity is now the deep link destination.

When there are multiple deep-link targets, we do have a separate constructor that allows you to pass in a custom URL scheme for the deep link [here](https://github.com/braintree/braintree_android/blob/c87a6861d418731952f5b4ef5584c48257d97781/BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java#L93). Then in your `AndroidManifest.xml` you can customize [the template](https://github.com/braintree/braintree_android/blob/c87a6861d418731952f5b4ef5584c48257d97781/BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java#L93) and replace `${applicationId}.braintree"` with whichever URL scheme you'd like.

**Comment by sdoward** [comment]
@sshropshire Thanks for the quick reply. Is there some documentation on how I structure the URL scheme for the deeplink?

I think you linked the constructor again rather than the template :)

But I am still missing something... I guess i declare multiple activities that can accept deeplinks in the manifest? Then how do I handle those deeplinks?

**Comment by sshropshire** [comment]
@sdoward thanks yeah I forgot to Cmd-C, it's updated now. At the moment unfortunately we don't have documentation on this integration method.

You can declare multiple intent filters and the scheme can be in whichever format – `my.deep.link1://` and `my-deep-link2://` are some examples.

**Comment by sshropshire** [comment]
> @sshropshire Thanks for that. I have another question.. I am a little confused with the callback. It seems it only returns a nullable exception...

For `PayPalClient#tokenizePayPalAccount` we make a network request before browser switching to PayPal web. If the initial network request fails, you'll get an error here. It's `null` whenever the browser switch is successful.

**Comment by sshropshire** [comment]
> Sorry to throw so many questions at you....

All good!

1. That's correct there's a typo in the migration guide we can address.
2. By design technically they both cannot be null, but I guess theoretically anything is possible. I'm curious what you mean by improving the API surface? If you have a code snippet / example maybe open a separate GitHub issue and we'll take a look.
3. Yes the nonce has a `String` representation and we didn't want to collide with Java's `toString()` variant of the method since payment method nonces contain additional metadata as well. We felt that `payPalAccountNonce?.string` unwraps nicely when sending to the server on the Kotlin side.

**Comment by sdoward** [comment]
Thanks again for the answers.

With regards to your question...

With your current API we have to handle the following states and how I am handling..

| Nonce    | Exception | How I handle then                  |
|----------|-----------|-----------------------------|
| Not Null | Not Null  | Handle Nonce                |
| Not Null | Null      | Handle Nonce                |
| Null     | Not Null  | Handle Error                |
| Null     | Null      | throw IllegalStateException |

Braintree doesn't offer advice or documentation on state 1 and 4 because it is not supposed to happen. But we shouldn't have "dead ends" in our code and we should be handling all eventualities.  So in this case your API is giving us these 4 states when it shouldn't.

An obvious solution would be separated functions...

```
public interface PayPalBrowserSwitchResultCallback {

   void onSuccess(@Notnull PayPalAccountNonce payPalAccountNonce)

   void onError(@NotNull Exception error);
}
```

In the case we don't have any nullable object and only 2 states. But there are other options available such as an [Either Monad](https://github.com/functionaljava/functionaljava/blob/series/5.x/core/src/main/java/fj/data/Either.java) (probably overkills in this case). There are other options available. 

There are many examples of poor API's in the sdk. This coupled with bad documentation, which often doesn't compile, makes for a pretty poor developer experience. And I feel like as consumers of the lib we could expect more.

With that in mind I will take your advice and open up a separate issue with general API questions.

**Comment by sshropshire** [comment]
> Braintree doesn't offer advice or documentation on state 1 and 4 because it is not supposed to happen.

@sdoward for the record these states are highly improbable. States 1-4 are still theoretically possible in your example (and arguably more likely in the case of a bug) with two `@NotNull` callback methods e.g. if neither callback is called.

I understand your points of discussion. We do leverage [Single Abstract Method](https://www.baeldung.com/java-8-functional-interfaces) interfaces in our API to provide a callback style interface in both Java and Kotlin. We appreciate the feedback on documentation and will work to update the examples so they work out of the box. The Either Monad pattern looks cool, but my concern here is that it may further complicate the API for people who are new to Android / Java / Kotlin. Overall, we aim for the API of the SDK to appeal to a broad audience – this includes beginners and advanced users alike.

**Comment by sdoward** [comment]
@sshropshire I feel like we are missing each other on the crucial point here.

**Comment by gomera** [comment]
@sdoward  I have to congratulate you for your incredible patience trying to explain the obvious.

**Comment by sshropshire** [comment]
@gomera not sure exactly what we missed, but we do have an open [discussion](https://github.com/braintree/braintree_android/discussions/496) on improving the developer experience. Feel free to add input. We're looking to improve the SDK and we welcome merchant feedback.
