### ISSUE TITLE
onActivityResult is deprecated

### ISSUE THREAD

**Issue by darkharov** [braintree/braintree_android#489]
The library requires to override onActivityResult(). This method is deprecated.
https://developer.android.com/training/basics/intents/result

**Comment by sshropshire** [comment]
Hi @darkharov thanks for using the Braintree SDK for Android. We're evaluating multiple solutions to integrate with the updated `startActivityForResult` API. We'll provide more information when the time comes.

**Comment by sshropshire** [comment]
@darkharov we're discussing possible solutions internally. If you'd like to contribute check out the discussion on [Developer Experience](https://github.com/braintree/braintree_android/discussions/496) we created.

**Comment by sarahkoop** [comment]
Hi @darkharov - We have added a new integration pattern that does not require the deprecated `onActivityResult` method. Please upgrade to the latest version of the SDK (`4.10.0`) and take a look at our [Migration Guide](https://github.com/braintree/braintree_android/blob/master/v4.9.0%2B_MIGRATION_GUIDE.md) to integrate with the new integration pattern.
