### ISSUE TITLE
Please make method of PaymentType public

### ISSUE THREAD

**Issue by norman-kapschefsky** [braintree/braintree_android#49]
Hi,
can you please make the method <code> static PaymentType forType(String paymentMethodType)</code> <b>public</b> in class PaymentMethodView?. The enum itself is accessable but method isn't from outside. 

Thanks.

**Comment by sdcoffey** [comment]
@norman-kapschefsky Good idea, can you give us an idea of your use case?

**Comment by norman-kapschefsky** [comment]
@sdcoffey In our case we abstracted the payment methods from braintree into a class that we are using client- and server-side wise. Basically wrapping the information (type label, identifier, nonce etc.). For UI stuff we want to display the related icons like in PaymentMethodView. This would be easy if we could use the PaymentType enum where we could have access to the defined drawable ids. To accomplish that determing the type has to be public and there must be a getter for the properties (e.g. image resource id).

**Comment by quinnjn** [comment]
Sounds good. I don't see an issue in separating this class out. It'll probably make it into 2.0 however.
