### ISSUE TITLE
[Venmo] isVenmoAppSwitchAvailable always returns false on Android 12

### ISSUE THREAD

**Issue by niccorder-dd** [braintree/braintree_android#495]
### General information
implementation 'com.braintreepayments.api:venmo:4.4.1

### Issue description
`isVenmoAppSwitchAvailable` always returns false on Android 12 even though venmo is indeed installed on device.

**Comment by sshropshire** [comment]
Hi @niccorder-dd thanks for using the Braintree SDK for Android. Does upgrading to the latest `4.8.1` resolve this issue? We added official support for Android 12 in [4.6.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#460).

**Comment by niccorder-dd** [comment]
@sshropshire – this seemed to be the fix! Closing now.
