### ISSUE TITLE
I want to upgrade the Paypal version now, but I don't know how to use it

### ISSUE THREAD

**Issue by Yongyong-Zhou** [braintree/braintree_android#497]
https://developer.paypal.com/braintree/docs/guides/paypal/checkout-with-paypal  I didn't understand this document

![image](https://user-images.githubusercontent.com/86334406/150480358-aa18cd1f-8234-447e-9533-edd9762f175b.png)

![image](https://user-images.githubusercontent.com/86334406/150480571-3b93c59d-002f-43d3-afd3-6d530f4d1cd1.png)

The problem that bothers me:
1. myTokenizePayPalAccountWithCheckoutMethod() why not use?
2. browserSwitchResult I keep getting null,why?
3.I saw that the released 4.0.0-beta1 deletes the BraintreeFragment I used before, but I upgraded to the latest one, and I don't know how to call paypal?

Could you give me an integrated Pyapal demo? I'm stuck for 2 days?

Thank you very much!

**Comment by Yongyong-Zhou** [comment]
Are you not accessing the document? I didn't understand this.

**Comment by Yongyong-Zhou** [comment]
> 嗨@Yongyong-Zhou - 您是否按照[此处](https://developer.paypal.com/braintree/docs/guides/client-sdk/setup#browser-switch-setup)的设置步骤设置您的应用程序以处理浏览器切换结果？上面的文档代码片段旨在帮助将 PayPal 集成添加到您自己的应用程序活动设置中，它不是一个完整的代码示例。您需要定义`BraintreeClient`和`PayPalClient`变量，并将 链接`myTokenizePayPalAccountWithCheckoutMethod()`到您用于启动 PayPal 流程的任何按钮。[您可以在此处查看](https://github.com/braintree/braintree_android)自定义集成的完整演示应用程序，并在[此处查看](https://github.com/braintree/braintree-android-drop-in)Drop-in 集成。有关设置集成的更多帮助，我们建议[联系支持人员](https://developer.paypal.com/braintree/help)。如果您认为 SDK 中存在问题，请随时打开 GitHub 问题。

![Uploading image.png…]()

The browser settings are only to return to the app from the browser, but my current app can't jump outside the browser, and it keeps prompting that PayPal is not enabled.

Could you help me see what the problem is? How do I continue to integrate?

**Comment by Yongyong-Zhou** [comment]
![Uploading image.png…]()

The browser settings are only to return to the app from the browser, but my current app can't jump outside the browser, and it keeps prompting that PayPal is not enabled.

Could you help me see what the problem is? How do I continue to integrate?

**Comment by sarahkoop** [comment]
Hi @Yongyong-Zhou, our support team will be able to help you get your merchant account set up for PayPal, and assist with troubleshooting your integration further. Please contact them [here](https://developer.paypal.com/braintree/help).

**Comment by Yongyong-Zhou** [comment]
Did your integration not encounter my problem?
I just want to integrate test it now.
Did you not integrate the pyapal demo? Can you tell me how to call the code?
@sarahkoop

**Comment by Yongyong-Zhou** [comment]
I read the documentation several times, is there something wrong with my code above? @sarahkoop

**Comment by sshropshire** [comment]
@Yongyong-Zhou as @sarahkoop our [support team](https://developer.paypal.com/braintree/help) will be able to help resolve your integration issues. It appears your merchant account has yet to be enabled for using PayPal. This would happen through the [Braintree console](https://www.braintreegateway.com/login) and the support team can help guide you.
