### ISSUE TITLE
PayPal Error: Required field is not present

### ISSUE THREAD

**Issue by wamry** [braintree/braintree_android#498]
### General information

* SDK/Library version: `3.17.2`
* Environment: Both production and sandbox
* Android Version and Device: Any android device
* Braintree dependencies: `com.braintreepayments.api:braintree:3.17.2`

### Issue description
When I try to make a new Paypal billing request, using the following code
```
val request = PayPalRequest()
  .localeCode("US")
  .shippingAddressRequired(true)
  .billingAgreementDescription("")
PayPal.requestBillingAgreement(mBraintreeFragment, request)
```
I get this error message
```
["Required field city is not present", "Required field country_code is not present", "Required field line1 is not present"]
```
Removing `shippingAddressRequired(true)` prevents this error, but the result data would have no address information, which is needed.

This issue started on Jan 14th, previously same code was working fine.

**Comment by Kelv** [comment]
The issue seems to be this line :
https://github.com/braintree/braintree_android/blob/debd82965d4d3360c3e5f0d502f5d1db2d69810a/Braintree/src/main/java/com/braintreepayments/api/PayPal.java#L277

In iOS it works, but the client is sending a `0` instead of a `false`. I was testing and was able to make it work by using Android Studio to debug and replace the value of `NO_SHIPPING_KEY` for `0`. This error is still present in Android SDK v4.

**Comment by sshropshire** [comment]
@wamry @Kelv thanks for using the Braintree SDK for Android. We're reviewing this internally and will post here once we have more information.

**Comment by Kelv** [comment]
Thank you, it's working now! 🎉
I still can't get the user's phone number associated with that address, do I need to do something else?

**Comment by sarahkoop** [comment]
Once you get back a `PayPalAccountNonce` you can access the `phone` field on the nonce

**Comment by Kelv** [comment]
I am using a PayPal Sandbox account, just debugged until reaching this Line here:https://github.com/braintree/braintree_android/blob/debd82965d4d3360c3e5f0d502f5d1db2d69810a/Braintree/src/main/java/com/braintreepayments/api/TokenizationClient.java#L96
But `responseBody` doesn't come with the phone number.
