### ISSUE TITLE
I have integrated api:paypal:4.8.1, but BraintreeClient and PayPalClient are not initialized in onCreate(), BrowserSwitchResult has no callback

### ISSUE THREAD

**Issue by Yongyong-Zhou** [braintree/braintree_android#499]
![image](https://user-images.githubusercontent.com/86334406/150958976-88fbea2a-56a6-45b0-8d1b-b8f42a0e2384.png)
![image](https://user-images.githubusercontent.com/86334406/150959092-37ff0374-ea83-42f7-9607-d770d3d9f395.png)

braintreeClient = new BraintreeClient(this, "TOKENIZATION_KEY_OR_CLIENT_TOKEN");
payPalClient = new PayPalClient(braintreeClient);

1.They I can't put in onCreate() because I show a purchase list before calling Pyapal payment, click the payment button and go to the cloud to get the token operation and then get the payment.
I didn't pay the token in onCreate()?
So I wrote a demo, put them in setOnClickListener(), the method BrowserSwitchResult() did not return? why is that?

 Please check my bug, I have been troubled for several days, thank you.. thank you

**Comment by Yongyong-Zhou** [comment]
This is my test demo, ClickListener() calls BraintreeClient(), BrowserSwitchResult is not returned.

![image](https://user-images.githubusercontent.com/86334406/150961861-2e9e2c0f-9a2f-4111-8c37-769df341306b.png)
![image](https://user-images.githubusercontent.com/86334406/150961903-46434bd0-1666-489b-b1be-439354f34665.png)
![image](https://user-images.githubusercontent.com/86334406/150961938-6855ad8b-99c1-494a-8423-c10c1dc7e131.png)

**Comment by sshropshire** [comment]
Hi @Yongyong-Zhou thanks for using the Braintree SDK for Android. In the first code snippet I see there are two `BraintreeClient` instances: one in `onCreate` and one in the PayPal button `View.OnClickListener`. Having a single client instance will help the best. In this case, lazily instantiating the client will allow you to asynchronously fetch a client token, and you can display a loader while this occurs for the time being.

We do have a [proposed solution](https://github.com/braintree/braintree_android/discussions/496) that will help address the `onCreate` timeliness issue you mentioned, but for the time being, you may have to lazily create a `BraintreeClient`.

As for browser switch, if an event was not delivered before it may be delivered again. In your case, during active development, it may return an error initially if the flow was interrupted say by a debugger or running / re-running the application several times.

**Comment by Yongyong-Zhou** [comment]
![image](https://user-images.githubusercontent.com/86334406/151091540-936d878b-ef29-4f1c-ac54-0d2a0b664713.png)
Which dependency are you using? I can't cite it.

**Comment by Yongyong-Zhou** [comment]
@sshropshire I can't call ClientTokenProvider, am I missing some dependency library? 
![image](https://user-images.githubusercontent.com/86334406/151202871-f9fda6f4-4995-4f0e-90ce-33be8641025c.png)

**Comment by sshropshire** [comment]
@Yongyong-Zhou it is a proposal at this point in time. We are working on improving the onboarding experience and will release this in the near future. In the meantime, please follow these [integration steps](https://developer.paypal.com/braintree/docs/guides/paypal/client-side).

**Comment by Yongyong-Zhou** [comment]
I understand what you mean, thank you @sshropshire

**Comment by Yongyong-Zhou** [comment]
But I'm just short of the last step to integrate api:paypal:4.8.1.onCreate() method I have no token, I have to request the interface to get the token, and then I can initialize BraintreeClient(" token"). Can you help me think of a way to solve this problem Based on the current 4.8.1? 
@sshropshire  thank you

Or I can only integrate the 3.+ version first？

**Comment by sarahkoop** [comment]
Hi @Yongyong-Zhou - Thanks for your patience on this. The `ClientTokenProvider` and other classes related to the new API have been released in `4.9.0`

**Comment by sarahkoop** [comment]
Closing this as the new API has been released
