### ISSUE TITLE
Of the two PayPal payment methods, which should I use? Is there any difference between them?

### ISSUE THREAD

**Issue by Yongyong-Zhou** [braintree/braintree_android#503]
![image](https://user-images.githubusercontent.com/86334406/151114033-69541ed5-5e8e-433c-b297-e0fa9d935cf2.png)

Of the two PayPal payment methods, which should I use? Is there any difference between them?
Please check my bug, I have been troubled for several days, thank you.. thank you

**Comment by sarahkoop** [comment]
Please refer to our [developer docs ](https://developer.paypal.com/braintree/docs/guides/paypal/overview/android/v4) for information about PayPal Vault vs Checkout

**Comment by Yongyong-Zhou** [comment]
@sarahkoop Thanks for your reply, I understand
