### ISSUE TITLE
Why does the prompt prompt me to fail "sorry, something went wrong", but the browserSwitchResult returns a success message later, why?

### ISSUE THREAD

**Issue by Yongyong-Zhou** [braintree/braintree_android#504]
I recorded a debug video for this, can you help? I need to integrate paypal, but it's been bugging me for days, thanks.
I have this error pop up basically every time I pay.Why is this error reported?

![791643179139_ pic](https://user-images.githubusercontent.com/86334406/151115310-5bae6ac6-7229-4af2-bbff-

Because upload video cannot be larger than 10mb, record 2 videos

1.start:
https://user-images.githubusercontent.com/86334406/151115605-bd0bffe1-6f54-45cf-9127-4aaf94e2ad36.mp4

2. end:

https://user-images.githubusercontent.com/86334406/151115814-953113b9-edf0-421d-b65c-f95a4c3929c5.mp4

**Comment by sarahkoop** [comment]
Closing this as duplicated of #500

**Comment by Yongyong-Zhou** [comment]
@sarahkoop This is why this problem occurs, and IOS is normal.  @sshropshire

**Comment by Yongyong-Zhou** [comment]
IOS normally proves that it has nothing to do with the company's account, then why does this problem occur when I integrate it. @sarahkoop

**Comment by Yongyong-Zhou** [comment]
You watch the video above and although he returns an error, the BrowserSwitchResult gets 2 returns. The second return is successful. And there is card related information. @sarahkoop @sshropshire

**Comment by crookedneighbor** [comment]
@Yongyong-Zhou This issue was correctly identified as closely related to the one you posted in #500, so we've closed this one as a duplicate and linked it to #500 so we have reference to the video you posted. Please continue any further discussion about this in #500

**Comment by crookedneighbor** [comment]
I'm locking this issue. We've asked you to continue discussion in #500 to consolidate the discussion.
