### ISSUE TITLE
Custom PayPalCheckoutRequest billing agreement description text not displaying (api:paypal:4.8.1)

### ISSUE THREAD

**Issue by langsmith** [braintree/braintree_android#509]
### General information

* SDK/Library version:

4.8.1

<img width="431" alt="Screen Shot 2022-01-31 at 12 33 01 PM" src="https://user-images.githubusercontent.com/4394910/151868645-a485d82f-af0a-4643-9451-16817b68b1b1.png">

* Environment:

Sandbox

* Android Version and Device:

Physical OnePlus 8 Pro running Android 11

My app's SDK versions 👇🏽 

<img width="183" alt="Screen Shot 2022-01-31 at 12 52 19 PM" src="https://user-images.githubusercontent.com/4394910/151871213-a69749ff-a24a-43eb-af12-f12a383b5cf1.png">

* Braintree dependencies:

`implementation com.braintreepayments.api:paypal:4.+`

`implementation com.braintreepayments.api:data-collector:4.+`

### Issue description

It seems that a custom billing description string isn't being displayed at the top of the payment selection web page during an Android Checkout payment flow. I've set up my flow according to https://developer.paypal.com/braintree/docs/guides/paypal/checkout-with-paypal 

I've tried going through the flow with a personal *sandbox* account **and** a business *sandbox* account. The text doesn't display in neither situation.

I'm trying to get the `Preferred Funding...` sentence to show below the `Hi, John` area.

**On Android:** 👇🏽

<img width="345" alt="Screen Shot 2022-01-31 at 12 47 58 PM" src="https://user-images.githubusercontent.com/4394910/151870649-05a6eb66-e447-461a-9f94-be287164eeb3.png">

The same sentence is displayed for my iOS colleague when he set up the same flow on iOS 👇🏽

<img width="341" alt="Screen Shot 2022-01-31 at 12 35 43 PM" src="https://user-images.githubusercontent.com/4394910/151868997-f65841e4-e2cd-494f-b8f8-65dde0359aa5.png">

This is how I'm building my `PayPalCheckoutRequest` object.
<img width="1150" alt="Screen Shot 2022-01-31 at 12 24 10 PM" src="https://user-images.githubusercontent.com/4394910/151867365-88242571-7a72-40ee-b229-ef3946c7e84a.png">

I logged the description string (`getStringOrEmpty(R.string.booking_payment_fragment_paypal_billing_description` seen in the screenshot above) to make sure that I wasn't erroneously using a blank string when building the `PayPalCheckoutRequest` object. It appears to be fine in the logcat 👇🏽

<img width="1102" alt="Screen Shot 2022-01-28 at 3 44 24 PM (1)" src="https://user-images.githubusercontent.com/4394910/151867468-a85d475f-e210-42dd-a3b7-9be4e1c7ece0.png">

I also checked the request's billing description before I actually tokenize the PayPal account 👇🏽

<img width="867" alt="Screen Shot 2022-01-31 at 12 45 14 PM" src="https://user-images.githubusercontent.com/4394910/151870264-5eea9980-ab95-43bd-aa0e-905d817ce0d9.png">

<img width="1100" alt="Screen Shot 2022-01-31 at 12 44 54 PM" src="https://user-images.githubusercontent.com/4394910/151870211-aef4caf7-151d-4114-a64d-e224e4864cd9.png">

Any of you know what might be going wrong? A known bug?

**Comment by sarahkoop** [comment]
Hi @langsmith thanks for using the Braintree Android SDK. We are currently investigating this issue and will post an update here when we have more information.

**Comment by langsmith** [comment]
Ok, thanks for the update @sarahkoop

**Comment by sarahkoop** [comment]
This fix has been released in `4.8.3`.
