### ISSUE TITLE
Paypal SDK missing some classes

### ISSUE THREAD

**Issue by mayi203** [braintree/braintree_android#51]
Paypal SDK in braintree-api-1.7.0-full.jar missing some classes (eg:PayPalPayment, PaymentActivity, PaymentConfirmation), which leads to the method of Paypal before the call can not be used

**Comment by lkorth** [comment]
@mayi203 Those classes were removed around the beginning of the year as they are not used in the Braintree PayPal integration. You should not need them if you are using `braintree_android` to integrate with PayPal. If you are attempting to do a PayPal integration directly with the PayPal SDK using the PayPal SDK that is included inside of `braintree_android`, that is not currently supported. It is also not possible to use `braintree_android` and the PayPal SDK in the same app as they declare some of the same classes in the same packages.
