### ISSUE TITLE
Not Show Records in Braintree Transactions.

### ISSUE THREAD

**Issue by rashid-sdsol** [braintree/braintree_android#52]
No Results Found

https://sandbox.braintreegateway.com/merchants/xgz6xz9cmwmbdjm5/transactions/advanced_search

in Transactions ; No Results Found

Even I set  private static final String BRAINTREE_MERCHANT_ID = "xgz6xz9cmwmbdjm5";

**Comment by gbramwell** [comment]
Rashid,

The Android library is only one component you'll need to run a transaction. Our SDK will give you a payment method nonce, which you'll need to send to your server, which you'll use to create a transaction (https://developers.braintreepayments.com/android/start/hello-server#receive-a-payment-method-nonce-from-your-client)

If you're running into issues, our support team is great at helping figure out what is happening with your integration - they can be reached via support@braintreepayments.com or via phone at 877.434.2894.
