### ISSUE TITLE
Problems with initializing ThreeDSecureClient

### ISSUE THREAD

**Issue by jcamarena-sh** [braintree/braintree_android#541]
### General information

* SDK/Library version: 4.10.1
* Environment: Production
* Android Version and Device: Android version 10-12

### Issue description

According to the documentation, `onBrowserSwitchResult` is deprecated and it must be replaced by `ThreeDSecureListener`. To initialize ThreeDSecureClient, it must be done on `Activity.onCreate()` state. The problem is that our Activity must request the `token` to our backend (it takes time), and then initialize BraintreeClient  and finally ThreeDSecureClient. So, it is not possible to initialize before getting `RESUME` state on the Activity, and the app crashes because is not posible to set a Listener before onResume():

`java.lang.IllegalStateException: LifecycleOwner com.stubhub.checkout.CheckoutActivity@a83975d is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.`
 
Is there any way to avoid this issue? Otherwise I should refactor again the app.

Thanks in advance.

**Comment by sarahkoop** [comment]
Hi @jcamarena-sh thanks for using the Braintree Android SDK! We've created a `ClientTokenProvider` interface that should be used to allow you to instantiate a client in `onCreate`.  With the provider, the SDK will fetch a client token on your behalf when it is needed. Our [v4.9.0+ Migration Guide](https://github.com/braintree/braintree_android/blob/master/v4.9.0%2B_MIGRATION_GUIDE.md#client-token-provider) has an example `ClientTokenProvider` implementation that can be used as a guide. 

Leaving this issue open for now, please let us know if additional clarification is needed, or if the `ClientTokenProvider` solves this issue for you.

**Comment by sarahkoop** [comment]
Closing this as resolved - please re-open if the documentation does not provide the clarity you need.

**Comment by Vitanio** [comment]
Hi! I've the exactly same problem with DropInClient. The ClientTokenProvider can be used with DropInClient as well? I'm trying to integrate it but i don't find any docs on the migration of DropInClient. Can you help me?

**Comment by yarodevuci** [comment]
same error. LifecycleOwners must call register before they are STARTED

**Comment by sshropshire** [comment]
@Vitanio yes the `DropInClient` now has support for client token provider. You can view the migration guide docs [here](https://github.com/braintree/braintree-android-drop-in/blob/master/v6_MIGRATION_GUIDE.md#option-2-dropinclient-with-clienttokenprovider).

**Comment by dhvani023** [comment]
same error, anyone can help ? 
LifecycleOwner SelectPaymentActivity@766330 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.

// calling this in onCreate
getClientToken(new ApiCallBack() {
            @Override
            public void onSuccess(String token) {
                dropInClient = new DropInClient(SelectPaymentActivity.this, token); // A 240523
                dropInClient.setListener(SelectPaymentActivity.this);
                dropInRequest = new DropInRequest();
                dropInClient.launchDropIn(dropInRequest); // A 240523
            }

            @Override
            public void onFail(String error) {
                Log.e("onFail - ", "" + error);
            }
        });


// getClientToken is function which return token
