### ISSUE TITLE
No ability to invalidate cached credentials

### ISSUE THREAD

**Issue by josephyanks** [braintree/braintree_android#544]
### General information

* SDK/Library version: 4.9.0
* Environment: Production
* Android Version and Device: N/A
* Braintree dependencies:

com.braintreepayments.api:card:4.9.0
com.braintreepayments.api:data-collector:4.9.0
com.braintreepayments.api:google-pay:4.9.0
com.braintreepayments.api:paypal:4.9.0
com.braintreepayments.api:three-d-secure:4.9.0
com.braintreepayments.api:venmo:4.9.0

### Issue description

There is currently no way to invalidate the credentials once they are read once from a `ClientTokenProvider` or set via `initialAuthString`. Because of the instantiation strategy for 3rd party clients (google pay, venmo, etc.) on android requiring the instantiation to be prior to the onCreate lifecycle, there is no way to change the braintree client or invalidate the cached credentials once a token has been read.

We have a few places where we are being provided a braintree client token to use for authentication, and the permissions tied to that token may vary from screen to screen. Because we use a single activity application, the clients are shared across all screens. Once the authentication token is read once (either from the `initialAuthString` or `clientTokenProvider`), that authentication value persists for the entirety of the application. This behavior has downstream effects for us if, for example, 3D Secure is not enabled for the first token received, but is for a subsequent token. 

From the contract of the `ClientTokenProvider`, it appears from the onset that this will act like an interceptor and will read the client token value any time authorization is requested. Instead, the `ClientTokenProvider` class is essentially setting the `initialAuthString` in a `by lazy` way.

There are several solutions to this, which I'd be happy to make a PR for, but I'm not sure what is preferable. One of the main problems from an architecture perspective is that external consumers of the braintree api don't have any concept of the `AuthorizationLoader` or its caching strategy.

This is our interim solution, which uses reflection and is very undesirable:

```
private fun forceAuthorizationRefresh() = try {
        // Find the authorization loader field that has the cached auth credentials
        val authorizationLoaderField = braintreeClient.javaClass
            .getDeclaredField("authorizationLoader")
            .apply {
                isAccessible = true
            }

        val authorizationField = authorizationLoaderField
            .type
            .getDeclaredField("authorization")

        // Get the current value of the authorizationLoader field so that we can overwrite it
        val authorizationLoader = authorizationLoaderField.get(braintreeClient)

        authorizationField
            .apply {
                isAccessible = true
                // Actually apply the nullification here so the credential is refetched on next getAuthorization request
                set(authorizationLoader, null)
            }
    } catch (e: Exception) {
        e.printStackTrace()
    }
```

I think the most straightforward solution to this would be to add a method to the interface for `ClientTokenProvider` along the lines of a `boolean fetchNewToken()` (name pending!) and is then used in the `AuthorizationLoader` code as such:

```
void loadAuthorization(@NonNull final AuthorizationCallback callback) {
        final boolean shouldForceClientTokenProviderUsage = clientTokenProvider != null && clientTokenProvider.fetchNewToken(); 
        if (authorization != null && !shouldForceClientTokenProviderUsage) {
            callback.onAuthorizationResult(authorization, null);
        } else if (clientTokenProvider != null) {
            clientTokenProvider.getClientToken(new ClientTokenCallback() {
                @Override
                public void onSuccess(@NonNull String clientToken) {
                    authorization = Authorization.fromString(clientToken);
                    callback.onAuthorizationResult(authorization, null);
                }

                @Override
                public void onFailure(@NonNull Exception error) {
                    callback.onAuthorizationResult(null, error);
                }
            });
        } else {
            String clientSDKSetupURL
                = "https://developer.paypal.com/braintree/docs/guides/client-sdk/setup/android/v4#initialization";
            String message = String.format("Authorization required. See %s for more info.", clientSDKSetupURL);
            callback.onAuthorizationResult(null, new BraintreeException(message));
        }
    }
```

Another option would be to just never use the cached value of `authorization` if `clientTokenProvider` is non-null, but that is probably a breaking change.

If the `BraintreeClient` could be swapped for the 3rd party clients, that is also an option (albeit more dangerous since there are so many touchpoints for those variables).

A final option is probably to expose a method / param on the braintree client that disables the cached authentication.

**Comment by sshropshire** [comment]
Hi @josephyanks thanks for using the Braintree SDK for Android. We appreciate this feedback!

Implementing a caching strategy is something we have on our roadmap, but we haven't prioritized the work yet. Technically creating a new client allows the cache to be cleared implicitly, since at the moment we only cache client tokens in memory as you pointed out.

In the short term, for this scenario `invalidateClientToken()` feels like a feature we could add for `ClientTokenProvider` integrations. Would that work? I don't have a timeline on when this will be available, but it is something we can prioritize.

**Comment by josephyanks** [comment]
That works for us - I can certainly also make a PR for you as well, if that helps.

**Comment by sshropshire** [comment]
Awesome! Yes please feel free. Once a PR is up we'll get it through our review process.

**Comment by josephyanks** [comment]
@sshropshire I added the two pr's, and can add test if you can point to one you prefer (or if changes should be made). I think I prefer the method directly on braintree client itself, since the client is what owns the authorization loader. I know above you mentioned the `invalidateClientToken()` method on the `ClientTokenProvider`, but the problem is that the `ClientTokenProvider` sits within the `AuthorizationLoader`, so any call to the provider won't actually impact the caching that the loader does until the next `getAuthorization` call. It's also strange to call invalidate in either PR since the you can't really invalidate if you passed in the initial client token value (and not a `ClientTokenProvider`).

Anyway, let me know, thanks.
