### ISSUE TITLE
Error:(19, 40) error: package com.braintreepayments.api.dropin does not exist in 2.0 beta version

### ISSUE THREAD

**Issue by sirvon** [braintree/braintree_android#55]
I'm not able to import

```java
 import com.braintreepayments.api.dropin.BraintreePaymentActivity;
```

using the 2.0 beta version...

**Comment by sirvon** [comment]
the correct compile statement is:
FIXED

```java
    compile 'com.braintreepayments.api:braintree:2+'
    compile 'com.braintreepayments.api:data:2.+'
    compile 'com.braintreepayments.api:drop-in:2.+'
```

**Comment by lkorth** [comment]
@sirvon those are the correct, the documentation with the correct dependency statements is going out later today. Note that the `data` dependency is only required if you with to use Braintree's fraud prevention.
