### ISSUE TITLE
BrainTreePaymentActivity not found 

### ISSUE THREAD

**Issue by Livinlawrence** [braintree/braintree_android#56]
I'm using 'com.braintreepayments.api:braintree:1+' but couldn't find the BrainTreePaymentActivity in that repository. In your documentation you are saying about calling the method below.
 (It is buggy).

public void onBraintreeSubmit(View v) {
  Intent intent = new Intent(context, BraintreePaymentActivity.class);
      .putExtra(BraintreePaymentActivity.EXTRA_CLIENT_TOKEN, "token");
  startActivityForResult(intent, 100);
}

So after writing a documentation like this and you are not providing the specified class, is really painful for developers. I'm using Android studio and I want to use your drop in UI. Is there any way for me to use the DropIn UI, not by switching to your package as stated " Unable to fined BraintreePaymentActivity Calass in Braintreen-api-1.2.7.jar #18"..

**Comment by lkorth** [comment]
Using `com.braintreepayments.api:braintree:1+` and `braintree-api-1.2.7.jar` are two very different dependencies. Yes, `BraintreePaymentActivity` does not exist in `braintree-api-1.2.7.jar`, the documentation states you must use `com.braintreepayments.api:braintree:1+`.
