### ISSUE TITLE
Update kount-data-collector 

### ISSUE THREAD

**Issue by spinnerx1** [braintree/braintree_android#569]
Currently library uses outdated [kount-data-collector](https://github.com/braintree/braintree_android/blob/master/BraintreeDataCollector/libs/kount-data-collector-3.2.jar) 

I'm kindly ask you to update it to use fresh version published in Jitpack:
https://developer.kount.com/hc/en-us/articles/4777351032084-How-to-Integrate-the-Device-Data-Collector-into-Mobile-Apps-using-Android-Gradle

In our project we already used this lib and now because of the different versions we struggle with a duplicated classes of this lib...

**Comment by sshropshire** [comment]
@spinnerx1 thanks for using the Braintree SDK for Android. We're considering removing Kount as a dependency in our next major version.

On the other hand, we have recently changed how Kount is referenced in our latest [4.12.1-SNAPSHOT](https://github.com/braintree/braintree_android#adding-it-to-your-project) build. Could you try out this SNAPSHOT version to see if your issue is resolved? A release will follow shortly once we have confirmation that lazy loading Kount resolves the issue.

**Comment by sshropshire** [comment]
@spinnerx1 oh got it. We are planning to remove Kount in our next major version. I don't have a timeline for when that will be, but we are prioritizing its removal.

**Comment by spinnerx1** [comment]
@sshropshire Remove completelly??? But we need it for our backend, to collect device data (recieve correlation_id field)
According to the docs:
https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/client-side/android/v4

**Comment by sshropshire** [comment]
@spinnerx1 you'll still receive a `correlation_id` via our SDK data collector. Kount is a 3rd party tool for the Braintree SDK and we are gradually phasing it out in favor of 1st party data collection.

**Comment by sshropshire** [comment]
Hey @spinnerx1 in version [4.15.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4140) we have a new `:PayPalDataCollector` module. It has the same interface as `:BraintreeDataCollector`, and removes Kount as a dependency internally.

If you replace a `DataCollector` instance with a `PayPalDataCollector` instance, is this issue resolved?

**Comment by spinnerx1** [comment]
@sshropshire yes, it should help! Thank you!

**Comment by sshropshire** [comment]
@spinnerx1 awesome! Closing this issue for now. Feel free to re-open, or start a new ticket if an issue arises.
