### ISSUE TITLE
No access with dropin UI classes

### ISSUE THREAD

**Issue by elainedizon** [braintree/braintree_android#57]
```java
public void onBraintreeSubmit(View v) {
  Intent intent = new Intent(context, BraintreePaymentActivity.class);
      .putExtra(BraintreePaymentActivity.EXTRA_CLIENT_TOKEN, TOKEN);
  startActivityForResult(intent, 100);
}
```

I am using `compile 'com.braintreepayments.api:braintree:1.7.4'` in gradle to use the library

Code block is from developers website. 
In version 1.7.3, I can import `BraintreePaymentActivity` in my code but during version 1.7.4, I cannot.

**Comment by lkorth** [comment]
Looking at the sha of `1.7.4`, [`BraintreePaymentActivity`](https://github.com/braintree/braintree_android/blob/fefae792a93eacab8ff743842a60754993a98d80/Drop-In/src/main/java/com/braintreepayments/api/dropin/BraintreePaymentActivity.java#L84) is indeed there. Have you ensured you're using `1.7.4`, resynced and cleaned the project?

**Comment by elainedizon** [comment]
Thank you @lkorth , I guess my AS bugged
