### ISSUE TITLE
Migrating to 3D Secure 2

### ISSUE THREAD

**Issue by Jake-Jiang** [braintree/braintree_android#576]
I saw the following message on Brtaintree for a customer who is unable to place an order
"Due to card network changes, 3DS1 transactions will see increasing decline rates in the coming months. By mid October 2022 all 3DS1 transactions will be declined. If you haven't already, please make sure to upgrade to 3DS2“
I check my code,I have call setVersionRequested and set param ThreeDSecureRequest.VERSION_2
` threeDSecureRequest.setVersionRequested(ThreeDSecureRequest.VERSION_2);`
I saw that the documentation sets a lot of user information to ThreeDSecurePostalAddress, such as givenName , surname. Are these fields required? Will the SDK automatically downgrade from VERSION_2 to VERSION_1 if this information is missing?

**Comment by sshropshire** [comment]
Hi @Jake-Jiang as long as you request `ThreeDSecureRequest.VERSION_2` as your preferred version, the SDK will perform 3DS using V2. I believe the additional fields like postal address, etc. are additional data points you may provide to help shift transaction liability to the card issuer.

I'll close this for now. If you have additional questions, feel free to reach out to our [support team](https://developer.paypal.com/braintree/help) for additional questions regarding 3D Secure.
