### ISSUE TITLE
Payload Validation failed

### ISSUE THREAD

**Issue by Jake-Jiang** [braintree/braintree_android#579]
Hello, user received the error "Payload Validation failed" when paying , I am confused by this error, could you provide more detailed information about this error? Thanks!

**Comment by sshropshire** [comment]
Hey @Jake-Jiang can you provide the SDK version, the module you're using, and some steps to reproduce the error?

**Comment by asen-ruuby** [comment]
Hi, customers received the same error in braintree-drop-in. I searched through Braintree documentation and I couldn't find anything about it.

**Comment by sshropshire** [comment]
Hi @asen-ruuby @Jake-Jiang we need more information. Please re-open an issue and follow the template for reporting and issue with the Braintree SDK. Closing this for now.
