### ISSUE TITLE
These keys are invalid: deviceData[correlation_id]

### ISSUE THREAD

**Issue by fordiego44** [braintree/braintree_android#584]
Hello, I am using braintree in Flutter, the integration is good. I created a button to active this function with this parameters:

```
var request = BraintreeDropInRequest(
      tokenizationKey: 'my sandbox of sandbox.braintreegateway', 
      collectDeviceData: true,
      paypalRequest: BraintreePayPalRequest(
        amount: '10.00',
        displayName: 'Raja Yogan'
      ),
      cardEnabled: true
    );
BraintreeDropInResult? result = await BraintreeDropIn.start(request);
```

this run very good ( show the view of paypal ) and when I do the buy generate this response: 
```
 result.paymentMethodNonce.nonce
 result.deviceData  -----> "deviceData":  {"correlation_id":"fb622ea087d046229735917c7082b09e"}
```

I send the "result.deviceData" to my backend node.js and run this code:
```
require...
const  gateway = new braintree.BraintreeGateway({
            environment: braintree.Environment.Sandbox,
            merchantId: '<Merchant ID of braintree>',
            publicKey:'<Public Key of braintree>',
            privateKey:'c525751fa60de4bdfddaa18c9e38452a'
        });
 
        gateway.transaction.sale({
            amount:'10.00',
            // paymentMethodNonce:nonceFromTheClient,
            paymentMethodNonce:'fake-paypal-one-time-nonce',
            deviceData:deviceData,    -----> I send 'result.deviceData' here
            options:{
                submitForSettlement:true
            }
        }, (err, result)=>{ ...
```
but I receive this error for node.js:
`These keys are invalid: deviceData[correlation_id]` 

I connect the braintree with paypal, and I realize the same steps in a video:
https://www.youtube.com/watch?v=E05uXmUh9t4
Help me please.

**Comment by fordiego44** [comment]
I think resolve the problem, I think is 'deviceData' ( in node.js) receive a  String and I put an object. 
How I pass to production, what parameter I change in my code ?

**Comment by hollabaq86** [comment]
👋 @fordiego44 the Android SDK is not designed for hybrid frameworks like Flutter in mind. As such we can't provide much support. If you have questions getting a Braintree account, please [contact Support](https://developer.paypal.com/braintree/help).
