### ISSUE TITLE
venmo:4.10.0

### ISSUE THREAD

**Issue by JeffYi2017** [braintree/braintree_android#595]
Use venmo. Return exception An unknown Android error occurred with the activity result API.

**Comment by sshropshire** [comment]
Hi @JeffYi2017 thanks for using the Braintree SDK for Android. Can you provide steps to reproduce the Venmo issue? I'd also recommend updating to the latest [4.16.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4160) version to see if the issue persists.
