### ISSUE TITLE
Failed to resolve: org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.6-2 

### ISSUE THREAD

**Issue by halfaHalfawy** [braintree/braintree_android#600]
my dependencies :

![image](https://user-images.githubusercontent.com/56086892/193853024-b0bd5e8e-bb17-4ac5-8221-5d82b3c4953d.png)

gradle sync :
<img width="606" alt="image" src="https://user-images.githubusercontent.com/56086892/193853363-e39ee2c7-1e27-4d2a-91ca-d0ddbaf23733.png">

errors when run : 
<img width="517" alt="image" src="https://user-images.githubusercontent.com/56086892/193853492-556e3a79-d74f-4d3a-9791-f16a7b03e736.png">

build .gradle app : 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/56086892/193853750-27f06dd5-ea98-47c3-8060-d8a98f2274ca.png">

**Comment by scannillo** [comment]
👋 Hello. You also need to include the CardinalCommerce Maven repository to your app-level gradle. See instructions in our README [here](https://github.com/braintree/braintree-android-drop-in#adding-it-to-your-project) and in our [Developer Docs](https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side/android/v4#generate-a-client-token).

In the future, only open an issue here if you think you've found an issue with our SDK. If you need help troubleshooting your integration, reach out to Braintree Support at https://help.braintreepayments.com.
