### ISSUE TITLE
Regression: PayPal browser result is delivered to wrong BraintreeFragment instance 

### ISSUE THREAD

**Issue by bramley-stride** [braintree/braintree_android#603]
### General information

* Environment: tested on sandbox
* Android Version and Device: tested on Android 11 and 12
* Braintree dependencies:
- com.braintreepayments.api:drop-in:5.3.0
- com.braintreepayments.api:braintree:3.19.0
 

### Issue description
We have a situation where we have different merchant ids for different payment methods on our checkout screen, for internal business reasons. We have encountered a problem where the wrong BraintreeFragment instance receives the result from the web browser.
Steps to reproduce:
1. Create a BraintreeFragment for a Google Pay payment.
1. Cancel the payment in the Google UI (or encounter an error like 'No Google Account' exists on the device/emulator)
1. Create a BraintreeFragment for a PayPal payment, with a different merchant ID.
1. User completes the payment details successfully in the browser, and is redirected back to our app
1. The wrong BraintreeFragment instance receives the result. The `BraintreeErrorListener` for the Google Pay fragment is called (with the error being `ErrorWithResponse (422): Merchant account not found` instead of the PayPal fragment instance.

I encountered a very similar issue, which I raised a few years ago in #274. The fix in v3.7.1 worked, so this is a regression. My workaround I describe there (manually removing the old fragment before creating the new one), works for this issue as well:
```java
String oldAuthorization = "...";
FragmentManager fm = getActivity().getSupportFragmentManager();
String tag = "BraintreeFragment" + "." + UUID.nameUUIDFromBytes(oldAuthorization.getBytes());
Fragment f = fm.findFragmentByTag(tag);
if(f!=null) try{
    fm.beginTransaction()
            .remove(f)
            .commitNowAllowingStateLoss();
    Log.d(TAG, "Removed existing Braintree fragment");
}catch (Exception e){
    Log.e(TAG, "Error removing existing Braintree fragment",e);
}
```

**Comment by scannillo** [comment]
👋 Hello @bramley-stride. V3 of `braintree_android` and V5 of `braintree-android-drop-in` are deprecated. As documented in our [Client SDK Deprecation policy](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy#status-deprecated), deprecated SDKs do not receive updates.

Can you first upgrade to the latest major version of both `braintree_android` (V4) and `braintree-android-drop-in` (V6) and let us know if this is still an issue?

**Comment by bramley-stride** [comment]
Thanks, I misunderstood what deprecated but supported means.
BraintreeFragment has been deleted in V4, so it's a non-trivial upgrade for us. That also means the issue is unlikely to exist in that version! Perhaps issues like these were part of the reason that was done.

We'll use my workaround for now, and schedule the migration in the next month.

**Comment by jaxdesmarais** [comment]
Thanks for providing an update. Please feel free to open a new issue if you run into any errors updating to v4 of the Android SDK.
