### ISSUE TITLE
Parallel, and Chained Payment

### ISSUE THREAD

**Issue by DevSubhashis** [braintree/braintree_android#62]
This is just a question. Do this sdk support Parallel and Chained Payment ?

**Comment by lkorth** [comment]
No, the current Android, iOS and JavaScript SDKs do not support parallel or chained payments. These SDKs are built on top of the PayPal REST APIs which do not currently support parallel or chained payments and until they do it will not be possible. Support for these features is something that is being looked into and may be supported in the future.
