### ISSUE TITLE
Error Processing Message Request

### ISSUE THREAD

**Issue by bm185178** [braintree/braintree_android#622]
**Integration Details (please complete the following information):**

    api 'com.braintreepayments.api:drop-in:6.4.0'
    implementation 'com.braintreepayments.api:data-collector:4.19.0'

**Describe the bug**
Make sure 3DS enabled

Drop in UI is failing on listener  dropInClient.setListener(object : DropInListener {
 ....
}

American Express is returning `Error Processing Message Request`

Every other card type works. Tested: VISA, DISCOVER, and etc

**To Reproduce**
1. Open dropin UI
2. Enter amex test card
3. Enter 3DS code
4. It gets an error message `Error Processing Message Request`

**Expected behavior**
Should work without failure

**Screenshots**
![Screen Shot 2022-11-14 at 12 26 40 PM](https://user-images.githubusercontent.com/66744335/201726078-acb0b2a6-5180-47d4-85e9-2915c03bb9aa.png)

**Additional NOTE:**
https://cardinaldocs.atlassian.net/wiki/spaces/CCen/pages/856064294/Centinel+Core+Error+Codes?showComments=true&showCommentArea=true

It seems 1001 from cardinal. Why?

**Comment by sshropshire** [comment]
@bm185178 thanks for using the Braintree SDK for Android.

Is this happening in Sandbox or Production? If Sandbox, are these test cards? And is this reproducible via our Demo application?

**Comment by bm185178** [comment]
Both environment - Sandbox and Production. Not sure about your demo app but it is happening with us. We have upgraded from v3 to v4 dropin. It still is happing with v4. We found this with v3.

**Comment by sshropshire** [comment]
@bm185178 understood. Do you have a test Amex Card for Sandbox that I can use to try and reproduce the issue?

**Comment by bm185178** [comment]
3774 0011 1111 115
3712 3480 6987 034
3711 1111 1111 114
3760 0000 0000 006

**Comment by bm185178** [comment]
Production I have used my personal one.

**Comment by bm185178** [comment]
It has been two weeks. Any update on this? OR resolutions?

**Comment by sshropshire** [comment]
@bm185178 apologies for the delay. Have you tried any of the cards listed [here](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing-go-live)? I don't recognize the test cards listed above that may be part of the issue in Sandbox.

**Comment by bm185178** [comment]
Tried 340000000001007 and 340000000001098 from [here](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing-go-live). Still having issue.

**Comment by bm185178** [comment]
1007 works with
```
    api 'com.braintreepayments.api:drop-in:6.5.0'
    implementation 'com.braintreepayments.api:data-collector:4.20.0'

**Comment by sshropshire** [comment]
Thanks @bm185178. We've had some test cards expire in the past. We appreciate the feedback here. Please feel free to file a new GitHub issue if this comes up again.
