### ISSUE TITLE
Broken error message

### ISSUE THREAD

**Issue by sdoward** [braintree/braintree_android#623]
**Integration Details (please complete the following information):**

https://developer.paypal.com/braintree/docs/guides/client-sdk/android/#browser-switch

* SDK/Library version:4.8.3
* Environment: Sandbox
* Android Version and Device: N/A

**Describe the bug**

I see the following error..

```
com.braintreepayments.api.BraintreeException: AndroidManifest.xml is incorrectly configured or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/#browser-switch for the correct configuration
```

But [the link](https://developers.braintreepayments.com/guides/client-sdk/android/#browser-switch) is broken

**Comment by scannillo** [comment]
👋 Hi @sdoward - thanks for bringing this issue to our attention.

The proper URL for that is https://developer.paypal.com/braintree/docs/guides/client-sdk/setup/android/v4#browser-switch-setup. We will update the outdated link in a PR soon.

**Comment by auxDK** [comment]
@scannillo HI
I have some problems in production but the file Manifest is configured right. 
In the test environment, it is ok.

`com.braintreepayments.api.BraintreeException: AndroidManifest.xml is incorrectly configured or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/#browser-switch for the correct configuration`

And another case if devices don`t have any browser we catch the same message 

Can you help me with this? 

**Activity from Manifest** 
```
<activity
            android:name=".Activity"
            android:exported="true"
            android:launchMode="singleTask" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="${applicationId}.braintree" />
            </intent-filter>
        </activity>
```

**Braintree bependencies**
```
   //Braintree
    implementation('com.braintreepayments.api:card:4.19.0')
    implementation 'com.braintreepayments.api:paypal:4.19.0'
    implementation 'com.braintreepayments.api:google-pay:4.19.0'
    implementation 'com.braintreepayments.api:three-d-secure:4.19.0'
```

**Comment by sshropshire** [comment]
Hey @sdoward and @auxDK can you share code snippets of your `BraintreeClient` instantiation?

**Comment by auxDK** [comment]
Hi @sshropshire  Is it enough?
```
internal class DemoPaypalPaymentDriver : BraintreeService<PaypalOrder>(), PayPalListener {

    private lateinit var payPalClient: PayPalClient
    private lateinit var braintreeClient: BraintreeClient

    override fun makeMerchant(paymentModel: PaypalOrder) {
        clientTokenProvider.onTokenNeeded = {    getToken(orderId, it)    }

        braintreeClient = BraintreeClient(fragment.requireActivity(), clientTokenProvider)
        payPalClient = PayPalClient(fragment, braintreeClient)
        payPalClient.setListener(this@DemoPaypalPaymentDriver)
    }

    override fun perform(paymentModel: PaypalOrder) {
        payPalClient.tokenizePayPalAccount(
            fragment.requireActivity(),
            PayPalRequestFactory.checkoutRequest()
        )
    }

    override fun onPayPalSuccess(payPalAccountNonce: PayPalAccountNonce) {
       
    }

    override fun onPayPalFailure(error: Exception) {
      
    }
}
```

**Comment by sshropshire** [comment]
@auxDK yup! That works. I wanted to make sure there wasn't a custom return url scheme defined. Do you have the prod and test versions of your app installed on the device / emulator at the same time? The manifest looks correct it's difficult to say what could be causing the issue.

If you like, you could step through `PayPalClient#tokenizePayPalAccount()` internally until the exception is called back. Then we could gather more information on why it's failing for your integration (and hopefully come up with a solution).

**Comment by hollabaq86** [comment]
Closing this issue since there hasn't been an update from OP in some time. Please feel free to make a new issue or [contact Support](https://developer.paypal.com/braintree/help) if you need additional assistance.
