### ISSUE TITLE
ThreeDSecureClient performVerification 

### ISSUE THREAD

**Issue by vakhileshwar** [braintree/braintree_android#625]
I am adding 3ds fro my card 
when I call ThreeDSecureClient performVerification with listeners, it does nothing
I dont see any error logs 

How do I know, about my configuration ?

My build gradle 
            implementation 'com.braintreepayments.api:card:4.20.0'
            implementation 'com.braintreepayments.api:three-d-secure:4.20.0'
            implementation 'com.braintreepayments.api:paypal:4.20.0'
            
         manifesto:
           <activity
            android:name=".ui.activity.CheckoutActivity"
            android:exported="true"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <data android:scheme="${applicationId}.braintree"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
            </intent-filter>
        </activity>

Code :

  init {

        braintreeClient = BraintreeClient(activity, payPalClientAuth)
        cardClient = CardClient(braintreeClient)
        dataCollector = DataCollector.getInstance()
        threeDSecureClient =  ThreeDSecureClient(activity, braintreeClient)
        threeDSecureClient.setListener(this)
    }

=====

       threeDSecureClient.performVerification(activity, threeDSecureRequest) { result, error ->
            result?.let { threeDSecureResult ->
                // examine lookup response (if necessary), then continue verification
                threeDSecureClient.continuePerformVerification(activity, threeDSecureRequest, threeDSecureResult)
            }
        }

Result: It throws error says 
**com.braintreepayments.api.AuthorizationException: Tokenization key authorization not allowed for this endpoint. Please use an authentication method with upgraded permissions**

**Comment by vakhileshwar** [comment]
How can I address : 
com.braintreepayments.api.AuthorizationException: Tokenization key authorization not allowed for this endpoint. Please use an authentication method with upgraded permissions

**Comment by sshropshire** [comment]
Hi @vakhileshwar thanks for using the Braintree SDK for Android.

3DS requires client token authorization. Here's a guide to [Client Tokens](https://developer.paypal.com/braintree/docs/guides/authorization/client-token) in the Braintree docs. Also take a look at implementing a [ClientTokenProvider](https://github.com/braintree/braintree_android/blob/master/v4.9.0%2B_MIGRATION_GUIDE.md#client-token-provider) when creating a `BraintreeClient`. This will allow your app to fetch a client token only when it is needed.

For additional help with your integration, please contact our [support team](https://developer.paypal.com/braintree/help).
