### ISSUE TITLE
FAILED_GET_GEO_REDIRECT_LINK error while redirecting back to the app

### ISSUE THREAD

**Issue by spinnerx1** [braintree/braintree_android#626]
**Integration Details (please complete the following information):**

* SDK/Library version: 4.16.0
* Environment: Production
* Android Version and Device: N/A
* Braintree dependencies:
com.braintreepayments.api:paypal:4.16.0
com.braintreepayments.api:data-collector:4.16.0

**Describe the bug**
Sometimes we receive this error from PayPal side on production:
`FAILED_GET_GEO_REDIRECT_LINK_EMPTY_RESPONSE_200`
It is happening when user confirmed PayPal method in the WebView and there is a redirection back to the app.
Please provide some details regarding this error code, what could be the issue. 
Thanks!

**Comment by spinnerx1** [comment]
@scannillo thank for replying! Yes, we raised same issue for iOS. 
We implemented it following [the official guide](https://developer.paypal.com/braintree/docs/guides/client-sdk/setup/android/v4) using [Browser switch setup](https://developer.paypal.com/braintree/docs/guides/client-sdk/setup/android/v4) so there is a WebView opening automatically and when user filled and confirmed PayPal details it's being redirected back to the app via registered in the app scheme, like `<data android:scheme="${applicationId}.braintree" />`
So we don't have more details, just receiving this error sometimes from PayPal: FAILED_GET_GEO_REDIRECT_LINK_EMPTY_RESPONSE_200
Same for iOS. Looks like something wrong with fetching geolocation data, but we tried with GPS turned off and could not reproduce it manually

**Comment by sshropshire** [comment]
Hey @spinnerx1 can you provide a video of the unexpected behavior to give more context?

**Comment by spinnerx1** [comment]
@sshropshire unfortunatelly no, we cannot reproduce it, just have it as a log from our users. And this error code should mean something, because it's coming from the PayPal side, but we cannot find any information so far:
`FAILED_GET_GEO_REDIRECT_LINK_EMPTY_RESPONSE_200`

**Comment by sshropshire** [comment]
@spinnerx1 I'm looking into this further. Does this error prevent your users from completing a transaction?

**Comment by spinnerx1** [comment]
@sshropshire Our investigations show, that this error message is a PayPal internal one and has no effect on the actual conversion. It is an error caused by the user for e.g. entering a wrong password during login process. In short, not critical after all.

**Comment by sshropshire** [comment]
@spinnerx1 good to know! Thanks for following up and resolving.
