### ISSUE TITLE
com.braintreepayments.api.BraintreeException: PayPal is not enabled.

### ISSUE THREAD

**Issue by vakhileshwar** [braintree/braintree_android#632]
We are using Brain Tree V4 in android application

Here is my code
```
        braintreeClient = BraintreeClient(activity, BrainTreeClientTokenProvider())
        payPalClient = PayPalClient(activity ,braintreeClient)
        payPalClient.setListener(this)
```

```

        val request = PayPalVaultRequest()
        request.merchantAccountId = maid
        request.localeCode = countryCode
        payPalClient.tokenizePayPalAccount(activity, request)
```

_I am ending off calling with  the error block saying,  com.braintreepayments.api.BraintreeException: PayPal is not enabled. See https://developers.braintreepayments.com/guides/paypal/overview/android/ for more information_

**Clint token and tokenatzaion keys were working fine with Android BrainTree v3 Please help me**

**Comment by sshropshire** [comment]
@vakhileshwar thanks for using the Braintree SDK for Android. This occurs when PayPal is not enabled for the current merchant account.

Are you using the same merchant account / client token authorization method in your `v3` integration?

**Comment by vakhileshwar** [comment]
Yes @sshropshire 
I am using same ame merchant account / client token authorization method in your v3 integration

**Comment by sshropshire** [comment]
@vakhileshwar can you run `BraintreeClient#getConfiguration()` in your app and set a breakpoint to debug your config? Make sure that `isPayPalEnabled` equals `true`.

You can also do this on your `v3` branch to compare and make sure that it's identical to your `v4` branch's configuration.

**Comment by sshropshire** [comment]
Hi @vakhileshwar any luck? Your app's gateway configuration needs PayPal to be enabled in order for DropIn to display the PayPal flow.

**Comment by hollabaq86** [comment]
I'm going to close this issue since we haven't heard back from OP. If you continue to encounter problems, please make a new issue or [contact Support](https://developer.paypal.com/braintree/help).
