### ISSUE TITLE
Brain Tree  Android v4API in multiple activities 

### ISSUE THREAD

**Issue by vakhileshwar** [braintree/braintree_android#637]
Hi we have Braintree Android v3 implemented in our application 

Now we are migrating to v4

Issue is

In Activity A
In this activity we have functionality to vault PayPal,

In Activity B
I need to perform ThreeDS verification on CC 

How can I handle these activities in manifesto.

In Activity B
I need to perform ThreeDS verification in CC  is implemented and its working fine.

Not sure how to configure Activity A and its Braintree calls backs

**Comment by sshropshire** [comment]
Hi @vakhileshwar this is possible using a `customUrlScheme`. Please take a look at our [migration guide](https://github.com/braintree/braintree_android/blob/master/v4.9.0%2B_MIGRATION_GUIDE.md#browser-switch) for more details. Closing this for now.
