### ISSUE TITLE
Provide a way to not require com.google.android.gms:play-services-wallet, so avoid GET_ACCOUNTS permission

### ISSUE THREAD

**Issue by jamesrgrinter** [braintree/braintree_android#64]
The current BraintreeApi module specifies com.google.android.gms:play-services-wallet as a dependency.

This means the App Manifest ends up with the GET_ACCOUNTS permission.

If we're not yet ready to use Android Pay (as most of us are not/unable to), then we ought to be able to avoid the com.google.android.gms:play-services-wallet dependency, and so avoid GET_ACCOUNTS.

**Comment by lkorth** [comment]
While the `com.braintreepayments.api:braintree` library does specificy `com.google.android.gms:play-services-wallet` as a dependency, it is marked as an optional dependency in [the pom](https://repo1.maven.org/maven2/com/braintreepayments/api/braintree/2.0.1/braintree-2.0.1.pom) and should not be included or have it's manifest merged with your app's manifest unless you require the Google Play Services dependency yourself.

I just created a new app and included the dependency `compile 'com.braintreepayments.api:braintree:2.+'`. Inspecting the merged manifest and the permissions on the device and `GET_ACCOUNTS` is not present. Do you have an isolated app that you can reproduce your issue in?

**Comment by lkorth** [comment]
Closing this as an old issue.

@jamesrgrinter if you have more information or can reproduce it, please reply and we will reopen this issues and investigate more.
