### ISSUE TITLE
Cannot read property 'locale' of undefined when authorizing new paypal account

### ISSUE THREAD

**Issue by hootener** [braintree/braintree_android#65]
We use the drop in ui to facilitate accepting payments with both credit cards and paypal. For the past few hours whenever a new user attempts to pay with paypal (i.e., they don't have a braintree token already, or haven't paid on the site with paypal before) the authorization process breaks. After clicking ''pay with paypal'' in the drop in UI, a new window is opened to authorize paypal with a URL of the following structure: 

https://checkout.paypal.com/pwpp/2.17.2/html/braintree-frame.html#<someUUID>

This page refuses to load and generates the following error in braintree-paypal-internal.min.js on line 7:

Uncaught TypeError: Cannot read property 'locale' of undefined

Since this is a minified JS file, I can't really provide any more detail than this. However, it doesn't appear that the issue has any workarounds (if the user wishes to pay with paypal, anyways), and I can't debug it since this authorization flow happens off-site. 

Any ideas what could be going on? I would really like to consider accepting payment via paypal...

**Comment by gbramwell** [comment]
@hootener: It sounds like you're actually using [braintree-web](https://github.com/braintree/braintree-web), not the Android library. We had an issue with the latest release, with some discussion [in this issue](https://github.com/braintree/braintree-web/issues/105). Long story short we'll have a fix out shortly.

**Comment by hootener** [comment]
You're right. Got hasty and accidentally filed this to braintree_android instead of web. Thanks for the link.
