### ISSUE TITLE
Staging URLs present in production code - Security Issue - For our Customer

### ISSUE THREAD

**Issue by gsci0001** [braintree/braintree_android#657]
**Integration Details (please complete the following information):**

* SDK/Library version: <3.20.0> or <3.17.0>
* Environment: <Production>
* Android Version and Device: <N/A>
* Braintree dependencies:
compile 'com.braintreepayments.api:data-collector:2.+'

**Describe the bug**
Description of what the bug is. Please include as many details as possible.

In the lib.android.paypal.com.magnessdk Stage URLS are present within the code. Our customers have a zero tolerance policy for staging urls in production mobile clients that are submitted via the Google Play Store and/or preloaded in the latest android devices. Would it be possible to remove the staging URLs from the library? Decompiling the the magnes jar it appears these URLs are located in  lib/android/paypal/com/magnessdk/c$h$d
        public static enum d {
            a("https://c.paypal.com/r/v1/device/mg-audit"),
            b("https://c.paypal.com/r/v1/device/client-metadata"),
            c("https://b.stats.paypal.com/counter.cgi"),
            d("https://c.paypal.com/r/v1/device/mg"),
            e("https://www.paypalobjects.com/rdaAssets/magnes/magnes_android_rac.json"),
            f("https://www.paypalobjects.com/rdaAssets/magnes/magnes_android_rec.json"),
            g("https://c.sandbox.paypal.com/r/v1/device/client-metadata"),
            h("https://c.sandbox.paypal.com/r/v1/device/s"),
            i("https://c.paypal.com/r/v1/device/s"),

STAGING URLS
>             j("https://www.stage2du13.stage.paypal.com/r/v1/device/mg-audit"),
>             k("https://www.stage2du13.stage.paypal.com/r/v1/device/mg");

Please let us know if it is possible to remove these URLs. Our customer will not submit the app to the playstore unless the URLs are removed.

**Comment by sshropshire** [comment]
Hi @gsci0001 version `3.x` of the SDK is technically [no longer supported](https://github.com/braintree/braintree_android#versions). Please upgrade to the latest [4.23.1](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4231) version of the SDK using our [migration guide](https://github.com/braintree/braintree_android/blob/master/v4.9.0%2B_MIGRATION_GUIDE.md). Feel free to open a separate issue if this is still a concern in the latest version.

**Comment by gsci0001** [comment]
@sshropshire this is an issue in every version... including 4.23.1 the issue is within the magnes SDK 
![magnes](https://user-images.githubusercontent.com/92740754/213732200-238af786-de1d-4ac1-bb7e-f36a73ec9c47.png)

**Comment by sshropshire** [comment]
Ok let us confirm then. This is a 3rd party library. Is there a specific security scan you're using to encounter this issue that we can use? We can forward the result to the team in charge of this dependency.

**Comment by gsci0001** [comment]
Hi @sshropshire , 
The tool they are using is proprietary (they will not reveal the scanning tool to us). This is a tier 1 telecom customer.

Scanning tool aside, inspecting magnes SDK it is very clear that staging URLs are present within the SDK and this breaches their security policy since "staging" urls are showing up in "production" application. The 3rd party that owns this library can easily find the URLs via search of their repo. 

https://www.stage2du13.stage.paypal.com/r/v1/device/mg-audit
https://www.stage2du13.stage.paypal.com/r/v1/device/mg

Thanks,
Greg Scillitani
Product Owner - Cloud
Synchronoss Technologies, Inc.

**Comment by sshropshire** [comment]
Got it. I'll reach out to the 3rd party to voice a concern. Will report here with more information as it becomes available.

**Comment by gjegadesh** [comment]
Thank you @sshropshire  for reaching out to the third-party library provider regarding this stage URL in the jar file. This is a big concern for us as well. I appreciate your help.

**Comment by gsci0001** [comment]
@sshropshire , while the stage URLs are our issue at the moment... It would also be great if we can inquire about the "sandbox" urls as well. Considering those are definitely non-prod.

**Comment by gjegadesh** [comment]
@sshropshire is there an update for this issue? Let us know of the timeline for a fix for this issue. Much thanks.

**Comment by gsci0001** [comment]
@sshropshire Can you please provide a contact who we can reach out to with support for this issue. We are up against a very tight deadline and considering the security implications of exposed staging URLs we need to get this resolved as soon as possible. Please feel free to send me contact information via email gsci0001@synchronoss.com

**Comment by crookedneighbor** [comment]
We just got confirmation from the team that owns that SDK that they will be prioritizing it to remove it later this month.

**Comment by gsci0001** [comment]
Thanks @crookedneighbor  for the update!

**Comment by sshropshire** [comment]
Hi @gsci0001 this has now been fixed in version [4.26.1](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4261).
