### ISSUE TITLE
Paypal Payment Nonce Not Getting Index 0 After Transaction

### ISSUE THREAD

**Issue by elainedizon** [braintree/braintree_android#66]
Tested using card nonces, and after transaction, the last used card nonce becomes the index 0 of the payment nonces list. But that is not the case when using a paypal nonce. After a paypal nonce transaction, it does not assign to index 0.

**Comment by lkorth** [comment]
@elainedizon I assume you are referring to using Drop-in. Is you question about when a user has an existing card in Drop-in and adds a PayPal account that the PayPal account does not show up first in the list? There is a [test for that case](https://github.com/braintree/braintree_android/blob/master/Drop-In/src/androidTest/java/com/braintreepayments/api/ListPaymentMethodNonceTest.java#L174). If you are referring to creating transactions on the server side and expecting the last transacted payment method to be the first payment method displayed in Drop-in, that is the current behavior only if the payment method was vaulted for that customer.

**Comment by lkorth** [comment]
Closing old issue.

@elainedizon if you have more details or questions, feel free to comment and we will respond and reopen.
