### ISSUE TITLE
Samsung Pay NoPaymentMethod Error

### ISSUE THREAD

**Issue by yarodevuci** [braintree/braintree_android#666]
```
@Override
public void onSamsungPayStartError(@NonNull Exception error) {
       //error = {JSONException@31792} "org.json.JSONException: No value for paymentMethod"
      //Error is here <---------------
 }
```
Implemented exact same code from the SDK docs and getting paymentMethod error. Did anyone else faced the same issue?
 Using latest SDK version:   implementation 'com.braintreepayments.api:samsung-pay:4.23.1'

**Comment by sshropshire** [comment]
Hi @yarodevuci thanks for using the Braintree SDK. Can you fill out the [full issue template](https://github.com/braintree/braintree_android/issues/new?assignees=&labels=&template=bug_report.md) for this bug with more information? I'll close this one and refer to the new one.

**Comment by yarodevuci** [comment]
@sshropshire done, can you reopen the issue?
