### ISSUE TITLE
SamsungPayStartError: PaymentMethod Error

### ISSUE THREAD

**Issue by yarodevuci** [braintree/braintree_android#668]
SDK/Library version: 4.23.1
Environment: Production
Android Version and Device: Android Studio Electric Eel | 2022.1.1; Samsung S20 with Android 11.0
Braintree dependencies:
implementation 'com.braintreepayments.api:card:4.23.1'
implementation 'com.braintreepayments.api:google-pay:4.23.1'
implementation 'com.braintreepayments.api:samsung-pay:4.23.1'
implementation 'com.braintreepayments.api:venmo:4.23.1'
implementation 'com.braintreepayments.api:data-collector:4.23.1'
implementation 'com.braintreepayments.api:paypal:4.23.1'
To Reproduce

Implemented Samsung Pay
2.Tap Pay, select card
See error below.
//error = {JSONException@31792} "org.json.JSONException: No value for paymentMethod"

```
@Override
public void onSamsungPayStartError(@NonNull Exception error) {
       //error = {JSONException@31792} "org.json.JSONException: No value for paymentMethod"
      //Error is here <---------------
 }
```

**Expected behavior**
Expected to end at onSamsungPayStartSuccess method.

**Comment by sshropshire** [comment]
Thanks @yarodevuci can you set a breakpoint where the error occurs and provide a stack trace? That should help pinpoint the issue.

**Comment by yarodevuci** [comment]
@sshropshire do you mean inside `onSamsungPayStartError` callback if fine ?

**Comment by yarodevuci** [comment]
```
stackTrace = {StackTraceElement[12]@32102} 
 0 = {StackTraceElement@32105} "org.json.JSONObject.get(JSONObject.java:398)"
 1 = {StackTraceElement@32106} "org.json.JSONObject.getJSONObject(JSONObject.java:618)"
 2 = {StackTraceElement@32107} "com.braintreepayments.api.SamsungPayNonce.fromJSON(SamsungPayNonce.java:27)"
 3 = {StackTraceElement@32108} "com.braintreepayments.api.SamsungPayInternalClient$3.onSuccess(SamsungPayInternalClient.java:144)"
 4 = {StackTraceElement@32109} "com.samsung.android.sdk.samsungpay.v2.payment.PaymentManager$1.handleMessage(PaymentManager.java:1183)"
 5 = {StackTraceElement@32110} "android.os.Handler.dispatchMessage(Handler.java:106)"
 6 = {StackTraceElement@32111} "android.os.Looper.loopOnce(Looper.java:226)"
 7 = {StackTraceElement@32112} "android.os.Looper.loop(Looper.java:313)"
 8 = {StackTraceElement@32113} "android.app.ActivityThread.main(ActivityThread.java:8751)"
 9 = {StackTraceElement@32114} "java.lang.reflect.Method.invoke(Native Method)"
 10 = {StackTraceElement@32115} "com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)"
 11 = {StackTraceElement@32116} "com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)"
```

@sshropshire  hopefully that helps.

**Comment by yarodevuci** [comment]
we had crashes reports on v2 and v3 SDK with same issue, we have spent a lot of time to upgrade to v4, now we have same exact error, no crash though. Instead error goes to `onSamsungPayStartError` callback. and users are not able to finish the transactions. We have tried selecting different cards and paypal inside Samsung Pay Sheet, still same error.

**Comment by sshropshire** [comment]
@yarodevuci yes it does thank you. Is there a chance you could reproduce and set a breakpoint here in [SamsungPayNonce.java](https://github.com/braintree/braintree_android/blob/13800b04a7ba0e98098a40c8e484274d11f63ab2/SamsungPay/src/main/java/com/braintreepayments/api/SamsungPayNonce.java#L25) and inspect the JSON data? It looks like "paymentMethod" is missing it isn't clear why.

**Comment by yarodevuci** [comment]
@sshropshire here is the content of the JSON file. yes it's missing paymentMethod. No idea why.

```
{
   "data":{
      "tokenizeSamsungPayCard":{
         "singleUseToken":{
            "id":"tokensam_bc_8wfwkk_bgzk7f_xdvbdq_fwyx97_9yz",
            "details":{
               "brand":"Mastercard",
               "brandCode":"MASTERCARD",
               "sourceCardLast4":"XXXX",
               "binData":{
                  "prepaid":"NO",
                  "healthcare":"NO",
                  "debit":"NO",
                  "durbinRegulated":"NO",
                  "commercial":"NO",
                  "payroll":"NO",
                  "issuingBank":"CAPITAL ONE, NATIONAL ASSOCIAT ION",
                  "countryOfIssuance":"USA",
                  "productId":"MPL"
               }
            }
         }
      }
   },
   "extensions":{
      "requestId":"8898c2e1-5515-4bdb-bf80-3e17ce6e4bd0"
   }
}
```

**Comment by yarodevuci** [comment]
maybe if that JSON parser had a default value to empty ? Or it's a mandatory field? We looked at the SP pay docs and there is no where to provide that field, and i don't think it's a user field, seems like an internal value for me.

**Comment by yarodevuci** [comment]
ok @sshropshire thank you for the assistance.

**Comment by yarodevuci** [comment]
Hi @sshropshire, should we wait for braintree SDK update? I saw pull request was done.

**Comment by sshropshire** [comment]
Hi @yarodevuci this update is now available in [4.25.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4250)!

**Comment by yarodevuci** [comment]
@sshropshire thanks for the update, we noticed that 4.25.0 requires Android SDK 33 and we are on 31. Is there an alternative way to pull this changes without updating SDK to 33?

**Comment by sshropshire** [comment]
There shouldn't be a requirement for Android 33. The minimum supported SDK is API level 21. Are you seeing a compilation error in Android studio?

**Comment by yarodevuci** [comment]
yes.

An issue was found when checking AAR metadata:

  1.  Dependency 'androidx.security:security-crypto:1.1.0-alpha04' requires libraries and applications that
      depend on it to compile against version 33 or later of the
      Android APIs.

      :app is currently compiled against android-31.

      Recommended action: Update this project to use a newer compileSdkVersion
      of at least 33, for example 33.

      Note that updating a library or application's compileSdkVersion (which
      allows newer APIs to be used) can be done separately from updating
      targetSdkVersion (which opts the app in to new runtime behavior) and
      minSdkVersion (which determines which devices the app can be installed
      on).

**Comment by sshropshire** [comment]
Thanks for this feedback. That library has been problematic. Making a PR to revert the version https://github.com/braintree/braintree_android/pull/674.

**Comment by yarodevuci** [comment]
@sshropshire so we are waiting for another SDK update version correct?

**Comment by yarodevuci** [comment]
@sshropshire Hi, unfortunately new update did not work out for us.
SamsungPayNonce.java has
`String last4 = details.getString("last4");
but the data in JSON has `sourceCardLast4` so because of that we have error again.

**Comment by sshropshire** [comment]
@yarodevuci thanks I just noticed this. I made a [separate PR](https://github.com/braintree/braintree_android/pull/676/) to address.
