### ISSUE TITLE
Unauthorized error when trying to get the drop-in configuration

### ISSUE THREAD

**Issue by 4gus71n** [braintree/braintree_android#671]
### Braintree SDK Version

2.2.7-2

### Environment

Production

### Android Version & Device

Android 13 & SM-G991U 

### Braintree dependencies

com.braintreepayments.api:drop-in:6.5.1

### Describe the bug

One of our users got this error 👇 

<img width="425" alt="image" src="https://user-images.githubusercontent.com/2055468/216436686-d430dc5a-8576-485a-8c24-6b24b1a8f4ab.png">

I see the exception gets triggered from Braintree but I don't understand why. 

This is how we initialize the DropIn in our Activity👇 

```
  private fun initDropInClient() {
    val tokenizationKey = getString(R.string.braintree_tokenization_key)
    val dropInRequest = DropInRequest()
    dropInRequest.isPayPalDisabled = true
    dropInClient = DropInClient(this, dropInRequest, tokenizationKey)
    dropInClient.setListener(this)
  }
```

The `DropInListener` triggers the `onDropInFailure(Exception)` and that's when we show the error message.

### To reproduce

Try to add a new payment method

### Expected behavior

Maybe we are missing some configuration or something, but this same user was able to use that exact same payment method through the web platform.

### Screenshots

It is suspiciously similar to this other issue 👇 
https://github.com/braintree/braintree_android/issues/155

But that one got fixed quite some time ago.

Let me know if there's any more data we can provide, thanks a lot! 🙇

**Comment by sshropshire** [comment]
Hi @4gus71n thanks for using the Braintree SDK for Android. Could you re-open this issue in the DropIn repo? I'll help troubleshoot once we're there.
