### ISSUE TITLE
Browser switch setup not needed when using Drop-In UI (v6)

### ISSUE THREAD

**Issue by xX7** [braintree/braintree_android#692]
### Is your feature request related to a problem? Please describe.

According to this Drop-In implementation documentation under the '3D Secure' section: [Setup and Integration](https://developer.paypal.com/braintree/docs/guides/drop-in/setup-and-integration) it is required to add the browser switch intent-filter to the App's manifest. This is clearly incorrect when only the Drop-In UI is in use, as the DropInActivity already defines this intent-filter as seen in the merged manifest. 

Furthermore the [Drop-In v6 migration guide](https://github.com/braintree/braintree-android-drop-in/blob/master/v6_MIGRATION_GUIDE.md)  also doesn't reference the browser switching at all.

This could lead to a potential confusion whilst implementing/migrating and only utilizing the Drop-In UI. At first glimpse, the in client v4 added freedom of specifying a custom browser-switch activity, results in following questions on how to connect this to the Drop-In UI eventually. 

Thanks!
Regards

### Describe the solution you'd like.

- Adjust the implementation guide of the Drop-In UI
- Add a note about the browser-switch in the Drop-In UI v6 migration guide

**Comment by sshropshire** [comment]
@xX7 thanks for using the Braintree SDK for Android and for providing this feedback. We'll look into this and update the docs with the correct information.

**Comment by sshropshire** [comment]
Hey @xX7 we're updating our documentation soon. I also made a pull request to update the migration guide.

**Comment by hollabaq86** [comment]
closing as this has been updated. If there are any remaining problems with the documentation let us know and we can re-open this!
