### ISSUE TITLE
java.lang.RuntimeException Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by nzakharchenko** [braintree/braintree_android#70]
After releasing application with included Braintree I start getting such error http://crashes.to/s/203287ac1bc. 

```compile "com.braintreepayments.api:braintree:2.1.0"```

```minSdkVersion 14```
```targetSdkVersion 23```
```compileSdkVersion 23```
```buildToolsVersion "23.0.2"```

**Comment by lkorth** [comment]
@nzakharchenko we're currently working on several large changes related to where this crash occurred. These changes should go out in the next minor release. I'll be sure to keep these issues updated.

**Comment by lkorth** [comment]
@nzakharchenko: we recently released version 2.2.0 with several changes to the areas you are seeing crashes, please let us know if you are still seeing any crashes in the new version.
