### ISSUE TITLE
How to verify CVV with existing card?

### ISSUE THREAD

**Issue by JammyZ** [braintree/braintree_android#701]
### Braintree SDK Version

4.26.1

### Environment

Production

### Android Version & Device

Google Pixel 5 - Android 13

### Braintree dependencies

com.braintreepayments.api:card:4.26.1,
com.braintreepayments.api:samsung-pay:4.26.1,
com.braintreepayments.api:paypal:4.26.1,
com.braintreepayments.api:local-payment:4.26.1,
com.braintreepayments.api:union-pay:4.26.1,
com.braintreepayments.api:data-collector:4.26.1,
com.braintreepayments.api:three-d-secure:4.26.1,
com.braintreepayments.api:google-pay:4.26.1,
com.braintreepayments.api:american-express:4.26.1,
com.braintreepayments:card-form:5.4.0']

### Describe the bug

I did not find how to verify CVV with existing card in Android SDK. Could you show me how to do it?

And another issue was when I added a real card with an invalid CVV, CardClient.tokenize still did not return an Error, but a card nonce returned. Is it expected behavior?

### To reproduce

None

### Expected behavior

None

**Comment by scannillo** [comment]
Hi @JammyZ thanks for using the Braintree Android SDK! This GH Issues form is only for if you've found bugs in our SDK.

If you need help troubleshooting your integration, reach out to[ Braintree Support](https://developer.paypal.com/braintree/help). Only open a GitHub issue if you've found an issue with our SDK.
