### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference

### ISSUE THREAD

**Issue by nzakharchenko** [braintree/braintree_android#71]
After releasing application with included Braintree I start getting such error http://crashes.to/s/8ff82d9c1d1. 

Here is not a lot of information, but maybe you could take a look inside what's going on.

```compile "com.braintreepayments.api:braintree:2.1.0"```

```minSdkVersion 14```
```targetSdkVersion 23```
```compileSdkVersion 23```
```buildToolsVersion "23.0.2"```

**Comment by lkorth** [comment]
@nzakharchenko we're currently working on several large changes related to where this crash occurred. These changes should go out in the next minor release. I'll be sure to keep these issues updated.

**Comment by lkorth** [comment]
@nzakharchenko: we recently released version 2.2.0 with several changes to the areas you are seeing crashes, please let us know if you are still seeing any crashes in the new version.
