### ISSUE TITLE
Retry limit has been exceeded

### ISSUE THREAD

**Issue by stwonary** [braintree/braintree_android#716]
### Braintree SDK Version

4.26.1

### Environment

Production

### Android Version & Device

Android OS Version 10, 11, 12, 13

### Braintree dependencies

```
    ext.braintree_version = '4.26.1'
```
```
    implementation "com.braintreepayments.api:card:$braintree_version"
    implementation "com.braintreepayments.api:data-collector:$braintree_version"
    implementation "com.braintreepayments.api:three-d-secure:$braintree_version"

    implementation "com.braintreepayments.api:american-express:$braintree_version"
    implementation "com.braintreepayments.api:google-pay:$braintree_version"
    implementation "com.braintreepayments.api:samsung-pay:$braintree_version"
    implementation "com.braintreepayments.api:paypal:$braintree_version"
    implementation "com.braintreepayments.api:venmo:$braintree_version"
```

### Describe the bug

Unable to proceed with the 3D Secure workflow when the SDK fails to retrieve the configuration from Braintree.

getting this error message:

```
Request for configuration has failed: Retry limit has been exceeded. Try again later., com.braintreepayments.api.q1: Retry limit has been exceeded. Try again later.
```

### To reproduce

Difficult to replicate, occurring sporadically with actual users

### Expected behavior

Capable of obtaining configuration from either cache or server to proceed with the 3D Secure workflow.

**Comment by hollabaq86** [comment]
@stwonary please [contact support](https://developer.paypal.com/braintree/help) referencing this issue and the following information to help them troubleshoot:
- your merchant ID
- timestamps of when you're seeing these error messages
- how are you setting up authorization of Braintree, via tokenization key or client token?
- if you're using a client token, are you re-using this client token for more than one 3DS verification?
