### ISSUE TITLE
Gradle Compilation Error

### ISSUE THREAD

**Issue by yenpei** [braintree/braintree_android#72]
I face this compilation error on Gradle build:

Error:(280, 30) error: method newInstance in class PaymentButton cannot be applied to given types;
required: Activity,int,PaymentRequest
found: Activity,PaymentRequest
reason: actual and formal argument lists differ in length

**Comment by lkorth** [comment]
That method was changed as part of 2.1.0, the Fragment was never added to the view because no container was specified. If you add an id of a view to your `PaymentButton#newInstance` method call, the Fragment wíll be added to the given view.
