### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by rok5ek** [braintree/braintree_android#720]
### Braintree SDK Version

4.27.1

### Environment

Sandbox

### Android Version & Device

Google Pixel 4 - Android 13.0

### Braintree dependencies

"com.braintreepayments.api:paypal-native-checkout:4.27.1"
"com.braintreepayments.api:paypal-data-collector:4.27.1"

### Describe the bug

When opening PayPal Native checkout a NPE crash occurs.

`java.lang.NullPointerException: Parameter specified as non-null is null: method com.paypal.checkout.config.CheckoutConfig.<init>, parameter returnUrl`

### To reproduce

1. Create client 
`val braintreeClient = BraintreeClient(context, tokenResponse.clientToken)`
`val payPalClient = PayPalNativeCheckoutClient(braintreeClient)`
2.  Launch flow
`braintreeClient.getConfiguration {`
`    payPalClient.launchNativeCheckout(activity, request)`
`}`

### Expected behavior

The value should not be null.

**Comment by sshropshire** [comment]
Hi @rok5ek thanks for using the Braintree SDK for Android. There may be a piece of our documentation that's missing for this feature. We're aware, and are looking to update the docs on our site.

In the meantime could you try adding the return url to your request object [like we do in our demo application](https://github.com/braintree/braintree_android/blob/710c04314e7eb736def62869b62010f2b7e30da3/Demo/src/main/java/com/braintreepayments/demo/PayPalNativeCheckoutRequestFactory.java#L22)?

**Comment by sshropshire** [comment]
@rok5ek the custom URL scheme will be the same as your app's `applicationId` e.g. `com.myawesomeapp.android://paypalpay`. Also please make sure to [register your app's return url](https://developer.paypal.com/braintree/docs/guides/paypal/native-checkout/android/v4#register-the-apps-returnurl).

**Comment by rok5ek** [comment]
@sshropshire Great, the app does not crash anymore, please update the public docs :).
