### ISSUE TITLE
implementing SDK on activity that does not extend from FragmentActivity

### ISSUE THREAD

**Issue by IndianaSloan** [braintree/braintree_android#721]
### Braintree SDK Version

6.9.0

### Environment

Sandbox

### Braintree dependencies

com.braintreepayments.api:drop-in:6.9.0

### Describe the bug

I am attempting to implement the Braintree SDK in my native android application and following the docs as provided [here](https://developer.paypal.com/braintree/docs/start/hello-client).

In order to create a new instance of the `DropInClient`, I notice that in each of the constructors that are _not_ deprecated, the only options are to either provide a `Fragment` or a `FragmentActivity`. However in my application I am using Jetpack Compose and following a single activity architecture. My single Activity does not extend from `FragmentActivity` and I am not using `Fragment`s in my application.

I see there is a `@Deprecated` constructor that takes a `Context` however it does not allow you to provide a `ClientTokenProvider` which I will need to do.

Is there some solution or workaround that can be implemented to support launching the Drop In SDK from within a project that is using Jetpack Compose?

### To reproduce

Implement the SDK in a project that does not extend `FragmentActivity`

### Expected behavior

A constructor provided that perhaps takes a `ComponentActivity` in order to create an instance of the `DropInClient`

**Comment by ajeihala** [comment]
Hello, @IndianaSloan . I'm curious if just changing from `ComponentActivity` to `FragmentActivity` in your application will fix all the problems without any drawbacks? Or there are some implications and more changes will be required?

**Comment by IndianaSloan** [comment]
@ajeihala seeing as I'm using Jetpack Compose for my UI and not using fragments, I am extending from `androidx.activity.ComponentActivity` so that I have access to the `setContent{}` API in order to render compose UI.

One consideration I could make is to extend from `FragmentActivity` instead and then wrap my root composable in a ComposeView, but I'm not sure if that will lead to other implications or problems. I had hoped there would be a way to either get an intent from the SDK that I could launch, or another solution available that wasn't so dependent to fragment implementation.

I'll look into this and let you know if it's a possible solution!

**Comment by scannillo** [comment]
👋 Hi @IndianaSloan - thanks for opening an issue with us. However, this is related to our Braintree Android Drop-In product (https://github.com/braintree/braintree-android-drop-in). Do you mind re-opening this issue in that repo so that it can get proper visibility?

**Comment by IndianaSloan** [comment]
Gotcha, my bad! Thanks for the redirect 👌🏻

**Comment by ajeihala** [comment]
@IndianaSloan a `FragmentActivity` extends `ComponentActivity`, so you can use them both the same way with `setContent{}` without changes. Am I missing something?
A `FragmentActivity` will have some extra features for fragment manipulation, etc. that you won't need but that's not a problem, I guess.
