### ISSUE TITLE
Getting BraintreeException instead of UserCanceledException for Venmo

### ISSUE THREAD

**Issue by aminezebdi** [braintree/braintree_android#734]
### Braintree SDK Version

4.28.0

### Environment

Sandbox

### Android Version & Device

Pixel 4

### Braintree dependencies

com.braintreepayments.api:paypal:4.28.0
com.braintreepayments.api:venmo:4.28.0
com.braintreepayments.api:data-collector:4.28.0

### Describe the bug

When I try to cancel the Venmo flow, I don't receive a `UserCanceledException` but instead I have a `BraintreeException` with this message: `An unknown Android error occurred with the activity result API.`

### To reproduce

1. Launch Venmo flow
2. After Venmo app starts, click on back

### Expected behavior

I should have a `UserCanceledException`.

**Comment by sshropshire** [comment]
Hey @aminezebdi thanks for using the Braintree SDK for Android. Can you provide which Android version you're using? I'm having trouble reproducing this issue on a Pixel 6 Pro running Android 13. The Venmo app overrides all back button presses and provides custom back button behavior.

**Comment by aminezebdi** [comment]
I'm using Pixel on Android 11.

I tried to debug further to understand what was happening. If it may help, I found the error was thrown with `VenmoActivityResultContract` when calling `parseResult`. When intent is null, a Venmo result is returned with the `BraintreeException` I mentioned.

**Comment by sshropshire** [comment]
@aminezebdi got it. Yeah the best thing we can do is be defensive. In #735 I refactored the parsing logic to only check for intent data when the result code is `RESULT_OK`.

**Comment by aminezebdi** [comment]
Hey @sshropshire , thank you for the quick response and quick fix.
It's a weird issue. I debugged and I see the intent is being created correctly in `VenmoActivityResultContract.createIntent` but is null when calling `parseResult`.

Anyway, checking if the intent is null only when `resultCode` is `RESULT_OK` make sense and will fix the issue on my side!

I guess the fix can expected in the next release ?

**Comment by sshropshire** [comment]
@aminezebdi yep! Once we get some team members to review and run our integration tests we'll deploy the changes. No strict timeline but it should be released soon.

**Comment by aminezebdi** [comment]
Tested with version v4.33.0 and it has been fixed. Closing the issue.
