### ISSUE TITLE
Keyboard not dismissed after 3DSecure authentication and returning to the app

### ISSUE THREAD

**Issue by RyanLinXiang** [braintree/braintree_android#739]
### Braintree SDK Version

6.8.1

### Environment

Sandbox

### Android Version & Device

Pixel XL

### Braintree dependencies

https://github.com/wgltony/react-native-braintree-dropin-ui

### Describe the bug

When successfully authenticated with 3DSecure and before returning to the app, keyboard is hiding and popping up again and will not be dismissed, even when user returns to the app.

This is however not always the case and happens only, when after clicking on the 'submit' button on the authentication website for 3DSecure the user is redirected back to the app too quickly.

I am using the React Native SDK of Braintree (https://github.com/wgltony/react-native-braintree-dropin-ui) which uses version 6.8.1 of this SDK.

### To reproduce

1. Checkout with a Visa 3DSecure card, e.g. 4000 0000 0000 1091
2. Get redirected to the test bank's authentication website
3. Returning to the app sometimes opens the keyboard again

### Expected behavior

When user returns to the app, keyboard should be dismissed.

**Comment by scannillo** [comment]
👋 Hi @RyanLinXiang - we don't offer official support for React Native at this time. That library is not developed by Braintree/PayPal engineers.

That said, if you're able to replicate using just the Braintree Drop In SDK, please re-open this issue in the corresponding [repository for Braintree Drop In](https://github.com/braintree/braintree-android-drop-in). A video of the issue would be helpful as well!
