### ISSUE TITLE
BraintreePaymentActivity leaks upon exit

### ISSUE THREAD

**Issue by bpollock-coursera** [braintree/braintree_android#74]
Hello, I have found the BraintreePaymentActivity to leak upon exit. 

== Steps ==
1. Launch MyPaymentFragment
2. Launch BrainTreePaymentActivity
3. BrainTreePaymentActivity Loads
4. Exit BrainTreePaymentActivity
5. LeakCanary heap dump

LeakCanary: https://github.com/square/leakcanary

== Gradle Integration ==

apply plugin: 'com.android.library'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
}

...

dependancies {
     ...
     compile 'com.braintreepayments.api:braintree:1.+'
     ...
}

== END ==
 
Compiles with BraintreepaymentsApiBraintree175Library and BraintreepaymentsCardForm201Library 

== Relevant Code ==

    public class MyPaymentFragment extends Fragment implements BrainTreeActivityHandler {
        public void onPurchaseProduct(clientToken, name, secondaryDescription, priceDisplay) {

            Intent intent = new Intent(this, BraintreePaymentActivity.class);
            Customization customization = new Customization.CustomizationBuilder()
                    .primaryDescription(name)
                    .secondaryDescription(secondaryDescription)
                    .submitButtonText(this.getString(R.string.purchase_for, priceDisplay))
                    .build();
            intent.putExtra(BraintreePaymentActivity.EXTRA_CUSTOMIZATION, customization);
            intent.putExtra(BraintreePaymentActivity.EXTRA_CLIENT_TOKEN, clientToken);
            this.startBrainTreeActivityForResult(intent, BRAINTREE_REQUEST_CODE);
        }

        @Override
        public void startBrainTreeActivityForResult(Intent intent, int requestCode) {
            startActivityForResult(intent, requestCode);
        }
    }

== LeakCanary Output ==

I/art﹕ hprof: heap dump "/storage/emulated/0/Download/leakcanary/suspected_leak_heapdump.hprof" starting...
D/LeakCanary﹕ In <redacted>.
D/LeakCanary﹕ * com.braintreepayments.api.dropin.BraintreePaymentActivity has leaked:
D/LeakCanary﹕ * GC ROOT thread java.lang.Thread.<Java Local> (named 'pool-26-thread-1')
D/LeakCanary﹕ * references java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.queue
D/LeakCanary﹕ * references array java.util.concurrent.RunnableScheduledFuture[].[0]
D/LeakCanary﹕ * references java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.callable
D/LeakCanary﹕ * references java.util.concurrent.Executors$RunnableAdapter.task
D/LeakCanary﹕ * references com.braintreepayments.api.dropin.BraintreePaymentActivity$2.this$0 (anonymous class implements java.lang.Runnable)
D/LeakCanary﹕ * leaks com.braintreepayments.api.dropin.BraintreePaymentActivity instance
D/LeakCanary﹕ [ 01-05 22:10:40.391 22156:28395 D/LeakCanary ]
    * Reference Key: 29178c9a-396c-497a-b118-132bd4557618
D/LeakCanary﹕ * Device: samsung samsung GT-I9500 ja3gub
D/LeakCanary﹕ * Android Version: 5.0.1 API: 21 LeakCanary: 1.3.1
D/LeakCanary﹕ * Durations: watch=5038ms, gc=315ms, heap dump=5845ms, analysis=49142ms
D/LeakCanary﹕ [ 01-05 22:10:40.391 22156:28395 D/LeakCanary ]
    * Details:
D/LeakCanary﹕ * Instance of java.lang.Thread
D/LeakCanary﹕ |   static $staticOverhead = byte[] [id=0x700e63b1;length=48;size=64]
D/LeakCanary﹕ |   static defaultUncaughtHandler = com.crashlytics.android.v [id=0x13052520]
D/LeakCanary﹕ |   static MAX_PRIORITY = 10
D/LeakCanary﹕ |   static MIN_PRIORITY = 1
D/LeakCanary﹕ |   static NANOS_PER_MILLI = 1000000
D/LeakCanary﹕ |   static NORM_PRIORITY = 5
D/LeakCanary﹕ |   static count = 4241
D/LeakCanary﹕ |   contextClassLoader = dalvik.system.PathClassLoader [id=0x76fcd790]
D/LeakCanary﹕ |   group = java.lang.ThreadGroup [id=0x7250dcc8]
D/LeakCanary﹕ |   inheritableValues = null
D/LeakCanary﹕ |   interruptActions = java.util.ArrayList [id=0x138f1540]
D/LeakCanary﹕ |   localValues = null
D/LeakCanary﹕ |   lock = java.lang.Object [id=0x135559f0]
D/LeakCanary﹕ |   name = java.lang.String [id=0x138f14e0]
D/LeakCanary﹕ |   parkBlocker = java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject [id=0x138f1280]
D/LeakCanary﹕ |   target = java.util.concurrent.ThreadPoolExecutor$Worker [id=0x132de670]
D/LeakCanary﹕ |   uncaughtHandler = null
D/LeakCanary﹕ |   id = 4238
D/LeakCanary﹕ |   nativePeer = -1922445312
D/LeakCanary﹕ |   stackSize = 0
D/LeakCanary﹕ |   daemon = false
D/LeakCanary﹕ |   hasBeenStarted = true
D/LeakCanary﹕ |   parkState = 3
D/LeakCanary﹕ |   priority = 5
D/LeakCanary﹕ * Instance of java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue
D/LeakCanary﹕ |   static $staticOverhead = byte[] [id=0x7024f4b9;length=8;size=24]
D/LeakCanary﹕ |   static INITIAL_CAPACITY = 16
D/LeakCanary﹕ |   available = java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject [id=0x138f1280]
D/LeakCanary﹕ |   leader = java.lang.Thread [id=0x13e7a740]
D/LeakCanary﹕ |   lock = java.util.concurrent.locks.ReentrantLock [id=0x13555760]
D/LeakCanary﹕ |   queue = java.util.concurrent.RunnableScheduledFuture[] [id=0x13e5c250;length=16]
D/LeakCanary﹕ |   size = 1
D/LeakCanary﹕ * Array of java.util.concurrent.RunnableScheduledFuture[]
D/LeakCanary﹕ |   [0] = java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask [id=0x136e3540]
D/LeakCanary﹕ |   [1] = null
D/LeakCanary﹕ |   [2] = null
D/LeakCanary﹕ |   [3] = null
D/LeakCanary﹕ |   [4] = null
D/LeakCanary﹕ |   [5] = null
D/LeakCanary﹕ |   [6] = null
D/LeakCanary﹕ |   [7] = null
D/LeakCanary﹕ |   [8] = null
D/LeakCanary﹕ |   [9] = null
D/LeakCanary﹕ |   [10] = null
D/LeakCanary﹕ |   [11] = null
D/LeakCanary﹕ |   [12] = null
D/LeakCanary﹕ |   [13] = null
D/LeakCanary﹕ |   [14] = null
D/LeakCanary﹕ |   [15] = null
D/LeakCanary﹕ * Instance of java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask
D/LeakCanary﹕ |   outerTask = java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask [id=0x136e3540]
D/LeakCanary﹕ |   this$0 = java.util.concurrent.ScheduledThreadPoolExecutor [id=0x13e5c200]
D/LeakCanary﹕ |   heapIndex = 0
D/LeakCanary﹕ |   period = 0
D/LeakCanary﹕ |   sequenceNumber = 56
D/LeakCanary﹕ |   time = 35326153473922
D/LeakCanary﹕ |   callable = java.util.concurrent.Executors$RunnableAdapter [id=0x135559e0]
D/LeakCanary﹕ |   outcome = null
D/LeakCanary﹕ |   runner = null
D/LeakCanary﹕ |   waiters = null
D/LeakCanary﹕ |   state = 0
D/LeakCanary﹕ * Instance of java.util.concurrent.Executors$RunnableAdapter
D/LeakCanary﹕ |   result = null
D/LeakCanary﹕ |   task = com.braintreepayments.api.dropin.BraintreePaymentActivity$2 [id=0x13555830]
D/LeakCanary﹕ * Instance of com.braintreepayments.api.dropin.BraintreePaymentActivity$2
D/LeakCanary﹕ |   this$0 = com.braintreepayments.api.dropin.BraintreePaymentActivity [id=0x1403e9e0]
D/LeakCanary﹕ * Instance of com.braintreepayments.api.dropin.BraintreePaymentActivity
D/LeakCanary﹕ |   static $staticOverhead = byte[] [id=0x134b3801;length=88;size=104]
D/LeakCanary﹕ |   static EXTRA_ANDROID_PAY_CART = java.lang.String [id=0x1362df60]
D/LeakCanary﹕ |   static EXTRA_ANDROID_PAY_IS_BILLING_AGREEMENT = java.lang.String [id=0x1362df80]
D/LeakCanary﹕ |   static EXTRA_CLIENT_TOKEN = java.lang.String [id=0x13726ae0]
D/LeakCanary﹕ |   static EXTRA_CUSTOMIZATION = java.lang.String [id=0x137269c0]
D/LeakCanary﹕ |   static EXTRA_ERROR_MESSAGE = java.lang.String [id=0x1362dfa0]
D/LeakCanary﹕ |   static EXTRA_PAYMENT_METHOD = java.lang.String [id=0x1362dfc0]
D/LeakCanary﹕ |   static EXTRA_PAYMENT_METHOD_NONCE = java.lang.String [id=0x1362dfe0]
D/LeakCanary﹕ |   static ON_PAYMENT_METHOD_ADD_FORM_KEY = java.lang.String [id=0x13755040]
D/LeakCanary﹕ |   static BRAINTREE_RESULT_DEVELOPER_ERROR = 2
D/LeakCanary﹕ |   static BRAINTREE_RESULT_SERVER_ERROR = 3
D/LeakCanary﹕ |   static BRAINTREE_RESULT_SERVER_UNAVAILABLE = 4
D/LeakCanary﹕ |   mAddPaymentMethodViewController = com.braintreepayments.api.dropin.AddPaymentMethodViewController [id=0x1406fbc0]
D/LeakCanary﹕ |   mBraintree = com.braintreepayments.api.Braintree [id=0x1360e040]
D/LeakCanary﹕ |   mCustomization = com.braintreepayments.api.dropin.Customization [id=0x134ad060]
D/LeakCanary﹕ |   mHavePaymentMethodsBeenReceived = java.util.concurrent.atomic.AtomicBoolean [id=0x12c03610]
D/LeakCanary﹕ |   mSavedInstanceState = android.os.Bundle [id=0x1345ee80]
D/LeakCanary﹕ |   mSelectPaymentMethodViewController = null
D/LeakCanary﹕ |   mActionBar = null
D/LeakCanary﹕ |   mActivityInfo = android.content.pm.ActivityInfo [id=0x12c4c230]
D/LeakCanary﹕ |   mActivityTransitionState = android.app.ActivityTransitionState [id=0x1330ebc0]
D/LeakCanary﹕ |   mAllLoaderManagers = android.util.ArrayMap [id=0x13591360]
D/LeakCanary﹕ |   mApplication = <redacted>
D/LeakCanary﹕ |   mComponent = android.content.ComponentName [id=0x12fca240]
D/LeakCanary﹕ |   mContainer = android.app.Activity$1 [id=0x12c030a0]
D/LeakCanary﹕ |   mCurrentConfig = android.content.res.Configuration [id=0x13f1e400]
D/LeakCanary﹕ |   mDecor = null
D/LeakCanary﹕ |   mDefaultKeySsb = null
D/LeakCanary﹕ |   mEmbeddedID = null
D/LeakCanary﹕ |   mEnterTransitionListener = android.app.SharedElementCallback$1 [id=0x7252ed30]
D/LeakCanary﹕ |   mExitTransitionListener = android.app.SharedElementCallback$1 [id=0x7252ed30]
D/LeakCanary﹕ |   mFeatureContextMenuListener = android.app.Activity$FeatureContextMenuListener [id=0x12c03e10]
D/LeakCanary﹕ |   mFragments = android.app.FragmentManagerImpl [id=0x13f1e320]
D/LeakCanary﹕ |   mHandler = android.os.Handler [id=0x13435960]
D/LeakCanary﹕ |   mInjectionManager = null
D/LeakCanary﹕ |   mInstanceTracker = android.os.StrictMode$InstanceTracker [id=0x12c03600]
D/LeakCanary﹕ |   mInstrumentation = android.app.Instrumentation [id=0x12c4fe80]
D/LeakCanary﹕ |   mIntent = android.content.Intent [id=0x13c98070]
D/LeakCanary﹕ |   mLastNonConfigurationInstances = null
D/LeakCanary﹕ |   mLauncherBooster = null
D/LeakCanary﹕ |   mLoaderManager = null
D/LeakCanary﹕ |   mMainThread = android.app.ActivityThread [id=0x12c241e0]
D/LeakCanary﹕ |   mManagedCursors = java.util.ArrayList [id=0x13435860]
D/LeakCanary﹕ |   mManagedDialogs = null
D/LeakCanary﹕ |   mMenuInflater = null
D/LeakCanary﹕ |   mMultiWindowStyle = com.samsung.android.multiwindow.MultiWindowStyle [id=0x12c11790]
D/LeakCanary﹕ |   mParent = null
D/LeakCanary﹕ |   mResultData = null
D/LeakCanary﹕ |   mSearchManager = null
D/LeakCanary﹕ |   mSubDecor = null
D/LeakCanary﹕ |   mSubWindow = null
D/LeakCanary﹕ |   mTitle = java.lang.String [id=0x130f9060]
D/LeakCanary﹕ |   mToken = android.os.BinderProxy [id=0x13434180]
D/LeakCanary﹕ |   mTranslucentCallback = null
D/LeakCanary﹕ |   mUiThread = java.lang.Thread [id=0x86fcbef0]
D/LeakCanary﹕ |   mVoiceInteractor = null
D/LeakCanary﹕ |   mWindow = com.android.internal.policy.impl.PhoneWindow [id=0x13cddf80]
D/LeakCanary﹕ |   mWindowManager = android.view.WindowManagerImpl [id=0x13437d20]
D/LeakCanary﹕ |   myName = java.lang.String [id=0x137264e0]
D/LeakCanary﹕ |   DEBUG_ELASTIC = true
D/LeakCanary﹕ |   isElasticEnabled = false
D/LeakCanary﹕ |   mCalled = true
D/LeakCanary﹕ |   mChangeCanvasToTranslucent = false
D/LeakCanary﹕ |   mChangingConfigurations = false
D/LeakCanary﹕ |   mCheckedForLoaderManager = true
D/LeakCanary﹕ |   mConfigChangeFlags = 0
D/LeakCanary﹕ |   mDefaultKeyMode = 0
D/LeakCanary﹕ |   mDestroyed = true
D/LeakCanary﹕ |   mDoReportFullyDrawn = false
D/LeakCanary﹕ |   mEnableDefaultActionBarUp = false
D/LeakCanary﹕ |   mFinished = true
D/LeakCanary﹕ |   mFlipfont = 0
D/LeakCanary﹕ |   mIdent = 832527157
D/LeakCanary﹕ |   mLoadersStarted = false
D/LeakCanary﹕ |   mPreventEmbeddedTabs = false
D/LeakCanary﹕ |   mResultCode = 0
D/LeakCanary﹕ |   mResumed = false
D/LeakCanary﹕ |   mStackedHeight = -1
D/LeakCanary﹕ |   mStartedActivity = false
D/LeakCanary﹕ |   mStopped = true
D/LeakCanary﹕ |   mSubWindowAdded = false
D/LeakCanary﹕ |   mTemporaryPause = false
D/LeakCanary﹕ |   mTitleColor = 0
D/LeakCanary﹕ |   mTitleReady = true
D/LeakCanary﹕ |   mVisibleBehind = false
D/LeakCanary﹕ |   mVisibleFromClient = true
D/LeakCanary﹕ |   mVisibleFromServer = true
D/LeakCanary﹕ |   mWindowAdded = true
D/LeakCanary﹕ |   mInflater = com.android.internal.policy.impl.PhoneLayoutInflater [id=0x12c11dc0]
D/LeakCanary﹕ |   mOverrideConfiguration = null
D/LeakCanary﹕ |   mResources = android.content.res.Resources [id=0x12c0d580]
D/LeakCanary﹕ |   mTheme = android.content.res.Resources$Theme [id=0x13437f80]
D/LeakCanary﹕ |   mThemeResource = 2131427534
D/LeakCanary﹕ |   mBase = android.app.ContextImpl [id=0x13218b20]
V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : png

**Comment by lkorth** [comment]
Thanks for the report @bpollock-coursera. I've fixed this leak and it will go out in the next release.

**Comment by lkorth** [comment]
1.7.6 was just released with a fix for this.
