### ISSUE TITLE
PayPal service crash

### ISSUE THREAD

**Issue by dsn5ft** [braintree/braintree_android#75]
Hi,

I'm an Android developer at Yodle and we just released the 1.4 version of our app last night (which has Braintree integration) and we’ve seen the crash below happen 4 times already for two different users (Android 4.1.1 & 5.0.2). We haven’t enabled the payments feature for any of our clients yet so we don’t think our payment processing code has even been called yet, but nonetheless I pasted an abbreviated version of our Braintree integration code below as well. I found a post online with a similar exception (http://stackoverflow.com/questions/29647861/android-paypal-integration) but we are never starting or using the PayPalService directly.

We are currently using version 1.7.5 of the Braintree Android SDK (com.braintreepayments.api:braintree:1.7.5) because when we looked at the 2.X version we couldn't figure out a way to tokenize a credit card without using a Fragment or Activity (we have an asynchronous CC processing service which looks like this: network call -> tokenize CC info with Braintree -> network call). Is there any way we can exclude the PayPal service if its not needed for tokenization or accomplish the same type of tokenization as below using the 2.X SDK if this issue has been resolved?

Thanks for your help!

Abbreviated code:
```
Braintree.setup(application, clientToken, new Braintree.BraintreeSetupFinishedListener() {
    @Override
    public void onBraintreeSetupFinished(boolean setupSuccessful, Braintree braintree, String errorMessage, Exception exception) {
        if (setupSuccessful) {
            braintree.addListener(new Braintree.PaymentMethodNonceListener() {
                @Override
                public void onPaymentMethodNonce(String paymentMethodNonce) {
                    // handle nonce
                }
            });
            braintree.addListener(new Braintree.ErrorListener() {
                @Override
                public void onUnrecoverableError(Throwable throwable) {
                    // handle exception
                }

                @Override
                public void onRecoverableError(ErrorWithResponse error) {
                    // handle exception
                }
            });
            braintree.tokenize(paymentMethodBuilder);
        } else {
            // handle exception
        }
    }
});
```

Crash log:
```
Fatal Exception: java.lang.RuntimeException
Unable to start service com.paypal.android.sdk.payments.PayPalService@32e8cf9e with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.yodle.android.lhfs/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.RuntimeException: Missing EXTRA_PAYPAL_CONFIGURATION. To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity.

Fatal Exception: java.lang.RuntimeException: Unable to start service com.paypal.android.sdk.payments.PayPalService@32e8cf9e with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.yodle.android.lhfs/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.RuntimeException: Missing EXTRA_PAYPAL_CONFIGURATION. To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity.
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2933)
       at android.app.ActivityThread.access$2100(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1385)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5273)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by java.lang.RuntimeException: Missing EXTRA_PAYPAL_CONFIGURATION. To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity.
       at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
       at com.paypal.android.sdk.payments.PayPalService.onStartCommand(Unknown Source)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2916)
       at android.app.ActivityThread.access$2100(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1385)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5273)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by lkorth** [comment]
The PayPal service is only started [in one place in the SDK](https://github.com/braintree/braintree_android/blob/1.x/BraintreeApi/src/main/java/com/braintreepayments/api/Braintree.java#L482), when `Braintree#startPayWithPayPal` is called. The stack trace looks pretty suspicious that it's trying to start `PayPalService` with an `Intent` action of MAIN.

```
com.paypal.android.sdk.payments.PayPalService@32e8cf9e with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.yodle.android.lhfs/com.paypal.android.sdk.payments.PayPalService
```

While in comparison, the `Intent` that we create to start the service looks like this:

```
Intent { cmp=com.braintreepayments.demo/com.paypal.android.sdk.payments.PayPalService (has extras) }
```
You may want to double check your `AndroidManifest.xml` and if there is nothing obviously wrong you can feel free to share it here and we'll take a look at it.

The next release of `1.x` will use maven for the PayPal SDK so you will be able to exclude PayPal from the SDK entirely if you are not using it with a simple exclusion in your dependencies.

**Comment by dsn5ft** [comment]
Thanks for the quick response! So I checked our manifest and there is no mention of PayPalService or anything related to that; however, I did some digging and found this in the [Braintree SDK manifest](https://github.com/braintree/braintree_android/blob/1.x/BraintreeApi/src/main/AndroidManifest.xml):

```
<service android:name="com.paypal.android.sdk.payments.PayPalService"
    android:exported="false" />
```

Also, I'm a little confused by the setup of these libraries on maven:

http://mvnrepository.com/artifact/com.braintreepayments.api/braintree-api
http://mvnrepository.com/artifact/com.braintreepayments.api/braintree

Is there a reason there will be another release of 1.x when there is already a 2.x version released?

**Comment by lkorth** [comment]
Ok, so you're getting the manifest declaration from manifest merging.

If you're not making any calls to `Braintree#startPayWithPayPal` then something else outside the SDK must be launching that `Intent`. I'll do some more looking around, but that method is the only place in the SDK that starts the service.

This SDK follows [SEMVER](http://semver.org/) and thus breaking changes are a new major version. 2.0 was a large breaking change, however we still maintain bug fixes and patch level changes on the 1.x branch.

**Comment by dsn5ft** [comment]
Gotchya, yeah we're definitely not making any calls to Braintree.startPayWithPayPal(). Do you know when we can expect the next release of 1.x with the maven PayPal dependency?

**Comment by lkorth** [comment]
It was just released, it should be available on maven soon.

**Comment by dsn5ft** [comment]
Awesome, it looks like there is a 1.7.6 version now so I will try this and let you know:

```
    compile('com.braintreepayments.api:braintree:1.7.6') {
        exclude group: 'com.paypal.sdk', module: 'paypal-partner-android-sdk'
    }
```

Also, should we be using the `braintree-api` or `braintree` artifact?

**Comment by lkorth** [comment]
Assuming you are only doing credit card tokenization, that will work. If you access any of the methods that use PayPal however, it will crash.

The `braintree` package contains our Drop-in UI, `braintree-api` only contains the networking and models for tokenizing payment methods. If you are using a custom integration and not Drop-in or the `PaymentButton` you will be fine using `braintree-api`.

**Comment by dsn5ft** [comment]
Understood, I will try switching to `braintree-api` in that case.

**Comment by lkorth** [comment]
@dsn5ft: has this solved the crash caused by the `PayPalService` for you?

**Comment by dsn5ft** [comment]
Hi @lkorth, we haven't seen the crash since we released the version of our app with the gradle exclusion, so so far so good. Thanks for your suggestion!
