### ISSUE TITLE
Additional translations for Drop-in UI

### ISSUE THREAD

**Issue by carn1x** [braintree/braintree_android#76]
Please can you advise whether you are open to translations of https://github.com/braintree/braintree_android/blob/master/Drop-In/src/main/res/values/strings.xml (specifically for values-zh-rTW , Traditional Chinese) via pull request? Or is there another channel by which we should submit translations?
Thanks!

**Comment by lkorth** [comment]
@carn1x thank you for the request. We actually have an internal team dedicated to translations and they have done the existing translations. We've had a few requests for traditional Chinese translations, I'll record this for some upcoming work we have on the UI and plan on adding translations to a future release.
