### ISSUE TITLE
Is AGP 8.x.x changes to R8 taken into account already?

### ISSUE THREAD

**Issue by mikkoville** [braintree/braintree_android#768]
### Is your feature request related to a problem? Please describe.

This is more of a question than a feature request.

Does Braintree sdks' already take into account breaking changes introduced in AGP 8.x.x ?

Most notably how R8 now works since it has `android.enableR8.fullMode` as `true` by default?
https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes

We have seen many of our 3rd party sdks crashing for R8 issues when we tried the update some months ago.

Here is one example by Adyen: https://github.com/Adyen/adyen-3ds2-android/issues/53

So do you already support new more strict proguard rules or do we need to wait for new release?

Thanks

### Describe the solution you'd like.

Make sure Braintree sdk works with all new defaults
https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes

**Comment by sarahkoop** [comment]
Hi @mikkoville - We are in the process of testing support for AGP 8. We will provide an update here once we have confirmed if any changes are required.

**Comment by sarahkoop** [comment]
Hi @mikkoville - The latest version of the SDK (currently `4.38.2`) should support AGP 8 with no additional changes required! Please feel free to re-open this if you experience any issues after upgrading.
