### ISSUE TITLE
onGooglePaySuccess/onGooglePayFailure not being called from GooglePayListener

### ISSUE THREAD

**Issue by ka7erina** [braintree/braintree_android#781]
### Braintree SDK Version

4.37.0

### Environment

Sandbox

### Android Version & Device

Google Pixel 6 pro

### Braintree dependencies

com.braintreepayments.api.googlepay
com.braintreepayments.api.three-d-secure
com.braintreepayments.api.three-d-secure
com.braintreepayments.api.braintree-core

### Describe the bug

When trying to initiate payment (after clicking confirm on the payment sheet) the SDK doesn't return any success/failure

### To reproduce

try to initiate payment,
payment sheet is created, 
click on confirm button on the payment sheet

### Expected behavior

in case of success, nonce should be returned
in case of error, error message should be returned

**Comment by scannillo** [comment]
👋 Hi @ka7erina, thanks for using the Braintree Android SDK.

For help troubleshooting your integration, consult our [Google Pay integration docs](https://developer.paypal.com/braintree/docs/guides/google-pay/client-side/android/v4) or reach out to[ Braintree Support](https://developer.paypal.com/braintree/help). This GitHub issue forum is for if you find bugs/issues with our SDK.

If you do find a bug, please feel free to open a new issue with us including code samples and steps to replicate.
