### ISSUE TITLE
data-collector:3.20.0 non compliant on play store

### ISSUE THREAD

**Issue by Baart** [braintree/braintree_android#783]
### Braintree SDK Version

3.21.0

### Environment

Both

### Braintree dependencies

    implementation 'com.braintreepayments.api:braintree:3.20.0'
    implementation 'com.braintreepayments.api:three-d-secure:3.20.0'
    implementation 'com.braintreepayments.api:data-collector:3.20.0'
    implementation 'com.braintreepayments.api:drop-in:5.3.0'

### Describe the bug

Publication of our updated app is rejected due to 
com.braintreepayments.api:data-collector collects persistent device identifiers

It suggest to switch to version com.braintreepayments.api:data-collector:4.31.0

### To reproduce

Publish an app on play store using data-collector:3.X.X

### Expected behavior

App must be accepted on play store using braintree V3 for android

### Screenshots

![rejected](https://github.com/braintree/braintree_android/assets/6576872/eb51fbc9-b9eb-4780-87b5-64bf9d93feff)

**Comment by Baart** [comment]
Note that switching to V4 may be considered, but does it means V3 is considered deprecated and unusable ?

**Comment by venkatasaisankar12** [comment]
Hello,

Same issue for me, 

We are using data-collecter version is ```3.15.0```
by using this we are getting device data using this fuction 

```
override fun getDeviceData(activity: AppCompatActivity, config: String): Result<String> {
        val braintreeFragment = BraintreeFragment.newInstance(activity, config)
        val deviceDataBox = ArrayBlockingQueue<Result<String>>(1)
        DataCollector.collectDeviceData(braintreeFragment) { deviceData ->
            print(deviceData)
            deviceDataBox.put(Result.Valid(deviceData))
        }
        return deviceDataBox.take()
    }
```
But, After upgrading data-collecter version - ```4.31.0```

getting error in this 

```
DataCollector.collectDeviceData(braintreeFragment) { deviceData ->
            print(deviceData)
            deviceDataBox.put(Result.Valid(deviceData))
}
```

Can anyone help on this? how we modify this with getting device data ?

**Comment by saisankar12** [comment]
> ### Braintree SDK Version
> 3.21.0
> 
> ### Environment
> Both
> 
> ### Android Version & Device
> _No response_
> 
> ### Braintree dependencies
> ```
> implementation 'com.braintreepayments.api:braintree:3.20.0'
> implementation 'com.braintreepayments.api:three-d-secure:3.20.0'
> implementation 'com.braintreepayments.api:data-collector:3.20.0'
> implementation 'com.braintreepayments.api:drop-in:5.3.0'
> ```
> 
> ### Describe the bug
> Publication of our updated app is rejected due to com.braintreepayments.api:data-collector collects persistent device identifiers
> 
> It suggest to switch to version com.braintreepayments.api:data-collector:4.31.0
> 
> ### To reproduce
> Publish an app on play store using data-collector:3.X.X
> 
> ### Expected behavior
> App must be accepted on play store using braintree V3 for android
> 
> ### Screenshots
> ![rejected](https://user-images.githubusercontent.com/6576872/266271606-eb51fbc9-b9eb-4780-87b5-64bf9d93feff.png)

@Baart is this working for you. Is that app approved if you are using 3.21.0

**Comment by saisankar12** [comment]
> ### Braintree SDK Version
> 3.21.0
> 
> ### Environment
> Both
> 
> ### Android Version & Device
> _No response_
> 
> ### Braintree dependencies
> ```
> implementation 'com.braintreepayments.api:braintree:3.20.0'
> implementation 'com.braintreepayments.api:three-d-secure:3.20.0'
> implementation 'com.braintreepayments.api:data-collector:3.20.0'
> implementation 'com.braintreepayments.api:drop-in:5.3.0'
> ```
> 
> ### Describe the bug
> Publication of our updated app is rejected due to com.braintreepayments.api:data-collector collects persistent device identifiers
> 
> It suggest to switch to version com.braintreepayments.api:data-collector:4.31.0
> 
> ### To reproduce
> Publish an app on play store using data-collector:3.X.X
> 
> ### Expected behavior
> App must be accepted on play store using braintree V3 for android
> 
> ### Screenshots
> ![rejected](https://user-images.githubusercontent.com/6576872/266271606-eb51fbc9-b9eb-4780-87b5-64bf9d93feff.png)

@Baart  Is this working for you. If it works help me out. What are the changes you made it.

**Comment by sarahkoop** [comment]
Closing this issue since versions `4.31.0` and later of the SDK are compliant. Please upgrade to `4.31.0` or higher and look through all versions of your app on all tracks that use the SDK. In all of those apps and tracks you need to update to `4.31.0` or higher to resolve this issue.

**Comment by Baart** [comment]
> > ### Braintree SDK Version
> > 3.21.0
> > ### Environment
> > Both
> > ### Android Version & Device
> > _No response_
> > ### Braintree dependencies
> > ```
> > implementation 'com.braintreepayments.api:braintree:3.20.0'
> > implementation 'com.braintreepayments.api:three-d-secure:3.20.0'
> > implementation 'com.braintreepayments.api:data-collector:3.20.0'
> > implementation 'com.braintreepayments.api:drop-in:5.3.0'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Describe the bug
> > Publication of our updated app is rejected due to com.braintreepayments.api:data-collector collects persistent device identifiers
> > It suggest to switch to version com.braintreepayments.api:data-collector:4.31.0
> > ### To reproduce
> > Publish an app on play store using data-collector:3.X.X
> > ### Expected behavior
> > App must be accepted on play store using braintree V3 for android
> > ### Screenshots
> > ![rejected](https://user-images.githubusercontent.com/6576872/266271606-eb51fbc9-b9eb-4780-87b5-64bf9d93feff.png)
> 
> @Baart Is this working for you. If it works help me out. What are the changes you made it.

Yes updating to 3.21.0 did work.

**Comment by davwheat** [comment]
We use 3.21.1 and just got this alert in the Play Console.

We downgraded from v4 a few months ago because we had a transaction failure rate of around 10-15% which coincided with our upgrade to v4 before that.
