### ISSUE TITLE
Paypal addition working differently on Firefox

### ISSUE THREAD

**Issue by sekai44** [braintree/braintree_android#784]
### Braintree SDK Version

4.27.0

### Environment

Production

### Braintree dependencies

private const val core = "com.braintreepayments.api:braintree-core:$braintreeVersion"
private const val paypal = "com.braintreepayments.api:paypal:$braintreeVersion"
private const val paypal_data_collector = "com.braintreepayments.api:paypal-data-collector:$braintreeVersion"

### Describe the bug

When default browser is set to **Chrome** all is working properly, webview opens -> select payment method -> redirected back to the app.

When default browser is set to **Firefox**, webview opens -> select payment method -> redirected back to the app, but the app is opened via deep-link: `braintree://onetouch/v1/success?token=EXAMPLE&ba_token=EXAMPLE`

Is this intented? If so, how to handle this success deep-link on Android?

### To reproduce

1. Set firefox as the default browser.
2. Try to add Paypal as a payment method.

### Expected behavior

Firefox redirects back to the app normally.

**Comment by sshropshire** [comment]
Hi @sekai44 thanks for using the Braintree SDK for Android. Is the deep link that returns while using Firefox the same as the one returned while using Chrome?

**Comment by sekai44** [comment]
Hi @sshropshire, thanks for the fast response.

Some additional details:

The deep-link is returned is the same. Though `PayPalClient.onPayPalSuccess` method is only invoked on Chrome. On Firefox it's as if when I select "Agree & continue" the app is restarted and only opens via the deep-link. (App is still present if I don't "Agree & continue" and just go back)

<img src="https://github.com/braintree/braintree_android/assets/85495518/3ec61748-9b43-4190-8930-95d79b840878" width=50% height=50%>

**Comment by sshropshire** [comment]
That's interesting it sounds like Android is recreating the deep link destination Activity when using Firefox.

Can you try changing the launch mode of your Activity to `singleTask` or `singleTop` and override `onNewIntent()`? We have an example of the [onNewIntent() override](https://github.com/braintree/braintree_android/blob/master/v4.9.0%2B_MIGRATION_GUIDE.md#paypal) in our migration guide.

**Comment by sekai44** [comment]
Changing from `singleTop` to `singleTask` resolves this issue 🎉

**Comment by sarahkoop** [comment]
Great - closing this issue as resolved.
