### ISSUE TITLE
User canceled PayPal error upon successful authorization

### ISSUE THREAD

**Issue by ab12346789** [braintree/braintree_android#789]
### Braintree SDK Version

4.38.2

### Environment

Sandbox

### Android Version & Device

Google Pixel 5, Samsung 22

### Braintree dependencies

implementation 'com.braintreepayments.api:paypal:4.38.2'
implementation 'com.braintreepayments.api:venmo:4.38.0'

### Describe the bug

I'm making a `PayPalVaultRequest`. It takes the user to the PayPal screens where I authenticate. And when it returns, the `onNewIntent` method gets triggered with the Intent containing the Braintree data. However, the PayPalListener callback `onPayPalFailure` gets triggered with an error of "User canceled PayPal" even after a successful authorization.

I originally put the tokenize call in the Fragment. The activity had the `onNewIntent`  method since my activity is a singleTask. And the fragment had the PayPalListener. The `onPayPalFailure` callback doesn't get called until that fragment is navigated to. 

Then I put the tokenize call in the Activity. I saw that the `onNewIntent`  method gets called twice - once with the Braintree Intent and one without it. After the 2nd time `onNewIntent` was called, then the `onPayPalFailure` method gets called with the cancel error.

Not sure if this is relevant, but when I go to Venmo and authorize there and it comes back to my app, I don't see the `VenmoListener` callbacks get called at all.

### To reproduce

1. Go to PayPal web browser.
2. Successfully login and click "Save and Continue"
3. See the logcat to see that User canceled PayPal message

### Expected behavior

The onPayPalSuccess callback should be called.

### Screenshots

<img width="883" alt="Screen Shot 2023-09-22 at 10 32 03 AM" src="https://github.com/braintree/braintree_android/assets/145782369/bf6ec8aa-4129-445d-802a-f5071f072afd">
<img width="630" alt="Screen Shot 2023-09-22 at 10 30 52 AM" src="https://github.com/braintree/braintree_android/assets/145782369/2d44250b-18e5-44ee-aba7-057ecfaa4b6f">

**Comment by sshropshire** [comment]
Hi @ab12346789 thanks for using the Braintree SDK for Android. Can you share a code snippet of your `onNewIntent()` implementation?

**Comment by ab12346789** [comment]
The second time its `null`.
The first time it looks like this at the end of it: `/onetouch/v1/success?token=EC-8TX67893HS0024459&ba_token=BA-7EG06789U5278082W`

**Comment by sshropshire** [comment]
That's interesting. I'm looking at this [stack post](https://stackoverflow.com/questions/11005657/android-onnewintent-uri-is-always-null) it appears `onNewIntent()` may be called with `data == null` at times.

Does it help if we conditionally call `setIntent(intent)` only when `intent.data != null`?

**Comment by ab12346789** [comment]
It does help!!! It is now returning to the onPayPalSuccess callback!!! However, I'm not sure if this will have other effects on our app. I am going to have to test that before I know that this is a viable solution.

**Comment by ab12346789** [comment]
I put in the `intent.data != null` check, but it seems when `setIntent(intent)` is called it triggers the `onNewIntent(intent: Intent)` method to be called in a loop.

**Comment by ab12346789** [comment]
Never mind! I got it!!!! Thanks for all your help.
