### ISSUE TITLE
Creating a tokenized braintree client using custom UI

### ISSUE THREAD

**Issue by rubiconsocial** [braintree/braintree_android#79]
I've already created a client token and want to tokenize a cardbuilder object using this client token. How do I create a braintree client with this client token to tokenize the cardbuilder object to get the nonce?

**Comment by lkorth** [comment]
Please see the documentation for [initializing the SDK](https://developers.braintreepayments.com/guides/client-sdk/android/#initialization) and [tokenizing a credit card](https://developers.braintreepayments.com/guides/credit-cards/client-side/android/). 

If you still have questions, please feel free to reach out to our support team at support@braintreepayments.com.

**Comment by rubiconsocial** [comment]
Unfortunately I am creating a custom UI to tokenize the cardbuilder. Is there any way I can create the nonce using the client token without having to use the activity and fragment callback? By the way I am using Xamarin.Android which is in c#.

**Comment by lkorth** [comment]
No, you must use the `BraintreeFragment` in version `2.0`.

**Comment by rubiconsocial** [comment]
Ok thank you. I have tried binding the braintree api but I am unable to get the BraintreeFragment. Any idea why?

**Comment by lkorth** [comment]
I don't have any experience with Xamarin, but I would imagine they have documentation about binding third party libraries with fragments.

**Comment by andrewescutia** [comment]
@rubiconsocial were you able to gain access to the BraintreeFragment within your binding?
