### ISSUE TITLE
Unable to obtain Postal Code from Google Pay

### ISSUE THREAD

**Issue by yarodevuci** [braintree/braintree_android#797]
### Braintree SDK Version

4.27.2

### Environment

Both

### Android Version & Device

Android 13

### Braintree dependencies

None

### Describe the bug

GooglePayRequest googlePayRequest = new GooglePayRequest();
        googlePayRequest.setTransactionInfo(TransactionInfo.newBuilder()
                .setTotalPrice(orderTotal)
                .setTotalPriceStatus(WalletConstants.TOTAL_PRICE_STATUS_FINAL)
                .setCurrencyCode(currencyCode)
                .build());

        googlePayRequest.setShippingAddressRequired(false);
        googlePayRequest.setPhoneNumberRequired(false);
        googlePayRequest.setBillingAddressRequired(true);
        googlePayClient.requestPayment(this, googlePayRequest);

All I can get is paymentMethodNonce. How to obtain postal address that is being requested in the googlePayRequest?
 googlePayClient.setListener(new GooglePayListener() {
                @Override
                public void onGooglePaySuccess(@NonNull PaymentMethodNonce paymentMethodNonce) {

### To reproduce

N/A

### Expected behavior

Expected a callback with requested details

**Comment by sarahkoop** [comment]
Hi @yarodevuci - The `PaymentMethodNonce` returned here can be of different payment method types. You can check if it's a `GooglePayCardNonce` or `PayPalAccountNonce`, and then cast to those types to access the Shipping Address details.

**Comment by yarodevuci** [comment]
@sarahkoop could you provide a sample code?
