### ISSUE TITLE
Unable to close BraintreePaymentActivity when user chooses Paypal in Drop-In UI

### ISSUE THREAD

**Issue by DarkMinstrel** [braintree/braintree_android#80]
Steps to reproduce:
1) launch BraintreePaymentActivity in this way:
`startActivityForResult(paymentRequest.getIntent(getActivity()), REQUEST_CODE_BRAINTREE);`
2) click "Change Payment Method" -> "Add New Payment Method"
3) click "Paypal", wait for browser to open
4) click Back button several times, until you get back to initial Braintree screen
5) click Back button once more to quit Braintree flow, it doesn't work

Library version: 2.1.2

Quick debugging shows that BraintreePaymentActivity.onBackButton() method prevents activity from finishing because mAddPaymentMethodViewController.isSubmitting() is returning true for some reason.

**Comment by DarkMinstrel** [comment]
Finally, I've found the reason of this bug. 

BraintreePaymentActivity.java from jCenter distribution (version 2.1.2):
```java
    @Override
    public void onCancel(int requestCode) {
        showAddPaymentMethodView();
    }
```
BraintreePaymentActivity.java from actual github project (version 2.1.2-SNAPSHOT) :
```java
    @Override
    public void onCancel(int requestCode) {
        showAddPaymentMethodView();
        mAddPaymentMethodViewController.endSubmit();
    }
```

This one line difference was the cause. So, the question is: when should we expect for a new build?

**Comment by lkorth** [comment]
Correct, this has already been fixed. The release of the next version is in progress and will be finished today.
