### ISSUE TITLE
Unnecessary import of support library in 2.2.0

### ISSUE THREAD

**Issue by DarkMinstrel** [braintree/braintree_android#81]
After updating your library to version 2.2.0, I get the following compilation error:
```
AGPBI: {"kind":"SIMPLE","text":"UNEXPECTED TOP-LEVEL EXCEPTION:","position":{},"original":"UNEXPECTED TOP-LEVEL EXCEPTION:"}
AGPBI: {"kind":"SIMPLE","text":"com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;","position":{},"original":"com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;"}
```

Most likely, it's caused by data-collector-2.2.0.jar, which mistakenly contains "android.support.annotation" package.

**Comment by lkorth** [comment]
Correct, support annotations are being incorrectly bundled into the jar and will conflict if you include support annotations in you app already. 2.2.1 is being released today to fix this.
