### ISSUE TITLE
BrainTree Card Form with Card I.O integration

### ISSUE THREAD

**Issue by HarryMMR** [braintree/braintree_android#82]
I am following Demo's CustomActivity and trying to integrate com.braintreepayments.cardform.view.CardForm with Card I.O. 
After scanning the card, I would like to populate CardForm's Card Number field and Expiry Field with the scan result. And I notice that there is no setter method in CardForm to populate with the scan result. There is getter only. Can you please add Setter methods? Or what's the best practice or workaround?

**Comment by HarryMMR** [comment]
Another issue is that BraintreeFragment.newInstance(getActivity( ), mAuthorization) fails to work when I use it in Fragment instead of Activity. There is no call back happening when I click on PURCHASE button. Please update your API to work with fragment.

**Comment by lkorth** [comment]
This issue probably belongs on the [android-card-form](https://github.com/braintree/android-card-form) repo. I've been looking at adding optional support for card.io to the card form so when card.io is present the form shows an icon for scanning.

Are you added and removing your listeners from the `BraintreeFragment` during your fragment's lifecycle?

>Braintree provides several interfaces which will be called when events occur. Any Braintree interface that BraintreeFragment's host Activity implements will be automatically managed for you. However, if you wish to manage the Braintree listeners yourself, use BraintreeFragment#addListener. In this case, be sure to use BraintreeFragment#removeListener to clean up in the event of a state change to avoid memory leaks.

https://developers.braintreepayments.com/guides/client-sdk/android/v2#register-listeners

**Comment by HarryMMR** [comment]
I added listener. From the log cat, I noticed that "public void onConfigurationFetched(Configuration configuration)" gets never called back in Fragment lifecycle. But when I ported the same code to Activity, onConfigurationFetched got called back and Purchase button works as normal. 

As for card-form, if we can do like 
cardForm.setCardNumber(xxxx);
cardForm.setExpirationMonth(xxx);
cardForm.setExpirationYear(xxx);
Then onActivityResult called back from Card I.O, we can populate the card form's text fields with the scan result.

**Comment by lkorth** [comment]
I've [created an issue](https://github.com/braintree/android-card-form/issues/5) for this in [android-card-form](https://github.com/braintree/android-card-form/).

If you are having other issues with using the SDK inside of a fragment, please create a separate issue.
