### ISSUE TITLE
-

### ISSUE THREAD

**Issue by jamesyorke** [braintree/braintree_android#822]

**Comment by desai-deep** [comment]
+1

**Comment by sarahkoop** [comment]
Hi @jamesyorke - the latest version of the Braintree SDK does not contain any reference to the Cardinal SDK below 2.2.7-5. We will investigate to confirm that 2.2.7-5 isn't causing the issue. 

Is it possible that there are other versions of your app or tracks that are still including a prior Braintree Android version? Please confirm that all versions of your app on all tracks have been updated to `4.39.0`.

**Comment by sarahkoop** [comment]
In the meantime - can anyone experiencing this issue provide a screenshot including the additional information about the rejection reason?

**Comment by jamesyorke** [comment]
Okay i've add another build to each track too. Lets wait and see.

Here's the full rejection email screen shot

<img width="728" alt="Screenshot 2023-11-08 at 15 38 06" src="https://github.com/braintree/braintree_android/assets/7203530/aa17f91b-0f92-452f-8c4a-028c12c8a406">


Appreciate the quick response 👍

**Comment by jamesyorke** [comment]
✅ Update: Seems like updating a build on each track on Google Play Console fixed the issue, even tho some of the tracks have been unused for ~1 year.

@Google Play - fix your bug where you reject an app because of an app on another track please!
