### ISSUE TITLE
Need API to TokenizationClient.getPaymentMethodNonces() 

### ISSUE THREAD

**Issue by deandalm** [braintree/braintree_android#84]
When TokenizationClient was changed to package access, we lost access to getPaymentMethodNonces().  So there is no public API to get a user's payment methods.

**Comment by lkorth** [comment]
@deandalm: thanks for reporting this issue. We're currently looking at adding a new class that exposes this and we will keep this issue updated when the feature is added.

**Comment by romanmikhailov** [comment]
@lkorth How can we get user's payment methods on client now?
Can I use wrapper for `TokenizationClient` as temporary solution?

**Comment by lkorth** [comment]
Support for this has been added and will go out in the next release.
