### ISSUE TITLE
Special characters error in PayPalRequest().billingAgreementDescription()

### ISSUE THREAD

**Issue by parespacochaga** [braintree/braintree_android#86]
I am using special characters in the billing agreement description.

PayPalRequest request = new PayPalRequest().billingAgreementDescription("Descripción de acuerdo");

And it crashes with this error:

com.braintreepayments.api.exceptions.UnexpectedException:
at com.braintreepayments.api.internal.HttpClient.parseResponse(HttpClient.java:249)
at com.braintreepayments.api.internal.BraintreeHttpClient.parseResponse(BraintreeHttpClient.java:121)
at com.braintreepayments.api.internal.HttpClient$2.run(HttpClient.java:197)

I have tried with different encodings, and it does not crash, but it is not showed correctly in PayPal pages. For example with URLEncoder.encode("descripción de acuerdo", "UTF-8")
PayPal shows: "descripci%C3%B3n+de+acuerdo"

**Comment by lkorth** [comment]
It's not crashing, it's returning an error to your error listener correct? Please see issue #85, special characters currently return a HTTP 400 response. We are looking at accepting the characters correctly or returning a more helpful error message.

**Comment by lkorth** [comment]
@parespacochaga this was fixed ae7e9adce6119f3558d5410ddf47b46cbb31772b and will go out in the next release.

**Comment by parespacochaga** [comment]
thank you Luke!
