### ISSUE TITLE
Couldn't find PaymentMethodCreatedListener for collecting billing addresses

### ISSUE THREAD

**Issue by tomoima525** [braintree/braintree_android#88]
Hi I have a question about collecting billing addresses from Paypal using Braintree SDK.
I was reading the instruction [here](https://developers.braintreepayments.com/guides/paypal/client-side/android/v2), but could not find PaymentMethodCreatedListener. 
Looks like this interface is not in the repository as well.
Do I need an extra library to use this feature?

I am using braintreepayment v2.2.3. Not using Drop-in. 
Thank you in advance.

**Comment by lkorth** [comment]
The docs are wrong and should actually read [`PaymentMethodNonceCreatedListener`](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/interfaces/PaymentMethodNonceCreatedListener.java). They have been corrected and the update will deployed in the next few days.
