### ISSUE TITLE
PaymentNonce created for PayPal when canceling out of flow

### ISSUE THREAD

**Issue by cdeonier** [braintree/braintree_android#90]
I'm observing that `PaymentMethodNonceCreatedListener` is being called with a `paymentMethodNonce` for Paypal when canceling out of the flow. Is it expected that a nonce will be created for both successful and failure cases? If so, should I be looking at something other than if a nonce was created for determining authorization of Paypal as a payment instrument?

Here were the steps I followed to recreate this:

1) In my flow, trigger:

```
        List<String> scopes = Collections.singletonList(PayPal.SCOPE_ADDRESS);
        PayPal.authorizeAccount(braintreeFragment, scopes);
```

2) Note that Paypal app opens up and see the login screen.
3) Don't enter email/password, and simply hit the "back" button.
4) Observe that `PaymentMethodNonceCreatedListener` is called with a `paymentMethodNonce` with the following data:

![paymentmanagerfragment java - android - --projects-android - android studio 2 1 preview 5 2016-04-13 17-23-40](https://cloud.githubusercontent.com/assets/726474/14513469/f31ffb20-019c-11e6-9e91-4f40cd1ed802.png)

**Comment by sdcoffey** [comment]
Hey @cdeonier, 

Thanks for letting us know. What version of the Braintree SDK are you using? We'll take a peek at this.

**Comment by cdeonier** [comment]
2.2.1, thanks!

**Comment by lkorth** [comment]
@cdeonier: this has been fixed and will go out in the next release.
