### ISSUE TITLE
screen count difference between Android and iOS

### ISSUE THREAD

**Issue by hannesa2** [braintree/braintree_android#91]
When I pay with Android I need 3 screens 
![screenshot_3x_2016-04-26-13-21-06](https://cloud.githubusercontent.com/assets/3314607/14818839/7235bba8-0bbf-11e6-914b-5e83fe6493b4.png)

But with iOS, the third screen is not visible, there are only two of them

Is there a way for Android to eliminate the third screen ?

**Comment by lkorth** [comment]
The iOS and Android SDKs are not completely identical in terms of their Drop-in UI. To eliminate the third screen you can build your own UI, or modify Drop-in to suit your needs. We are also working on a design refresh to Drop-in on both platforms that will bring also bring them to parity.
