### ISSUE TITLE
com.paypal.android.sdk:data-collector not compliant with Play store policy

### ISSUE THREAD

**Issue by grepx** [braintree/braintree_android#914]
### Braintree SDK Version

3.21.1

### Environment

Production

### Braintree dependencies

com.braintreepayments.api:braintree:3.21.1

### Describe the bug

Same issue as: https://github.com/braintree/braintree_android/issues/783 that issue was closed a while back so opened this new one. 
Google is threatening to not let us release a new app, saying:

> Paypal Data Collector com.paypal.android.sdk:data-collector: Consider upgrading to version com.braintreepayments.api:data-collector:3.21.0 of the SDK.

We previously dismissed this issue by upgrading from 3.21.0 to 3.21.1 but it appears to have come back as of today.

Looking at the dependency tree in Gradle we can see that 3.21.1 is still using com.paypal.android.sdk:data-collector and not com.braintreepayments.api:data-collector.

```
     +--- com.braintreepayments.api:braintree:3.21.1
     |    +--- androidx.appcompat:appcompat:1.2.0 -> 1.6.1 (*)
     |    +--- com.braintreepayments.api:google-payment:3.3.1
     |    +--- com.braintreepayments.api:core:3.21.1
     |    |    \--- com.braintreepayments:browser-switch:1.2.0
     |    |         +--- androidx.annotation:annotation:1.1.0 -> 1.7.0 (*)
     |    |         +--- androidx.appcompat:appcompat:1.2.0 -> 1.6.1 (*)
     |    |         \--- androidx.fragment:fragment:1.2.5 -> 1.6.2 (*)
     |    \--- com.paypal.android.sdk:paypal-one-touch:3.21.1
     |         +--- com.braintreepayments.api:core:3.21.1 (*)
     |         \--- com.paypal.android.sdk:data-collector:3.21.1
```

We currently do not have the resources as an organisation to spend on upgrading to the v4 version of the SDK (our use case is more complex than simple payments) and require a fix for the v3 version.

### To reproduce

Release an app to the Play store using com.braintreepayments.api:braintree:3.21.1

### Expected behavior

The app is not flagged by Google.

**Comment by sarahkoop** [comment]
Hi @grepx - the `com.paypal.android.sdk:data-collector` dependency is still correct for v3 (it was renamed in v4 and should be `com.braintreepayments.api:data-collector` then). An underlying dependency causing this non-compliance within the library was removed from `com.paypal.android.sdk:data-collector` to resolve the issue in version `3.21.0`. We are not aware of any new issues within this version. 

Can you confirm that all apps and all tracks have been updated to the compliant version?

Is there any other info in the email from Google that you can share?

**Comment by olessavluk** [comment]
Hi @sarahkoop
I've forwarded email from Google Play to your address( `s***p@paypal.com` ), hope it helps

**Comment by sarahkoop** [comment]
The email looks like potentially all apps and tracks have not been updated. Can you please try the following and confirm if the issue still exists:

Note: If you are seeing Google Play Store flag your APK after updating to the latest version of our SDK, please try following these steps:
1. Go to your Play Console
2. Select the app
3. Go to App bundle explorer
4. Select the violating APK/app bundle's App version at the top right dropdown menu, and make a note of which releases they are under
5. Go to the track with the violation. It will be one of these 4 pages: Internal / Closed / Open testing or Production
6. Near the top right of the page, click Create new release. (You may need to click Manage track first) If the release with the violating APK is in a draft state, discard the release
7. Add the new version of app bundles or APKs
Make sure the non-compliant version of app bundles or APKs is under the Not included section of this release
8. To save any changes you make to your release, select Save
9. When you've finished preparing your release, select Review release, and then proceed to roll out the release to 100%.
10. If the violating APK is released to multiple tracks, repeat steps 5-9 in each track

**Comment by achalkias** [comment]
I have the same problem with multiiple apps.

In all of them i import the braintree drop in like this 

  implementation 'com.braintreepayments.api:drop-in:3.+', {
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.com.paypal.android.sdk', module:'data-collector'
  }

and i received the same email saying 

Issue details

We found an issue in the following area(s):

Version code 22:
SDK: Paypal Data Collector com.paypal.android.sdk:data-collector (consider upgrading to version com.braintreepayments.api:data-collector:3.21.0)

But i suppose i already have the 3.21 version correct?

**Comment by grepx** [comment]
Hi @sarahkoop - I have checked all of the tracks and the message from Google specifically calls out our latest release in Production in the "Reviewed app bundles -> Affected app bundles and APKs" section of the Issue details. This is a release that I know is using `com.braintreepayments.api:braintree:3.21.1`

**Comment by olessavluk** [comment]
In my case issue was caused by old APK, thanks @sarahkoop for such a detailed steps! Newly uplaoded APK seems fine, maybe takes google some time to analyze and flag it - will update if happens later

**Comment by alvaro-ritual** [comment]
Hello, similar to @grepx , we have also received a policy warning on our latest release. I have double checked all tracks and everything is up to date. Our gradle dependency graph clearly shows we are only using `com.paypal.android.sdk:data-collector:3.21.1` as a dependency and no other version.

**Comment by sarahkoop** [comment]
Hi all - We have reached out to the Google privacy team to confirm if there is a new issue in the previously compliant version of the SDK and will post here when we have an update. In the meantime, I encourage everyone to follow the steps outlined in my previous comment and confirm if that resolves the issue!

**Comment by sarahkoop** [comment]
We've received an update that there were no changes to the rules made recently that would block a previously compliant SDK version, but the enforcement team *did* move forward with apps that have not fixed the underlying issue in 1 or more of their tracks in the last day or so. 

If you have confirmed that you are using a compliant version (`3.21.0`+, or `4.31.0`+), please double-check all tracks (even private and unpublished tracks) and then to submit an appeal to Play directly.
