### ISSUE TITLE
Android Pay Integration

### ISSUE THREAD

**Issue by sivailangos** [braintree/braintree_android#92]
I am trying to Integrate Android Pay in my app with Braintree Sandbox account, I followed the instructions from https://developers.braintreepayments.com/guides/android-pay/client-side/android/v2, using Custom Integration. I could detect that the User has Android Pay in mobile, then I try to start the MaskedWallet on button click, Immediately it opens Android Pay popup with "Loading" at Right side of the Popup and automatically get closed. It did not go to onActivityResult(). 

```java
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.provider.SyncStateContract;
import android.support.v7.app.ActionBar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import com.braintreepayments.api.AndroidPay;
import com.braintreepayments.api.BraintreeFragment;
import com.braintreepayments.api.exceptions.InvalidArgumentException;
import com.braintreepayments.api.interfaces.BraintreeResponseListener;
import com.braintreepayments.api.interfaces.TokenizationParametersListener;
import com.google.android.gms.common.api.GoogleApiClient;
import com.google.android.gms.wallet.Cart;
import com.google.android.gms.wallet.LineItem;
import com.google.android.gms.wallet.MaskedWallet;
import com.google.android.gms.wallet.MaskedWalletRequest;
import com.google.android.gms.wallet.PaymentMethodTokenizationParameters;
import com.google.android.gms.wallet.Wallet;
import com.google.android.gms.wallet.WalletConstants;

public class NotificationActivity extends AppCompatActivity {

    private BraintreeFragment mBraintreeFragment;
    private GoogleApiClient mGoogleApiClient;

    private int MASKED_WALLET_REQUEST_CODE = 888;

    @Override
    public void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_notification);

        final TextView mAndroidPayTxt = (TextView) findViewById(R.id.text_androidpay_status);

        try {
            mBraintreeFragment = BraintreeFragment.newInstance(this, "tokenizationKey");
            mBraintreeFragment.getGoogleApiClient(new BraintreeResponseListener<GoogleApiClient>() {
                @Override
                public void onResponse(GoogleApiClient googleApiClient) {
                    mGoogleApiClient = googleApiClient;
                }
            });
        } catch (InvalidArgumentException e) {

        }

        AndroidPay.isReadyToPay(mBraintreeFragment, new BraintreeResponseListener<Boolean>() {
            @Override
            public void onResponse(Boolean aBoolean) {
                if(aBoolean) {
                    mAndroidPayTxt.setText("Android Pay is enabled");
                } else {
                    mAndroidPayTxt.setText("Android Pay is disabled");
                }
            }
        });
    }

    public void startAndroidPay(View v) {

        AndroidPay.getTokenizationParameters(mBraintreeFragment, new TokenizationParametersListener() {

            @Override
            public void onResult(PaymentMethodTokenizationParameters parameters, Collection<Integer> allowedCardNetworks) {

                MaskedWalletRequest maskedWalletRequest =
                        MaskedWalletRequest.newBuilder()
                                .setPaymentMethodTokenizationParameters(parameters)
                                .addAllowedCardNetworks(allowedCardNetworks)
                                .setMerchantName("Google I/O Codelab")
                                .setCurrencyCode("USD")
                                .setCart(Cart.newBuilder()
                                        .setCurrencyCode("USD")
                                        .setTotalPrice("15.00")
                                        .addLineItem(LineItem.newBuilder()
                                                .setCurrencyCode("USD")
                                                .setDescription("Google I/O Sticker")
                                                .setQuantity("1")
                                                .setUnitPrice("15.00")
                                                .setTotalPrice("15.00")
                                                .build())
                                        .build())
                                .setEstimatedTotalPrice("15.00")
                                .build();

                Wallet.Payments.loadMaskedWallet(mGoogleApiClient, maskedWalletRequest, MASKED_WALLET_REQUEST_CODE);

            }
        });
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if(requestCode == MASKED_WALLET_REQUEST_CODE && resultCode == Activity.RESULT_OK) {
            MaskedWallet maskedWallet = (MaskedWallet) data.getParcelableExtra(WalletConstants.EXTRA_MASKED_WALLET);
            String googleTransactionId = maskedWallet.getGoogleTransactionId();
            String merchantTranasctionId = maskedWallet.getMerchantTransactionId();
            // maskedWallet.getBuyerShippingAddress(), etc...
        }

    }

}
```

I could not find any sample for it. What is the problem on this code?

**Note on Documentation:**

https://developers.braintreepayments.com/guides/android-pay/client-side/android/v2, there are some wrong code in this documentation, In masked walled snippet, please change ```
Wallet.Payments.loadMaskedWallet.(mGoogleApiClient, maskedWalletRequest, MASKED_WALLET_REQUEST_CODE);```
 to 
```Wallet.Payments.loadMaskedWallet(mGoogleApiClient, maskedWalletRequest, MASKED_WALLET_REQUEST_CODE);```

 and 
```if (requestCode == MASKED_WALLET_REQUEST_CODE && resultCode = Activity.RESULT_OK) {``` 
to 
```if (requestCode == MASKED_WALLET_REQUEST_CODE && resultCode == Activity.RESULT_OK) {``` 

below that.

**Comment by lkorth** [comment]
You are almost certainly running into a validation error or other error from Android Pay. Run `adb logcat` and watch the logs when the Android Pay dialog appears and dismisses it self, it should log an error code and possibly a reason.

The [demo app](https://github.com/braintree/braintree_android/tree/master/Demo) contains a few different examples of an Android Pay integration that you can also reference.

Thanks for pointing out the syntax issues in the docs, they have been corrected and will be released shortly.

**Comment by sivailango** [comment]
```
Request Code: 888 Result Code: 1 Error Code: 405
Request Code: 1 Result Code: 1 Error Code: 405
````
I am getting this one. What is the error?

**Comment by lkorth** [comment]
That is a [`ERROR_CODE_MERCHANT_ACCOUNT_ERROR`](https://developers.google.com/android/reference/com/google/android/gms/wallet/WalletConstants.html#ERROR_CODE_MERCHANT_ACCOUNT_ERROR). Are you making these requests in sandbox or production?

**Comment by sivailango** [comment]
I am making this request from Sandbox.

**Comment by lkorth** [comment]
I've reached out to Google about this error. I'll update this issue when I have more information.

**Comment by lkorth** [comment]
Would it be possible to provide a copy of the logs from the time you click the button to start Android Pay up until the Android Pay dialog is dismissed?

**Comment by sivailangos** [comment]
04-26 09:28:39.253 17209-17209/io.cambi D/ERROR: java.lang.Exception: Request Code: 888 Result Code: 1 Error Code: 405
04-26 09:28:39.253 17209-17209/io.cambi D/ERROR: java.lang.Exception: Request Code: 1 Result Code: 1 Error Code: 405

**Comment by lkorth** [comment]
Is that filtered at all? I would expect somewhere between 20-100 lines of logs when that dialog is opened and closed.

**Comment by sivailangos** [comment]
04-26 11:19:27.262 3278-3278/io.cambi I/GMPM: App measurement is starting up, version: 8487
04-26 11:19:27.262 3278-3278/io.cambi I/GMPM: To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
04-26 11:19:27.275 3278-3278/io.cambi E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
04-26 11:19:27.275 3278-3278/io.cambi E/GMPM: Scheduler not set. Not logging error/warn.
04-26 11:19:27.346 3278-3590/io.cambi E/GMPM: Uploading is not possible. App measurement disabled
04-26 11:19:27.625 3278-3292/io.cambi W/art: Suspending all threads took: 6.208ms
04-26 11:19:27.647 3278-3292/io.cambi I/art: Background sticky concurrent mark sweep GC freed 30337(3MB) AllocSpace objects, 66(1852KB) LOS objects, 24% free, 17MB/23MB, paused 6.666ms total 46.345ms
04-26 11:19:27.767 3278-3604/io.cambi D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-26 11:19:27.803 3278-3604/io.cambi I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
04-26 11:19:27.810 3278-3604/io.cambi I/OpenGLRenderer: Initialized EGL, version 1.4
04-26 11:19:49.536 3278-3278/io.cambi V/TDCollateJSON: SQLite3 handle is -1636323840
04-26 11:19:49.714 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@4303855 changed.
04-26 11:19:49.718 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@2667d09 changed.
04-26 11:19:49.762 3278-3604/io.cambi V/RenderScript: 0x9dfb4000 Launching thread(s), CPUs 4
04-26 11:19:50.495 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@2667d09 changed.
04-26 11:19:51.194 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@4303855 changed.
04-26 11:19:51.912 3278-3278/io.cambi W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
04-26 11:19:53.201 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@4303855 changed.
04-26 11:19:53.202 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@4303855 changed.
04-26 11:19:53.714 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@4303855 changed.
04-26 11:19:54.834 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@4303855 changed.
04-26 11:19:55.498 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@2667d09 changed.
04-26 11:19:55.573 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@2667d09 changed.
04-26 11:19:55.637 3278-3604/io.cambi D/OpenGLRenderer: endAllStagingAnimators on 0xa01fdc80 (NavigationMenuView) with handle 0xb073ecd0
04-26 11:19:59.837 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@4303855 changed.
04-26 11:19:59.925 3278-4165/io.cambi D/SyncGateway: Replication : com.couchbase.lite.replicator.Replication@4303855 changed.
04-26 11:20:02.013 3278-3278/io.cambi D/ERROR: java.lang.Exception: Request Code: 1 Result Code: 1 Error Code: 405

**Comment by lkorth** [comment]
```
04-26 11:19:27.275 3278-3278/io.cambi E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
```

seems very suspect. Have you included Google Play Services Wallet or just Google Play Services as a dependency in your `build.gradle`

```groovy
compile 'com.google.android.gms:play-services-wallet:8.4.0'
```

and in your `AndroidManifest.xml`?

```xml
<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />
```

**Comment by sivailangos** [comment]
I didn't not add Google services json,  but I have included every thing you mentioned.

**Comment by pamalraj** [comment]
Thanks for trying to help us. 

To be clear, we have these in build.gradle:
```
compile 'com.google.android.gms:play-services:8.4.0'
compile 'com.google.android.gms:play-services-wallet:8.4.0'

```
This in Android manifets
```
<meta-data android:name="com.google.android.gms.wallet.api.enabled"
        `android:value="true"/>

```

**Comment by lkorth** [comment]
Are you using other Google Play services other than for Android Pay? If not, I would recommend removing them to reduce the scope of the issue.

Can you confirm that the tokenization key that you are using is indeed for sandbox? I would expect this error if the tokenization key was a production key. Also, if you wouldn't mind sharing your merchant account id and app package name by emailing support@braintreepayments.com we can look into the requests further to try to see what is happening.

**Comment by pamalraj** [comment]
The Tokenization key that we are using is for Sandbox

The only other Google service we are using is Google Maps.

Earlier this morning, I sent the support team an email with the entire code, background/context, our merchant id. Waiting for a response.

**Comment by sivailangos** [comment]
Should we really include google-services.json? 
```
dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'
        classpath 'com.google.gms:google-services:2.0.0-alpha2'    
}
```

Thisi is our build.gradle (Module level)

**Comment by lkorth** [comment]
Could you verify that the final merged manifest for you app contains the manifest declaration?

```
<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true"/>
```

According to server logs this appears to be the issue, however it could have been from an earlier request that was missing this and it's now a red herring.

**Comment by sivailangos** [comment]
@lkorth We found the problem, we misplaced the <meta-data>, moved it into <application> context in Andorid Manifest and it works. Thanks for your help.
