### ISSUE TITLE
Android Pay: Unrecognized app

### ISSUE THREAD

**Issue by sivailangos** [braintree/braintree_android#93]
We are on Braintree Sandbox mode with Android Pay and enabled the permissions in Android Manifest file `<uses-permission android:name="com.android.vending.BILLING" />`, we could see that there is a warning message on top of Android Pay screen, please see the screenshot

![screenshot_20160509-094138_960 1](https://cloud.githubusercontent.com/assets/17606063/15120640/4273ccb4-1634-11e6-891e-c86760267992.png)

What will we need to do? Are we missing anything?

**Comment by lkorth** [comment]
You do not need `<uses-permission android:name="com.android.vending.BILLING" />` for Android Pay.

This message appears for every app that is using the Android Pay test environment and is not production signed. It is not an issue unless you're seeing it in production.

**Comment by pamalraj** [comment]
Thanks! We will try the production account and see how it goes

**Comment by lkorth** [comment]
Do note you will only be able to make a `MaskedWalletRequest` in production if you have been enabled in the Braintree Gateway and by Google.

**Comment by pamalraj** [comment]
Duly noted...thanks again
