### ISSUE TITLE
Braintree - Paypal not working anymore if AppId contains Capital Letters

### ISSUE THREAD

**Issue by carlosjuarezflash** [braintree/braintree_android#939]
### Braintree SDK Version

4.40.1

### Environment

Both

### Android Version & Device

Any

### Braintree dependencies

const val braintree = "4.40.1"

com.braintreepayments.api:paypal:${Versions.braintree}

### Describe the bug

When updating the version of the sdk I noticed that PayPal wasn't working anymore.
the error that i received was:

**AndroidManifest.xml is incorrectly configured or another app defines the same browser switch url as this app. See https://developer.paypal.com/braintree/docs/guides/client-sdk/setup/android/v4#browser-switch-setup for the correct configuration: 

The return url scheme was not set up, incorrectly set up, or more than one Activity on this device defines the same url scheme in it's Android Manifest. See [GitHub - braintree/browser-switch-android: Open a url in a browser or Chrome Custom Tab and receive a response as the result of user interaction.](https://github.com/braintree/browser-switch-android)  for more information on setting up a return url scheme.**

but there haven't been any modification in my project or manifest file.

I found out that, the process to create a default returnURLScheme was changed:

in version 4.12.0 (my previous version) this was the code 

```
private static BraintreeClientParams createDefaultParams(Context context, String authString, ClientTokenProvider clientTokenProvider) {
        String returnUrlScheme = context
                .getApplicationContext()
                .getPackageName()
                .toLowerCase(Locale.ROOT)
                .replace("_", "") + ".braintree";
        return createDefaultParams(context, authString, clientTokenProvider, returnUrlScheme, null, IntegrationType.CUSTOM);
    }

```

notice the lowerCase call there.

in the version i updated 4.40.1, the lower case call no longer exists, making the check for configured activity and data scheme fail

```
      val url = Uri.parse("https://braintreepayments.com")
        val returnUrlScheme = getReturnUrlScheme()
        val browserSwitchOptions = BrowserSwitchOptions()
            .url(url)
            .returnUrlScheme(returnUrlScheme)
            .requestCode(requestCode)
        browserSwitchClient.assertCanPerformBrowserSwitch(activity, browserSwitchOptions)
```

```
      boolean isDeviceConfiguredForDeepLinking(Context context, String returnUrlScheme) {
              String browserSwitchUrl = String.format("%s://", returnUrlScheme);
              Intent deepLinkIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(browserSwitchUrl));
              deepLinkIntent.addCategory(Intent.CATEGORY_DEFAULT);
              deepLinkIntent.addCategory(Intent.CATEGORY_BROWSABLE);
      
              return canResolveActivityForIntent(context, deepLinkIntent);
          }

```

```
       private fun getAppPackageNameWithoutUnderscores(context: Context) =
            context.applicationContext.packageName.replace("_", "")

        private fun createDefaultReturnUrlScheme(context: Context) =
            "${getAppPackageNameWithoutUnderscores(context)}.braintree"
```

### To reproduce

Create a new application or change the id of the application to add a capital letter

using the default return schema try to open paypal

you will get an error like the above

### Expected behavior

My application contains a capital letter "com.parkwhiz.driverApp" 
so i defined the url schema as "com.parkwhiz.driverapp"

using the default configuration you should be able to open a paypal page if the activity is configured in the manifest

I have another application that doesn't contain capital letters and is working correctly

**Comment by sshropshire** [comment]
Hey @carlosjuarezflash thanks for using the Braintree SDK for Android. I believe a custom URL scheme will solve your issue as a workaround (see [MIGRATION_GUIDE](https://github.com/braintree/braintree_android/blob/main/v4.9.0%2B_MIGRATION_GUIDE.md#browser-switch)).

We had an unrelated issue that required us to remove lowercasing in for browser switch deep links. The `customUrlScheme` we provide will allow you to be more explicit about the format of the deep link.

**Comment by carlosjuarezflash** [comment]
Hey @sshropshire thanks for the fast response, I figured that I could use that. I just added the error here in case somebody else suffered the same problem.

Thanks ablot

**Comment by sshropshire** [comment]
@carlosjuarezflash is this complete? I can go ahead and close it out.

**Comment by carlosjuarezflash** [comment]
Yes, it is complete.

Thank you again for the fast response

**Comment by sshropshire** [comment]
No problem. Closing for now.
