### ISSUE TITLE
Does checking if Google Pay is ready to pay require activity instead of plain context?

### ISSUE THREAD

**Issue by jupblb** [braintree/braintree_android#949]
### Is your feature request related to a problem? Please describe.

When checking for Google Pay availability the Braintree SDK calls `com.google.android.gms.wallet.Wallet` with `Activity` as argument: https://github.com/braintree/braintree_android/blob/032c1ca999bc749f750d1d4241997f973dedbf6c/GooglePay/src/main/java/com/braintreepayments/api/GooglePayInternalClient.java#L16-L31

But that same function can be called with just `Context` which is simpler to get. Is there any particular reason why `Activity` is used instead?

### Describe the solution you'd like.

Be able to run `GooglePayClient.isReadyToPay` with `Context` instead of `Activity`.

**Comment by sshropshire** [comment]
Hey @jupblb we've added a [new method](https://github.com/braintree/braintree_android/blob/main/CHANGELOG.md#unreleased) that takes `Context` it'll be in an upcoming release. For now it's available in our `4.43.1-SNAPSHOT` version if you'd like to get a preview.

**Comment by jupblb** [comment]
Thank you. The code change is released so I'm closing this issue.
