### ISSUE TITLE
Users getting UserCanceledException on PayPal CustomTabs tokenization after minimizing the CustomTabs

### ISSUE THREAD

**Issue by LAMESGIT** [braintree/braintree_android#953]
### Braintree SDK Version

4.33.0

### Environment

Both

### Android Version & Device

Google Pixel 4 - Android 13.0

### Braintree dependencies

implementation 'com.braintreepayments.api:paypal:4.33.0'

### Describe the bug

Hi,
We have a feedback from one of our testers that the authorization in paypal webpage using Chrome CustomTabs cancels once he clicks the "minimize" button on the CustomTabs toolbar. 
We analyze the log and find Braintree returns "UserCanceledException: User canceled PayPal" from `onPayPalFailure` method.

### To reproduce

1. Install Chrome of which version at least 122 on the phone, and set it as the CustomTabs provider.
2. Choose PayPal as the payment method and checkout (i.e. invoke PayPalClient.tokenizePayPalAccount method).
3. Some users can see screen like this below:
![Screenshot_20240322-170944](https://github.com/braintree/braintree_android/assets/10525530/783688cb-bf00-4318-a9de-c9e09be3742e)
4. On the right of close button, there is a down arrow. Click it and the customTabs will be minimized, after that `onPayPalFailure` is called.

If you can't see the minimize button on CustomTabs toolbar, make sure the brand of the test phone is NOT Xiaomi. And if you still can't see the button, open chrome and open uri: chrome://flags/#cct-minimized, set the flag to ENABLED and check again.

### Expected behavior

We don't wanna receive this UserCanceledException when minimize the customTabs. We hope the calling process can be waiting while the customTabs is minimized and receive token result after customTabs is truly cancelled.
Also we did some analysis of the code logic, we think the minimization feature enabled by Chrome is the reason (may be wrong :) ), according to this doc about the overview of Android customTabs: https://developer.chrome.com/docs/android/custom-tabs. This feature is based on Picture-in-Picture in Android system. Once the customTabs is minimized, the checkout page would be resumed, and the **PayPalLifecycleObserver** would get ON_RESUME lifecycle event, which triggers the SDK flow. 

Have a nice day~ :)

**Comment by sarahkoop** [comment]
Hi @LAMESGIT - Thank you for reporting this issue. We are currently investigating this behavior and will post here when we have an update!

**Comment by LAMESGIT** [comment]
@sarahkoop Thanks a lot! It would be a great help to us. 😊

**Comment by tdchow** [comment]
Hi @LAMESGIT - We just released the GA version of v5! In this version, the interface has been updated to give the additional browser switch flexibility.

For the case where the user minimizes the Chrome Custom Tab and returns to the app, the callback will return `NoResult`. You can then handle this however you need. The buyer can still return to the Chrome Custom Tab to complete the payment flow.

Please give v5 a try and let us know if you run into any issues!

Releases: https://github.com/braintree/braintree_android/releases/tag/5.0.0
v5 Migration Guide: https://github.com/braintree/braintree_android/blob/main/v5_MIGRATION_GUIDE.md

**Comment by sarahkoop** [comment]
Closing this issue since v5 is available in GA - please re-open or create a new issue if you experience this with v5!
