### ISSUE TITLE
Android Pay in Braintree production

### ISSUE THREAD

**Issue by pamalraj** [braintree/braintree_android#97]
Background:
Everything tested fine in Sandbox (Android Pay pop came up, could select payment card, make purchase, transaction shows up in sandbox dashboard)

We are now in Braintree production:
1. Updated to production client token
2. Launched app from local build, as well as thru Android Dev Console (set up an alpha list and uploaded the .apk)

In both cases, the Android Pay pop-up comes up and then disappears...less than a second on the screen.

We havent done anything extra on the Android Dev Console or Google Dev Console...dont know if we need to.

Here is the error that we get: 

install_non_market_apps has moved from android.provider.Settings.Global to android.provider.Settings.Secure, returning read-only value.
05-13 10:31:18.028 31780-31892/? E/Volley: [1888] BasicNetwork.performRequest: Unexpected response code 400 for https://wallet.google.com/payments/apis/instantbuy/android/v1/getWalletItems
05-13 10:31:18.037 20093-20093/? E/OwServiceUtils: Wallet error code: 51
05-13 10:31:18.037 20093-20093/? E/OwServiceUtils: Wallet error detail: You have not registered to use this `API.

**Comment by lkorth** [comment]
@pamalraj: your app has not been whitelisted by Google for use in production. Please see the [documentation](https://developers.braintreepayments.com/guides/android-pay/testing-go-live) for how to submit your app for approval.
