### ISSUE TITLE
Drop-in UI CardForm EditText styles

### ISSUE THREAD

**Issue by polbins** [braintree/braintree_android#98]
I would like to modify the CardForm > EditText > textColor inside the Drop-in UI for our app. The problem right now is that the textColor is white, and the background is light grey, which makes it hard to read.

I'm trying to override it through 

	<style name="bt_card_form_field"...> 
	
but it seems that it doesn't get applied. Or maybe I'm missing something?

**Comment by lkorth** [comment]
The [`android-card-form`](https://github.com/braintree/android-card-form) [reads the text color from the theme](https://github.com/braintree/android-card-form/blob/master/CardForm/src/main/java/com/braintreepayments/cardform/view/ErrorEditText.java#L80). You should be able to apply a theme to the `BraintreePaymentActivity` in your manifest to set the text color used.

For reference you can check out the [card form sample app](https://github.com/braintree/android-card-form/tree/master/Sample) which shows [using several activities](https://github.com/braintree/android-card-form/blob/master/Sample/src/main/AndroidManifest.xml) with different themes and how that affects the look of the form.

**Comment by polbins** [comment]
Thanks!! 👍
