### ISSUE TITLE
403 when building the mobile SDK

### ISSUE THREAD

**Issue by dorsametvia** [braintree/braintree_android#995]
### Braintree SDK Version

4.39.0

### Environment

Production

### Android Version & Device

Jenkins build

### Braintree dependencies

    implementation "com.braintreepayments.api:card:$brainTreeVersion"
    implementation "com.braintreepayments.api:google-pay:$brainTreeVersion"
    implementation "com.braintreepayments.api:paypal:$brainTreeVersion"
    implementation "com.braintreepayments.api:local-payment:$brainTreeVersion"
    implementation "com.braintreepayments.api:data-collector:$brainTreeVersion"

    // don't remove this dependency, we use it in this way because we have conflict with the Magnes
    // sdk for stripe that is use as jar in this dependency that used by all braintree dependencies
    // https://developer.paypal.com/limited-release/magnes/integrate/android
    implementation "com.braintreepayments.api:paypal-data-collector:$brainTreeVersion"

    implementation("com.braintreepayments.api:three-d-secure:$brainTreeVersion") {
        exclude group: 'org.bouncycastle'
    }
    implementation 'com.braintreepayments.api:drop-in:6.13.0'
    implementation 'com.braintreepayments:encryption:2.1.0'

    //support paypal web implementation
    implementation 'com.braintreepayments:popup-bridge:3.2.0'

### Describe the bug

Every once in a while whenever we try to build an app in our automations we receive the error:
```
* What went wrong:
Execution failed for task ':via-rider:mapReleaseSourceSetPaths'.
> Could not resolve all files for configuration ':via-rider:releaseRuntimeClasspath'.
   > Failed to transform cardinalmobilesdk-2.2.7-5.aar (org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-5) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not download cardinalmobilesdk-2.2.7-5.aar (org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-5)
         > Could not get resource 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.aar'.
            > Could not GET 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-5/cardinalmobilesdk-2.2.7-5.aar'. Received status code 403 from server: 
 ```

### To reproduce

Build the app with the following dependencies on a Jenkins server

### Expected behavior

Cardinal SDK should be installed alongside with the Braintree dependencies

**Comment by sarahkoop** [comment]
Hey @dorsametvia - Unfortunately, this intermittent access issue is due to the hosting platform (Jfrog) of the Cardinal Mobile SDK, so we do not have control over it. We have ongoing communication with the Cardinal teams to try and improve this. Currently, we suggest retrying as the issue usually resolves in a few hours.
