### ISSUE TITLE
URGENT!! java.lang.IllegalStateException: Method addObserver must be called on the main thread

### ISSUE THREAD

**Issue by thanh-fluz** [braintree/braintree_android#997]
### Braintree SDK Version

4.45

### Environment

Both

### Braintree dependencies

    implementation 'com.braintreepayments.api:google-pay:4.45.0'
    implementation 'com.braintreepayments.api:data-collector:4.45.0'
    implementation 'com.braintreepayments.api:paypal-data-collector:4.45.0'
    implementation 'com.braintreepayments.api:venmo:4.45.0'
    implementation 'com.braintreepayments.api:paypal:4.45.0'
    implementation 'com.braintreepayments.api:three-d-secure:4.45.0'

### Describe the bug

I am getting an addObserver must be called on the main thread error after upgrading to braintree android v4.45 on android.
I saw that the venmo Client class has a addObserver method. How come the googlePay Client doesnt?

https://github.com/thanh-fluz/react-native-braintree-no-ui/blob/master/android/src/main/java/com/pw/droplet/braintree/Braintree.java

### To reproduce

Upgrade braintree to 4.45

### Expected behavior

Running the without the "addObserver must be called on the main thread" error

### Screenshots

![image](https://github.com/braintree/braintree_android/assets/165301863/7d0992ac-2b48-4acf-9537-097ff2f499e0)

**Comment by sarahkoop** [comment]
Can you share a snipped of your integration code? Constructing the feature clients in the `onCreate` method of your fragment or activity should resolve this error.

**Comment by thanh-fluz** [comment]
I saw that the venmo Client class has a addObserver method. How come the googlePay Client doesnt?

**Comment by thanh-fluz** [comment]
@sarahkoop Here is our integration. We followed the migration guide to v4+ the best we can but there are current items we are not 100% on as I am finding out now during testing.

https://github.com/thanh-fluz/react-native-braintree-no-ui/blob/master/android/src/main/java/com/pw/droplet/braintree/Braintree.java

**Comment by sarahkoop** [comment]
Both[ VenmoClient](https://github.com/braintree/braintree_android/blob/a8be6574ac74d65eb9adcc3620d12d3a5ef41d5b/Venmo/src/main/java/com/braintreepayments/api/VenmoClient.java#L110) and [GooglePayClient ](https://github.com/braintree/braintree_android/blob/a8be6574ac74d65eb9adcc3620d12d3a5ef41d5b/GooglePay/src/main/java/com/braintreepayments/api/GooglePayClient.java#L95) add observers in the same way. Unfortunately, we do not offer official support for react native, if there are react native specific integration issues.

**Comment by sarahkoop** [comment]
I'm not sure I understand the use case here - the `addObserver` method is private in the VenmoClient and internal to the SDK, it is not meant to be integrated with directly.

**Comment by thanh-fluz** [comment]
@sarahkoop what i am trying to understand is if we need to implement our own lifecycle.addObserver(this.observer) and create our own observer?

**Comment by sarahkoop** [comment]
I recommend checking out our [developer docs](https://developer.paypal.com/braintree/docs/guides/google-pay/client-side/android/v4#requesting-a-payment) - they contain the necessary steps to integrate with the SDK. Implementing a custom observer is not necessary for integrating with the SDK.

**Comment by thanh-fluz** [comment]
I have the activity like this but I am still getting a "Method addObserver must be called on the main thread" error

```

public class MyActivity extends AppCompatActivity implements GooglePayListener {
  
  private BraintreeClient braintreeClient;
  private GooglePayClient googlePayClient;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    braintreeClient = new BraintreeClient(this, new ExampleClientTokenProvider());
    googlePayClient = new GooglePayClient(this, braintreeClient);
    googlePayClient.setListener(this);
  }

  public void onGooglePayButtonClick(View view) {
    GooglePayRequest googlePayRequest = new GooglePayRequest();
    googlePayRequest.setTransactionInfo(TransactionInfo.newBuilder()
        .setTotalPrice("1.00")
        .setTotalPriceStatus(WalletConstants.TOTAL_PRICE_STATUS_FINAL)
        .setCurrencyCode("USD")
        .build());
    googlePayRequest.setBillingAddressRequired(true);

    googlePayClient.requestPayment(this, googlePayRequest);
  }

  @Override
  public void onGooglePaySuccess(@NonNull PaymentMethodNonce paymentMethodNonce) {
      // send paymentMethodNonce.getString() to server
  }

  @Override
  public void onGooglePayFailure(@NonNull Exception error) {
    if (error instanceof UserCanceledException) {
      // user canceled
    } else {
      // handle error
    }
  }
}

```

**Comment by sshropshire** [comment]
Hey @thanh-fluz can you place the following in your `onCreate()` method to see if it evaluates to `true`?

```java
boolean isMainThread = Looper.myLooper() == Looper.getMainLooper()
```
> Source: [Stackoverflow.com](https://stackoverflow.com/questions/11411022/how-to-check-if-current-thread-is-not-main-thread)

Also, is this a pure Android activity i.e. without react native? I'm not as familiar with the React Native threading model, but at the moment we do have an implicit requirement that some of our feature clients must be instantiated and have their listeners added on the main thread for payment methods that perform either a browser switch or an app switch.

It's a limitation that we're working to improve in our next major version.
